[package]
edition = "2021"
name = "type_variants_from_reqwest_response"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = {version = "=1.0.67"}
quote = {version = "=1.0.33"}
syn = {version = "=1.0.107"}
strum = {version = "=0.24.1"}
strum_macros = {version = "=0.24.3"}
convert_case = {version = "=0.6.0"}
enum_extension = {path = "../enum_extension"}
proc_macro_helpers = {path = "../proc_macro_helpers"}
proc_macro_common = {path = "../proc_macro_common"}

[lints]
workspace = true
