pub mod param;
use gen_quotes::dq_str;
pub use naming_common::{
    AsRefStrToScStr, AsRefStrToScTs, AsRefStrToUccStr, AsRefStrToUccTs, AsRefStrToUpperScStr,
    AsRefStrToUpperScTs, DisplayToScStr, DisplayToScTs, DisplayToUccStr, DisplayToUccTs,
    DisplayToUpperScStr, DisplayToUpperScTs, ToTokensToScStr, ToTokensToScTs, ToTokensToUccStr,
    ToTokensToUccTs, ToTokensToUpperScStr, ToTokensToUpperScTs,
};
pub use naming_macros::{
    AsRefStrEnumWithUnitFieldsToScStr, AsRefStrEnumWithUnitFieldsToUccStr,
    AsRefStrEnumWithUnitFieldsToUpperScStr,
};
use optml::Optml;
use proc_macro2::TokenStream as Ts2;
use quote::{ToTokens, quote};
use std::fmt::{Display, Formatter, Result as FmtResult};
pub const GITHUB_URL: &str = "https://github.com/kuqmua/tufa_project";
naming_macros::gen_ucc_and_sc_str_and_ts!([
    ["pk"],
    ["serde"],
    ["with", "serde"],
    ["loc"],
    ["is", "none"],
    ["try", "from"],
    ["from", "str"],
    ["column", "not", "found"],
    ["req", "er"],
    ["row", "not", "found"],
    ["type", "not", "found"],
    ["column", "index", "out", "of", "bounds"],
    ["column", "decode"],
    ["pool", "timed", "out"],
    ["pool", "closed"],
    ["worker", "crashed"],
    ["json", "data", "er"],
    ["json", "syntax", "er"],
    ["missing", "json", "content", "type"],
    ["bytes", "rejection"],
    ["unexpected", "case"],
    ["expected", "type"],
    ["unexpected", "status", "code"],
    ["failed", "to", "get", "res", "text"],
    ["deserialize", "res"],
    ["status", "code"],
    ["res", "text"],
    ["res", "text", "result"],
    ["std", "opt", "opt"],
    ["w", "vec", "column"],
    ["order", "by"],
    ["p", "ks"],
    ["not", "unique", "pk"],
    ["res", "vrts"],
    ["tvfrr", "extraction", "logic"],
    ["bind", "query"],
    ["into", "serde", "version"],
    ["checked", "add"],
    ["pk", "from", "row", "and", "rollback"],
    ["non", "existing", "p", "ks"],
    ["non", "existing", "p", "ks", "and", "rollback"],
    ["commit", "failed"],
    [
        "op", "done", "but", "p", "k", "inn", "type", "try", "from", "p", "k", "inn", "type",
        "with", "serde", "failed"
    ],
    ["app", "state"],
    ["column", "sel"],
    ["opts", "try", "from", "sqlx", "row"],
    ["qp", "er"],
    ["pk", "try", "from", "sqlx", "row"],
    ["extraction", "result"],
    ["serde", "json", "to", "string"],
    [
        "op", "done", "but", "p", "k", "inn", "type", "try", "from", "p", "k", "inn", "type",
        "with", "serde", "failed", "in", "server"
    ],
    [
        "op", "done", "but", "p", "k", "inn", "type", "try", "from", "p", "k", "inn", "type",
        "with", "serde", "failed", "in", "client"
    ],
    [
        "op", "done", "but", "p", "k", "inn", "type", "try", "from", "p", "k", "inn", "type",
        "with", "serde", "failed", "in", "client", "er", "unnamed"
    ],
    [
        "op", "done", "but", "p", "k", "inn", "type", "try", "from", "p", "k", "inn", "type",
        "with", "serde", "failed", "in", "client", "many"
    ],
    ["no", "payload", "fields"],
    ["no", "payload", "params"],
    ["try", "extract", "v"],
    ["endpoint", "location"],
    ["pg", "connection"],
    ["query", "string"],
    ["binded", "query"],
    ["current", "vec", "len"],
    ["into", "inn", "type", "vec"],
    ["not", "unique", "field"],
    ["get", "axum", "http", "status", "code"],
    ["body", "bytes"],
    ["into", "res"],
    [
        "pk", "inn", "type", "try", "from", "pk", "inn", "type", "with", "serde", "in", "client"
    ],
    ["check", "commit"],
    ["check", "commit", "er"],
    ["check", "body", "size"],
    ["src", "h"],
    ["column", "decode", "index"],
    ["expected", "res"],
    ["pg", "crud"],
    ["check", "body", "size", "er"],
    ["cm", "er", "vrts"],
    ["co", "er", "vrts"],
    ["rm", "er", "vrts"],
    ["ro", "er", "vrts"],
    ["um", "er", "vrts"],
    ["uo", "er", "vrts"],
    ["dm", "er", "vrts"],
    ["dlo", "er", "vrts"],
    ["common", "er", "vrts"],
    ["cm", "logic"],
    ["co", "logic"],
    ["rm", "logic"],
    ["ro", "logic"],
    ["um", "logic"],
    ["uo", "logic"],
    ["dm", "logic"],
    ["dlo", "logic"],
    ["common", "logic"],
    ["not", "unique", "field", "vec"],
    ["rollback", "er"],
    ["not", "unique", "pk", "with", "serde"],
    ["not", "unique"],
    ["no", "payload", "fields", "pk"],
    ["no", "p", "ks"],
    ["row", "and", "rollback"],
    ["pg", "transaction"],
    ["results", "vec"],
    ["serde", "json"],
    ["unexpected", "rows", "length"],
    ["unexpected", "rows", "length", "and", "rollback"],
    ["expected", "length"],
    ["got", "length"],
    ["pool", "connection"],
    ["type"],
    ["in"],
    ["as"],
    ["where"],
    ["named"],
    ["unnamed"],
    ["er"],
    ["occurence"],
    ["string"],
    ["params"],
    ["payload"],
    ["el"],
    ["try"],
    ["from"],
    ["path"],
    ["k"],
    ["ks"],
    ["value"],
    ["vec"],
    ["reference"],
    ["with"],
    ["serialize"],
    ["deserialize"],
    ["req"],
    ["res"],
    ["vrts"],
    ["opts"],
    ["code"],
    ["config"],
    ["is"],
    ["none"],
    ["str"],
    ["uuid"],
    ["w"],
    ["possible"],
    ["src"],
    ["display"],
    ["foreign"],
    ["to"],
    ["into"],
    ["get"],
    ["column"],
    ["sel"],
    ["order"],
    ["by"],
    ["not"],
    ["found"],
    ["desirable"],
    ["rollback"],
    ["limit"],
    ["offset"],
    ["client"],
    ["server"],
    ["no"],
    ["fields"],
    ["commit"],
    ["begin"],
    ["acc"],
    ["query"],
    ["upd"],
    ["set"],
    ["insert"],
    ["values"],
    ["del"],
    ["and"],
    ["unnest"],
    ["configuration"],
    ["database"],
    ["io"],
    ["tls"],
    ["protocol"],
    ["row"],
    ["index"],
    ["out"],
    ["of"],
    ["bounds"],
    ["decode"],
    ["pool"],
    ["timed"],
    ["closed"],
    ["worker"],
    ["crashed"],
    ["migrate"],
    ["json"],
    ["data"],
    ["syntax"],
    ["missing"],
    ["content"],
    ["bytes"],
    ["rejection"],
    ["expected"],
    ["unexpected"],
    ["case"],
    ["status"],
    ["failed"],
    ["text"],
    ["reqwest"],
    ["headers"],
    ["result"],
    ["debug"],
    ["or"],
    ["asc"],
    ["desc"],
    ["unique"],
    ["many"],
    ["std"],
    ["opt"],
    ["p"],
    ["inn"],
    ["existing"],
    ["non"],
    ["current"],
    ["len"],
    ["sqlx"],
    ["returning"],
    ["app"],
    ["state"],
    ["permission"],
    ["tvfrr"],
    ["rd"],
    ["rd", "inn"],
    ["logic"],
    ["extraction"],
    ["generated"],
    ["route"],
    ["body"],
    ["env"],
    ["collections"],
    ["pg"],
    ["bind"],
    ["version"],
    ["checked"],
    ["add"],
    ["upper"],
    ["snake"],
    ["camel"],
    ["token"],
    ["stream"],
    ["done"],
    ["but"],
    ["op"],
    ["gen"],
    ["incrs"],
    ["incr"],
    ["extra"],
    ["http"],
    ["codes"],
    ["extract"],
    ["location"],
    ["connection"],
    ["binded"],
    ["axum"],
    ["check"],
    ["size"],
    ["h"],
    ["url"],
    ["future"],
    ["field"],
    ["else"],
    ["end"],
    ["when"],
    ["then"],
    ["rows"],
    ["results"],
    ["executor"],
    ["prefix"],
    ["filter"],
    ["empty", "column", "json", "rder"],
    ["not", "unique", "column", "json", "rder"],
    ["gen", "pg", "json", "to", "rd", "from", "vec"],
    ["gen", "pg", "json", "to", "rd", "from", "vec", "er"],
    ["gen", "pg", "json", "to", "rd", "er"],
    ["opt", "to", "rd"],
    ["opt", "to", "upd"],
    ["id"],
    ["to", "cr"],
    ["rder"],
    ["field", "to", "upd"],
    ["json", "arr", "el", "change"],
    ["not", "unique", "id"],
    ["std", "vec", "vec", "generic"],
    ["fields", "filter", "is", "empty"],
    ["not", "unique", "field", "filter"],
    ["pgn"],
    ["field", "vec"],
    ["obj", "acc"],
    ["std", "opt", "opt", "obj", "acc"],
    ["cr", "upd", "del", "check", "fields", "are", "empty"],
    ["not", "unique", "id", "in", "json", "upd", "arr"],
    ["not", "unique", "id", "in", "json", "del", "arr"],
    [
        "not", "unique", "id", "in", "json", "upd", "and", "del", "arrs"
    ],
    ["fields", "are", "empty"],
    ["wrap", "into", "jsonb", "build", "obj"],
    ["gen", "jsonb", "set", "target"],
    ["gen", "jsonb", "set", "path"],
    ["column", "fi"],
    ["column", "field", "for", "er", "message", "ident"],
    ["gen", "not", "unique", "field"],
    ["all", "fields", "are", "none"],
    ["self"],
    ["opt", "to", "upd", "try", "gen", "pg", "json", "er"],
    ["cr", "qp"],
    ["cr", "qb"],
    ["sel", "qp"],
    ["jsonb", "set", "accumulator"],
    ["jsonb", "set", "target"],
    ["jsonb", "set", "path"],
    ["column", "field"],
    ["column", "field", "for", "er", "message"],
    ["fi"],
    ["pg", "json"],
    ["cr", "qp", "er"],
    ["cr"],
    ["dotenv"],
    ["std", "env", "var", "er"],
    ["env", "var", "name"],
    ["try", "from", "std", "env", "var", "ok"],
    ["table", "name"],
    ["gen", "pg", "crud", "pk"],
    ["dflt", "opt", "some", "vec", "one", "el"],
    ["all", "vrts", "dflt", "opt", "some", "vec", "one", "el"],
    ["gen", "pg", "json"],
    ["to", "std", "string", "string"],
    ["location", "lib"],
    ["oprtr"],
    ["pub"],
    ["self", "cr"],
    ["self", "to", "rd"],
    ["self", "sel"],
    ["self", "rd"],
    ["pg", "crud", "base", "self", "traits"],
    ["pg", "base", "type"],
    ["pg", "base", "type", "self"],
    ["pg", "base", "type", "pk"],
    ["pg", "base", "type", "pk", "self"],
    ["pg", "base", "type", "std", "opt", "opt", "self"],
    ["pg", "type", "self", "traits"],
    ["pg", "type"],
    ["self", "column"],
    ["pg", "json", "obj", "self", "sel"],
    ["pg", "json", "std", "opt", "opt", "obj", "self", "sel"],
    [
        "pg", "json", "std", "vec", "vec", "obj", "with", "id", "self", "sel"
    ],
    [
        "pg", "json", "std", "opt", "opt", "std", "vec", "vec", "obj", "with", "id", "self", "sel"
    ],
    ["true"],
    ["false"],
    ["null"],
    ["upd", "qp"],
    ["upd", "qb"],
    ["qp"],
    ["qb"],
    ["crate"],
    ["between"],
    ["add", "oprtr"],
    ["case", "sensitive", "regex"],
    ["case", "insensitive", "regex"],
    ["equal"],
    ["greater", "than"],
    ["hexadecimal", "notation", "equal"],
    ["equal", "to", "encoded", "string", "representation"],
    ["find", "ranges", "within", "given", "range"],
    [
        "find", "ranges", "that", "fully", "contain", "the", "given", "range"
    ],
    ["is", "null"],
    ["try", "new", "er"],
    ["start", "more", "or", "equal", "to", "end"],
    ["is", "empty"],
    ["length", "is", "negative"],
    ["start", "is", "equal", "to", "end"],
    ["start"],
    ["strictly", "to", "left", "of", "range"],
    ["strictly", "to", "right", "of", "range"],
    ["included", "lower", "bound"],
    ["excluded", "upper", "bound"],
    ["greater", "than", "included", "lower", "bound"],
    ["greater", "than", "excluded", "upper", "bound"],
    ["overlap", "with", "range"],
    ["adjacent", "with", "range"],
    ["range", "length"],
    ["length", "is", "negative", "or", "zero"],
    ["before"],
    ["current", "date"],
    ["current", "time"],
    ["greater", "than", "current", "date"],
    ["greater", "than", "current", "time"],
    ["current", "timestamp"],
    ["greater", "than", "current", "timestamp"],
    ["position", "equal"],
    ["position", "is", "less", "or", "equal", "zero"],
    ["self", "where"],
    ["position"],
    ["bit", "vec", "position", "equal"],
    ["position", "is", "less", "than", "zero"],
    ["position", "case", "sensitive", "regex"],
    ["position", "case", "insensitive", "regex"],
    ["dim", "one", "contains", "all", "els", "of", "arr"],
    ["dim", "two", "contains", "all", "els", "of", "arr"],
    ["dim", "three", "contains", "all", "els", "of", "arr"],
    ["dim", "four", "contains", "all", "els", "of", "arr"],
    ["contained", "in", "arr"],
    ["dim", "one", "overlaps", "with", "arr"],
    ["dim", "two", "overlaps", "with", "arr"],
    ["dim", "three", "overlaps", "with", "arr"],
    ["dim", "four", "overlaps", "with", "arr"],
    ["dim", "one", "length", "equal"],
    ["dim", "two", "length", "equal"],
    ["dim", "three", "length", "equal"],
    ["dim", "four", "length", "equal"],
    ["dim", "one", "length", "greater", "than"],
    ["dim", "two", "length", "greater", "than"],
    ["dim", "three", "length", "greater", "than"],
    ["dim", "four", "length", "greater", "than"],
    ["dim", "one", "all", "els", "equal"],
    ["dim", "two", "all", "els", "equal"],
    ["dim", "three", "all", "els", "equal"],
    ["dim", "four", "all", "els", "equal"],
    ["dim", "one", "contains", "el", "greater", "than"],
    ["dim", "two", "contains", "el", "greater", "than"],
    ["dim", "three", "contains", "el", "greater", "than"],
    ["dim", "four", "contains", "el", "greater", "than"],
    ["dim", "one", "all", "els", "greater", "than"],
    ["dim", "two", "all", "els", "greater", "than"],
    ["dim", "three", "all", "els", "greater", "than"],
    ["dim", "four", "all", "els", "greater", "than"],
    ["contains", "el", "case", "sensitive", "regex"],
    ["contains", "el", "case", "insensitive", "regex"],
    ["all", "els", "case", "sensitive", "regex"],
    ["all", "els", "case", "insensitive", "regex"],
    ["contains", "el"],
    ["equal", "second", "dim"],
    ["from", "calendar", "date"],
    ["less", "than", "minimum", "pg", "v"],
    ["year"],
    ["month"],
    ["day"],
    ["months"],
    ["days"],
    ["microseconds"],
    ["date"],
    ["time"],
    ["std", "vec", "vec"],
    ["std", "vec", "vec", "std", "vec", "vec"],
    ["uuid", "uuid"],
    ["fixed", "length"],
    ["pg", "type", "where", "filter"],
    ["is", "pk"],
    ["cr", "table", "column", "qp"],
    ["table", "type"],
    ["mut"],
    ["boolean"],
    ["obj"],
    ["arr"],
    ["nbr"],
    ["integer"],
    ["not", "null"],
    ["nullable"],
    ["vec", "of"],
    ["arr", "of"],
    ["arr", "length", "dim", "one"],
    ["arr", "length", "greater", "than", "dim", "one"],
    ["jsonb", "obj"],
    ["with", "id"],
    ["uuid", "uuid", "as", "not", "null", "jsonb", "string"],
    ["jsonb"],
    ["regex"],
    ["dim", "one", "regex"],
    ["dim", "two", "regex"],
    ["dim", "three", "regex"],
    ["dim", "four", "regex"],
    ["dim", "one", "contains", "el", "regex"],
    ["dim", "two", "contains", "el", "regex"],
    ["dim", "three", "contains", "el", "regex"],
    ["dim", "four", "contains", "el", "regex"],
    ["dim", "one", "all", "els", "regex"],
    ["dim", "two", "all", "els", "regex"],
    ["dim", "three", "all", "els", "regex"],
    ["dim", "four", "all", "els", "regex"],
    ["dim", "one", "equal"],
    ["dim", "two", "equal"],
    ["dim", "three", "equal"],
    ["dim", "four", "equal"],
    ["dim", "position"],
    ["dim", "one", "greater", "than"],
    ["dim", "two", "greater", "than"],
    ["dim", "three", "greater", "than"],
    ["dim", "four", "greater", "than"],
    ["dim", "one", "in"],
    ["dim", "two", "in"],
    ["dim", "three", "in"],
    ["dim", "four", "in"],
    ["dim", "one", "between"],
    ["dim", "two", "between"],
    ["dim", "three", "between"],
    ["dim", "four", "between"],
    ["dim", "one", "before"],
    ["dim", "one", "current", "date"],
    ["dim", "one", "greater", "than", "current", "date"],
    ["dim", "one", "current", "timestamp"],
    ["dim", "one", "greater", "than", "current", "timestamp"],
    ["dim", "one", "current", "time"],
    ["dim", "one", "greater", "than", "current", "time"],
    ["dim", "one", "arr", "length", "dim", "one"],
    [
        "dim", "one", "arr", "length", "greater", "than", "dim", "one"
    ],
    [
        "dim",
        "one",
        "equal",
        "to",
        "encoded",
        "string",
        "representation"
    ],
    ["dim", "one", "find", "ranges", "within", "given", "range"],
    [
        "dim", "one", "find", "ranges", "that", "fully", "contain", "the", "given", "range"
    ],
    ["dim", "one", "strictly", "to", "left", "of", "range"],
    ["dim", "one", "strictly", "to", "right", "of", "range"],
    ["dim", "one", "included", "lower", "bound"],
    ["dim", "one", "excluded", "upper", "bound"],
    [
        "dim", "one", "greater", "than", "included", "lower", "bound"
    ],
    [
        "dim", "one", "greater", "than", "excluded", "upper", "bound"
    ],
    ["dim", "one", "overlap", "with", "range"],
    ["dim", "one", "adjacent", "with", "range"],
    ["dim", "one", "range", "length"],
    ["dims"],
    ["dims", "ies"],
    ["obj", "uuid", "equal"],
    ["length", "equal"],
    ["length", "greater", "than"],
    ["contains", "all", "els", "of", "arr"],
    ["overlaps", "with", "arr"],
    ["contains", "el", "regex"],
    ["all", "els", "regex"],
    ["all", "els", "equal"],
    ["contains", "el", "greater", "than"],
    ["all", "els", "greater", "than"],
    ["cr", "extension", "if", "not", "exists", "pg", "jsonschema"],
    ["cr", "extension", "if", "not", "exists", "uuid", "ossp"],
    ["prep", "pg"],
    ["prep", "pg", "table"],
    [
        "header",
        "content",
        "type",
        "application",
        "json",
        "not",
        "found"
    ],
    ["where", "many"],
    ["no", "fields", "provided"],
    ["extra", "params"],
    ["gen", "sel", "qp"],
    ["upd", "qp", "pk"],
    ["gen", "column", "queals", "v", "comma", "uo", "qp"],
    ["pk", "qp"],
    ["columns"],
    ["gen", "when", "column", "id", "then", "v"],
    ["gen", "when", "column", "id", "then", "v", "um", "qp"],
    ["test", "cases"],
    ["contains", "null", "byte"],
    ["new", "or", "try", "new", "unwraped", "for", "test"],
    ["pg", "type", "test", "cases"],
    ["included", "start", "greater", "than", "included", "end"],
    ["included", "start", "greater", "than", "excluded", "end"],
    ["excluded", "start", "greater", "than", "included", "end"],
    ["excluded", "start", "greater", "than", "excluded", "end"],
    ["included", "end", "cannot", "be", "max"],
    ["earlier", "date", "not", "supported"],
    ["earliest", "supported", "date"],
    ["naive", "date"],
    ["naive", "time"],
    [
        "invalid",
        "hour",
        "or",
        "minute",
        "or",
        "second",
        "or",
        "microsecond"
    ],
    ["hour"],
    ["min"],
    ["sec"],
    ["micro"],
    ["minute"],
    ["second"],
    ["microsecond"],
    ["nanosecond", "precision", "is", "not", "supported"],
    ["date", "naive"],
    ["nanosecond"],
    ["included"],
    ["excluded"],
    ["unbounded"],
    ["normalize"],
    ["new"],
    ["try", "new"],
    ["try", "new", "for", "deserialize"],
    ["pg", "json", "test", "cases"],
    ["pg", "pool"],
    ["pg", "pool", "for", "tokio", "spawn", "sync", "move"],
    ["ident", "cr", "dflt"],
    ["vec", "of", "p", "ks", "from", "cm"],
    ["sel", "pk"],
    ["sort", "vec", "of", "ident", "rd", "with", "pk", "by", "pk"],
    ["gen", "el"],
    ["some", "v", "pk", "rd", "from", "co"],
    ["pk", "rd", "from", "co"],
    ["sel", "pk", "fi"],
    ["sel", "qp", "pg", "type"],
    ["sel", "qp", "pg", "json"],
    ["upd", "qp", "pg", "type"],
    ["upd", "qp", "pg", "json"],
    ["upd", "qb", "pg", "type"],
    ["upd", "qb", "pg", "json"],
    ["rd", "ids"],
    ["sel", "only", "ids", "qp"],
    ["rd", "ids", "from", "co"],
    ["some", "v", "rd", "ids", "from", "co"],
    ["sel", "only", "updd", "ids", "qp"],
    ["cr", "upd", "del", "are", "empty"],
    ["uo", "params"],
    ["upd", "to", "rd", "ids"],
    ["self", "rd", "ids", "h"],
    ["rd", "ids", "from", "cm"],
    ["common", "rd", "ids", "from", "co"],
    ["gen", "pg", "table", "pk"],
    ["rd", "new", "or", "try", "new", "unwraped", "for", "test"],
    ["rd", "ids", "to", "opt", "v", "rd", "inn"],
    ["try", "bind"],
    ["sel", "only", "updd", "ids", "qb"],
    ["cr", "for", "query"],
    ["upd", "new", "or", "try", "new", "unwraped", "for", "test"],
    [
        "rd", "ids", "to", "opt", "v", "rd", "dflt", "opt", "some", "vec", "one", "el"
    ],
    ["rd", "from", "previous", "rd", "unwraped", "and", "upd"],
    ["opt", "upd"],
    ["sel", "only", "crd", "ids", "qp"],
    ["sel", "only", "crd", "ids", "qb"],
    ["upd", "for", "query"],
    ["upd", "for", "query", "vec"],
    ["rd", "inn", "vec", "vec"],
    ["cr", "vec"],
    ["rd", "ids", "and", "cr", "into", "opt", "v", "rd"],
    [
        "dflt", "opt", "some", "vec", "one", "el", "max", "page", "size"
    ],
    [
        "all", "vrts", "dflt", "opt", "some", "vec", "one", "el", "max", "page", "size"
    ],
    ["ids", "are", "not", "unique"],
    ["pg", "type", "pk"],
    ["pg", "type", "rd"],
    ["pg", "type", "not", "pk"],
    ["rd", "ids", "and", "cr", "into", "where", "equal"],
    ["rd", "ids", "and", "cr", "into", "rd"],
    ["rd", "ids", "and", "cr", "into", "table", "type"],
    [
        "rd", "inn", "into", "rd", "with", "new", "or", "try", "new", "unwraped"
    ],
    [
        "rd", "inn", "into", "upd", "with", "new", "or", "try", "new", "unwraped"
    ],
    ["rd", "ids", "to2", "dims", "vec", "of", "rd", "inn"],
    ["rd", "ids", "into", "opt", "v", "rd", "inn"],
    ["previous", "rd", "and", "opt", "upd", "into", "rd"],
    [
        "rd", "ids", "and", "cr", "into", "vec", "where", "equal", "using", "fields"
    ],
    ["equal", "oprtr"],
    ["pg", "type", "equal", "oprtr"],
    ["rd", "ids", "into", "table", "type"],
    ["rd", "ids", "into", "rd"],
    ["rd", "ids", "into", "upd"],
    ["rd", "into", "table", "type"],
    [
        "rd", "ids", "and", "cr", "into", "where", "equal", "to", "json", "field"
    ],
    ["opt", "vec", "cr"],
    ["rd", "ids", "to2", "dims", "vec", "rd", "inn"],
    [
        "rd", "ids", "and", "cr", "into", "opt", "vec", "where", "equal", "to", "json", "field"
    ],
    [
        "rd", "ids", "and", "cr", "into", "vec", "where", "equal", "to", "json", "field"
    ],
    [
        "cr", "into", "pg", "type", "opt", "vec", "where", "dim", "one", "equal"
    ],
    [
        "rd", "ids", "and", "table", "type", "into", "pg", "type", "opt", "where", "greater",
        "than"
    ],
    [
        "pg", "type", "opt", "vec", "where", "greater", "than", "test"
    ],
    [
        "rd", "ids", "and", "cr", "into", "pg", "json", "opt", "vec", "where", "dim", "one",
        "equal"
    ],
    [
        "rd", "ids", "and", "cr", "into", "pg", "json", "opt", "vec", "where", "dim", "two",
        "equal"
    ],
    [
        "rd", "ids", "and", "cr", "into", "pg", "json", "opt", "vec", "where", "dim", "three",
        "equal"
    ],
    [
        "rd", "ids", "and", "cr", "into", "pg", "json", "opt", "vec", "where", "dim", "four",
        "equal"
    ],
    ["prep", "extensions"],
    ["prep", "pg", "table", "and", "extensions"],
    ["table"],
    ["routes"],
    ["routes", "h"],
    [
        "cr", "into", "pg", "json", "opt", "vec", "where", "length", "greater", "than"
    ],
    [
        "cr", "into", "pg", "json", "opt", "vec", "where", "length", "equal"
    ],
    ["from", "h"],
    [
        "rd", "ids", "and", "cr", "into", "pg", "json", "opt", "vec", "where", "greater", "than"
    ],
    [
        "rd", "ids", "and", "cr", "into", "pg", "json", "opt", "vec", "where", "between"
    ],
    [
        "rd", "ids", "and", "cr", "into", "pg", "json", "opt", "vec", "where", "in"
    ],
    [
        "rd", "ids", "and", "cr", "into", "pg", "json", "opt", "vec", "where", "regex"
    ],
    [
        "rd", "ids", "and", "cr", "into", "pg", "json", "opt", "vec", "where", "contains", "el",
        "greater", "than"
    ],
    [
        "rd", "ids", "and", "cr", "into", "pg", "json", "opt", "vec", "where", "contains", "el",
        "regex"
    ],
    ["executor", "acquire"],
    ["gen", "pg", "json", "mod"],
    ["gen", "pg", "types", "mod"],
    ["to", "err", "string"],
    ["body", "size", "er"],
    ["max"],
    ["near", "zero"],
    ["negative", "less", "typical"],
    ["negative", "more", "typical"],
    ["positive", "less", "typical"],
    ["positive", "more", "typical"],
    ["v"]
]);
#[derive(Debug, Clone, Copy, Optml)]
pub struct HashMap;
#[derive(Debug, Clone, Copy, Optml)]
pub struct HashMapUcc;
impl Display for HashMapUcc {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(f, "HashMap")
    }
}
impl ToTokens for HashMapUcc {
    fn to_tokens(&self, tokens: &mut Ts2) {
        quote! {HashMap}.to_tokens(tokens);
    }
}
#[derive(Debug, Clone, Copy, Optml)]
pub struct HashMapSc;
impl Display for HashMapSc {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(f, "hashmap")
    }
}
impl ToTokens for HashMapSc {
    fn to_tokens(&self, tokens: &mut Ts2) {
        quote! {hashmap}.to_tokens(tokens);
    }
}
pub trait DisplayPlusToTokens: Display + ToTokens {}
impl<T> DisplayPlusToTokens for T where T: Display + ToTokens {}
pub trait SwaggerUrlPathSelfQuotesStr {
    fn swagger_url_path_self_quotes_str(&self, v: &str) -> String;
}
impl<T> SwaggerUrlPathSelfQuotesStr for T
where
    T: AsRefStrToScStr,
{
    fn swagger_url_path_self_quotes_str(&self, v: &str) -> String {
        dq_str(&format!("/{}/{}", v, self.case(),))
    }
}
pub trait SwaggerUrlPathSelfQuotesTokenStream {
    fn swagger_url_path_self_quotes_ts(&self, v: &str) -> Ts2;
}
impl<T> SwaggerUrlPathSelfQuotesTokenStream for T
where
    T: SwaggerUrlPathSelfQuotesStr,
{
    fn swagger_url_path_self_quotes_ts(&self, v: &str) -> Ts2 {
        self.swagger_url_path_self_quotes_str(v)
            .parse::<Ts2>()
            .expect("f292686b")
    }
}
