pub mod parameter;
use gen_quotes::dq_str;
pub use naming_common::{
    AsRefStrToScStr, AsRefStrToScTs, AsRefStrToUccStr, AsRefStrToUccTs, AsRefStrToUpperScStr,
    AsRefStrToUpperScTs, DisplayToScStr, DisplayToScTs, DisplayToUccStr, DisplayToUccTs,
    DisplayToUpperScStr, DisplayToUpperScTs, ToTokensToScStr, ToTokensToScTs, ToTokensToUccStr,
    ToTokensToUccTs, ToTokensToUpperScStr, ToTokensToUpperScTs,
};
pub use naming_macros::{
    AsRefStrEnumWithUnitFieldsToScStr, AsRefStrEnumWithUnitFieldsToUccStr,
    AsRefStrEnumWithUnitFieldsToUpperScStr,
};
use proc_macro2::TokenStream as Ts2;
use quote::{ToTokens, quote};
use std::fmt::{Display, Formatter, Result as FmtResult};
pub const GITHUB_URL: &str = "https://github.com/kuqmua/tufa_project";
pub const SUPPORTS_ONLY_STRINGIFIED: &str = "supports only";
pub const SYN_FIELDS: &str = "syn::Fields";
pub const SYN_GENERIC_ARGUMENT_TYPE_STRINGIFIED: &str = "syn::GenericArgument::Type";
pub const IS_NONE_STRINGIFIED: &str = "is None";
pub const STD_STRINGIFIED: &str = "std";
pub const SQLX_TYPES_UUID_STRINGIFIED: &str = "sqlx::types::Uuid";
pub const FIELD_IDENT_IS_NONE: &str = "field.ident is None";
pub const SYN_TYPE_PATH: &str = "syn::Type::Path";
naming_macros::gen_ucc_and_sc_str_and_ts!([
    ["primary", "key"],
    ["serde"],
    ["with", "serde"],
    ["er", "occurence"],
    ["code", "occurence"],
    ["is", "none"],
    ["try", "from"],
    ["from", "str"],
    ["column", "not", "found"],
    ["request", "er"],
    ["row", "not", "found"],
    ["type", "not", "found"],
    ["column", "index", "out", "of", "bounds"],
    ["column", "decode"],
    ["pool", "timed", "out"],
    ["pool", "closed"],
    ["worker", "crashed"],
    ["json", "data", "er"],
    ["json", "syntax", "er"],
    ["missing", "json", "content", "type"],
    ["bytes", "rejection"],
    ["unexpected", "case"],
    ["expected", "type"],
    ["unexpected", "status", "code"],
    ["failed", "to", "get", "response", "text"],
    ["deserialize", "response"],
    ["status", "code"],
    ["response", "text"],
    ["response", "text", "result"],
    ["std", "option", "option"],
    ["wrapper", "vec", "column"],
    ["order", "by"],
    ["primary", "keys"],
    ["not", "unique", "primary", "key"],
    ["response", "variants"],
    ["tvfrr", "extraction", "logic"],
    ["bind", "query"],
    ["into", "serde", "version"],
    ["checked", "add"],
    ["primary", "key", "from", "row", "and", "rollback"],
    ["non", "existing", "primary", "keys"],
    ["non", "existing", "primary", "keys", "and", "rollback"],
    ["commit", "failed"],
    [
        "operation",
        "done",
        "but",
        "primary",
        "key",
        "inner",
        "type",
        "try",
        "from",
        "primary",
        "key",
        "inner",
        "type",
        "with",
        "serde",
        "failed"
    ],
    ["app", "state"],
    ["column", "select"],
    ["options", "try", "from", "sqlx", "row"],
    ["query", "part", "er"],
    ["primary", "key", "try", "from", "sqlx", "row"],
    ["extraction", "result"],
    ["serde", "json", "to", "string"],
    [
        "operation",
        "done",
        "but",
        "primary",
        "key",
        "inner",
        "type",
        "try",
        "from",
        "primary",
        "key",
        "inner",
        "type",
        "with",
        "serde",
        "failed",
        "in",
        "server"
    ],
    [
        "operation",
        "done",
        "but",
        "primary",
        "key",
        "inner",
        "type",
        "try",
        "from",
        "primary",
        "key",
        "inner",
        "type",
        "with",
        "serde",
        "failed",
        "in",
        "client"
    ],
    [
        "operation",
        "done",
        "but",
        "primary",
        "key",
        "inner",
        "type",
        "try",
        "from",
        "primary",
        "key",
        "inner",
        "type",
        "with",
        "serde",
        "failed",
        "in",
        "client",
        "er",
        "unnamed"
    ],
    [
        "operation",
        "done",
        "but",
        "primary",
        "key",
        "inner",
        "type",
        "try",
        "from",
        "primary",
        "key",
        "inner",
        "type",
        "with",
        "serde",
        "failed",
        "in",
        "client",
        "many"
    ],
    ["no", "payload", "fields"],
    ["no", "payload", "parameters"],
    ["try", "extract", "value"],
    ["endpoint", "location"],
    ["pg", "connection"],
    ["query", "string"],
    ["binded", "query"],
    ["current", "vec", "len"],
    ["into", "inner", "type", "vec"],
    ["not", "unique", "field"],
    ["get", "axum", "http", "status", "code"],
    ["body", "bytes"],
    ["into", "response"],
    [
        "primary", "key", "inner", "type", "try", "from", "primary", "key", "inner", "type",
        "with", "serde", "in", "client"
    ],
    ["check", "commit"],
    ["check", "commit", "er"],
    ["check", "body", "size"],
    ["source", "handle"],
    ["column", "decode", "index"],
    ["expected", "response"],
    ["pg", "crud"],
    ["check", "body", "size", "er"],
    ["create", "many", "additional", "er", "variants"],
    ["create", "one", "additional", "er", "variants"],
    ["read", "many", "additional", "er", "variants"],
    ["read", "one", "additional", "er", "variants"],
    ["update", "many", "additional", "er", "variants"],
    ["update", "one", "additional", "er", "variants"],
    ["delete", "many", "additional", "er", "variants"],
    ["delete", "one", "additional", "er", "variants"],
    ["common", "additional", "er", "variants"],
    ["create", "many", "additional", "logic"],
    ["create", "one", "additional", "logic"],
    ["read", "many", "additional", "logic"],
    ["read", "one", "additional", "logic"],
    ["update", "many", "additional", "logic"],
    ["update", "one", "additional", "logic"],
    ["delete", "many", "additional", "logic"],
    ["delete", "one", "additional", "logic"],
    ["common", "additional", "logic"],
    ["not", "unique", "field", "vec"],
    ["rollback", "er"],
    ["not", "unique", "primary", "key", "with", "serde"],
    ["not", "unique"],
    ["no", "payload", "fields", "primary", "key"],
    ["no", "primary", "keys"],
    ["row", "and", "rollback"],
    ["pg", "transaction"],
    ["results", "vec"],
    ["serde", "json"],
    ["unexpected", "rows", "length"],
    ["unexpected", "rows", "length", "and", "rollback"],
    ["expected", "length"],
    ["got", "length"],
    ["pool", "connection"],
    ["type"],
    ["in"],
    ["as"],
    ["where"],
    ["named"],
    ["unnamed"],
    ["er"],
    ["occurence"],
    ["string"],
    ["parameters"],
    ["payload"],
    ["element"],
    ["try"],
    ["from"],
    ["path"],
    ["key"],
    ["keys"],
    ["value"],
    ["vec"],
    ["reference"],
    ["with"],
    ["serialize"],
    ["deserialize"],
    ["request"],
    ["response"],
    ["variants"],
    ["options"],
    ["code"],
    ["config"],
    ["is"],
    ["none"],
    ["str"],
    ["uuid"],
    ["wrapper"],
    ["possible"],
    ["source"],
    ["display"],
    ["foreign"],
    ["to"],
    ["into"],
    ["get"],
    ["column"],
    ["select"],
    ["order"],
    ["by"],
    ["not"],
    ["found"],
    ["desirable"],
    ["rollback"],
    ["limit"],
    ["offset"],
    ["client"],
    ["server"],
    ["no"],
    ["fields"],
    ["commit"],
    ["begin"],
    ["acc"],
    ["query"],
    ["update"],
    ["set"],
    ["insert"],
    ["values"],
    ["delete"],
    ["and"],
    ["unnest"],
    ["configuration"],
    ["database"],
    ["io"],
    ["tls"],
    ["protocol"],
    ["row"],
    ["index"],
    ["out"],
    ["of"],
    ["bounds"],
    ["decode"],
    ["pool"],
    ["timed"],
    ["closed"],
    ["worker"],
    ["crashed"],
    ["migrate"],
    ["json"],
    ["data"],
    ["syntax"],
    ["missing"],
    ["content"],
    ["bytes"],
    ["rejection"],
    ["expected"],
    ["unexpected"],
    ["case"],
    ["status"],
    ["failed"],
    ["text"],
    ["reqwest"],
    ["headers"],
    ["result"],
    ["debug"],
    ["or"],
    ["asc"],
    ["desc"],
    ["unique"],
    ["many"],
    ["std"],
    ["option"],
    ["primary"],
    ["inner"],
    ["existing"],
    ["non"],
    ["current"],
    ["len"],
    ["sqlx"],
    ["returning"],
    ["app"],
    ["state"],
    ["permission"],
    ["tvfrr"],
    ["read"],
    ["read", "inner"],
    ["logic"],
    ["extraction"],
    ["generated"],
    ["route"],
    ["body"],
    ["env"],
    ["collections"],
    ["pg"],
    ["bind"],
    ["version"],
    ["checked"],
    ["add"],
    ["upper"],
    ["snake"],
    ["camel"],
    ["token"],
    ["stream"],
    ["done"],
    ["but"],
    ["operation"],
    ["gen"],
    ["increments"],
    ["increment"],
    ["additional"],
    ["http"],
    ["codes"],
    ["extract"],
    ["location"],
    ["connection"],
    ["binded"],
    ["axum"],
    ["check"],
    ["size"],
    ["handle"],
    ["url"],
    ["future"],
    ["field"],
    ["else"],
    ["end"],
    ["when"],
    ["then"],
    ["rows"],
    ["results"],
    ["executor"],
    ["prefix"],
    ["filter"],
    ["empty", "column", "json", "reader"],
    ["not", "unique", "column", "json", "reader"],
    ["gen", "pg", "json", "type", "to", "read", "from", "vec"],
    [
        "gen", "pg", "json", "type", "to", "read", "from", "vec", "er"
    ],
    ["gen", "pg", "json", "type", "to", "read", "er"],
    ["option", "to", "read"],
    ["option", "to", "update"],
    ["id"],
    ["to", "create"],
    ["reader"],
    ["field", "to", "update"],
    ["json", "array", "el", "change"],
    ["not", "unique", "id"],
    ["std", "vec", "vec", "generic"],
    ["fields", "filter", "is", "empty"],
    ["not", "unique", "field", "filter"],
    ["pagination"],
    ["field", "vec"],
    ["object", "acc"],
    ["std", "option", "option", "object", "acc"],
    [
        "create", "update", "delete", "check", "fields", "are", "empty"
    ],
    ["not", "unique", "id", "in", "json", "update", "array"],
    ["not", "unique", "id", "in", "json", "delete", "array"],
    [
        "not", "unique", "id", "in", "json", "update", "and", "delete", "arrays"
    ],
    ["fields", "are", "empty"],
    ["wrap", "into", "jsonb", "build", "object"],
    ["gen", "jsonb", "set", "target"],
    ["gen", "jsonb", "set", "path"],
    [
        "column", "name", "and", "maybe", "field", "getter", "field", "ident"
    ],
    [
        "column", "name", "and", "maybe", "field", "getter", "for", "er", "message", "field",
        "ident"
    ],
    ["gen", "not", "unique", "field"],
    ["all", "fields", "are", "none"],
    ["self"],
    [
        "option", "to", "update", "try", "gen", "pg", "json", "type", "er"
    ],
    ["create", "query", "part"],
    ["create", "query", "bind"],
    ["select", "query", "part"],
    ["jsonb", "set", "accumulator"],
    ["jsonb", "set", "target"],
    ["jsonb", "set", "path"],
    ["column", "name", "and", "maybe", "field", "getter"],
    [
        "column", "name", "and", "maybe", "field", "getter", "for", "er", "message"
    ],
    ["field", "ident"],
    ["pg", "json", "type"],
    ["create", "query", "part", "er"],
    ["create"],
    ["dotenv"],
    ["std", "env", "var", "er"],
    ["env", "var", "name"],
    ["try", "from", "std", "env", "var", "ok"],
    ["table", "name"],
    ["gen", "pg", "crud", "primary", "key"],
    ["default", "option", "some", "vec", "one", "el"],
    [
        "all", "variants", "default", "option", "some", "vec", "one", "el"
    ],
    ["gen", "pg", "json", "type"],
    ["to", "std", "string", "string"],
    ["er", "occurence", "lib"],
    ["logical", "operator"],
    ["pub"],
    ["self", "create"],
    ["self", "to", "read"],
    ["self", "select"],
    ["self", "read"],
    ["pg", "crud", "base", "self", "traits"],
    ["pg", "base", "type"],
    ["pg", "base", "type", "self"],
    ["pg", "base", "type", "primary", "key"],
    ["pg", "base", "type", "primary", "key", "self"],
    ["pg", "base", "type", "std", "option", "option", "self"],
    ["pg", "type", "self", "traits"],
    ["pg", "type"],
    ["self", "column"],
    ["pg", "json", "type", "object", "self", "select"],
    [
        "pg", "json", "type", "std", "option", "option", "object", "self", "select"
    ],
    [
        "pg", "json", "type", "std", "vec", "vec", "object", "with", "id", "self", "select"
    ],
    [
        "pg", "json", "type", "std", "option", "option", "std", "vec", "vec", "object", "with",
        "id", "self", "select"
    ],
    ["true"],
    ["false"],
    [
        "column", "name", "and", "maybe", "field", "getter", "handle"
    ],
    ["null"],
    ["update", "query", "part"],
    ["update", "query", "bind"],
    ["query", "part"],
    ["query", "bind"],
    ["crate"],
    ["between"],
    ["is", "need", "to", "add", "logical", "operator"],
    ["case", "sensitive", "regular", "expression"],
    ["case", "insensitive", "regular", "expression"],
    ["equal"],
    ["greater", "than"],
    ["hexadecimal", "notation", "equal"],
    ["equal", "to", "encoded", "string", "representation"],
    ["find", "ranges", "within", "given", "range"],
    [
        "find", "ranges", "that", "fully", "contain", "the", "given", "range"
    ],
    ["is", "null"],
    ["try", "new", "er"],
    ["start", "more", "or", "equal", "to", "end"],
    ["is", "empty"],
    ["length", "is", "negative"],
    ["start", "is", "equal", "to", "end"],
    ["start"],
    ["strictly", "to", "left", "of", "range"],
    ["strictly", "to", "right", "of", "range"],
    ["included", "lower", "bound"],
    ["excluded", "upper", "bound"],
    ["greater", "than", "included", "lower", "bound"],
    ["greater", "than", "excluded", "upper", "bound"],
    ["overlap", "with", "range"],
    ["adjacent", "with", "range"],
    ["range", "length"],
    ["length", "is", "negative", "or", "zero"],
    ["before"],
    ["current", "date"],
    ["current", "time"],
    ["greater", "than", "current", "date"],
    ["greater", "than", "current", "time"],
    ["current", "timestamp"],
    ["greater", "than", "current", "timestamp"],
    ["position", "equal"],
    ["position", "is", "less", "or", "equal", "zero"],
    ["self", "where"],
    ["position"],
    ["bit", "vec", "position", "equal"],
    ["position", "is", "less", "than", "zero"],
    ["position", "case", "sensitive", "regular", "expression"],
    ["position", "case", "insensitive", "regular", "expression"],
    ["dim", "one", "contains", "all", "elements", "of", "array"],
    ["dim", "two", "contains", "all", "elements", "of", "array"],
    ["dim", "three", "contains", "all", "elements", "of", "array"],
    ["dim", "four", "contains", "all", "elements", "of", "array"],
    ["contained", "in", "array"],
    ["dim", "one", "overlaps", "with", "array"],
    ["dim", "two", "overlaps", "with", "array"],
    ["dim", "three", "overlaps", "with", "array"],
    ["dim", "four", "overlaps", "with", "array"],
    ["dim", "one", "length", "equal"],
    ["dim", "two", "length", "equal"],
    ["dim", "three", "length", "equal"],
    ["dim", "four", "length", "equal"],
    ["dim", "one", "length", "greater", "than"],
    ["dim", "two", "length", "greater", "than"],
    ["dim", "three", "length", "greater", "than"],
    ["dim", "four", "length", "greater", "than"],
    ["dim", "one", "all", "elements", "equal"],
    ["dim", "two", "all", "elements", "equal"],
    ["dim", "three", "all", "elements", "equal"],
    ["dim", "four", "all", "elements", "equal"],
    ["dim", "one", "contains", "el", "greater", "than"],
    ["dim", "two", "contains", "el", "greater", "than"],
    ["dim", "three", "contains", "el", "greater", "than"],
    ["dim", "four", "contains", "el", "greater", "than"],
    ["dim", "one", "all", "elements", "greater", "than"],
    ["dim", "two", "all", "elements", "greater", "than"],
    ["dim", "three", "all", "elements", "greater", "than"],
    ["dim", "four", "all", "elements", "greater", "than"],
    [
        "contains",
        "el",
        "case",
        "sensitive",
        "regular",
        "expression"
    ],
    [
        "contains",
        "el",
        "case",
        "insensitive",
        "regular",
        "expression"
    ],
    [
        "all",
        "elements",
        "case",
        "sensitive",
        "regular",
        "expression"
    ],
    [
        "all",
        "elements",
        "case",
        "insensitive",
        "regular",
        "expression"
    ],
    ["contains", "el"],
    ["equal", "second", "dim"],
    ["from", "calendar", "date"],
    ["less", "than", "minimum", "pg", "value"],
    ["year"],
    ["month"],
    ["day"],
    ["months"],
    ["days"],
    ["microseconds"],
    ["date"],
    ["time"],
    ["std", "vec", "vec"],
    ["std", "vec", "vec", "std", "vec", "vec"],
    ["uuid", "uuid"],
    ["fixed", "length"],
    ["pg", "type", "where", "filter"],
    ["is", "primary", "key"],
    ["create", "table", "column", "query", "part"],
    ["table", "type", "declaration"],
    ["mut"],
    ["boolean"],
    ["object"],
    ["array"],
    ["number"],
    ["integer"],
    ["not", "null"],
    ["nullable"],
    ["vec", "of"],
    ["array", "of"],
    ["array", "length", "dim", "one"],
    ["array", "length", "greater", "than", "dim", "one"],
    ["jsonb", "object"],
    ["with", "id"],
    ["uuid", "uuid", "as", "not", "null", "jsonb", "string"],
    ["jsonb"],
    ["regular", "expression"],
    ["dim", "one", "regular", "expression"],
    ["dim", "two", "regular", "expression"],
    ["dim", "three", "regular", "expression"],
    ["dim", "four", "regular", "expression"],
    ["dim", "one", "contains", "el", "regular", "expression"],
    ["dim", "two", "contains", "el", "regular", "expression"],
    ["dim", "three", "contains", "el", "regular", "expression"],
    ["dim", "four", "contains", "el", "regular", "expression"],
    ["dim", "one", "all", "elements", "regular", "expression"],
    ["dim", "two", "all", "elements", "regular", "expression"],
    ["dim", "three", "all", "elements", "regular", "expression"],
    ["dim", "four", "all", "elements", "regular", "expression"],
    ["dim", "one", "equal"],
    ["dim", "two", "equal"],
    ["dim", "three", "equal"],
    ["dim", "four", "equal"],
    ["dim", "position"],
    ["dim", "one", "greater", "than"],
    ["dim", "two", "greater", "than"],
    ["dim", "three", "greater", "than"],
    ["dim", "four", "greater", "than"],
    ["dim", "one", "in"],
    ["dim", "two", "in"],
    ["dim", "three", "in"],
    ["dim", "four", "in"],
    ["dim", "one", "between"],
    ["dim", "two", "between"],
    ["dim", "three", "between"],
    ["dim", "four", "between"],
    ["dim", "one", "before"],
    ["dim", "one", "current", "date"],
    ["dim", "one", "greater", "than", "current", "date"],
    ["dim", "one", "current", "timestamp"],
    ["dim", "one", "greater", "than", "current", "timestamp"],
    ["dim", "one", "current", "time"],
    ["dim", "one", "greater", "than", "current", "time"],
    ["dim", "one", "array", "length", "dim", "one"],
    [
        "dim", "one", "array", "length", "greater", "than", "dim", "one"
    ],
    [
        "dim",
        "one",
        "equal",
        "to",
        "encoded",
        "string",
        "representation"
    ],
    ["dim", "one", "find", "ranges", "within", "given", "range"],
    [
        "dim", "one", "find", "ranges", "that", "fully", "contain", "the", "given", "range"
    ],
    ["dim", "one", "strictly", "to", "left", "of", "range"],
    ["dim", "one", "strictly", "to", "right", "of", "range"],
    ["dim", "one", "included", "lower", "bound"],
    ["dim", "one", "excluded", "upper", "bound"],
    [
        "dim", "one", "greater", "than", "included", "lower", "bound"
    ],
    [
        "dim", "one", "greater", "than", "excluded", "upper", "bound"
    ],
    ["dim", "one", "overlap", "with", "range"],
    ["dim", "one", "adjacent", "with", "range"],
    ["dim", "one", "range", "length"],
    ["dims"],
    ["dims", "indexes"],
    ["object", "uuid", "equal"],
    ["length", "equal"],
    ["length", "greater", "than"],
    ["contains", "all", "elements", "of", "array"],
    ["overlaps", "with", "array"],
    ["contains", "el", "regular", "expression"],
    ["all", "elements", "regular", "expression"],
    ["all", "elements", "equal"],
    ["contains", "el", "greater", "than"],
    ["all", "elements", "greater", "than"],
    [
        "create",
        "extension",
        "if",
        "not",
        "exists",
        "pg",
        "jsonschema"
    ],
    ["create", "extension", "if", "not", "exists", "uuid", "ossp"],
    ["prepare", "pg"],
    ["prepare", "pg", "table"],
    [
        "header",
        "content",
        "type",
        "application",
        "json",
        "not",
        "found"
    ],
    ["where", "many"],
    ["no", "fields", "provided"],
    ["additional", "parameters"],
    ["gen", "select", "query", "part"],
    ["update", "query", "part", "primary", "key"],
    [
        "gen", "column", "queals", "value", "comma", "update", "one", "query", "part"
    ],
    ["primary", "key", "query", "part"],
    ["columns"],
    ["gen", "when", "column", "id", "then", "value"],
    [
        "gen", "when", "column", "id", "then", "value", "update", "many", "query", "part"
    ],
    ["test", "cases"],
    ["contains", "null", "byte"],
    ["new", "or", "try", "new", "unwraped", "for", "test"],
    ["pg", "type", "test", "cases"],
    ["included", "start", "greater", "than", "included", "end"],
    ["included", "start", "greater", "than", "excluded", "end"],
    ["excluded", "start", "greater", "than", "included", "end"],
    ["excluded", "start", "greater", "than", "excluded", "end"],
    ["included", "end", "cannot", "be", "max"],
    ["earlier", "date", "not", "supported"],
    ["earliest", "supported", "date"],
    ["naive", "date"],
    ["naive", "time"],
    [
        "invalid",
        "hour",
        "or",
        "minute",
        "or",
        "second",
        "or",
        "microsecond"
    ],
    ["hour"],
    ["min"],
    ["sec"],
    ["micro"],
    ["minute"],
    ["second"],
    ["microsecond"],
    ["nanosecond", "precision", "is", "not", "supported"],
    ["date", "naive"],
    ["nanosecond"],
    ["included"],
    ["excluded"],
    ["unbounded"],
    ["normalize"],
    ["new"],
    ["try", "new"],
    ["try", "new", "for", "deserialize"],
    ["pg", "json", "type", "test", "cases"],
    ["pg", "pool"],
    ["pg", "pool", "for", "tokio", "spawn", "sync", "move"],
    ["ident", "create", "default"],
    [
        "vec", "of", "primary", "keys", "returned", "from", "create", "many"
    ],
    ["select", "primary", "key"],
    [
        "sort", "vec", "of", "ident", "read", "with", "primary", "key", "by", "primary", "key"
    ],
    ["gen", "el"],
    [
        "some", "value", "primary", "key", "read", "returned", "from", "create", "one"
    ],
    [
        "primary", "key", "read", "returned", "from", "create", "one"
    ],
    ["select", "primary", "key", "field", "ident"],
    ["select", "query", "part", "pg", "type"],
    ["select", "query", "part", "pg", "json", "type"],
    ["update", "query", "part", "pg", "type"],
    ["update", "query", "part", "pg", "json", "type"],
    ["update", "query", "bind", "pg", "type"],
    ["update", "query", "bind", "pg", "json", "type"],
    ["read", "only", "ids"],
    ["select", "only", "ids", "query", "part"],
    ["read", "only", "ids", "returned", "from", "create", "one"],
    [
        "some", "value", "read", "only", "ids", "returned", "from", "create", "one"
    ],
    ["select", "only", "updated", "ids", "query", "part"],
    ["create", "update", "delete", "are", "empty"],
    ["update", "one", "parameters"],
    ["update", "to", "read", "only", "ids"],
    ["self", "read", "only", "ids", "handle"],
    ["read", "only", "ids", "returned", "from", "create", "many"],
    [
        "common", "read", "only", "ids", "returned", "from", "create", "one"
    ],
    ["gen", "pg", "table", "primary", "key"],
    ["read", "new", "or", "try", "new", "unwraped", "for", "test"],
    [
        "read", "only", "ids", "to", "option", "value", "read", "inner"
    ],
    ["try", "bind"],
    ["select", "only", "updated", "ids", "query", "bind"],
    ["create", "for", "query"],
    [
        "update", "new", "or", "try", "new", "unwraped", "for", "test"
    ],
    [
        "read", "only", "ids", "to", "option", "value", "read", "default", "option", "some", "vec",
        "one", "el"
    ],
    [
        "read", "from", "previous", "read", "unwraped", "merged", "with", "update"
    ],
    ["option", "update"],
    ["select", "only", "created", "ids", "query", "part"],
    ["select", "only", "created", "ids", "query", "bind"],
    ["update", "for", "query"],
    ["update", "for", "query", "vec"],
    ["read", "inner", "vec", "vec"],
    ["create", "vec"],
    [
        "read", "only", "ids", "merged", "with", "create", "into", "option", "value", "read"
    ],
    [
        "default", "option", "some", "vec", "one", "el", "max", "page", "size"
    ],
    [
        "all", "variants", "default", "option", "some", "vec", "one", "el", "max", "page", "size"
    ],
    ["ids", "are", "not", "unique"],
    ["pg", "type", "primary", "key"],
    ["pg", "type", "read"],
    ["pg", "type", "not", "primary", "key"],
    [
        "read", "only", "ids", "merged", "with", "create", "into", "where", "equal"
    ],
    [
        "read", "only", "ids", "merged", "with", "create", "into", "read"
    ],
    [
        "read",
        "only",
        "ids",
        "merged",
        "with",
        "create",
        "into",
        "table",
        "type",
        "declaration"
    ],
    [
        "read", "inner", "into", "read", "with", "new", "or", "try", "new", "unwraped"
    ],
    [
        "read", "inner", "into", "update", "with", "new", "or", "try", "new", "unwraped"
    ],
    [
        "read", "only", "ids", "to", "two", "dimal", "vec", "of", "read", "inner"
    ],
    [
        "read", "only", "ids", "into", "option", "value", "read", "inner"
    ],
    [
        "previous", "read", "merged", "with", "option", "update", "into", "read"
    ],
    [
        "read", "only", "ids", "merged", "with", "create", "into", "vec", "where", "equal",
        "using", "fields"
    ],
    ["equal", "operator"],
    ["pg", "type", "equal", "operator"],
    [
        "read",
        "only",
        "ids",
        "into",
        "table",
        "type",
        "declaration"
    ],
    ["read", "only", "ids", "into", "read"],
    ["read", "only", "ids", "into", "update"],
    ["read", "into", "table", "type", "declaration"],
    [
        "read", "only", "ids", "merged", "with", "create", "into", "where", "equal", "to", "json",
        "field"
    ],
    ["option", "vec", "create"],
    [
        "read", "only", "ids", "to", "two", "dimal", "vec", "read", "inner"
    ],
    [
        "read", "only", "ids", "merged", "with", "create", "into", "option", "vec", "where",
        "equal", "to", "json", "field"
    ],
    [
        "read", "only", "ids", "merged", "with", "create", "into", "vec", "where", "equal", "to",
        "json", "field"
    ],
    [
        "create", "into", "pg", "type", "option", "vec", "where", "dim", "one", "equal"
    ],
    [
        "read",
        "only",
        "ids",
        "merged",
        "with",
        "table",
        "type",
        "declaration",
        "into",
        "pg",
        "type",
        "option",
        "where",
        "greater",
        "than"
    ],
    [
        "pg", "type", "option", "vec", "where", "greater", "than", "test"
    ],
    [
        "read", "only", "ids", "merged", "with", "create", "into", "pg", "json", "type", "option",
        "vec", "where", "dim", "one", "equal"
    ],
    [
        "read", "only", "ids", "merged", "with", "create", "into", "pg", "json", "type", "option",
        "vec", "where", "dim", "two", "equal"
    ],
    [
        "read", "only", "ids", "merged", "with", "create", "into", "pg", "json", "type", "option",
        "vec", "where", "dim", "three", "equal"
    ],
    [
        "read", "only", "ids", "merged", "with", "create", "into", "pg", "json", "type", "option",
        "vec", "where", "dim", "four", "equal"
    ],
    ["prepare", "extensions"],
    ["prepare", "pg", "table", "and", "extensions"],
    ["table"],
    ["routes"],
    ["routes", "handle"],
    [
        "create", "into", "pg", "json", "type", "option", "vec", "where", "length", "greater",
        "than"
    ],
    [
        "create", "into", "pg", "json", "type", "option", "vec", "where", "length", "equal"
    ],
    ["from", "handle"],
    [
        "read", "only", "ids", "merged", "with", "create", "into", "pg", "json", "type", "option",
        "vec", "where", "greater", "than"
    ],
    [
        "read", "only", "ids", "merged", "with", "create", "into", "pg", "json", "type", "option",
        "vec", "where", "between"
    ],
    [
        "read", "only", "ids", "merged", "with", "create", "into", "pg", "json", "type", "option",
        "vec", "where", "in"
    ],
    [
        "read",
        "only",
        "ids",
        "merged",
        "with",
        "create",
        "into",
        "pg",
        "json",
        "type",
        "option",
        "vec",
        "where",
        "regular",
        "expression"
    ],
    [
        "read", "only", "ids", "merged", "with", "create", "into", "pg", "json", "type", "option",
        "vec", "where", "contains", "el", "greater", "than"
    ],
    [
        "read",
        "only",
        "ids",
        "merged",
        "with",
        "create",
        "into",
        "pg",
        "json",
        "type",
        "option",
        "vec",
        "where",
        "contains",
        "el",
        "regular",
        "expression"
    ],
    ["executor", "acquire"],
    ["gen", "pg", "json", "types", "mod"],
    ["gen", "pg", "types", "mod"],
    ["to", "err", "string"],
    ["body", "size", "er"],
    ["max"],
    ["near", "zero"],
    ["negative", "less", "typical"],
    ["negative", "more", "typical"],
    ["positive", "less", "typical"],
    ["positive", "more", "typical"]
]);
#[derive(Debug, Clone, Copy)]
pub struct HashMap;
#[derive(Debug, Clone, Copy)]
pub struct HashMapUcc;
impl Display for HashMapUcc {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(f, "HashMap")
    }
}
impl ToTokens for HashMapUcc {
    fn to_tokens(&self, tokens: &mut Ts2) {
        quote! {HashMap}.to_tokens(tokens);
    }
}
#[derive(Debug, Clone, Copy)]
pub struct HashMapSc;
impl Display for HashMapSc {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(f, "hashmap")
    }
}
impl ToTokens for HashMapSc {
    fn to_tokens(&self, tokens: &mut Ts2) {
        quote! {hashmap}.to_tokens(tokens);
    }
}
pub trait DisplayPlusToTokens: Display + ToTokens {}
impl<T> DisplayPlusToTokens for T where T: Display + ToTokens {}
pub trait SwaggerUrlPathSelfQuotesStr {
    fn swagger_url_path_self_quotes_str(&self, table_name_str: &str) -> String;
}
impl<T> SwaggerUrlPathSelfQuotesStr for T
where
    T: AsRefStrToScStr,
{
    fn swagger_url_path_self_quotes_str(&self, table_name_str: &str) -> String {
        dq_str(&format!("/{}/{}", table_name_str, self.case(),))
    }
}
pub trait SwaggerUrlPathSelfQuotesTokenStream {
    fn swagger_url_path_self_quotes_ts(&self, table_name_str: &str) -> Ts2;
}
impl<T> SwaggerUrlPathSelfQuotesTokenStream for T
where
    T: SwaggerUrlPathSelfQuotesStr,
{
    fn swagger_url_path_self_quotes_ts(&self, table_name_str: &str) -> Ts2 {
        let value = self.swagger_url_path_self_quotes_str(table_name_str);
        value.parse::<Ts2>().expect("f292686b")
    }
}
