//todo
use proc_macro2::TokenStream as Ts2;
use quote::ToTokens;
naming_macros::gen_self_ucc_and_sc_str_and_ts!([
    ["self", "payload"],
    ["try", "self"],
    ["self", "er", "with", "serde"],
    ["self", "payload", "example"],
    ["self", "cr"],
    ["self", "rd"],
    ["self", "rd", "inn"],
    ["self", "upd"],
    ["self", "upd", "for", "query"],
    ["self", "sel"],
    ["self", "with", "serde"],
    ["self", "try", "from", "env", "er"],
    ["get", "self"],
    ["try", "from", "std", "env", "var", "ok", "self", "er"],
    ["er", "self"],
    ["is", "self", "upd", "exist"],
    ["self", "wh"],
    ["std", "opt", "opt", "self"],
    ["self", "upd", "el"],
    ["self", "upd", "try", "new", "er"],
    ["std", "opt", "opt", "self", "wh"],
    ["self", "nn"],
    ["pg", "type", "wh", "self"],
    ["pg", "json", "wh", "self"],
    ["self", "tt"],
    ["self", "orgn"],
    ["self", "sel", "el"],
    ["self", "rd", "try", "from", "er"],
    ["el", "self"],
    ["self", "prep", "pg", "er"],
    ["self", "wh", "many"],
    ["self", "wh", "many", "try", "new", "er"],
    ["std", "opt", "opt", "self", "wh", "many"],
    [
        "try", "from", "sqlx", "pg", "pg", "row", "with", "not", "empty", "unq", "vec", "self",
        "sel"
    ],
    ["upd", "qp", "self"],
    ["self", "tests"],
    ["self", "orgn", "try", "new", "er"],
    ["self", "orgn", "try", "new", "for", "de", "er"],
    ["self", "rd", "ids"],
    ["self", "rd", "ids", "h"],
    ["self", "last"],
    ["self", "crnt"],
    ["jsonb", "self"],
    ["self", "cr", "for", "query"],
    ["self", "upd", "for", "query", "el"],
    ["self", "dm", "prms"],
    ["self", "dm", "payload"],
    ["self", "dlo", "prms"],
    ["self", "dlo", "payload"],
    ["self", "try", "ro", "er"],
    ["self", "ro", "er", "with", "serde"],
    ["self", "um", "prms"],
    ["self", "um", "payload"],
    ["self", "try", "dlo", "er"],
    ["self", "dlo", "er", "with", "serde"],
    ["self", "h"],
    ["try", "self", "h"],
    ["d", "self"],
    ["d", "self", "if"],
    [
        "self", "rd", "ids", "to2", "dims", "vec", "rd", "inn", "acc"
    ],
    ["self", "gen", "pg", "json", "obj", "mod"],
    ["self", "gen", "pg", "tbl", "mod"]
]);
