[package]
name = "naming_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
regex = {version = "=1.9.3"}
serde_json = {version = "=1.0"}
proc-macro2 = {version = "=1.0.81"}
quote = {version = "=1.0.36"}
syn = {version = "=2.0.60"}
proc_macro_common = {path = "../../proc_macro_common"}