use optml::Optml;
#[allow(clippy::arbitrary_source_item_ordering)]
#[derive(Debug, Clone, Copy, pg_crud::GenPgTbl, Optml)]
#[pg_crud::gen_pg_tbl_config{{
    "tests_write_into_file": "False",
    "cmn_write_into_file": "False",
    "whole_write_into_file": "False"
}}]
#[pg_crud::cm_er_vrts{enum CmErVrts{}}]
#[pg_crud::co_er_vrts{enum CoErVrts{}}]
#[pg_crud::rm_er_vrts{enum RmErVrts{}}]
#[pg_crud::ro_er_vrts{enum RoErVrts{}}]
#[pg_crud::um_er_vrts{enum UmErVrts{}}]
#[pg_crud::uo_er_vrts{enum UoErVrts{}}]
#[pg_crud::dm_er_vrts{enum DmErVrts{}}]
#[pg_crud::dlo_er_vrts{enum DloErVrts{}}]
#[pg_crud::cmn_er_vrts{
    enum CmnErVrts {
        // CheckCommit {
        //     #[eo_location]
        //     check_commit: pg_crud::check_commit::CommitEr,
        //     loc: location_lib::loc::Loc,
        // },
    }
}]
#[pg_crud::cm_logic{}]
#[pg_crud::co_logic{}]
#[pg_crud::rm_logic{}]
#[pg_crud::ro_logic{}]
#[pg_crud::um_logic{}]
#[pg_crud::uo_logic{}]
#[pg_crud::dm_logic{}]
#[pg_crud::dlo_logic{}]
#[pg_crud::cmn_logic{}]
pub struct TblExample {
    // #[gen_pg_crud_pk]
    // pub pk: pg_crud::I64AsNnBigSerialInitByPg,
    #[gen_pg_tbl_pk]
    pub pk_col: pg_crud::SqlxTypesUuidUuidAsNnUuidV4InitByPg,
    // pub col_0: pg_crud::I16AsNnInt2,
    // pub col_1: pg_crud::OptI16AsNlInt2,
    // pub col_2: pg_crud::VecOfI16AsNnArrOfNnInt2,
    // pub col_3: pg_crud::OptVecOfI16AsNlArrOfNnInt2,
    // pub col_4: pg_crud::VecOfOptI16AsNnArrOfNlInt2,
    // pub col_5: pg_crud::OptVecOfOptI16AsNlArrOfNlInt2,
    // pub col_6: pg_crud::I32AsNnInt4,
    // pub col_7: pg_crud::OptI32AsNlInt4,
    // pub col_8: pg_crud::VecOfI32AsNnArrOfNnInt4,
    // pub col_9: pg_crud::OptVecOfI32AsNlArrOfNnInt4,
    // pub col_10: pg_crud::VecOfOptI32AsNnArrOfNlInt4,
    // pub col_11: pg_crud::OptVecOfOptI32AsNlArrOfNlInt4,
    // pub col_12: pg_crud::I64AsNnInt8,
    // pub col_13: pg_crud::OptI64AsNlInt8,
    // pub col_14: pg_crud::VecOfI64AsNnArrOfNnInt8,
    // pub col_15: pg_crud::OptVecOfI64AsNlArrOfNnInt8,
    // pub col_16: pg_crud::VecOfOptI64AsNnArrOfNlInt8,
    // pub col_17: pg_crud::OptVecOfOptI64AsNlArrOfNlInt8,
    // pub col_18: pg_crud::F32AsNnFloat4,
    // pub col_19: pg_crud::OptF32AsNlFloat4,
    // pub col_20: pg_crud::VecOfF32AsNnArrOfNnFloat4,
    // pub col_21: pg_crud::OptVecOfF32AsNlArrOfNnFloat4,
    // pub col_22: pg_crud::VecOfOptF32AsNnArrOfNlFloat4,
    // pub col_23: pg_crud::OptVecOfOptF32AsNlArrOfNlFloat4,
    // pub col_24: pg_crud::F64AsNnFloat8,
    // pub col_25: pg_crud::OptF64AsNlFloat8,
    // pub col_26: pg_crud::VecOfF64AsNnArrOfNnFloat8,
    // pub col_27: pg_crud::OptVecOfF64AsNlArrOfNnFloat8,
    // pub col_28: pg_crud::VecOfOptF64AsNnArrOfNlFloat8,
    // pub col_29: pg_crud::OptVecOfOptF64AsNlArrOfNlFloat8,
    // pub col_30: pg_crud::I16AsNnSmallSerialInitByPg,
    // pub col_31: pg_crud::I32AsNnSerialInitByPg,
    // pub col_32: pg_crud::I64AsNnBigSerialInitByPg,
    // pub col_33: pg_crud::SqlxPgTypesPgMoneyAsNnMoney,
    // pub col_34: pg_crud::OptSqlxPgTypesPgMoneyAsNlMoney,
    // pub col_35: pg_crud::VecOfSqlxPgTypesPgMoneyAsNnArrOfNnMoney,
    // pub col_36: pg_crud::OptVecOfSqlxPgTypesPgMoneyAsNlArrOfNnMoney,
    // pub col_37: pg_crud::VecOfOptSqlxPgTypesPgMoneyAsNnArrOfNlMoney,
    // pub col_38: pg_crud::OptVecOfOptSqlxPgTypesPgMoneyAsNlArrOfNlMoney,
    // pub col_39: pg_crud::BoolAsNnBool,
    // pub col_40: pg_crud::OptBoolAsNlBool,
    // pub col_41: pg_crud::VecOfBoolAsNnArrOfNnBool,
    // pub col_42: pg_crud::OptVecOfBoolAsNlArrOfNnBool,
    // pub col_43: pg_crud::VecOfOptBoolAsNnArrOfNlBool,
    // pub col_44: pg_crud::OptVecOfOptBoolAsNlArrOfNlBool,
    // pub col_45: pg_crud::StringAsNnText,
    // pub col_46: pg_crud::OptStringAsNlText,
    // pub col_47: pg_crud::VecOfStringAsNnArrOfNnText,
    // pub col_48: pg_crud::OptVecOfStringAsNlArrOfNnText,
    // pub col_49: pg_crud::VecOfOptStringAsNnArrOfNlText,
    // pub col_50: pg_crud::OptVecOfOptStringAsNlArrOfNlText,
    // pub col_51: pg_crud::StdVecVecU8AsNnBytea,
    // pub col_52: pg_crud::OptStdVecVecU8AsNlBytea,
    // pub col_53: pg_crud::VecOfStdVecVecU8AsNnArrOfNnBytea,
    // pub col_54: pg_crud::OptVecOfStdVecVecU8AsNlArrOfNnBytea,
    // pub col_55: pg_crud::VecOfOptStdVecVecU8AsNnArrOfNlBytea,
    // pub col_56: pg_crud::OptVecOfOptStdVecVecU8AsNlArrOfNlBytea,
    // pub col_57: pg_crud::SqlxTypesChronoNaiveTimeAsNnTime,
    // pub col_58: pg_crud::OptSqlxTypesChronoNaiveTimeAsNlTime,
    // pub col_59: pg_crud::VecOfSqlxTypesChronoNaiveTimeAsNnArrOfNnTime,
    // pub col_60: pg_crud::OptVecOfSqlxTypesChronoNaiveTimeAsNlArrOfNnTime,
    // pub col_61: pg_crud::VecOfOptSqlxTypesChronoNaiveTimeAsNnArrOfNlTime,
    // pub col_62: pg_crud::OptVecOfOptSqlxTypesChronoNaiveTimeAsNlArrOfNlTime,
    // pub col_63: pg_crud::SqlxTypesTimeTimeAsNnTime,
    // pub col_64: pg_crud::OptSqlxTypesTimeTimeAsNlTime,
    // pub col_65: pg_crud::VecOfSqlxTypesTimeTimeAsNnArrOfNnTime,
    // pub col_66: pg_crud::OptVecOfSqlxTypesTimeTimeAsNlArrOfNnTime,
    // pub col_67: pg_crud::VecOfOptSqlxTypesTimeTimeAsNnArrOfNlTime,
    // pub col_68: pg_crud::OptVecOfOptSqlxTypesTimeTimeAsNlArrOfNlTime,
    // pub col_69: pg_crud::SqlxPgTypesPgIntervalAsNnInterval,
    // pub col_70: pg_crud::OptSqlxPgTypesPgIntervalAsNlInterval,
    // pub col_71: pg_crud::VecOfSqlxPgTypesPgIntervalAsNnArrOfNnInterval,
    // pub col_72: pg_crud::OptVecOfSqlxPgTypesPgIntervalAsNlArrOfNnInterval,
    // pub col_73: pg_crud::VecOfOptSqlxPgTypesPgIntervalAsNnArrOfNlInterval,
    // pub col_74: pg_crud::OptVecOfOptSqlxPgTypesPgIntervalAsNlArrOfNlInterval,
    // pub col_75: pg_crud::SqlxTypesChronoNaiveDateAsNnDate,
    // pub col_76: pg_crud::OptSqlxTypesChronoNaiveDateAsNlDate,
    // pub col_77: pg_crud::VecOfSqlxTypesChronoNaiveDateAsNnArrOfNnDate,
    // pub col_78: pg_crud::OptVecOfSqlxTypesChronoNaiveDateAsNlArrOfNnDate,
    // pub col_79: pg_crud::VecOfOptSqlxTypesChronoNaiveDateAsNnArrOfNlDate,
    // pub col_80: pg_crud::OptVecOfOptSqlxTypesChronoNaiveDateAsNlArrOfNlDate,
    // pub col_81: pg_crud::SqlxTypesChronoNaiveDateTimeAsNnTimestamp,
    // pub col_82: pg_crud::OptSqlxTypesChronoNaiveDateTimeAsNlTimestamp,
    // pub col_83: pg_crud::VecOfSqlxTypesChronoNaiveDateTimeAsNnArrOfNnTimestamp,
    // pub col_84: pg_crud::OptVecOfSqlxTypesChronoNaiveDateTimeAsNlArrOfNnTimestamp,
    // pub col_85: pg_crud::VecOfOptSqlxTypesChronoNaiveDateTimeAsNnArrOfNlTimestamp,
    // pub col_86: pg_crud::OptVecOfOptSqlxTypesChronoNaiveDateTimeAsNlArrOfNlTimestamp,
    // pub col_87: pg_crud::SqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNnTimestampTz,
    // pub col_88: pg_crud::OptSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNlTimestampTz,
    // pub col_89: pg_crud::VecOfSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNnArrOfNnTimestampTz,
    // pub col_90: pg_crud::OptVecOfSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNlArrOfNnTimestampTz,
    // pub col_91: pg_crud::VecOfOptSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNnArrOfNlTimestampTz,
    // pub col_92: pg_crud::OptVecOfOptSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNlArrOfNlTimestampTz,
    // pub col_93: pg_crud::SqlxTypesUuidUuidAsNnUuidV4InitByPg,
    // pub col_94: pg_crud::SqlxTypesUuidUuidAsNnUuidInitByClient,
    // pub col_95: pg_crud::OptSqlxTypesUuidUuidAsNlUuidInitByClient,
    // pub col_96: pg_crud::VecOfSqlxTypesUuidUuidAsNnArrOfNnUuidInitByClient,
    // pub col_97: pg_crud::OptVecOfSqlxTypesUuidUuidAsNlArrOfNnUuidInitByClient,
    // pub col_98: pg_crud::VecOfOptSqlxTypesUuidUuidAsNnArrOfNlUuidInitByClient,
    // pub col_99: pg_crud::OptVecOfOptSqlxTypesUuidUuidAsNlArrOfNlUuidInitByClient,
    // pub col_100: pg_crud::SqlxTypesIpnetworkIpNetworkAsNnInet,
    // pub col_101: pg_crud::OptSqlxTypesIpnetworkIpNetworkAsNlInet,
    // pub col_102: pg_crud::VecOfSqlxTypesIpnetworkIpNetworkAsNnArrOfNnInet,
    // pub col_103: pg_crud::OptVecOfSqlxTypesIpnetworkIpNetworkAsNlArrOfNnInet,
    // pub col_104: pg_crud::VecOfOptSqlxTypesIpnetworkIpNetworkAsNnArrOfNlInet,
    // pub col_105: pg_crud::OptVecOfOptSqlxTypesIpnetworkIpNetworkAsNlArrOfNlInet,
    // pub col_106: pg_crud::SqlxTypesMacAddressMacAddressAsNnMacAddr,
    // pub col_107: pg_crud::OptSqlxTypesMacAddressMacAddressAsNlMacAddr,
    // pub col_108: pg_crud::VecOfSqlxTypesMacAddressMacAddressAsNnArrOfNnMacAddr,
    // pub col_109: pg_crud::OptVecOfSqlxTypesMacAddressMacAddressAsNlArrOfNnMacAddr,
    // pub col_110: pg_crud::VecOfOptSqlxTypesMacAddressMacAddressAsNnArrOfNlMacAddr,
    // pub col_111: pg_crud::OptVecOfOptSqlxTypesMacAddressMacAddressAsNlArrOfNlMacAddr,
    // pub col_112: pg_crud::SqlxPgTypesPgRangeI32AsNnInt4Range,
    // pub col_113: pg_crud::OptSqlxPgTypesPgRangeI32AsNlInt4Range,
    // pub col_114: pg_crud::VecOfSqlxPgTypesPgRangeI32AsNnArrOfNnInt4Range,
    // pub col_115: pg_crud::OptVecOfSqlxPgTypesPgRangeI32AsNlArrOfNnInt4Range,
    // pub col_116: pg_crud::VecOfOptSqlxPgTypesPgRangeI32AsNnArrOfNlInt4Range,
    // pub col_117: pg_crud::OptVecOfOptSqlxPgTypesPgRangeI32AsNlArrOfNlInt4Range,
    // pub col_118: pg_crud::SqlxPgTypesPgRangeI64AsNnInt8Range,
    // pub col_119: pg_crud::OptSqlxPgTypesPgRangeI64AsNlInt8Range,
    // pub col_120: pg_crud::VecOfSqlxPgTypesPgRangeI64AsNnArrOfNnInt8Range,
    // pub col_121: pg_crud::OptVecOfSqlxPgTypesPgRangeI64AsNlArrOfNnInt8Range,
    // pub col_122: pg_crud::VecOfOptSqlxPgTypesPgRangeI64AsNnArrOfNlInt8Range,
    // pub col_123: pg_crud::OptVecOfOptSqlxPgTypesPgRangeI64AsNlArrOfNlInt8Range,
    // pub col_124: pg_crud::SqlxPgTypesPgRangeSqlxTypesChronoNaiveDateAsNnDateRange,
    // pub col_125: pg_crud::OptSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateAsNlDateRange,
    // pub col_126: pg_crud::VecOfSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateAsNnArrOfNnDateRange,
    // pub col_127: pg_crud::OptVecOfSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateAsNlArrOfNnDateRange,
    // pub col_128: pg_crud::VecOfOptSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateAsNnArrOfNlDateRange,
    // pub col_129: pg_crud::OptVecOfOptSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateAsNlArrOfNlDateRange,
    // pub col_130: pg_crud::SqlxPgTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNnTimestampRange,
    // pub col_131: pg_crud::OptSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNlTimestampRange,
    // pub col_132: pg_crud::VecOfSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNnArrOfNnTimestampRange,
    // pub col_133: pg_crud::OptVecOfSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNlArrOfNnTimestampRange,
    // pub col_134: pg_crud::VecOfOptSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNnArrOfNlTimestampRange,
    // pub col_135: pg_crud::OptVecOfOptSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNlArrOfNlTimestampRange,
    // pub col_136: pg_crud::SqlxPgTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNnTimestampTzRange,
    // pub col_137: pg_crud::OptSqlxPgTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNlTimestampTzRange,
    // pub col_138: pg_crud::VecOfSqlxPgTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNnArrOfNnTimestampTzRange,
    // pub col_139: pg_crud::OptVecOfSqlxPgTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNlArrOfNnTimestampTzRange,
    // pub col_140: pg_crud::VecOfOptSqlxPgTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNnArrOfNlTimestampTzRange,
    // pub col_141: pg_crud::OptVecOfOptSqlxPgTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNlArrOfNlTimestampTzRange,
    pub col_142: server_types::AnimalAsNnJsonbObj,
    // pub col_143: server_types::OptAnimalAsNlJsonbObj,
    // pub col_144: server_types::VecOfAnimalWithIdAsNnArrOfNnJsonbObjWithId,
    // pub col_145: server_types::OptVecOfAnimalWithIdAsNlArrOfNnJsonbObjWithId,
}
