[package]
name = "tufa_postgresql_crud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utoipa = {version = "=4.1.0", features = ["axum_extras"]}
generate_postgresql_crud = {path = "./generate_postgresql_crud"}

[lints]
workspace = true
