[package]
edition = "2021"
name = "init_from_env"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
convert_case = {version = "=0.6.0"}
proc-macro2 = {version = "=1.0.81"}
quote = {version = "=1.0.36"}
syn = {version = "=2.0.60"}
proc_macro_common = {path = "../../proc_macro_common"}
proc_macro_helpers = {path = "../../proc_macro_helpers"}
naming_constants = {path = "../../naming_constants"}

[lints]
workspace = true