use optml::Optml;
#[allow(unused_qualifications)]
#[allow(clippy::arbitrary_source_item_ordering)]
#[derive(Debug, Clone, Copy, pg_crud::GenPgJsonObj, Optml)]
#[pg_crud::pg_json_obj_config{
    {
        "pg_tbl_columns_write_into_pg_tbl_columns_using_pg_json_objs": "False",
        "whole_write_into_gen_pg_json_obj": "False",
        "vrt": 
        // {
        //     "is_nl": "False",
        //     "pattern": "Stdrt",
        //     "trait_gen": "PgTypeAndPgJson"
        // }
        // ,
        // {
        //     "is_nl": "True",
        //     "pattern": "Stdrt",
        //     "trait_gen": "PgTypeAndPgJson"
        // }
        // ,
        // {
        //     "is_nl": "False",
        //     "pattern": "Arr",
        //     "trait_gen": "PgTypeAndPgJson"
        // }
        // ,
        {
            "is_nl": "True",
            "pattern": "Arr",
            "trait_gen": "PgTypeAndPgJson"
        }
    }
}]
pub struct Animal {
    pub field_0: pg_crud::I8AsNnJsonbNbr,
    // pub field_1: pg_crud::OptI8AsNlJsonbNbr,
    pub field_2: pg_crud::VecOfI8AsNnArrOfNnJsonbNbr,
    // pub field_3: pg_crud::VecOfOptI8AsNnArrOfNlJsonbNbr,
    // pub field_4: pg_crud::OptVecOfI8AsNlArrOfNnJsonbNbr,
    // pub field_5: pg_crud::OptVecOfOptI8AsNlArrOfNlJsonbNbr,
    // pub field_6: pg_crud::VecOfVecOfI8AsNnArrOfNnArrOfNnJsonbNbr,
    // pub field_7: pg_crud::VecOfVecOfOptI8AsNnArrOfNnArrOfNlJsonbNbr,
    // pub field_8: pg_crud::VecOfOptVecOfI8AsNnArrOfNlArrOfNnJsonbNbr,
    // pub field_9: pg_crud::VecOfOptVecOfOptI8AsNnArrOfNlArrOfNlJsonbNbr,
    // pub field_10: pg_crud::OptVecOfVecOfI8AsNlArrOfNnArrOfNnJsonbNbr,
    // pub field_11: pg_crud::OptVecOfVecOfOptI8AsNlArrOfNnArrOfNlJsonbNbr,
    // pub field_12: pg_crud::OptVecOfOptVecOfI8AsNlArrOfNlArrOfNnJsonbNbr,
    // pub field_13: pg_crud::OptVecOfOptVecOfOptI8AsNlArrOfNlArrOfNlJsonbNbr,
    // pub field_14: pg_crud::VecOfVecOfVecOfI8AsNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_15: pg_crud::VecOfVecOfVecOfOptI8AsNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_16: pg_crud::VecOfVecOfOptVecOfI8AsNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_17: pg_crud::VecOfVecOfOptVecOfOptI8AsNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_18: pg_crud::VecOfOptVecOfVecOfI8AsNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_19: pg_crud::VecOfOptVecOfVecOfOptI8AsNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_20: pg_crud::VecOfOptVecOfOptVecOfI8AsNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_21: pg_crud::VecOfOptVecOfOptVecOfOptI8AsNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_22: pg_crud::OptVecOfVecOfVecOfI8AsNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_23: pg_crud::OptVecOfVecOfVecOfOptI8AsNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_24: pg_crud::OptVecOfVecOfOptVecOfI8AsNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_25: pg_crud::OptVecOfVecOfOptVecOfOptI8AsNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_26: pg_crud::OptVecOfOptVecOfVecOfI8AsNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_27: pg_crud::OptVecOfOptVecOfVecOfOptI8AsNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_28: pg_crud::OptVecOfOptVecOfOptVecOfI8AsNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_29: pg_crud::OptVecOfOptVecOfOptVecOfOptI8AsNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_30: pg_crud::VecOfVecOfVecOfVecOfI8AsNnArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_31: pg_crud::VecOfVecOfVecOfVecOfOptI8AsNnArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_32: pg_crud::VecOfVecOfVecOfOptVecOfI8AsNnArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_33: pg_crud::VecOfVecOfVecOfOptVecOfOptI8AsNnArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_34: pg_crud::VecOfVecOfOptVecOfVecOfI8AsNnArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_35: pg_crud::VecOfVecOfOptVecOfVecOfOptI8AsNnArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_36: pg_crud::VecOfVecOfOptVecOfOptVecOfI8AsNnArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_37: pg_crud::VecOfVecOfOptVecOfOptVecOfOptI8AsNnArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_38: pg_crud::VecOfOptVecOfVecOfVecOfI8AsNnArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_39: pg_crud::VecOfOptVecOfVecOfVecOfOptI8AsNnArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_40: pg_crud::VecOfOptVecOfVecOfOptVecOfI8AsNnArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_41: pg_crud::VecOfOptVecOfVecOfOptVecOfOptI8AsNnArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_42: pg_crud::VecOfOptVecOfOptVecOfVecOfI8AsNnArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_43: pg_crud::VecOfOptVecOfOptVecOfVecOfOptI8AsNnArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_44: pg_crud::VecOfOptVecOfOptVecOfOptVecOfI8AsNnArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_45: pg_crud::VecOfOptVecOfOptVecOfOptVecOfOptI8AsNnArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_46: pg_crud::OptVecOfVecOfVecOfVecOfI8AsNlArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_47: pg_crud::OptVecOfVecOfVecOfVecOfOptI8AsNlArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_48: pg_crud::OptVecOfVecOfVecOfOptVecOfI8AsNlArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_49: pg_crud::OptVecOfVecOfVecOfOptVecOfOptI8AsNlArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_50: pg_crud::OptVecOfVecOfOptVecOfVecOfI8AsNlArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_51: pg_crud::OptVecOfVecOfOptVecOfVecOfOptI8AsNlArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_52: pg_crud::OptVecOfVecOfOptVecOfOptVecOfI8AsNlArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_53: pg_crud::OptVecOfVecOfOptVecOfOptVecOfOptI8AsNlArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_54: pg_crud::OptVecOfOptVecOfVecOfVecOfI8AsNlArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_55: pg_crud::OptVecOfOptVecOfVecOfVecOfOptI8AsNlArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_56: pg_crud::OptVecOfOptVecOfVecOfOptVecOfI8AsNlArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_57: pg_crud::OptVecOfOptVecOfVecOfOptVecOfOptI8AsNlArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_58: pg_crud::OptVecOfOptVecOfOptVecOfVecOfI8AsNlArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_59: pg_crud::OptVecOfOptVecOfOptVecOfVecOfOptI8AsNlArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_60: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfI8AsNlArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_61: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfOptI8AsNlArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_62: pg_crud::I16AsNnJsonbNbr,
    // pub field_63: pg_crud::OptI16AsNlJsonbNbr,
    // pub field_64: pg_crud::VecOfI16AsNnArrOfNnJsonbNbr,
    // pub field_65: pg_crud::VecOfOptI16AsNnArrOfNlJsonbNbr,
    // pub field_66: pg_crud::OptVecOfI16AsNlArrOfNnJsonbNbr,
    // pub field_67: pg_crud::OptVecOfOptI16AsNlArrOfNlJsonbNbr,
    // pub field_68: pg_crud::VecOfVecOfI16AsNnArrOfNnArrOfNnJsonbNbr,
    // pub field_69: pg_crud::VecOfVecOfOptI16AsNnArrOfNnArrOfNlJsonbNbr,
    // pub field_70: pg_crud::VecOfOptVecOfI16AsNnArrOfNlArrOfNnJsonbNbr,
    // pub field_71: pg_crud::VecOfOptVecOfOptI16AsNnArrOfNlArrOfNlJsonbNbr,
    // pub field_72: pg_crud::OptVecOfVecOfI16AsNlArrOfNnArrOfNnJsonbNbr,
    // pub field_73: pg_crud::OptVecOfVecOfOptI16AsNlArrOfNnArrOfNlJsonbNbr,
    // pub field_74: pg_crud::OptVecOfOptVecOfI16AsNlArrOfNlArrOfNnJsonbNbr,
    // pub field_75: pg_crud::OptVecOfOptVecOfOptI16AsNlArrOfNlArrOfNlJsonbNbr,
    // pub field_76: pg_crud::VecOfVecOfVecOfI16AsNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_77: pg_crud::VecOfVecOfVecOfOptI16AsNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_78: pg_crud::VecOfVecOfOptVecOfI16AsNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_79: pg_crud::VecOfVecOfOptVecOfOptI16AsNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_80: pg_crud::VecOfOptVecOfVecOfI16AsNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_81: pg_crud::VecOfOptVecOfVecOfOptI16AsNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_82: pg_crud::VecOfOptVecOfOptVecOfI16AsNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_83: pg_crud::VecOfOptVecOfOptVecOfOptI16AsNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_84: pg_crud::OptVecOfVecOfVecOfI16AsNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_85: pg_crud::OptVecOfVecOfVecOfOptI16AsNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_86: pg_crud::OptVecOfVecOfOptVecOfI16AsNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_87: pg_crud::OptVecOfVecOfOptVecOfOptI16AsNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_88: pg_crud::OptVecOfOptVecOfVecOfI16AsNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_89: pg_crud::OptVecOfOptVecOfVecOfOptI16AsNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_90: pg_crud::OptVecOfOptVecOfOptVecOfI16AsNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_91: pg_crud::OptVecOfOptVecOfOptVecOfOptI16AsNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_92: pg_crud::VecOfVecOfVecOfVecOfI16AsNnArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_93: pg_crud::VecOfVecOfVecOfVecOfOptI16AsNnArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_94: pg_crud::VecOfVecOfVecOfOptVecOfI16AsNnArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_95: pg_crud::VecOfVecOfVecOfOptVecOfOptI16AsNnArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_96: pg_crud::VecOfVecOfOptVecOfVecOfI16AsNnArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_97: pg_crud::VecOfVecOfOptVecOfVecOfOptI16AsNnArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_98: pg_crud::VecOfVecOfOptVecOfOptVecOfI16AsNnArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_99: pg_crud::VecOfVecOfOptVecOfOptVecOfOptI16AsNnArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_100: pg_crud::VecOfOptVecOfVecOfVecOfI16AsNnArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_101: pg_crud::VecOfOptVecOfVecOfVecOfOptI16AsNnArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_102: pg_crud::VecOfOptVecOfVecOfOptVecOfI16AsNnArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_103: pg_crud::VecOfOptVecOfVecOfOptVecOfOptI16AsNnArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_104: pg_crud::VecOfOptVecOfOptVecOfVecOfI16AsNnArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_105: pg_crud::VecOfOptVecOfOptVecOfVecOfOptI16AsNnArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_106: pg_crud::VecOfOptVecOfOptVecOfOptVecOfI16AsNnArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_107: pg_crud::VecOfOptVecOfOptVecOfOptVecOfOptI16AsNnArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_108: pg_crud::OptVecOfVecOfVecOfVecOfI16AsNlArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_109: pg_crud::OptVecOfVecOfVecOfVecOfOptI16AsNlArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_110: pg_crud::OptVecOfVecOfVecOfOptVecOfI16AsNlArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_111: pg_crud::OptVecOfVecOfVecOfOptVecOfOptI16AsNlArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_112: pg_crud::OptVecOfVecOfOptVecOfVecOfI16AsNlArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_113: pg_crud::OptVecOfVecOfOptVecOfVecOfOptI16AsNlArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_114: pg_crud::OptVecOfVecOfOptVecOfOptVecOfI16AsNlArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_115: pg_crud::OptVecOfVecOfOptVecOfOptVecOfOptI16AsNlArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_116: pg_crud::OptVecOfOptVecOfVecOfVecOfI16AsNlArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_117: pg_crud::OptVecOfOptVecOfVecOfVecOfOptI16AsNlArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_118: pg_crud::OptVecOfOptVecOfVecOfOptVecOfI16AsNlArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_119: pg_crud::OptVecOfOptVecOfVecOfOptVecOfOptI16AsNlArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_120: pg_crud::OptVecOfOptVecOfOptVecOfVecOfI16AsNlArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_121: pg_crud::OptVecOfOptVecOfOptVecOfVecOfOptI16AsNlArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_122: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfI16AsNlArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_123: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfOptI16AsNlArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_124: pg_crud::I32AsNnJsonbNbr,
    // pub field_125: pg_crud::OptI32AsNlJsonbNbr,
    // pub field_126: pg_crud::VecOfI32AsNnArrOfNnJsonbNbr,
    // pub field_127: pg_crud::VecOfOptI32AsNnArrOfNlJsonbNbr,
    // pub field_128: pg_crud::OptVecOfI32AsNlArrOfNnJsonbNbr,
    // pub field_129: pg_crud::OptVecOfOptI32AsNlArrOfNlJsonbNbr,
    // pub field_130: pg_crud::VecOfVecOfI32AsNnArrOfNnArrOfNnJsonbNbr,
    // pub field_131: pg_crud::VecOfVecOfOptI32AsNnArrOfNnArrOfNlJsonbNbr,
    // pub field_132: pg_crud::VecOfOptVecOfI32AsNnArrOfNlArrOfNnJsonbNbr,
    // pub field_133: pg_crud::VecOfOptVecOfOptI32AsNnArrOfNlArrOfNlJsonbNbr,
    // pub field_134: pg_crud::OptVecOfVecOfI32AsNlArrOfNnArrOfNnJsonbNbr,
    // pub field_135: pg_crud::OptVecOfVecOfOptI32AsNlArrOfNnArrOfNlJsonbNbr,
    // pub field_136: pg_crud::OptVecOfOptVecOfI32AsNlArrOfNlArrOfNnJsonbNbr,
    // pub field_137: pg_crud::OptVecOfOptVecOfOptI32AsNlArrOfNlArrOfNlJsonbNbr,
    // pub field_138: pg_crud::VecOfVecOfVecOfI32AsNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_139: pg_crud::VecOfVecOfVecOfOptI32AsNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_140: pg_crud::VecOfVecOfOptVecOfI32AsNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_141: pg_crud::VecOfVecOfOptVecOfOptI32AsNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_142: pg_crud::VecOfOptVecOfVecOfI32AsNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_143: pg_crud::VecOfOptVecOfVecOfOptI32AsNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_144: pg_crud::VecOfOptVecOfOptVecOfI32AsNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_145: pg_crud::VecOfOptVecOfOptVecOfOptI32AsNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_146: pg_crud::OptVecOfVecOfVecOfI32AsNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_147: pg_crud::OptVecOfVecOfVecOfOptI32AsNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_148: pg_crud::OptVecOfVecOfOptVecOfI32AsNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_149: pg_crud::OptVecOfVecOfOptVecOfOptI32AsNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_150: pg_crud::OptVecOfOptVecOfVecOfI32AsNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_151: pg_crud::OptVecOfOptVecOfVecOfOptI32AsNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_152: pg_crud::OptVecOfOptVecOfOptVecOfI32AsNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_153: pg_crud::OptVecOfOptVecOfOptVecOfOptI32AsNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_154: pg_crud::VecOfVecOfVecOfVecOfI32AsNnArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_155: pg_crud::VecOfVecOfVecOfVecOfOptI32AsNnArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_156: pg_crud::VecOfVecOfVecOfOptVecOfI32AsNnArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_157: pg_crud::VecOfVecOfVecOfOptVecOfOptI32AsNnArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_158: pg_crud::VecOfVecOfOptVecOfVecOfI32AsNnArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_159: pg_crud::VecOfVecOfOptVecOfVecOfOptI32AsNnArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_160: pg_crud::VecOfVecOfOptVecOfOptVecOfI32AsNnArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_161: pg_crud::VecOfVecOfOptVecOfOptVecOfOptI32AsNnArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_162: pg_crud::VecOfOptVecOfVecOfVecOfI32AsNnArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_163: pg_crud::VecOfOptVecOfVecOfVecOfOptI32AsNnArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_164: pg_crud::VecOfOptVecOfVecOfOptVecOfI32AsNnArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_165: pg_crud::VecOfOptVecOfVecOfOptVecOfOptI32AsNnArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_166: pg_crud::VecOfOptVecOfOptVecOfVecOfI32AsNnArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_167: pg_crud::VecOfOptVecOfOptVecOfVecOfOptI32AsNnArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_168: pg_crud::VecOfOptVecOfOptVecOfOptVecOfI32AsNnArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_169: pg_crud::VecOfOptVecOfOptVecOfOptVecOfOptI32AsNnArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_170: pg_crud::OptVecOfVecOfVecOfVecOfI32AsNlArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_171: pg_crud::OptVecOfVecOfVecOfVecOfOptI32AsNlArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_172: pg_crud::OptVecOfVecOfVecOfOptVecOfI32AsNlArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_173: pg_crud::OptVecOfVecOfVecOfOptVecOfOptI32AsNlArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_174: pg_crud::OptVecOfVecOfOptVecOfVecOfI32AsNlArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_175: pg_crud::OptVecOfVecOfOptVecOfVecOfOptI32AsNlArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_176: pg_crud::OptVecOfVecOfOptVecOfOptVecOfI32AsNlArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_177: pg_crud::OptVecOfVecOfOptVecOfOptVecOfOptI32AsNlArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_178: pg_crud::OptVecOfOptVecOfVecOfVecOfI32AsNlArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_179: pg_crud::OptVecOfOptVecOfVecOfVecOfOptI32AsNlArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_180: pg_crud::OptVecOfOptVecOfVecOfOptVecOfI32AsNlArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_181: pg_crud::OptVecOfOptVecOfVecOfOptVecOfOptI32AsNlArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_182: pg_crud::OptVecOfOptVecOfOptVecOfVecOfI32AsNlArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_183: pg_crud::OptVecOfOptVecOfOptVecOfVecOfOptI32AsNlArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_184: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfI32AsNlArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_185: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfOptI32AsNlArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_186: pg_crud::I64AsNnJsonbNbr,
    // pub field_187: pg_crud::OptI64AsNlJsonbNbr,
    // pub field_188: pg_crud::VecOfI64AsNnArrOfNnJsonbNbr,
    // pub field_189: pg_crud::VecOfOptI64AsNnArrOfNlJsonbNbr,
    // pub field_190: pg_crud::OptVecOfI64AsNlArrOfNnJsonbNbr,
    // pub field_191: pg_crud::OptVecOfOptI64AsNlArrOfNlJsonbNbr,
    // pub field_192: pg_crud::VecOfVecOfI64AsNnArrOfNnArrOfNnJsonbNbr,
    // pub field_193: pg_crud::VecOfVecOfOptI64AsNnArrOfNnArrOfNlJsonbNbr,
    // pub field_194: pg_crud::VecOfOptVecOfI64AsNnArrOfNlArrOfNnJsonbNbr,
    // pub field_195: pg_crud::VecOfOptVecOfOptI64AsNnArrOfNlArrOfNlJsonbNbr,
    // pub field_196: pg_crud::OptVecOfVecOfI64AsNlArrOfNnArrOfNnJsonbNbr,
    // pub field_197: pg_crud::OptVecOfVecOfOptI64AsNlArrOfNnArrOfNlJsonbNbr,
    // pub field_198: pg_crud::OptVecOfOptVecOfI64AsNlArrOfNlArrOfNnJsonbNbr,
    // pub field_199: pg_crud::OptVecOfOptVecOfOptI64AsNlArrOfNlArrOfNlJsonbNbr,
    // pub field_200: pg_crud::VecOfVecOfVecOfI64AsNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_201: pg_crud::VecOfVecOfVecOfOptI64AsNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_202: pg_crud::VecOfVecOfOptVecOfI64AsNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_203: pg_crud::VecOfVecOfOptVecOfOptI64AsNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_204: pg_crud::VecOfOptVecOfVecOfI64AsNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_205: pg_crud::VecOfOptVecOfVecOfOptI64AsNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_206: pg_crud::VecOfOptVecOfOptVecOfI64AsNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_207: pg_crud::VecOfOptVecOfOptVecOfOptI64AsNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_208: pg_crud::OptVecOfVecOfVecOfI64AsNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_209: pg_crud::OptVecOfVecOfVecOfOptI64AsNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_210: pg_crud::OptVecOfVecOfOptVecOfI64AsNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_211: pg_crud::OptVecOfVecOfOptVecOfOptI64AsNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_212: pg_crud::OptVecOfOptVecOfVecOfI64AsNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_213: pg_crud::OptVecOfOptVecOfVecOfOptI64AsNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_214: pg_crud::OptVecOfOptVecOfOptVecOfI64AsNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_215: pg_crud::OptVecOfOptVecOfOptVecOfOptI64AsNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_216: pg_crud::VecOfVecOfVecOfVecOfI64AsNnArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_217: pg_crud::VecOfVecOfVecOfVecOfOptI64AsNnArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_218: pg_crud::VecOfVecOfVecOfOptVecOfI64AsNnArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_219: pg_crud::VecOfVecOfVecOfOptVecOfOptI64AsNnArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_220: pg_crud::VecOfVecOfOptVecOfVecOfI64AsNnArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_221: pg_crud::VecOfVecOfOptVecOfVecOfOptI64AsNnArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_222: pg_crud::VecOfVecOfOptVecOfOptVecOfI64AsNnArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_223: pg_crud::VecOfVecOfOptVecOfOptVecOfOptI64AsNnArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_224: pg_crud::VecOfOptVecOfVecOfVecOfI64AsNnArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_225: pg_crud::VecOfOptVecOfVecOfVecOfOptI64AsNnArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_226: pg_crud::VecOfOptVecOfVecOfOptVecOfI64AsNnArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_227: pg_crud::VecOfOptVecOfVecOfOptVecOfOptI64AsNnArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_228: pg_crud::VecOfOptVecOfOptVecOfVecOfI64AsNnArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_229: pg_crud::VecOfOptVecOfOptVecOfVecOfOptI64AsNnArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_230: pg_crud::VecOfOptVecOfOptVecOfOptVecOfI64AsNnArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_231: pg_crud::VecOfOptVecOfOptVecOfOptVecOfOptI64AsNnArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_232: pg_crud::OptVecOfVecOfVecOfVecOfI64AsNlArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_233: pg_crud::OptVecOfVecOfVecOfVecOfOptI64AsNlArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_234: pg_crud::OptVecOfVecOfVecOfOptVecOfI64AsNlArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_235: pg_crud::OptVecOfVecOfVecOfOptVecOfOptI64AsNlArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_236: pg_crud::OptVecOfVecOfOptVecOfVecOfI64AsNlArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_237: pg_crud::OptVecOfVecOfOptVecOfVecOfOptI64AsNlArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_238: pg_crud::OptVecOfVecOfOptVecOfOptVecOfI64AsNlArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_239: pg_crud::OptVecOfVecOfOptVecOfOptVecOfOptI64AsNlArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_240: pg_crud::OptVecOfOptVecOfVecOfVecOfI64AsNlArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_241: pg_crud::OptVecOfOptVecOfVecOfVecOfOptI64AsNlArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_242: pg_crud::OptVecOfOptVecOfVecOfOptVecOfI64AsNlArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_243: pg_crud::OptVecOfOptVecOfVecOfOptVecOfOptI64AsNlArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_244: pg_crud::OptVecOfOptVecOfOptVecOfVecOfI64AsNlArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_245: pg_crud::OptVecOfOptVecOfOptVecOfVecOfOptI64AsNlArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_246: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfI64AsNlArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_247: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfOptI64AsNlArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_248: pg_crud::U8AsNnJsonbNbr,
    // pub field_249: pg_crud::OptU8AsNlJsonbNbr,
    // pub field_250: pg_crud::VecOfU8AsNnArrOfNnJsonbNbr,
    // pub field_251: pg_crud::VecOfOptU8AsNnArrOfNlJsonbNbr,
    // pub field_252: pg_crud::OptVecOfU8AsNlArrOfNnJsonbNbr,
    // pub field_253: pg_crud::OptVecOfOptU8AsNlArrOfNlJsonbNbr,
    // pub field_254: pg_crud::VecOfVecOfU8AsNnArrOfNnArrOfNnJsonbNbr,
    // pub field_255: pg_crud::VecOfVecOfOptU8AsNnArrOfNnArrOfNlJsonbNbr,
    // pub field_256: pg_crud::VecOfOptVecOfU8AsNnArrOfNlArrOfNnJsonbNbr,
    // pub field_257: pg_crud::VecOfOptVecOfOptU8AsNnArrOfNlArrOfNlJsonbNbr,
    // pub field_258: pg_crud::OptVecOfVecOfU8AsNlArrOfNnArrOfNnJsonbNbr,
    // pub field_259: pg_crud::OptVecOfVecOfOptU8AsNlArrOfNnArrOfNlJsonbNbr,
    // pub field_260: pg_crud::OptVecOfOptVecOfU8AsNlArrOfNlArrOfNnJsonbNbr,
    // pub field_261: pg_crud::OptVecOfOptVecOfOptU8AsNlArrOfNlArrOfNlJsonbNbr,
    // pub field_262: pg_crud::VecOfVecOfVecOfU8AsNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_263: pg_crud::VecOfVecOfVecOfOptU8AsNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_264: pg_crud::VecOfVecOfOptVecOfU8AsNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_265: pg_crud::VecOfVecOfOptVecOfOptU8AsNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_266: pg_crud::VecOfOptVecOfVecOfU8AsNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_267: pg_crud::VecOfOptVecOfVecOfOptU8AsNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_268: pg_crud::VecOfOptVecOfOptVecOfU8AsNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_269: pg_crud::VecOfOptVecOfOptVecOfOptU8AsNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_270: pg_crud::OptVecOfVecOfVecOfU8AsNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_271: pg_crud::OptVecOfVecOfVecOfOptU8AsNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_272: pg_crud::OptVecOfVecOfOptVecOfU8AsNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_273: pg_crud::OptVecOfVecOfOptVecOfOptU8AsNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_274: pg_crud::OptVecOfOptVecOfVecOfU8AsNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_275: pg_crud::OptVecOfOptVecOfVecOfOptU8AsNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_276: pg_crud::OptVecOfOptVecOfOptVecOfU8AsNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_277: pg_crud::OptVecOfOptVecOfOptVecOfOptU8AsNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_278: pg_crud::VecOfVecOfVecOfVecOfU8AsNnArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_279: pg_crud::VecOfVecOfVecOfVecOfOptU8AsNnArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_280: pg_crud::VecOfVecOfVecOfOptVecOfU8AsNnArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_281: pg_crud::VecOfVecOfVecOfOptVecOfOptU8AsNnArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_282: pg_crud::VecOfVecOfOptVecOfVecOfU8AsNnArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_283: pg_crud::VecOfVecOfOptVecOfVecOfOptU8AsNnArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_284: pg_crud::VecOfVecOfOptVecOfOptVecOfU8AsNnArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_285: pg_crud::VecOfVecOfOptVecOfOptVecOfOptU8AsNnArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_286: pg_crud::VecOfOptVecOfVecOfVecOfU8AsNnArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_287: pg_crud::VecOfOptVecOfVecOfVecOfOptU8AsNnArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_288: pg_crud::VecOfOptVecOfVecOfOptVecOfU8AsNnArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_289: pg_crud::VecOfOptVecOfVecOfOptVecOfOptU8AsNnArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_290: pg_crud::VecOfOptVecOfOptVecOfVecOfU8AsNnArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_291: pg_crud::VecOfOptVecOfOptVecOfVecOfOptU8AsNnArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_292: pg_crud::VecOfOptVecOfOptVecOfOptVecOfU8AsNnArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_293: pg_crud::VecOfOptVecOfOptVecOfOptVecOfOptU8AsNnArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_294: pg_crud::OptVecOfVecOfVecOfVecOfU8AsNlArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_295: pg_crud::OptVecOfVecOfVecOfVecOfOptU8AsNlArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_296: pg_crud::OptVecOfVecOfVecOfOptVecOfU8AsNlArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_297: pg_crud::OptVecOfVecOfVecOfOptVecOfOptU8AsNlArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_298: pg_crud::OptVecOfVecOfOptVecOfVecOfU8AsNlArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_299: pg_crud::OptVecOfVecOfOptVecOfVecOfOptU8AsNlArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_300: pg_crud::OptVecOfVecOfOptVecOfOptVecOfU8AsNlArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_301: pg_crud::OptVecOfVecOfOptVecOfOptVecOfOptU8AsNlArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_302: pg_crud::OptVecOfOptVecOfVecOfVecOfU8AsNlArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_303: pg_crud::OptVecOfOptVecOfVecOfVecOfOptU8AsNlArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_304: pg_crud::OptVecOfOptVecOfVecOfOptVecOfU8AsNlArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_305: pg_crud::OptVecOfOptVecOfVecOfOptVecOfOptU8AsNlArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_306: pg_crud::OptVecOfOptVecOfOptVecOfVecOfU8AsNlArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_307: pg_crud::OptVecOfOptVecOfOptVecOfVecOfOptU8AsNlArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_308: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfU8AsNlArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_309: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfOptU8AsNlArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_310: pg_crud::U16AsNnJsonbNbr,
    // pub field_311: pg_crud::OptU16AsNlJsonbNbr,
    // pub field_312: pg_crud::VecOfU16AsNnArrOfNnJsonbNbr,
    // pub field_313: pg_crud::VecOfOptU16AsNnArrOfNlJsonbNbr,
    // pub field_314: pg_crud::OptVecOfU16AsNlArrOfNnJsonbNbr,
    // pub field_315: pg_crud::OptVecOfOptU16AsNlArrOfNlJsonbNbr,
    // pub field_316: pg_crud::VecOfVecOfU16AsNnArrOfNnArrOfNnJsonbNbr,
    // pub field_317: pg_crud::VecOfVecOfOptU16AsNnArrOfNnArrOfNlJsonbNbr,
    // pub field_318: pg_crud::VecOfOptVecOfU16AsNnArrOfNlArrOfNnJsonbNbr,
    // pub field_319: pg_crud::VecOfOptVecOfOptU16AsNnArrOfNlArrOfNlJsonbNbr,
    // pub field_320: pg_crud::OptVecOfVecOfU16AsNlArrOfNnArrOfNnJsonbNbr,
    // pub field_321: pg_crud::OptVecOfVecOfOptU16AsNlArrOfNnArrOfNlJsonbNbr,
    // pub field_322: pg_crud::OptVecOfOptVecOfU16AsNlArrOfNlArrOfNnJsonbNbr,
    // pub field_323: pg_crud::OptVecOfOptVecOfOptU16AsNlArrOfNlArrOfNlJsonbNbr,
    // pub field_324: pg_crud::VecOfVecOfVecOfU16AsNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_325: pg_crud::VecOfVecOfVecOfOptU16AsNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_326: pg_crud::VecOfVecOfOptVecOfU16AsNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_327: pg_crud::VecOfVecOfOptVecOfOptU16AsNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_328: pg_crud::VecOfOptVecOfVecOfU16AsNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_329: pg_crud::VecOfOptVecOfVecOfOptU16AsNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_330: pg_crud::VecOfOptVecOfOptVecOfU16AsNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_331: pg_crud::VecOfOptVecOfOptVecOfOptU16AsNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_332: pg_crud::OptVecOfVecOfVecOfU16AsNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_333: pg_crud::OptVecOfVecOfVecOfOptU16AsNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_334: pg_crud::OptVecOfVecOfOptVecOfU16AsNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_335: pg_crud::OptVecOfVecOfOptVecOfOptU16AsNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_336: pg_crud::OptVecOfOptVecOfVecOfU16AsNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_337: pg_crud::OptVecOfOptVecOfVecOfOptU16AsNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_338: pg_crud::OptVecOfOptVecOfOptVecOfU16AsNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_339: pg_crud::OptVecOfOptVecOfOptVecOfOptU16AsNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_340: pg_crud::VecOfVecOfVecOfVecOfU16AsNnArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_341: pg_crud::VecOfVecOfVecOfVecOfOptU16AsNnArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_342: pg_crud::VecOfVecOfVecOfOptVecOfU16AsNnArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_343: pg_crud::VecOfVecOfVecOfOptVecOfOptU16AsNnArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_344: pg_crud::VecOfVecOfOptVecOfVecOfU16AsNnArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_345: pg_crud::VecOfVecOfOptVecOfVecOfOptU16AsNnArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_346: pg_crud::VecOfVecOfOptVecOfOptVecOfU16AsNnArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_347: pg_crud::VecOfVecOfOptVecOfOptVecOfOptU16AsNnArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_348: pg_crud::VecOfOptVecOfVecOfVecOfU16AsNnArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_349: pg_crud::VecOfOptVecOfVecOfVecOfOptU16AsNnArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_350: pg_crud::VecOfOptVecOfVecOfOptVecOfU16AsNnArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_351: pg_crud::VecOfOptVecOfVecOfOptVecOfOptU16AsNnArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_352: pg_crud::VecOfOptVecOfOptVecOfVecOfU16AsNnArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_353: pg_crud::VecOfOptVecOfOptVecOfVecOfOptU16AsNnArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_354: pg_crud::VecOfOptVecOfOptVecOfOptVecOfU16AsNnArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_355: pg_crud::VecOfOptVecOfOptVecOfOptVecOfOptU16AsNnArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_356: pg_crud::OptVecOfVecOfVecOfVecOfU16AsNlArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_357: pg_crud::OptVecOfVecOfVecOfVecOfOptU16AsNlArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_358: pg_crud::OptVecOfVecOfVecOfOptVecOfU16AsNlArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_359: pg_crud::OptVecOfVecOfVecOfOptVecOfOptU16AsNlArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_360: pg_crud::OptVecOfVecOfOptVecOfVecOfU16AsNlArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_361: pg_crud::OptVecOfVecOfOptVecOfVecOfOptU16AsNlArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_362: pg_crud::OptVecOfVecOfOptVecOfOptVecOfU16AsNlArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_363: pg_crud::OptVecOfVecOfOptVecOfOptVecOfOptU16AsNlArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_364: pg_crud::OptVecOfOptVecOfVecOfVecOfU16AsNlArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_365: pg_crud::OptVecOfOptVecOfVecOfVecOfOptU16AsNlArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_366: pg_crud::OptVecOfOptVecOfVecOfOptVecOfU16AsNlArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_367: pg_crud::OptVecOfOptVecOfVecOfOptVecOfOptU16AsNlArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_368: pg_crud::OptVecOfOptVecOfOptVecOfVecOfU16AsNlArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_369: pg_crud::OptVecOfOptVecOfOptVecOfVecOfOptU16AsNlArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_370: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfU16AsNlArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_371: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfOptU16AsNlArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_372: pg_crud::U32AsNnJsonbNbr,
    // pub field_373: pg_crud::OptU32AsNlJsonbNbr,
    // pub field_374: pg_crud::VecOfU32AsNnArrOfNnJsonbNbr,
    // pub field_375: pg_crud::VecOfOptU32AsNnArrOfNlJsonbNbr,
    // pub field_376: pg_crud::OptVecOfU32AsNlArrOfNnJsonbNbr,
    // pub field_377: pg_crud::OptVecOfOptU32AsNlArrOfNlJsonbNbr,
    // pub field_378: pg_crud::VecOfVecOfU32AsNnArrOfNnArrOfNnJsonbNbr,
    // pub field_379: pg_crud::VecOfVecOfOptU32AsNnArrOfNnArrOfNlJsonbNbr,
    // pub field_380: pg_crud::VecOfOptVecOfU32AsNnArrOfNlArrOfNnJsonbNbr,
    // pub field_381: pg_crud::VecOfOptVecOfOptU32AsNnArrOfNlArrOfNlJsonbNbr,
    // pub field_382: pg_crud::OptVecOfVecOfU32AsNlArrOfNnArrOfNnJsonbNbr,
    // pub field_383: pg_crud::OptVecOfVecOfOptU32AsNlArrOfNnArrOfNlJsonbNbr,
    // pub field_384: pg_crud::OptVecOfOptVecOfU32AsNlArrOfNlArrOfNnJsonbNbr,
    // pub field_385: pg_crud::OptVecOfOptVecOfOptU32AsNlArrOfNlArrOfNlJsonbNbr,
    // pub field_386: pg_crud::VecOfVecOfVecOfU32AsNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_387: pg_crud::VecOfVecOfVecOfOptU32AsNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_388: pg_crud::VecOfVecOfOptVecOfU32AsNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_389: pg_crud::VecOfVecOfOptVecOfOptU32AsNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_390: pg_crud::VecOfOptVecOfVecOfU32AsNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_391: pg_crud::VecOfOptVecOfVecOfOptU32AsNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_392: pg_crud::VecOfOptVecOfOptVecOfU32AsNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_393: pg_crud::VecOfOptVecOfOptVecOfOptU32AsNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_394: pg_crud::OptVecOfVecOfVecOfU32AsNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_395: pg_crud::OptVecOfVecOfVecOfOptU32AsNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_396: pg_crud::OptVecOfVecOfOptVecOfU32AsNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_397: pg_crud::OptVecOfVecOfOptVecOfOptU32AsNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_398: pg_crud::OptVecOfOptVecOfVecOfU32AsNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_399: pg_crud::OptVecOfOptVecOfVecOfOptU32AsNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_400: pg_crud::OptVecOfOptVecOfOptVecOfU32AsNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_401: pg_crud::OptVecOfOptVecOfOptVecOfOptU32AsNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_402: pg_crud::VecOfVecOfVecOfVecOfU32AsNnArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_403: pg_crud::VecOfVecOfVecOfVecOfOptU32AsNnArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_404: pg_crud::VecOfVecOfVecOfOptVecOfU32AsNnArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_405: pg_crud::VecOfVecOfVecOfOptVecOfOptU32AsNnArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_406: pg_crud::VecOfVecOfOptVecOfVecOfU32AsNnArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_407: pg_crud::VecOfVecOfOptVecOfVecOfOptU32AsNnArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_408: pg_crud::VecOfVecOfOptVecOfOptVecOfU32AsNnArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_409: pg_crud::VecOfVecOfOptVecOfOptVecOfOptU32AsNnArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_410: pg_crud::VecOfOptVecOfVecOfVecOfU32AsNnArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_411: pg_crud::VecOfOptVecOfVecOfVecOfOptU32AsNnArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_412: pg_crud::VecOfOptVecOfVecOfOptVecOfU32AsNnArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_413: pg_crud::VecOfOptVecOfVecOfOptVecOfOptU32AsNnArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_414: pg_crud::VecOfOptVecOfOptVecOfVecOfU32AsNnArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_415: pg_crud::VecOfOptVecOfOptVecOfVecOfOptU32AsNnArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_416: pg_crud::VecOfOptVecOfOptVecOfOptVecOfU32AsNnArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_417: pg_crud::VecOfOptVecOfOptVecOfOptVecOfOptU32AsNnArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_418: pg_crud::OptVecOfVecOfVecOfVecOfU32AsNlArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_419: pg_crud::OptVecOfVecOfVecOfVecOfOptU32AsNlArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_420: pg_crud::OptVecOfVecOfVecOfOptVecOfU32AsNlArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_421: pg_crud::OptVecOfVecOfVecOfOptVecOfOptU32AsNlArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_422: pg_crud::OptVecOfVecOfOptVecOfVecOfU32AsNlArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_423: pg_crud::OptVecOfVecOfOptVecOfVecOfOptU32AsNlArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_424: pg_crud::OptVecOfVecOfOptVecOfOptVecOfU32AsNlArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_425: pg_crud::OptVecOfVecOfOptVecOfOptVecOfOptU32AsNlArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_426: pg_crud::OptVecOfOptVecOfVecOfVecOfU32AsNlArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_427: pg_crud::OptVecOfOptVecOfVecOfVecOfOptU32AsNlArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_428: pg_crud::OptVecOfOptVecOfVecOfOptVecOfU32AsNlArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_429: pg_crud::OptVecOfOptVecOfVecOfOptVecOfOptU32AsNlArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_430: pg_crud::OptVecOfOptVecOfOptVecOfVecOfU32AsNlArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_431: pg_crud::OptVecOfOptVecOfOptVecOfVecOfOptU32AsNlArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_432: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfU32AsNlArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_433: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfOptU32AsNlArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_434: pg_crud::U64AsNnJsonbNbr,
    // pub field_435: pg_crud::OptU64AsNlJsonbNbr,
    // pub field_436: pg_crud::VecOfU64AsNnArrOfNnJsonbNbr,
    // pub field_437: pg_crud::VecOfOptU64AsNnArrOfNlJsonbNbr,
    // pub field_438: pg_crud::OptVecOfU64AsNlArrOfNnJsonbNbr,
    // pub field_439: pg_crud::OptVecOfOptU64AsNlArrOfNlJsonbNbr,
    // pub field_440: pg_crud::VecOfVecOfU64AsNnArrOfNnArrOfNnJsonbNbr,
    // pub field_441: pg_crud::VecOfVecOfOptU64AsNnArrOfNnArrOfNlJsonbNbr,
    // pub field_442: pg_crud::VecOfOptVecOfU64AsNnArrOfNlArrOfNnJsonbNbr,
    // pub field_443: pg_crud::VecOfOptVecOfOptU64AsNnArrOfNlArrOfNlJsonbNbr,
    // pub field_444: pg_crud::OptVecOfVecOfU64AsNlArrOfNnArrOfNnJsonbNbr,
    // pub field_445: pg_crud::OptVecOfVecOfOptU64AsNlArrOfNnArrOfNlJsonbNbr,
    // pub field_446: pg_crud::OptVecOfOptVecOfU64AsNlArrOfNlArrOfNnJsonbNbr,
    // pub field_447: pg_crud::OptVecOfOptVecOfOptU64AsNlArrOfNlArrOfNlJsonbNbr,
    // pub field_448: pg_crud::VecOfVecOfVecOfU64AsNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_449: pg_crud::VecOfVecOfVecOfOptU64AsNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_450: pg_crud::VecOfVecOfOptVecOfU64AsNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_451: pg_crud::VecOfVecOfOptVecOfOptU64AsNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_452: pg_crud::VecOfOptVecOfVecOfU64AsNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_453: pg_crud::VecOfOptVecOfVecOfOptU64AsNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_454: pg_crud::VecOfOptVecOfOptVecOfU64AsNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_455: pg_crud::VecOfOptVecOfOptVecOfOptU64AsNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_456: pg_crud::OptVecOfVecOfVecOfU64AsNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_457: pg_crud::OptVecOfVecOfVecOfOptU64AsNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_458: pg_crud::OptVecOfVecOfOptVecOfU64AsNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_459: pg_crud::OptVecOfVecOfOptVecOfOptU64AsNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_460: pg_crud::OptVecOfOptVecOfVecOfU64AsNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_461: pg_crud::OptVecOfOptVecOfVecOfOptU64AsNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_462: pg_crud::OptVecOfOptVecOfOptVecOfU64AsNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_463: pg_crud::OptVecOfOptVecOfOptVecOfOptU64AsNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_464: pg_crud::VecOfVecOfVecOfVecOfU64AsNnArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_465: pg_crud::VecOfVecOfVecOfVecOfOptU64AsNnArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_466: pg_crud::VecOfVecOfVecOfOptVecOfU64AsNnArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_467: pg_crud::VecOfVecOfVecOfOptVecOfOptU64AsNnArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_468: pg_crud::VecOfVecOfOptVecOfVecOfU64AsNnArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_469: pg_crud::VecOfVecOfOptVecOfVecOfOptU64AsNnArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_470: pg_crud::VecOfVecOfOptVecOfOptVecOfU64AsNnArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_471: pg_crud::VecOfVecOfOptVecOfOptVecOfOptU64AsNnArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_472: pg_crud::VecOfOptVecOfVecOfVecOfU64AsNnArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_473: pg_crud::VecOfOptVecOfVecOfVecOfOptU64AsNnArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_474: pg_crud::VecOfOptVecOfVecOfOptVecOfU64AsNnArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_475: pg_crud::VecOfOptVecOfVecOfOptVecOfOptU64AsNnArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_476: pg_crud::VecOfOptVecOfOptVecOfVecOfU64AsNnArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_477: pg_crud::VecOfOptVecOfOptVecOfVecOfOptU64AsNnArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_478: pg_crud::VecOfOptVecOfOptVecOfOptVecOfU64AsNnArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_479: pg_crud::VecOfOptVecOfOptVecOfOptVecOfOptU64AsNnArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_480: pg_crud::OptVecOfVecOfVecOfVecOfU64AsNlArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_481: pg_crud::OptVecOfVecOfVecOfVecOfOptU64AsNlArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_482: pg_crud::OptVecOfVecOfVecOfOptVecOfU64AsNlArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_483: pg_crud::OptVecOfVecOfVecOfOptVecOfOptU64AsNlArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_484: pg_crud::OptVecOfVecOfOptVecOfVecOfU64AsNlArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_485: pg_crud::OptVecOfVecOfOptVecOfVecOfOptU64AsNlArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_486: pg_crud::OptVecOfVecOfOptVecOfOptVecOfU64AsNlArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_487: pg_crud::OptVecOfVecOfOptVecOfOptVecOfOptU64AsNlArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_488: pg_crud::OptVecOfOptVecOfVecOfVecOfU64AsNlArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_489: pg_crud::OptVecOfOptVecOfVecOfVecOfOptU64AsNlArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_490: pg_crud::OptVecOfOptVecOfVecOfOptVecOfU64AsNlArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_491: pg_crud::OptVecOfOptVecOfVecOfOptVecOfOptU64AsNlArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_492: pg_crud::OptVecOfOptVecOfOptVecOfVecOfU64AsNlArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_493: pg_crud::OptVecOfOptVecOfOptVecOfVecOfOptU64AsNlArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_494: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfU64AsNlArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_495: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfOptU64AsNlArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_496: pg_crud::F32AsNnJsonbNbr,
    // pub field_497: pg_crud::OptF32AsNlJsonbNbr,
    // pub field_498: pg_crud::VecOfF32AsNnArrOfNnJsonbNbr,
    // pub field_499: pg_crud::VecOfOptF32AsNnArrOfNlJsonbNbr,
    // pub field_500: pg_crud::OptVecOfF32AsNlArrOfNnJsonbNbr,
    // pub field_501: pg_crud::OptVecOfOptF32AsNlArrOfNlJsonbNbr,
    // pub field_502: pg_crud::VecOfVecOfF32AsNnArrOfNnArrOfNnJsonbNbr,
    // pub field_503: pg_crud::VecOfVecOfOptF32AsNnArrOfNnArrOfNlJsonbNbr,
    // pub field_504: pg_crud::VecOfOptVecOfF32AsNnArrOfNlArrOfNnJsonbNbr,
    // pub field_505: pg_crud::VecOfOptVecOfOptF32AsNnArrOfNlArrOfNlJsonbNbr,
    // pub field_506: pg_crud::OptVecOfVecOfF32AsNlArrOfNnArrOfNnJsonbNbr,
    // pub field_507: pg_crud::OptVecOfVecOfOptF32AsNlArrOfNnArrOfNlJsonbNbr,
    // pub field_508: pg_crud::OptVecOfOptVecOfF32AsNlArrOfNlArrOfNnJsonbNbr,
    // pub field_509: pg_crud::OptVecOfOptVecOfOptF32AsNlArrOfNlArrOfNlJsonbNbr,
    // pub field_510: pg_crud::VecOfVecOfVecOfF32AsNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_511: pg_crud::VecOfVecOfVecOfOptF32AsNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_512: pg_crud::VecOfVecOfOptVecOfF32AsNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_513: pg_crud::VecOfVecOfOptVecOfOptF32AsNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_514: pg_crud::VecOfOptVecOfVecOfF32AsNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_515: pg_crud::VecOfOptVecOfVecOfOptF32AsNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_516: pg_crud::VecOfOptVecOfOptVecOfF32AsNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_517: pg_crud::VecOfOptVecOfOptVecOfOptF32AsNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_518: pg_crud::OptVecOfVecOfVecOfF32AsNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_519: pg_crud::OptVecOfVecOfVecOfOptF32AsNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_520: pg_crud::OptVecOfVecOfOptVecOfF32AsNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_521: pg_crud::OptVecOfVecOfOptVecOfOptF32AsNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_522: pg_crud::OptVecOfOptVecOfVecOfF32AsNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_523: pg_crud::OptVecOfOptVecOfVecOfOptF32AsNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_524: pg_crud::OptVecOfOptVecOfOptVecOfF32AsNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_525: pg_crud::OptVecOfOptVecOfOptVecOfOptF32AsNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_526: pg_crud::VecOfVecOfVecOfVecOfF32AsNnArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_527: pg_crud::VecOfVecOfVecOfVecOfOptF32AsNnArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_528: pg_crud::VecOfVecOfVecOfOptVecOfF32AsNnArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_529: pg_crud::VecOfVecOfVecOfOptVecOfOptF32AsNnArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_530: pg_crud::VecOfVecOfOptVecOfVecOfF32AsNnArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_531: pg_crud::VecOfVecOfOptVecOfVecOfOptF32AsNnArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_532: pg_crud::VecOfVecOfOptVecOfOptVecOfF32AsNnArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_533: pg_crud::VecOfVecOfOptVecOfOptVecOfOptF32AsNnArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_534: pg_crud::VecOfOptVecOfVecOfVecOfF32AsNnArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_535: pg_crud::VecOfOptVecOfVecOfVecOfOptF32AsNnArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_536: pg_crud::VecOfOptVecOfVecOfOptVecOfF32AsNnArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_537: pg_crud::VecOfOptVecOfVecOfOptVecOfOptF32AsNnArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_538: pg_crud::VecOfOptVecOfOptVecOfVecOfF32AsNnArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_539: pg_crud::VecOfOptVecOfOptVecOfVecOfOptF32AsNnArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_540: pg_crud::VecOfOptVecOfOptVecOfOptVecOfF32AsNnArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_541: pg_crud::VecOfOptVecOfOptVecOfOptVecOfOptF32AsNnArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_542: pg_crud::OptVecOfVecOfVecOfVecOfF32AsNlArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_543: pg_crud::OptVecOfVecOfVecOfVecOfOptF32AsNlArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_544: pg_crud::OptVecOfVecOfVecOfOptVecOfF32AsNlArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_545: pg_crud::OptVecOfVecOfVecOfOptVecOfOptF32AsNlArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_546: pg_crud::OptVecOfVecOfOptVecOfVecOfF32AsNlArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_547: pg_crud::OptVecOfVecOfOptVecOfVecOfOptF32AsNlArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_548: pg_crud::OptVecOfVecOfOptVecOfOptVecOfF32AsNlArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_549: pg_crud::OptVecOfVecOfOptVecOfOptVecOfOptF32AsNlArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_550: pg_crud::OptVecOfOptVecOfVecOfVecOfF32AsNlArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_551: pg_crud::OptVecOfOptVecOfVecOfVecOfOptF32AsNlArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_552: pg_crud::OptVecOfOptVecOfVecOfOptVecOfF32AsNlArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_553: pg_crud::OptVecOfOptVecOfVecOfOptVecOfOptF32AsNlArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_554: pg_crud::OptVecOfOptVecOfOptVecOfVecOfF32AsNlArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_555: pg_crud::OptVecOfOptVecOfOptVecOfVecOfOptF32AsNlArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_556: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfF32AsNlArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_557: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfOptF32AsNlArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_558: pg_crud::F64AsNnJsonbNbr,
    // pub field_559: pg_crud::OptF64AsNlJsonbNbr,
    // pub field_560: pg_crud::VecOfF64AsNnArrOfNnJsonbNbr,
    // pub field_561: pg_crud::VecOfOptF64AsNnArrOfNlJsonbNbr,
    // pub field_562: pg_crud::OptVecOfF64AsNlArrOfNnJsonbNbr,
    // pub field_563: pg_crud::OptVecOfOptF64AsNlArrOfNlJsonbNbr,
    // pub field_564: pg_crud::VecOfVecOfF64AsNnArrOfNnArrOfNnJsonbNbr,
    // pub field_565: pg_crud::VecOfVecOfOptF64AsNnArrOfNnArrOfNlJsonbNbr,
    // pub field_566: pg_crud::VecOfOptVecOfF64AsNnArrOfNlArrOfNnJsonbNbr,
    // pub field_567: pg_crud::VecOfOptVecOfOptF64AsNnArrOfNlArrOfNlJsonbNbr,
    // pub field_568: pg_crud::OptVecOfVecOfF64AsNlArrOfNnArrOfNnJsonbNbr,
    // pub field_569: pg_crud::OptVecOfVecOfOptF64AsNlArrOfNnArrOfNlJsonbNbr,
    // pub field_570: pg_crud::OptVecOfOptVecOfF64AsNlArrOfNlArrOfNnJsonbNbr,
    // pub field_571: pg_crud::OptVecOfOptVecOfOptF64AsNlArrOfNlArrOfNlJsonbNbr,
    // pub field_572: pg_crud::VecOfVecOfVecOfF64AsNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_573: pg_crud::VecOfVecOfVecOfOptF64AsNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_574: pg_crud::VecOfVecOfOptVecOfF64AsNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_575: pg_crud::VecOfVecOfOptVecOfOptF64AsNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_576: pg_crud::VecOfOptVecOfVecOfF64AsNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_577: pg_crud::VecOfOptVecOfVecOfOptF64AsNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_578: pg_crud::VecOfOptVecOfOptVecOfF64AsNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_579: pg_crud::VecOfOptVecOfOptVecOfOptF64AsNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_580: pg_crud::OptVecOfVecOfVecOfF64AsNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_581: pg_crud::OptVecOfVecOfVecOfOptF64AsNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_582: pg_crud::OptVecOfVecOfOptVecOfF64AsNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_583: pg_crud::OptVecOfVecOfOptVecOfOptF64AsNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_584: pg_crud::OptVecOfOptVecOfVecOfF64AsNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_585: pg_crud::OptVecOfOptVecOfVecOfOptF64AsNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_586: pg_crud::OptVecOfOptVecOfOptVecOfF64AsNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_587: pg_crud::OptVecOfOptVecOfOptVecOfOptF64AsNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_588: pg_crud::VecOfVecOfVecOfVecOfF64AsNnArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_589: pg_crud::VecOfVecOfVecOfVecOfOptF64AsNnArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_590: pg_crud::VecOfVecOfVecOfOptVecOfF64AsNnArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_591: pg_crud::VecOfVecOfVecOfOptVecOfOptF64AsNnArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_592: pg_crud::VecOfVecOfOptVecOfVecOfF64AsNnArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_593: pg_crud::VecOfVecOfOptVecOfVecOfOptF64AsNnArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_594: pg_crud::VecOfVecOfOptVecOfOptVecOfF64AsNnArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_595: pg_crud::VecOfVecOfOptVecOfOptVecOfOptF64AsNnArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_596: pg_crud::VecOfOptVecOfVecOfVecOfF64AsNnArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_597: pg_crud::VecOfOptVecOfVecOfVecOfOptF64AsNnArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_598: pg_crud::VecOfOptVecOfVecOfOptVecOfF64AsNnArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_599: pg_crud::VecOfOptVecOfVecOfOptVecOfOptF64AsNnArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_600: pg_crud::VecOfOptVecOfOptVecOfVecOfF64AsNnArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_601: pg_crud::VecOfOptVecOfOptVecOfVecOfOptF64AsNnArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_602: pg_crud::VecOfOptVecOfOptVecOfOptVecOfF64AsNnArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_603: pg_crud::VecOfOptVecOfOptVecOfOptVecOfOptF64AsNnArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_604: pg_crud::OptVecOfVecOfVecOfVecOfF64AsNlArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_605: pg_crud::OptVecOfVecOfVecOfVecOfOptF64AsNlArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_606: pg_crud::OptVecOfVecOfVecOfOptVecOfF64AsNlArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_607: pg_crud::OptVecOfVecOfVecOfOptVecOfOptF64AsNlArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_608: pg_crud::OptVecOfVecOfOptVecOfVecOfF64AsNlArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_609: pg_crud::OptVecOfVecOfOptVecOfVecOfOptF64AsNlArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_610: pg_crud::OptVecOfVecOfOptVecOfOptVecOfF64AsNlArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_611: pg_crud::OptVecOfVecOfOptVecOfOptVecOfOptF64AsNlArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_612: pg_crud::OptVecOfOptVecOfVecOfVecOfF64AsNlArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_613: pg_crud::OptVecOfOptVecOfVecOfVecOfOptF64AsNlArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_614: pg_crud::OptVecOfOptVecOfVecOfOptVecOfF64AsNlArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_615: pg_crud::OptVecOfOptVecOfVecOfOptVecOfOptF64AsNlArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_616: pg_crud::OptVecOfOptVecOfOptVecOfVecOfF64AsNlArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_617: pg_crud::OptVecOfOptVecOfOptVecOfVecOfOptF64AsNlArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_618: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfF64AsNlArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_619: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfOptF64AsNlArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_620: pg_crud::BoolAsNnJsonbBoolean,
    // pub field_621: pg_crud::OptBoolAsNlJsonbBoolean,
    // pub field_622: pg_crud::VecOfBoolAsNnArrOfNnJsonbBoolean,
    // pub field_623: pg_crud::VecOfOptBoolAsNnArrOfNlJsonbBoolean,
    // pub field_624: pg_crud::OptVecOfBoolAsNlArrOfNnJsonbBoolean,
    // pub field_625: pg_crud::OptVecOfOptBoolAsNlArrOfNlJsonbBoolean,
    // pub field_626: pg_crud::VecOfVecOfBoolAsNnArrOfNnArrOfNnJsonbBoolean,
    // pub field_627: pg_crud::VecOfVecOfOptBoolAsNnArrOfNnArrOfNlJsonbBoolean,
    // pub field_628: pg_crud::VecOfOptVecOfBoolAsNnArrOfNlArrOfNnJsonbBoolean,
    // pub field_629: pg_crud::VecOfOptVecOfOptBoolAsNnArrOfNlArrOfNlJsonbBoolean,
    // pub field_630: pg_crud::OptVecOfVecOfBoolAsNlArrOfNnArrOfNnJsonbBoolean,
    // pub field_631: pg_crud::OptVecOfVecOfOptBoolAsNlArrOfNnArrOfNlJsonbBoolean,
    // pub field_632: pg_crud::OptVecOfOptVecOfBoolAsNlArrOfNlArrOfNnJsonbBoolean,
    // pub field_633: pg_crud::OptVecOfOptVecOfOptBoolAsNlArrOfNlArrOfNlJsonbBoolean,
    // pub field_634: pg_crud::VecOfVecOfVecOfBoolAsNnArrOfNnArrOfNnArrOfNnJsonbBoolean,
    // pub field_635: pg_crud::VecOfVecOfVecOfOptBoolAsNnArrOfNnArrOfNnArrOfNlJsonbBoolean,
    // pub field_636: pg_crud::VecOfVecOfOptVecOfBoolAsNnArrOfNnArrOfNlArrOfNnJsonbBoolean,
    // pub field_637: pg_crud::VecOfVecOfOptVecOfOptBoolAsNnArrOfNnArrOfNlArrOfNlJsonbBoolean,
    // pub field_638: pg_crud::VecOfOptVecOfVecOfBoolAsNnArrOfNlArrOfNnArrOfNnJsonbBoolean,
    // pub field_639: pg_crud::VecOfOptVecOfVecOfOptBoolAsNnArrOfNlArrOfNnArrOfNlJsonbBoolean,
    // pub field_640: pg_crud::VecOfOptVecOfOptVecOfBoolAsNnArrOfNlArrOfNlArrOfNnJsonbBoolean,
    // pub field_641: pg_crud::VecOfOptVecOfOptVecOfOptBoolAsNnArrOfNlArrOfNlArrOfNlJsonbBoolean,
    // pub field_642: pg_crud::OptVecOfVecOfVecOfBoolAsNlArrOfNnArrOfNnArrOfNnJsonbBoolean,
    // pub field_643: pg_crud::OptVecOfVecOfVecOfOptBoolAsNlArrOfNnArrOfNnArrOfNlJsonbBoolean,
    // pub field_644: pg_crud::OptVecOfVecOfOptVecOfBoolAsNlArrOfNnArrOfNlArrOfNnJsonbBoolean,
    // pub field_645: pg_crud::OptVecOfVecOfOptVecOfOptBoolAsNlArrOfNnArrOfNlArrOfNlJsonbBoolean,
    // pub field_646: pg_crud::OptVecOfOptVecOfVecOfBoolAsNlArrOfNlArrOfNnArrOfNnJsonbBoolean,
    // pub field_647: pg_crud::OptVecOfOptVecOfVecOfOptBoolAsNlArrOfNlArrOfNnArrOfNlJsonbBoolean,
    // pub field_648: pg_crud::OptVecOfOptVecOfOptVecOfBoolAsNlArrOfNlArrOfNlArrOfNnJsonbBoolean,
    // pub field_649: pg_crud::OptVecOfOptVecOfOptVecOfOptBoolAsNlArrOfNlArrOfNlArrOfNlJsonbBoolean,
    // pub field_650: pg_crud::VecOfVecOfVecOfVecOfBoolAsNnArrOfNnArrOfNnArrOfNnArrOfNnJsonbBoolean,
    // pub field_651: pg_crud::VecOfVecOfVecOfVecOfOptBoolAsNnArrOfNnArrOfNnArrOfNnArrOfNlJsonbBoolean,
    // pub field_652: pg_crud::VecOfVecOfVecOfOptVecOfBoolAsNnArrOfNnArrOfNnArrOfNlArrOfNnJsonbBoolean,
    // pub field_653: pg_crud::VecOfVecOfVecOfOptVecOfOptBoolAsNnArrOfNnArrOfNnArrOfNlArrOfNlJsonbBoolean,
    // pub field_654: pg_crud::VecOfVecOfOptVecOfVecOfBoolAsNnArrOfNnArrOfNlArrOfNnArrOfNnJsonbBoolean,
    // pub field_655: pg_crud::VecOfVecOfOptVecOfVecOfOptBoolAsNnArrOfNnArrOfNlArrOfNnArrOfNlJsonbBoolean,
    // pub field_656: pg_crud::VecOfVecOfOptVecOfOptVecOfBoolAsNnArrOfNnArrOfNlArrOfNlArrOfNnJsonbBoolean,
    // pub field_657: pg_crud::VecOfVecOfOptVecOfOptVecOfOptBoolAsNnArrOfNnArrOfNlArrOfNlArrOfNlJsonbBoolean,
    // pub field_658: pg_crud::VecOfOptVecOfVecOfVecOfBoolAsNnArrOfNlArrOfNnArrOfNnArrOfNnJsonbBoolean,
    // pub field_659: pg_crud::VecOfOptVecOfVecOfVecOfOptBoolAsNnArrOfNlArrOfNnArrOfNnArrOfNlJsonbBoolean,
    // pub field_660: pg_crud::VecOfOptVecOfVecOfOptVecOfBoolAsNnArrOfNlArrOfNnArrOfNlArrOfNnJsonbBoolean,
    // pub field_661: pg_crud::VecOfOptVecOfVecOfOptVecOfOptBoolAsNnArrOfNlArrOfNnArrOfNlArrOfNlJsonbBoolean,
    // pub field_662: pg_crud::VecOfOptVecOfOptVecOfVecOfBoolAsNnArrOfNlArrOfNlArrOfNnArrOfNnJsonbBoolean,
    // pub field_663: pg_crud::VecOfOptVecOfOptVecOfVecOfOptBoolAsNnArrOfNlArrOfNlArrOfNnArrOfNlJsonbBoolean,
    // pub field_664: pg_crud::VecOfOptVecOfOptVecOfOptVecOfBoolAsNnArrOfNlArrOfNlArrOfNlArrOfNnJsonbBoolean,
    // pub field_665: pg_crud::VecOfOptVecOfOptVecOfOptVecOfOptBoolAsNnArrOfNlArrOfNlArrOfNlArrOfNlJsonbBoolean,
    // pub field_666: pg_crud::OptVecOfVecOfVecOfVecOfBoolAsNlArrOfNnArrOfNnArrOfNnArrOfNnJsonbBoolean,
    // pub field_667: pg_crud::OptVecOfVecOfVecOfVecOfOptBoolAsNlArrOfNnArrOfNnArrOfNnArrOfNlJsonbBoolean,
    // pub field_668: pg_crud::OptVecOfVecOfVecOfOptVecOfBoolAsNlArrOfNnArrOfNnArrOfNlArrOfNnJsonbBoolean,
    // pub field_669: pg_crud::OptVecOfVecOfVecOfOptVecOfOptBoolAsNlArrOfNnArrOfNnArrOfNlArrOfNlJsonbBoolean,
    // pub field_670: pg_crud::OptVecOfVecOfOptVecOfVecOfBoolAsNlArrOfNnArrOfNlArrOfNnArrOfNnJsonbBoolean,
    // pub field_671: pg_crud::OptVecOfVecOfOptVecOfVecOfOptBoolAsNlArrOfNnArrOfNlArrOfNnArrOfNlJsonbBoolean,
    // pub field_672: pg_crud::OptVecOfVecOfOptVecOfOptVecOfBoolAsNlArrOfNnArrOfNlArrOfNlArrOfNnJsonbBoolean,
    // pub field_673: pg_crud::OptVecOfVecOfOptVecOfOptVecOfOptBoolAsNlArrOfNnArrOfNlArrOfNlArrOfNlJsonbBoolean,
    // pub field_674: pg_crud::OptVecOfOptVecOfVecOfVecOfBoolAsNlArrOfNlArrOfNnArrOfNnArrOfNnJsonbBoolean,
    // pub field_675: pg_crud::OptVecOfOptVecOfVecOfVecOfOptBoolAsNlArrOfNlArrOfNnArrOfNnArrOfNlJsonbBoolean,
    // pub field_676: pg_crud::OptVecOfOptVecOfVecOfOptVecOfBoolAsNlArrOfNlArrOfNnArrOfNlArrOfNnJsonbBoolean,
    // pub field_677: pg_crud::OptVecOfOptVecOfVecOfOptVecOfOptBoolAsNlArrOfNlArrOfNnArrOfNlArrOfNlJsonbBoolean,
    // pub field_678: pg_crud::OptVecOfOptVecOfOptVecOfVecOfBoolAsNlArrOfNlArrOfNlArrOfNnArrOfNnJsonbBoolean,
    // pub field_679: pg_crud::OptVecOfOptVecOfOptVecOfVecOfOptBoolAsNlArrOfNlArrOfNlArrOfNnArrOfNlJsonbBoolean,
    // pub field_680: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfBoolAsNlArrOfNlArrOfNlArrOfNlArrOfNnJsonbBoolean,
    // pub field_681: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfOptBoolAsNlArrOfNlArrOfNlArrOfNlArrOfNlJsonbBoolean,
    // pub field_682: pg_crud::StringAsNnJsonbString,
    // pub field_683: pg_crud::OptStringAsNlJsonbString,
    // pub field_684: pg_crud::VecOfStringAsNnArrOfNnJsonbString,
    // pub field_685: pg_crud::VecOfOptStringAsNnArrOfNlJsonbString,
    // pub field_686: pg_crud::OptVecOfStringAsNlArrOfNnJsonbString,
    // pub field_687: pg_crud::OptVecOfOptStringAsNlArrOfNlJsonbString,
    // pub field_688: pg_crud::VecOfVecOfStringAsNnArrOfNnArrOfNnJsonbString,
    // pub field_689: pg_crud::VecOfVecOfOptStringAsNnArrOfNnArrOfNlJsonbString,
    // pub field_690: pg_crud::VecOfOptVecOfStringAsNnArrOfNlArrOfNnJsonbString,
    // pub field_691: pg_crud::VecOfOptVecOfOptStringAsNnArrOfNlArrOfNlJsonbString,
    // pub field_692: pg_crud::OptVecOfVecOfStringAsNlArrOfNnArrOfNnJsonbString,
    // pub field_693: pg_crud::OptVecOfVecOfOptStringAsNlArrOfNnArrOfNlJsonbString,
    // pub field_694: pg_crud::OptVecOfOptVecOfStringAsNlArrOfNlArrOfNnJsonbString,
    // pub field_695: pg_crud::OptVecOfOptVecOfOptStringAsNlArrOfNlArrOfNlJsonbString,
    // pub field_696: pg_crud::VecOfVecOfVecOfStringAsNnArrOfNnArrOfNnArrOfNnJsonbString,
    // pub field_697: pg_crud::VecOfVecOfVecOfOptStringAsNnArrOfNnArrOfNnArrOfNlJsonbString,
    // pub field_698: pg_crud::VecOfVecOfOptVecOfStringAsNnArrOfNnArrOfNlArrOfNnJsonbString,
    // pub field_699: pg_crud::VecOfVecOfOptVecOfOptStringAsNnArrOfNnArrOfNlArrOfNlJsonbString,
    // pub field_700: pg_crud::VecOfOptVecOfVecOfStringAsNnArrOfNlArrOfNnArrOfNnJsonbString,
    // pub field_701: pg_crud::VecOfOptVecOfVecOfOptStringAsNnArrOfNlArrOfNnArrOfNlJsonbString,
    // pub field_702: pg_crud::VecOfOptVecOfOptVecOfStringAsNnArrOfNlArrOfNlArrOfNnJsonbString,
    // pub field_703: pg_crud::VecOfOptVecOfOptVecOfOptStringAsNnArrOfNlArrOfNlArrOfNlJsonbString,
    // pub field_704: pg_crud::OptVecOfVecOfVecOfStringAsNlArrOfNnArrOfNnArrOfNnJsonbString,
    // pub field_705: pg_crud::OptVecOfVecOfVecOfOptStringAsNlArrOfNnArrOfNnArrOfNlJsonbString,
    // pub field_706: pg_crud::OptVecOfVecOfOptVecOfStringAsNlArrOfNnArrOfNlArrOfNnJsonbString,
    // pub field_707: pg_crud::OptVecOfVecOfOptVecOfOptStringAsNlArrOfNnArrOfNlArrOfNlJsonbString,
    // pub field_708: pg_crud::OptVecOfOptVecOfVecOfStringAsNlArrOfNlArrOfNnArrOfNnJsonbString,
    // pub field_709: pg_crud::OptVecOfOptVecOfVecOfOptStringAsNlArrOfNlArrOfNnArrOfNlJsonbString,
    // pub field_710: pg_crud::OptVecOfOptVecOfOptVecOfStringAsNlArrOfNlArrOfNlArrOfNnJsonbString,
    // pub field_711: pg_crud::OptVecOfOptVecOfOptVecOfOptStringAsNlArrOfNlArrOfNlArrOfNlJsonbString,
    // pub field_712: pg_crud::VecOfVecOfVecOfVecOfStringAsNnArrOfNnArrOfNnArrOfNnArrOfNnJsonbString,
    // pub field_713: pg_crud::VecOfVecOfVecOfVecOfOptStringAsNnArrOfNnArrOfNnArrOfNnArrOfNlJsonbString,
    // pub field_714: pg_crud::VecOfVecOfVecOfOptVecOfStringAsNnArrOfNnArrOfNnArrOfNlArrOfNnJsonbString,
    // pub field_715: pg_crud::VecOfVecOfVecOfOptVecOfOptStringAsNnArrOfNnArrOfNnArrOfNlArrOfNlJsonbString,
    // pub field_716: pg_crud::VecOfVecOfOptVecOfVecOfStringAsNnArrOfNnArrOfNlArrOfNnArrOfNnJsonbString,
    // pub field_717: pg_crud::VecOfVecOfOptVecOfVecOfOptStringAsNnArrOfNnArrOfNlArrOfNnArrOfNlJsonbString,
    // pub field_718: pg_crud::VecOfVecOfOptVecOfOptVecOfStringAsNnArrOfNnArrOfNlArrOfNlArrOfNnJsonbString,
    // pub field_719: pg_crud::VecOfVecOfOptVecOfOptVecOfOptStringAsNnArrOfNnArrOfNlArrOfNlArrOfNlJsonbString,
    // pub field_720: pg_crud::VecOfOptVecOfVecOfVecOfStringAsNnArrOfNlArrOfNnArrOfNnArrOfNnJsonbString,
    // pub field_721: pg_crud::VecOfOptVecOfVecOfVecOfOptStringAsNnArrOfNlArrOfNnArrOfNnArrOfNlJsonbString,
    // pub field_722: pg_crud::VecOfOptVecOfVecOfOptVecOfStringAsNnArrOfNlArrOfNnArrOfNlArrOfNnJsonbString,
    // pub field_723: pg_crud::VecOfOptVecOfVecOfOptVecOfOptStringAsNnArrOfNlArrOfNnArrOfNlArrOfNlJsonbString,
    // pub field_724: pg_crud::VecOfOptVecOfOptVecOfVecOfStringAsNnArrOfNlArrOfNlArrOfNnArrOfNnJsonbString,
    // pub field_725: pg_crud::VecOfOptVecOfOptVecOfVecOfOptStringAsNnArrOfNlArrOfNlArrOfNnArrOfNlJsonbString,
    // pub field_726: pg_crud::VecOfOptVecOfOptVecOfOptVecOfStringAsNnArrOfNlArrOfNlArrOfNlArrOfNnJsonbString,
    // pub field_727: pg_crud::VecOfOptVecOfOptVecOfOptVecOfOptStringAsNnArrOfNlArrOfNlArrOfNlArrOfNlJsonbString,
    // pub field_728: pg_crud::OptVecOfVecOfVecOfVecOfStringAsNlArrOfNnArrOfNnArrOfNnArrOfNnJsonbString,
    // pub field_729: pg_crud::OptVecOfVecOfVecOfVecOfOptStringAsNlArrOfNnArrOfNnArrOfNnArrOfNlJsonbString,
    // pub field_730: pg_crud::OptVecOfVecOfVecOfOptVecOfStringAsNlArrOfNnArrOfNnArrOfNlArrOfNnJsonbString,
    // pub field_731: pg_crud::OptVecOfVecOfVecOfOptVecOfOptStringAsNlArrOfNnArrOfNnArrOfNlArrOfNlJsonbString,
    // pub field_732: pg_crud::OptVecOfVecOfOptVecOfVecOfStringAsNlArrOfNnArrOfNlArrOfNnArrOfNnJsonbString,
    // pub field_733: pg_crud::OptVecOfVecOfOptVecOfVecOfOptStringAsNlArrOfNnArrOfNlArrOfNnArrOfNlJsonbString,
    // pub field_734: pg_crud::OptVecOfVecOfOptVecOfOptVecOfStringAsNlArrOfNnArrOfNlArrOfNlArrOfNnJsonbString,
    // pub field_735: pg_crud::OptVecOfVecOfOptVecOfOptVecOfOptStringAsNlArrOfNnArrOfNlArrOfNlArrOfNlJsonbString,
    // pub field_736: pg_crud::OptVecOfOptVecOfVecOfVecOfStringAsNlArrOfNlArrOfNnArrOfNnArrOfNnJsonbString,
    // pub field_737: pg_crud::OptVecOfOptVecOfVecOfVecOfOptStringAsNlArrOfNlArrOfNnArrOfNnArrOfNlJsonbString,
    // pub field_738: pg_crud::OptVecOfOptVecOfVecOfOptVecOfStringAsNlArrOfNlArrOfNnArrOfNlArrOfNnJsonbString,
    // pub field_739: pg_crud::OptVecOfOptVecOfVecOfOptVecOfOptStringAsNlArrOfNlArrOfNnArrOfNlArrOfNlJsonbString,
    // pub field_740: pg_crud::OptVecOfOptVecOfOptVecOfVecOfStringAsNlArrOfNlArrOfNlArrOfNnArrOfNnJsonbString,
    // pub field_741: pg_crud::OptVecOfOptVecOfOptVecOfVecOfOptStringAsNlArrOfNlArrOfNlArrOfNnArrOfNlJsonbString,
    // pub field_742: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfStringAsNlArrOfNlArrOfNlArrOfNlArrOfNnJsonbString,
    // pub field_743: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfOptStringAsNlArrOfNlArrOfNlArrOfNlArrOfNlJsonbString,
    // pub field_744: pg_crud::UuidUuidAsNnJsonbString,
    // pub field_745: pg_crud::OptUuidUuidAsNlJsonbString,
    // pub field_746: pg_crud::VecOfUuidUuidAsNnArrOfNnJsonbString,
    // pub field_747: pg_crud::VecOfOptUuidUuidAsNnArrOfNlJsonbString,
    // pub field_748: pg_crud::OptVecOfUuidUuidAsNlArrOfNnJsonbString,
    // pub field_749: pg_crud::OptVecOfOptUuidUuidAsNlArrOfNlJsonbString,
    // pub field_750: pg_crud::VecOfVecOfUuidUuidAsNnArrOfNnArrOfNnJsonbString,
    // pub field_751: pg_crud::VecOfVecOfOptUuidUuidAsNnArrOfNnArrOfNlJsonbString,
    // pub field_752: pg_crud::VecOfOptVecOfUuidUuidAsNnArrOfNlArrOfNnJsonbString,
    // pub field_753: pg_crud::VecOfOptVecOfOptUuidUuidAsNnArrOfNlArrOfNlJsonbString,
    // pub field_754: pg_crud::OptVecOfVecOfUuidUuidAsNlArrOfNnArrOfNnJsonbString,
    // pub field_755: pg_crud::OptVecOfVecOfOptUuidUuidAsNlArrOfNnArrOfNlJsonbString,
    // pub field_756: pg_crud::OptVecOfOptVecOfUuidUuidAsNlArrOfNlArrOfNnJsonbString,
    // pub field_757: pg_crud::OptVecOfOptVecOfOptUuidUuidAsNlArrOfNlArrOfNlJsonbString,
    // pub field_758: pg_crud::VecOfVecOfVecOfUuidUuidAsNnArrOfNnArrOfNnArrOfNnJsonbString,
    // pub field_759: pg_crud::VecOfVecOfVecOfOptUuidUuidAsNnArrOfNnArrOfNnArrOfNlJsonbString,
    // pub field_760: pg_crud::VecOfVecOfOptVecOfUuidUuidAsNnArrOfNnArrOfNlArrOfNnJsonbString,
    // pub field_761: pg_crud::VecOfVecOfOptVecOfOptUuidUuidAsNnArrOfNnArrOfNlArrOfNlJsonbString,
    // pub field_762: pg_crud::VecOfOptVecOfVecOfUuidUuidAsNnArrOfNlArrOfNnArrOfNnJsonbString,
    // pub field_763: pg_crud::VecOfOptVecOfVecOfOptUuidUuidAsNnArrOfNlArrOfNnArrOfNlJsonbString,
    // pub field_764: pg_crud::VecOfOptVecOfOptVecOfUuidUuidAsNnArrOfNlArrOfNlArrOfNnJsonbString,
    // pub field_765: pg_crud::VecOfOptVecOfOptVecOfOptUuidUuidAsNnArrOfNlArrOfNlArrOfNlJsonbString,
    // pub field_766: pg_crud::OptVecOfVecOfVecOfUuidUuidAsNlArrOfNnArrOfNnArrOfNnJsonbString,
    // pub field_767: pg_crud::OptVecOfVecOfVecOfOptUuidUuidAsNlArrOfNnArrOfNnArrOfNlJsonbString,
    // pub field_768: pg_crud::OptVecOfVecOfOptVecOfUuidUuidAsNlArrOfNnArrOfNlArrOfNnJsonbString,
    // pub field_769: pg_crud::OptVecOfVecOfOptVecOfOptUuidUuidAsNlArrOfNnArrOfNlArrOfNlJsonbString,
    // pub field_770: pg_crud::OptVecOfOptVecOfVecOfUuidUuidAsNlArrOfNlArrOfNnArrOfNnJsonbString,
    // pub field_771: pg_crud::OptVecOfOptVecOfVecOfOptUuidUuidAsNlArrOfNlArrOfNnArrOfNlJsonbString,
    // pub field_772: pg_crud::OptVecOfOptVecOfOptVecOfUuidUuidAsNlArrOfNlArrOfNlArrOfNnJsonbString,
    // pub field_773: pg_crud::OptVecOfOptVecOfOptVecOfOptUuidUuidAsNlArrOfNlArrOfNlArrOfNlJsonbString,
    // pub field_774: pg_crud::VecOfVecOfVecOfVecOfUuidUuidAsNnArrOfNnArrOfNnArrOfNnArrOfNnJsonbString,
    // pub field_775: pg_crud::VecOfVecOfVecOfVecOfOptUuidUuidAsNnArrOfNnArrOfNnArrOfNnArrOfNlJsonbString,
    // pub field_776: pg_crud::VecOfVecOfVecOfOptVecOfUuidUuidAsNnArrOfNnArrOfNnArrOfNlArrOfNnJsonbString,
    // pub field_777: pg_crud::VecOfVecOfVecOfOptVecOfOptUuidUuidAsNnArrOfNnArrOfNnArrOfNlArrOfNlJsonbString,
    // pub field_778: pg_crud::VecOfVecOfOptVecOfVecOfUuidUuidAsNnArrOfNnArrOfNlArrOfNnArrOfNnJsonbString,
    // pub field_779: pg_crud::VecOfVecOfOptVecOfVecOfOptUuidUuidAsNnArrOfNnArrOfNlArrOfNnArrOfNlJsonbString,
    // pub field_780: pg_crud::VecOfVecOfOptVecOfOptVecOfUuidUuidAsNnArrOfNnArrOfNlArrOfNlArrOfNnJsonbString,
    // pub field_781: pg_crud::VecOfVecOfOptVecOfOptVecOfOptUuidUuidAsNnArrOfNnArrOfNlArrOfNlArrOfNlJsonbString,
    // pub field_782: pg_crud::VecOfOptVecOfVecOfVecOfUuidUuidAsNnArrOfNlArrOfNnArrOfNnArrOfNnJsonbString,
    // pub field_783: pg_crud::VecOfOptVecOfVecOfVecOfOptUuidUuidAsNnArrOfNlArrOfNnArrOfNnArrOfNlJsonbString,
    // pub field_784: pg_crud::VecOfOptVecOfVecOfOptVecOfUuidUuidAsNnArrOfNlArrOfNnArrOfNlArrOfNnJsonbString,
    // pub field_785: pg_crud::VecOfOptVecOfVecOfOptVecOfOptUuidUuidAsNnArrOfNlArrOfNnArrOfNlArrOfNlJsonbString,
    // pub field_786: pg_crud::VecOfOptVecOfOptVecOfVecOfUuidUuidAsNnArrOfNlArrOfNlArrOfNnArrOfNnJsonbString,
    // pub field_787: pg_crud::VecOfOptVecOfOptVecOfVecOfOptUuidUuidAsNnArrOfNlArrOfNlArrOfNnArrOfNlJsonbString,
    // pub field_788: pg_crud::VecOfOptVecOfOptVecOfOptVecOfUuidUuidAsNnArrOfNlArrOfNlArrOfNlArrOfNnJsonbString,
    // pub field_789: pg_crud::VecOfOptVecOfOptVecOfOptVecOfOptUuidUuidAsNnArrOfNlArrOfNlArrOfNlArrOfNlJsonbString,
    // pub field_790: pg_crud::OptVecOfVecOfVecOfVecOfUuidUuidAsNlArrOfNnArrOfNnArrOfNnArrOfNnJsonbString,
    // pub field_791: pg_crud::OptVecOfVecOfVecOfVecOfOptUuidUuidAsNlArrOfNnArrOfNnArrOfNnArrOfNlJsonbString,
    // pub field_792: pg_crud::OptVecOfVecOfVecOfOptVecOfUuidUuidAsNlArrOfNnArrOfNnArrOfNlArrOfNnJsonbString,
    // pub field_793: pg_crud::OptVecOfVecOfVecOfOptVecOfOptUuidUuidAsNlArrOfNnArrOfNnArrOfNlArrOfNlJsonbString,
    // pub field_794: pg_crud::OptVecOfVecOfOptVecOfVecOfUuidUuidAsNlArrOfNnArrOfNlArrOfNnArrOfNnJsonbString,
    // pub field_795: pg_crud::OptVecOfVecOfOptVecOfVecOfOptUuidUuidAsNlArrOfNnArrOfNlArrOfNnArrOfNlJsonbString,
    // pub field_796: pg_crud::OptVecOfVecOfOptVecOfOptVecOfUuidUuidAsNlArrOfNnArrOfNlArrOfNlArrOfNnJsonbString,
    // pub field_797: pg_crud::OptVecOfVecOfOptVecOfOptVecOfOptUuidUuidAsNlArrOfNnArrOfNlArrOfNlArrOfNlJsonbString,
    // pub field_798: pg_crud::OptVecOfOptVecOfVecOfVecOfUuidUuidAsNlArrOfNlArrOfNnArrOfNnArrOfNnJsonbString,
    // pub field_799: pg_crud::OptVecOfOptVecOfVecOfVecOfOptUuidUuidAsNlArrOfNlArrOfNnArrOfNnArrOfNlJsonbString,
    // pub field_800: pg_crud::OptVecOfOptVecOfVecOfOptVecOfUuidUuidAsNlArrOfNlArrOfNnArrOfNlArrOfNnJsonbString,
    // pub field_801: pg_crud::OptVecOfOptVecOfVecOfOptVecOfOptUuidUuidAsNlArrOfNlArrOfNnArrOfNlArrOfNlJsonbString,
    // pub field_802: pg_crud::OptVecOfOptVecOfOptVecOfVecOfUuidUuidAsNlArrOfNlArrOfNlArrOfNnArrOfNnJsonbString,
    // pub field_803: pg_crud::OptVecOfOptVecOfOptVecOfVecOfOptUuidUuidAsNlArrOfNlArrOfNlArrOfNnArrOfNlJsonbString,
    // pub field_804: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfUuidUuidAsNlArrOfNlArrOfNlArrOfNlArrOfNnJsonbString,
    // pub field_805: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfOptUuidUuidAsNlArrOfNlArrOfNlArrOfNlArrOfNlJsonbString,
    pub field_806: crate::DoggieAsNnJsonbObj,
    pub field_808: crate::OptDoggieAsNlJsonbObj,
    pub field_807: crate::VecOfDoggieWithIdAsNnArrOfNnJsonbObjWithId,
    pub field_809: crate::OptVecOfDoggieWithIdAsNlArrOfNnJsonbObjWithId,
}
#[allow(unused_qualifications)]
#[allow(clippy::arbitrary_source_item_ordering)]
#[derive(Debug, Clone, Copy, pg_crud::GenPgJsonObj, Optml)]
#[pg_crud::pg_json_obj_config{
    {
        "pg_tbl_columns_write_into_pg_tbl_columns_using_pg_json_objs": "False",
        "whole_write_into_gen_pg_json_obj": "False",
        "vrt":
        // {
        //     "is_nl": "False",
        //     "pattern": "Stdrt",
        //     "trait_gen": "PgTypeAndPgJson"
        // }
        // ,
        // {
        //     "is_nl": "True",
        //     "pattern": "Stdrt",
        //     "trait_gen": "PgTypeAndPgJson"
        // }
        // ,
        // {
        //     "is_nl": "False",
        //     "pattern": "Arr",
        //     "trait_gen": "PgTypeAndPgJson"
        // }
        // ,
        {
            "is_nl": "True",
            "pattern": "Arr",
            "trait_gen": "PgTypeAndPgJson"
        }
    }
}]
pub struct Doggie {
    pub field_0: pg_crud::I8AsNnJsonbNbr,
    // pub field_1: pg_crud::OptI8AsNlJsonbNbr,
    // pub field_2: pg_crud::VecOfI8AsNnArrOfNnJsonbNbr,
    // pub field_3: pg_crud::VecOfOptI8AsNnArrOfNlJsonbNbr,
    // pub field_4: pg_crud::OptVecOfI8AsNlArrOfNnJsonbNbr,
    // pub field_5: pg_crud::OptVecOfOptI8AsNlArrOfNlJsonbNbr,
    // pub field_6: pg_crud::VecOfVecOfI8AsNnArrOfNnArrOfNnJsonbNbr,
    // pub field_7: pg_crud::VecOfVecOfOptI8AsNnArrOfNnArrOfNlJsonbNbr,
    // pub field_8: pg_crud::VecOfOptVecOfI8AsNnArrOfNlArrOfNnJsonbNbr,
    // pub field_9: pg_crud::VecOfOptVecOfOptI8AsNnArrOfNlArrOfNlJsonbNbr,
    // pub field_10: pg_crud::OptVecOfVecOfI8AsNlArrOfNnArrOfNnJsonbNbr,
    // pub field_11: pg_crud::OptVecOfVecOfOptI8AsNlArrOfNnArrOfNlJsonbNbr,
    // pub field_12: pg_crud::OptVecOfOptVecOfI8AsNlArrOfNlArrOfNnJsonbNbr,
    // pub field_13: pg_crud::OptVecOfOptVecOfOptI8AsNlArrOfNlArrOfNlJsonbNbr,
    // pub field_14: pg_crud::VecOfVecOfVecOfI8AsNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_15: pg_crud::VecOfVecOfVecOfOptI8AsNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_16: pg_crud::VecOfVecOfOptVecOfI8AsNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_17: pg_crud::VecOfVecOfOptVecOfOptI8AsNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_18: pg_crud::VecOfOptVecOfVecOfI8AsNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_19: pg_crud::VecOfOptVecOfVecOfOptI8AsNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_20: pg_crud::VecOfOptVecOfOptVecOfI8AsNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_21: pg_crud::VecOfOptVecOfOptVecOfOptI8AsNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_22: pg_crud::OptVecOfVecOfVecOfI8AsNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_23: pg_crud::OptVecOfVecOfVecOfOptI8AsNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_24: pg_crud::OptVecOfVecOfOptVecOfI8AsNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_25: pg_crud::OptVecOfVecOfOptVecOfOptI8AsNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_26: pg_crud::OptVecOfOptVecOfVecOfI8AsNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_27: pg_crud::OptVecOfOptVecOfVecOfOptI8AsNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_28: pg_crud::OptVecOfOptVecOfOptVecOfI8AsNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_29: pg_crud::OptVecOfOptVecOfOptVecOfOptI8AsNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_30: pg_crud::VecOfVecOfVecOfVecOfI8AsNnArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_31: pg_crud::VecOfVecOfVecOfVecOfOptI8AsNnArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_32: pg_crud::VecOfVecOfVecOfOptVecOfI8AsNnArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_33: pg_crud::VecOfVecOfVecOfOptVecOfOptI8AsNnArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_34: pg_crud::VecOfVecOfOptVecOfVecOfI8AsNnArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_35: pg_crud::VecOfVecOfOptVecOfVecOfOptI8AsNnArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_36: pg_crud::VecOfVecOfOptVecOfOptVecOfI8AsNnArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_37: pg_crud::VecOfVecOfOptVecOfOptVecOfOptI8AsNnArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_38: pg_crud::VecOfOptVecOfVecOfVecOfI8AsNnArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_39: pg_crud::VecOfOptVecOfVecOfVecOfOptI8AsNnArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_40: pg_crud::VecOfOptVecOfVecOfOptVecOfI8AsNnArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_41: pg_crud::VecOfOptVecOfVecOfOptVecOfOptI8AsNnArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_42: pg_crud::VecOfOptVecOfOptVecOfVecOfI8AsNnArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_43: pg_crud::VecOfOptVecOfOptVecOfVecOfOptI8AsNnArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_44: pg_crud::VecOfOptVecOfOptVecOfOptVecOfI8AsNnArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_45: pg_crud::VecOfOptVecOfOptVecOfOptVecOfOptI8AsNnArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_46: pg_crud::OptVecOfVecOfVecOfVecOfI8AsNlArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_47: pg_crud::OptVecOfVecOfVecOfVecOfOptI8AsNlArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_48: pg_crud::OptVecOfVecOfVecOfOptVecOfI8AsNlArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_49: pg_crud::OptVecOfVecOfVecOfOptVecOfOptI8AsNlArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_50: pg_crud::OptVecOfVecOfOptVecOfVecOfI8AsNlArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_51: pg_crud::OptVecOfVecOfOptVecOfVecOfOptI8AsNlArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_52: pg_crud::OptVecOfVecOfOptVecOfOptVecOfI8AsNlArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_53: pg_crud::OptVecOfVecOfOptVecOfOptVecOfOptI8AsNlArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_54: pg_crud::OptVecOfOptVecOfVecOfVecOfI8AsNlArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_55: pg_crud::OptVecOfOptVecOfVecOfVecOfOptI8AsNlArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_56: pg_crud::OptVecOfOptVecOfVecOfOptVecOfI8AsNlArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_57: pg_crud::OptVecOfOptVecOfVecOfOptVecOfOptI8AsNlArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_58: pg_crud::OptVecOfOptVecOfOptVecOfVecOfI8AsNlArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_59: pg_crud::OptVecOfOptVecOfOptVecOfVecOfOptI8AsNlArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_60: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfI8AsNlArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_61: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfOptI8AsNlArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_62: pg_crud::I16AsNnJsonbNbr,
    // pub field_63: pg_crud::OptI16AsNlJsonbNbr,
    // pub field_64: pg_crud::VecOfI16AsNnArrOfNnJsonbNbr,
    // pub field_65: pg_crud::VecOfOptI16AsNnArrOfNlJsonbNbr,
    // pub field_66: pg_crud::OptVecOfI16AsNlArrOfNnJsonbNbr,
    // pub field_67: pg_crud::OptVecOfOptI16AsNlArrOfNlJsonbNbr,
    // pub field_68: pg_crud::VecOfVecOfI16AsNnArrOfNnArrOfNnJsonbNbr,
    // pub field_69: pg_crud::VecOfVecOfOptI16AsNnArrOfNnArrOfNlJsonbNbr,
    // pub field_70: pg_crud::VecOfOptVecOfI16AsNnArrOfNlArrOfNnJsonbNbr,
    // pub field_71: pg_crud::VecOfOptVecOfOptI16AsNnArrOfNlArrOfNlJsonbNbr,
    // pub field_72: pg_crud::OptVecOfVecOfI16AsNlArrOfNnArrOfNnJsonbNbr,
    // pub field_73: pg_crud::OptVecOfVecOfOptI16AsNlArrOfNnArrOfNlJsonbNbr,
    // pub field_74: pg_crud::OptVecOfOptVecOfI16AsNlArrOfNlArrOfNnJsonbNbr,
    // pub field_75: pg_crud::OptVecOfOptVecOfOptI16AsNlArrOfNlArrOfNlJsonbNbr,
    // pub field_76: pg_crud::VecOfVecOfVecOfI16AsNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_77: pg_crud::VecOfVecOfVecOfOptI16AsNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_78: pg_crud::VecOfVecOfOptVecOfI16AsNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_79: pg_crud::VecOfVecOfOptVecOfOptI16AsNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_80: pg_crud::VecOfOptVecOfVecOfI16AsNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_81: pg_crud::VecOfOptVecOfVecOfOptI16AsNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_82: pg_crud::VecOfOptVecOfOptVecOfI16AsNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_83: pg_crud::VecOfOptVecOfOptVecOfOptI16AsNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_84: pg_crud::OptVecOfVecOfVecOfI16AsNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_85: pg_crud::OptVecOfVecOfVecOfOptI16AsNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_86: pg_crud::OptVecOfVecOfOptVecOfI16AsNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_87: pg_crud::OptVecOfVecOfOptVecOfOptI16AsNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_88: pg_crud::OptVecOfOptVecOfVecOfI16AsNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_89: pg_crud::OptVecOfOptVecOfVecOfOptI16AsNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_90: pg_crud::OptVecOfOptVecOfOptVecOfI16AsNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_91: pg_crud::OptVecOfOptVecOfOptVecOfOptI16AsNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_92: pg_crud::VecOfVecOfVecOfVecOfI16AsNnArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_93: pg_crud::VecOfVecOfVecOfVecOfOptI16AsNnArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_94: pg_crud::VecOfVecOfVecOfOptVecOfI16AsNnArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_95: pg_crud::VecOfVecOfVecOfOptVecOfOptI16AsNnArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_96: pg_crud::VecOfVecOfOptVecOfVecOfI16AsNnArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_97: pg_crud::VecOfVecOfOptVecOfVecOfOptI16AsNnArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_98: pg_crud::VecOfVecOfOptVecOfOptVecOfI16AsNnArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_99: pg_crud::VecOfVecOfOptVecOfOptVecOfOptI16AsNnArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_100: pg_crud::VecOfOptVecOfVecOfVecOfI16AsNnArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_101: pg_crud::VecOfOptVecOfVecOfVecOfOptI16AsNnArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_102: pg_crud::VecOfOptVecOfVecOfOptVecOfI16AsNnArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_103: pg_crud::VecOfOptVecOfVecOfOptVecOfOptI16AsNnArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_104: pg_crud::VecOfOptVecOfOptVecOfVecOfI16AsNnArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_105: pg_crud::VecOfOptVecOfOptVecOfVecOfOptI16AsNnArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_106: pg_crud::VecOfOptVecOfOptVecOfOptVecOfI16AsNnArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_107: pg_crud::VecOfOptVecOfOptVecOfOptVecOfOptI16AsNnArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_108: pg_crud::OptVecOfVecOfVecOfVecOfI16AsNlArrOfNnArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_109: pg_crud::OptVecOfVecOfVecOfVecOfOptI16AsNlArrOfNnArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_110: pg_crud::OptVecOfVecOfVecOfOptVecOfI16AsNlArrOfNnArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_111: pg_crud::OptVecOfVecOfVecOfOptVecOfOptI16AsNlArrOfNnArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_112: pg_crud::OptVecOfVecOfOptVecOfVecOfI16AsNlArrOfNnArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_113: pg_crud::OptVecOfVecOfOptVecOfVecOfOptI16AsNlArrOfNnArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_114: pg_crud::OptVecOfVecOfOptVecOfOptVecOfI16AsNlArrOfNnArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_115: pg_crud::OptVecOfVecOfOptVecOfOptVecOfOptI16AsNlArrOfNnArrOfNlArrOfNlArrOfNlJsonbNbr,
    // pub field_116: pg_crud::OptVecOfOptVecOfVecOfVecOfI16AsNlArrOfNlArrOfNnArrOfNnArrOfNnJsonbNbr,
    // pub field_117: pg_crud::OptVecOfOptVecOfVecOfVecOfOptI16AsNlArrOfNlArrOfNnArrOfNnArrOfNlJsonbNbr,
    // pub field_118: pg_crud::OptVecOfOptVecOfVecOfOptVecOfI16AsNlArrOfNlArrOfNnArrOfNlArrOfNnJsonbNbr,
    // pub field_119: pg_crud::OptVecOfOptVecOfVecOfOptVecOfOptI16AsNlArrOfNlArrOfNnArrOfNlArrOfNlJsonbNbr,
    // pub field_120: pg_crud::OptVecOfOptVecOfOptVecOfVecOfI16AsNlArrOfNlArrOfNlArrOfNnArrOfNnJsonbNbr,
    // pub field_121: pg_crud::OptVecOfOptVecOfOptVecOfVecOfOptI16AsNlArrOfNlArrOfNlArrOfNnArrOfNlJsonbNbr,
    // pub field_122: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfI16AsNlArrOfNlArrOfNlArrOfNlArrOfNnJsonbNbr,
    // pub field_123: pg_crud::OptVecOfOptVecOfOptVecOfOptVecOfOptI16AsNlArrOfNlArrOfNlArrOfNlArrOfNlJsonbNbr,
    pub field_806: crate::CatAsNnJsonbObj,
    pub field_807: crate::OptCatAsNlJsonbObj,
    pub field_808: crate::VecOfCatWithIdAsNnArrOfNnJsonbObjWithId,
    pub field_809: crate::OptVecOfCatWithIdAsNlArrOfNnJsonbObjWithId,
}
#[allow(unused_qualifications)]
#[allow(clippy::arbitrary_source_item_ordering)]
#[derive(Debug, Clone, Copy, pg_crud::GenPgJsonObj, Optml)]
#[pg_crud::pg_json_obj_config{
    {
        "pg_tbl_columns_write_into_pg_tbl_columns_using_pg_json_objs": "False",
        "whole_write_into_gen_pg_json_obj": "False",
        "vrt":
        // {
        //     "is_nl": "False",
        //     "pattern": "Stdrt",
        //     "trait_gen": "PgTypeAndPgJson"
        // }
        // ,
        // {
        //     "is_nl": "True",
        //     "pattern": "Stdrt",
        //     "trait_gen": "PgTypeAndPgJson"
        // }
        // ,
        // {
        //     "is_nl": "False",
        //     "pattern": "Arr",
        //     "trait_gen": "PgTypeAndPgJson"
        // }
        // ,
        {
            "is_nl": "True",
            "pattern": "Arr",
            "trait_gen": "PgTypeAndPgJson"
        }
    }
}]
pub struct Cat {
    pub field_0: pg_crud::I8AsNnJsonbNbr,
    // pub field_1: pg_crud::OptI8AsNlJsonbNbr,
    // pub field_2: pg_crud::VecOfI8AsNnArrOfNnJsonbNbr,
    // pub field_3: pg_crud::VecOfOptI8AsNnArrOfNlJsonbNbr,
    // pub field_4: pg_crud::OptVecOfI8AsNlArrOfNnJsonbNbr,
    // pub field_5: pg_crud::OptVecOfOptI8AsNlArrOfNlJsonbNbr,
    // pub field_6: pg_crud::VecOfVecOfI8AsNnArrOfNnArrOfNnJsonbNbr,
    // pub field_7: pg_crud::VecOfVecOfOptI8AsNnArrOfNnArrOfNlJsonbNbr,
    // pub field_8: pg_crud::VecOfOptVecOfI8AsNnArrOfNlArrOfNnJsonbNbr,
    // pub field_9: pg_crud::VecOfOptVecOfOptI8AsNnArrOfNlArrOfNlJsonbNbr,
    // pub field_10: pg_crud::OptVecOfVecOfI8AsNlArrOfNnArrOfNnJsonbNbr,
    // pub field_11: pg_crud::OptVecOfVecOfOptI8AsNlArrOfNnArrOfNlJsonbNbr,
    // pub field_12: pg_crud::OptVecOfOptVecOfI8AsNlArrOfNlArrOfNnJsonbNbr,
    // pub field_13: pg_crud::OptVecOfOptVecOfOptI8AsNlArrOfNlArrOfNlJsonbNbr,
}
