[package]
name = "generate_postgresql_json_types"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = {version = "=1.0.95"}
quote = {version = "=1.0.36"}
syn = {version = "=2.0.100"}
strum = {version = "=0.24.1"}
strum_macros = {version = "=0.24.3"}
schemars = {version = "=0.8.22"}
postgresql_crud_macros_common = {path = "../postgresql_crud_macros_common"}
constants = {path = "../../constants"}
enum_extension_lib = {path = "../../enum_extension_lib"}
generate_quotes = {path = "../../generate_quotes"}
panic_location = {path = "../../panic_location"}
macros_helpers = {path = "../../macros_helpers"}
naming = {path = "../../naming"}
token_patterns = {path = "../../token_patterns"}