[package]
name = "generate_postgresql_json_type"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = {version = "=1.0.81"}
quote = {version = "=1.0.36"}
syn = {version = "=2.0.60"}
postgresql_crud_macros_common = {path = "../postgresql_crud_common/postgresql_crud_macros_common"}
constants = {path = "../../constants"}
generate_quotes = {path = "../../generate_quotes"}
panic_location = {path = "../../panic_location"}
naming = {path = "../../naming"}
macros_helpers = {path = "../../macros_helpers"}
token_patterns = {path = "../../token_patterns"}

[lints]
workspace = true
