[package]
name = "postgresql_crud_macros_common"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = {version = "=1.0.81"}
quote = {version = "=1.0.36"}
naming_conventions = {path = "../../../naming_conventions"}
token_patterns = {path = "../../../token_patterns"}