[package]
edition = "2024"
name = "compile_time_git_info"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = {version = "=1.0.81"}
quote = {version = "=1.0.36"}
panic_location = {path = "../../panic_location"}

[lints]
workspace = true
