[package]
edition = "2021"
name = "tufa_common"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = {version = "=0.7.2", features = ["macros"]}
tower = {version = "=0.4.13"}
tower-http = {version = "=0.5.0", features = ["trace", "fs", "cors"]}
bytes = {version = "=1.2.1"}
chrono = {version = "=0.4"}
convert_case = {version = "=0.6.0"}
dotenv = {version = "=0.15.0"}
futures = {version = "=0.3.28"}
http = {version = "=0.2.9"}
regex = {version = "=1.9.3"}
config = {version = "=0.13.3"}
rand = {version = "=0.8", features = ["std_rng"]}
num_cpus = {version = "=1.15.0"}
argon2 = {version = "=0.4.0", features = ["std"]}
# mongodb = {version = "=2.0.1"}
reqwest = {version = "=0.11.17", default-features = false, features = ["json", "blocking", "rustls-tls", "cookies", "gzip", "brotli", "deflate", "trust-dns", "native-tls", "multipart", "stream", "cookies"]}
secrecy = {version = "=0.8", features = ["serde"]}
serde = {version = "=1.0", features = ["derive"]}
serde-aux = {version = "=4.0.0"}
serde-xml-rs = {version = "=0.6.0"}
serde_derive = {version = "=1.0"}
serde_json = {version = "=1.0"}
serde_path_to_error = {version = "=0.1.12"}
serde_with = {version = "=3.1.0"}
serde_urlencoded = {version = "=0.7.1"}
strum = {version = "=0.24.1"}
strum_macros = {version = "=0.24.3"}
thiserror = {version = "=1.0.48"}
tokio = {version = "=1.29.1", features = ["macros", "rt-multi-thread"]}
itertools = {version = "=0.10.1"}
uuid = {version = "=0.8", features = ["v4", "serde"]}
sqlx = {version = "=0.7.1", features = ["postgres", "uuid", "runtime-tokio"]}
valuable = {version = "=0.1.0", features = ["default", "std", "alloc", "derive", "valuable-derive"]}#maybe not all features needed
unicode-segmentation = {version = "=1"}
validator = {version = "=0.16.0"}
tracing = {version = "=0.1", features = ["log", "valuable"]}
tracing-subscriber = {version = "=0.3", features = ["registry", "env-filter"]}
tracing-bunyan-formatter = {version = "=0.3"}
tracing-log = {version = "=0.1"}
getset = {version = "=0.1.2"}
urlencoding = {version = "=2.1.2"}
utoipa = {version = "=4.1.0", features = ["axum_extras"]}
utoipa-swagger-ui = {version = "=5.0.0", features=["axum"]}
type_variants_from_reqwest_response = {path = "../type_variants_from_reqwest_response"}
from_str = {path = "../from_str"}
from_sqlx_postgres_error = {path = "../from_sqlx_postgres_error"}
compile_time_git_info = {path = "../compile_time_git_info"}
enum_extension = {path = "../enum_extension"}
error_occurence = {path = "../error_occurence"}
error_occurence_lib = {path = "../error_occurence_lib"}
generate_getter_traits_for_struct_fields = {path = "../generate_getter_traits_for_struct_fields"}
tufa_postgresql_crud = {path = "../tufa_postgresql_crud"}
init_from_env = {path = "../init_from_env"}
user_port_try_from_u16 = {path = "../user_port_try_from_u16"}

[lints]
workspace = true