use from_str::FromStr;
use location_lib::{Location, ToErrString, loc, loc::Loc};
use naming::{AscUcc, DescUcc, DisplayToScStr, DisplayToUccStr};
use optimal_pack::OptimalPack;
pub use pg_crud_common_and_macros_common::*;
use schemars::JsonSchema;
use serde::{Deserialize, Deserializer, Serialize};
use sqlx::{
    encode::IsNull,
    error::BoxDynError,
    postgres::{PgArgumentBuffer, PgArguments, PgValueRef},
    query::Query,
    types::Json,
    {Database, Decode, Encode, Postgres, Type},
};
use std::{
    error::Error as StdErEr,
    fmt::{
        Formatter, Result as StdFmtResult, {Debug, Display},
    },
};
use thiserror::Error;
use utoipa::ToSchema;
use uuid::Uuid;
macro_rules! trait_al {
    ($name:ident = $($bounds:tt)+) => {
        pub trait $name: $($bounds)+ {}
        impl<T: $($bounds)+> $name for T {}
    };
}
pub const DEFAULT_PAGINATION_LIMIT: i64 = 5;
trait_al!(DebugClonePartialEqAl = Debug + Clone + PartialEq);
trait_al!(DebugClonePartialEqSerializeAl = DebugClonePartialEqAl + Serialize);
trait_al!(DebugClonePartialEqSerdeAl = DebugClonePartialEqSerializeAl + for<'__> Deserialize<'__>);
trait_al!(
    DebugClonePartialEqSerdeDefaultSomeOneAl = DebugClonePartialEqSerdeAl + DfltOptSomeVecOneEl
);
trait_al!(SqlxEncodePgSqlxTypePgAl = for<'__> Encode<'__, Postgres> + Type<Postgres>);
trait_al!(UtoipaToSchemaAndSchemarsJsonSchemaAl = for<'__> ToSchema<'__> + JsonSchema);
trait_al!(TableTypeAl = DebugClonePartialEqSerdeDefaultSomeOneAl);
trait_al!(CreateAl = DebugClonePartialEqSerdeDefaultSomeOneAl);
trait_al!(CreateForQueryAl = DebugClonePartialEqSerializeAl + SqlxEncodePgSqlxTypePgAl);
trait_al!(SelectAl = DebugClonePartialEqSerdeDefaultSomeOneAl);
trait_al!(WhereAl = DebugClonePartialEqSerdeAl + for<'__> PgTypeWhereFilter<'__>);
trait_al!(ReadAl = DebugClonePartialEqSerdeAl);
trait_al!(ReadIdsAl = DebugClonePartialEqSerdeAl);
trait_al!(ReadInnerAl = DebugClonePartialEqAl);
trait_al!(UpdateAl = DebugClonePartialEqSerdeDefaultSomeOneAl);
trait_al!(UpdateForQueryAl = DebugClonePartialEqSerializeAl);
#[allow(clippy::arbitrary_source_item_ordering)]
pub trait PgType {
    //difference between Create and TableType - Create may not contain generated by pg id
    type TableType: TableTypeAl;
    fn create_table_column_qp(column: &dyn Display, _: bool) -> impl Display;
    type Create: CreateAl;
    fn create_qp(v: &Self::Create, incr: &mut u64) -> Result<String, QpEr>;
    fn create_qb(
        v: Self::Create,
        query: Query<'_, Postgres, PgArguments>,
    ) -> Result<Query<'_, Postgres, PgArguments>, String>;
    type Select: SelectAl;
    fn select_qp(v: &Self::Select, column: &str) -> Result<String, QpEr>;
    type Where: WhereAl;
    type Read: ReadAl + for<'__> Decode<'__, Postgres> + Type<Postgres>;
    fn normalize(v: Self::Read) -> Self::Read;
    type ReadIds: ReadIdsAl;
    fn select_only_ids_qp(column: &str) -> Result<String, QpEr>;
    type ReadInner: ReadInnerAl;
    fn into_inner(v: Self::Read) -> Self::ReadInner;
    type Update: UpdateAl;
    type UpdateForQuery: UpdateForQueryAl;
    fn update_qp(
        v: &Self::UpdateForQuery,
        jsonb_set_accumulator: &str,
        jsonb_set_target: &str,
        jsonb_set_path: &str,
        incr: &mut u64,
    ) -> Result<String, QpEr>;
    fn update_qb(
        v: Self::UpdateForQuery,
        query: Query<'_, Postgres, PgArguments>,
    ) -> Result<Query<'_, Postgres, PgArguments>, String>;
    fn select_only_updated_ids_qp(
        v: &Self::UpdateForQuery,
        column: &str,
        incr: &mut u64,
    ) -> Result<String, QpEr>;
    fn select_only_updated_ids_qb<'lt>(
        v: &'lt Self::UpdateForQuery,
        query: Query<'lt, Postgres, PgArguments>,
    ) -> Result<Query<'lt, Postgres, PgArguments>, String>;
}
#[allow(clippy::arbitrary_source_item_ordering)]
pub trait PgJsonType {
    type TableType: TableTypeAl + UtoipaToSchemaAndSchemarsJsonSchemaAl;
    type Create: CreateAl + UtoipaToSchemaAndSchemarsJsonSchemaAl;
    type CreateForQuery: CreateForQueryAl + From<Self::Create>;
    type Select: SelectAl + UtoipaToSchemaAndSchemarsJsonSchemaAl;
    fn select_qp(
        v: &Self::Select,
        fi: &str,
        column_field: &str,
        //todo remove this coz its used properly now
        column_field_for_er_message: &str,
        is_pg_type: bool,
    ) -> Result<String, QpEr>;
    type Where: WhereAl
        + UtoipaToSchemaAndSchemarsJsonSchemaAl
        + AllEnumVrtsArrDfltOptSomeVecOneEl
        + ToErrString;
    //todo impl get fields from read
    //todo mb add Decode trait here and Type
    type Read: ReadAl + UtoipaToSchemaAndSchemarsJsonSchemaAl + DfltOptSomeVecOneEl;
    type ReadIds: ReadIdsAl;
    fn select_only_ids_qp(column_field: &str) -> Result<String, QpEr>;
    type ReadInner: ReadInnerAl;
    fn into_inner(v: Self::Read) -> Self::ReadInner;
    type Update: UpdateAl + UtoipaToSchemaAndSchemarsJsonSchemaAl;
    type UpdateForQuery: UpdateForQueryAl + From<Self::Update>;
    fn update_qp(
        v: &Self::UpdateForQuery,
        jsonb_set_accumulator: &str,
        jsonb_set_target: &str,
        jsonb_set_path: &str,
        incr: &mut u64,
    ) -> Result<String, QpEr>;
    fn update_qb(
        v: Self::UpdateForQuery,
        query: Query<'_, Postgres, PgArguments>,
    ) -> Result<Query<'_, Postgres, PgArguments>, String>;
    fn select_only_updated_ids_qp(
        v: &Self::UpdateForQuery,
        fi: &str,
        column_field: &str,
        incr: &mut u64,
    ) -> Result<String, QpEr>;
    fn select_only_updated_ids_qb<'lt>(
        v: &'lt Self::UpdateForQuery,
        query: Query<'lt, Postgres, PgArguments>,
    ) -> Result<Query<'lt, Postgres, PgArguments>, String>;
    fn select_only_created_ids_qp(
        v: &Self::CreateForQuery,
        fi: &str,
        column_field: &str,
        incr: &mut u64,
    ) -> Result<String, QpEr>;
    fn select_only_created_ids_qb<'lt>(
        v: &'lt Self::CreateForQuery,
        query: Query<'lt, Postgres, PgArguments>,
    ) -> Result<Query<'lt, Postgres, PgArguments>, String>;
}
#[allow(clippy::arbitrary_source_item_ordering)]
pub trait PgTypePk {
    type PgType: PgType;
    type TableType: TableTypeAl + PartialOrd;
    fn read_ids_into_table_type(
        v: <Self::PgType as PgType>::ReadIds,
    ) -> <Self::PgType as PgType>::TableType;
    fn read_ids_into_read(v: <Self::PgType as PgType>::ReadIds) -> <Self::PgType as PgType>::Read;
    fn read_ids_into_update(
        v: <Self::PgType as PgType>::ReadIds,
    ) -> <Self::PgType as PgType>::Update;
    fn read_into_table_type(
        v: <Self::PgType as PgType>::Read,
    ) -> <Self::PgType as PgType>::TableType;
}
#[allow(clippy::arbitrary_source_item_ordering)]
pub trait PgTypeNotPk {
    type PgType: PgType;
    type Create: CreateAl + SqlxEncodePgSqlxTypePgAl;
}
#[allow(clippy::arbitrary_source_item_ordering)]
pub trait PgJsonTypeObjectVecElId {
    type PgJsonType: PgJsonType;
    type CreateForQuery: CreateForQueryAl
        + From<<Self::PgJsonType as PgJsonType>::Create>
        + From<<Self::PgJsonType as PgJsonType>::Update>;
    type Update: UpdateAl + UtoipaToSchemaAndSchemarsJsonSchemaAl + ToErrString;
    type ReadInner: ReadInnerAl;
    fn qb_string_as_pg_text_create_for_query(
        v: <Self::PgJsonType as PgJsonType>::CreateForQuery,
        query: Query<'_, Postgres, PgArguments>,
    ) -> Result<Query<'_, Postgres, PgArguments>, String>;
    fn qb_string_as_pg_text_update_for_query(
        v: <Self::PgJsonType as PgJsonType>::UpdateForQuery,
        query: Query<'_, Postgres, PgArguments>,
    ) -> Result<Query<'_, Postgres, PgArguments>, String>;
    fn get_inner(v: &<Self::PgJsonType as PgJsonType>::CreateForQuery) -> &Self::ReadInner;
    fn incr_checked_add_one(incr: &mut u64) -> Result<u64, QpEr>;
}
#[allow(clippy::arbitrary_source_item_ordering)]
#[cfg(feature = "test-utils")]
pub trait PgTypeTestCases {
    type PgType: PgType;
    type Select: SelectAl + DfltOptSomeVecOneElMaxPageSize;
    fn opt_vec_create() -> Option<Vec<<Self::PgType as PgType>::Create>>;
    fn read_ids_to_2_dims_vec_read_inner(
        read_ids: &<Self::PgType as PgType>::ReadIds,
    ) -> Vec<Vec<<Self::PgType as PgType>::ReadInner>>;
    fn read_inner_into_read_with_new_or_try_new_unwraped(
        v: <Self::PgType as PgType>::ReadInner,
    ) -> <Self::PgType as PgType>::Read;
    fn read_inner_into_update_with_new_or_try_new_unwraped(
        v: <Self::PgType as PgType>::ReadInner,
    ) -> <Self::PgType as PgType>::Update;
    fn update_to_read_ids(
        v: &<Self::PgType as PgType>::Update,
    ) -> <Self::PgType as PgType>::ReadIds;
    fn read_ids_to_opt_v_read_dflt_opt_some_vec_one_el(
        v: &<Self::PgType as PgType>::ReadIds,
    ) -> Option<V<<Self::PgType as PgType>::Read>>;
    fn previous_read_and_opt_update_into_read(
        read: <Self::PgType as PgType>::Read,
        opt_update: Option<<Self::PgType as PgType>::Update>,
    ) -> <Self::PgType as PgType>::Read;
    fn read_ids_and_create_into_read(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> <Self::PgType as PgType>::Read;
    fn read_ids_and_create_into_opt_v_read(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> Option<V<<Self::PgType as PgType>::Read>>;
    fn read_ids_and_create_into_table_type(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> <Self::PgType as PgType>::TableType;
    //todo add prefix pg_type or pg_json_type ?
    fn read_ids_and_create_into_where_equal(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> <Self::PgType as PgType>::Where;
    fn read_ids_and_create_into_vec_where_equal_using_fields(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> NotEmptyUniqueVec<<Self::PgType as PgType>::Where>;
    fn read_ids_and_create_into_opt_vec_where_equal_to_json_field(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> Option<NotEmptyUniqueVec<<Self::PgType as PgType>::Where>>;
    fn create_into_pg_type_opt_vec_where_dim_one_equal(
        create: <Self::PgType as PgType>::Create,
    ) -> Option<NotEmptyUniqueVec<<Self::PgType as PgType>::Where>>;
    fn pg_type_opt_vec_where_greater_than_test()
    -> Option<NotEmptyUniqueVec<PgTypeGreaterThanTest<Self::PgType>>>;
    fn read_ids_and_table_type_into_pg_type_opt_where_greater_than(
        greater_than_vrt: PgTypeGreaterThanVrt,
        read_ids: <Self::PgType as PgType>::ReadIds,
        table_type: <Self::PgType as PgType>::TableType,
    ) -> Option<<Self::PgType as PgType>::Where>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_dim_one_equal(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> Option<NotEmptyUniqueVec<<Self::PgType as PgType>::Where>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_dim_two_equal(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> Option<NotEmptyUniqueVec<<Self::PgType as PgType>::Where>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_dim_three_equal(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> Option<NotEmptyUniqueVec<<Self::PgType as PgType>::Where>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_dim_four_equal(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> Option<NotEmptyUniqueVec<<Self::PgType as PgType>::Where>>;
    fn create_into_pg_json_type_opt_vec_where_length_equal(
        create: <Self::PgType as PgType>::Create,
    ) -> Option<NotEmptyUniqueVec<<Self::PgType as PgType>::Where>>;
    fn create_into_pg_json_type_opt_vec_where_length_greater_than(
        create: <Self::PgType as PgType>::Create,
    ) -> Option<NotEmptyUniqueVec<<Self::PgType as PgType>::Where>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_greater_than(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> Option<NotEmptyUniqueVec<SingleOrMultiple<<Self::PgType as PgType>::Where>>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_between(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> Option<NotEmptyUniqueVec<SingleOrMultiple<<Self::PgType as PgType>::Where>>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_in(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> Option<NotEmptyUniqueVec<SingleOrMultiple<<Self::PgType as PgType>::Where>>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_regex(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> Option<NotEmptyUniqueVec<SingleOrMultiple<<Self::PgType as PgType>::Where>>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_contains_el_greater_than(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> Option<NotEmptyUniqueVec<SingleOrMultiple<<Self::PgType as PgType>::Where>>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_contains_el_regex(
        read_ids: <Self::PgType as PgType>::ReadIds,
        create: <Self::PgType as PgType>::Create,
    ) -> Option<NotEmptyUniqueVec<SingleOrMultiple<<Self::PgType as PgType>::Where>>>;
}
#[allow(clippy::arbitrary_source_item_ordering)]
#[derive(Debug, Clone, PartialEq, OptimalPack)]
pub struct PgTypeGreaterThanTest<T: PgType> {
    pub greater_than: <T as PgType>::TableType,
    pub create: <T as PgType>::Create,
    pub vrt: PgTypeGreaterThanVrt,
}
#[allow(clippy::arbitrary_source_item_ordering)]
#[derive(Debug, OptimalPack)]
pub struct PgTypeLengthGreaterThanTest<T: PgType> {
    pub create: <T as PgType>::Create,
    pub vrt: PgJsonTypeLengthGreaterThanVrt,
    pub length_greater_than: UnsignedPartOfI32,
}
#[allow(clippy::arbitrary_source_item_ordering)]
#[derive(Debug, OptimalPack)]
pub struct PgJsonTypeLengthGreaterThanTest<T: PgJsonType> {
    pub create: <T as PgJsonType>::Create,
    pub vrt: PgJsonTypeLengthGreaterThanVrt,
    pub length_greater_than: UnsignedPartOfI32,
}
#[allow(clippy::arbitrary_source_item_ordering)]
#[cfg(feature = "test-utils")]
pub trait PgJsonTypeTestCases {
    type PgJsonType: PgJsonType;
    type Select: SelectAl + UtoipaToSchemaAndSchemarsJsonSchemaAl + DfltOptSomeVecOneElMaxPageSize;
    fn opt_vec_create() -> Option<Vec<<Self::PgJsonType as PgJsonType>::Create>>;
    fn read_ids_to_2_dims_vec_read_inner(
        read_ids: &<Self::PgJsonType as PgJsonType>::ReadIds,
    ) -> Vec<Vec<<Self::PgJsonType as PgJsonType>::ReadInner>>;
    fn read_inner_into_read_with_new_or_try_new_unwraped(
        v: <Self::PgJsonType as PgJsonType>::ReadInner,
    ) -> <Self::PgJsonType as PgJsonType>::Read;
    fn read_inner_into_update_with_new_or_try_new_unwraped(
        v: <Self::PgJsonType as PgJsonType>::ReadInner,
    ) -> <Self::PgJsonType as PgJsonType>::Update;
    fn read_ids_into_opt_v_read_inner(
        v: <Self::PgJsonType as PgJsonType>::ReadIds,
    ) -> Option<V<<Self::PgJsonType as PgJsonType>::ReadInner>>;
    fn update_to_read_ids(
        v: &<Self::PgJsonType as PgJsonType>::Update,
    ) -> <Self::PgJsonType as PgJsonType>::ReadIds;
    fn read_ids_to_opt_v_read_dflt_opt_some_vec_one_el(
        v: &<Self::PgJsonType as PgJsonType>::ReadIds,
    ) -> Option<V<<Self::PgJsonType as PgJsonType>::Read>>;
    fn previous_read_and_opt_update_into_read(
        read: <Self::PgJsonType as PgJsonType>::Read,
        opt_update: Option<<Self::PgJsonType as PgJsonType>::Update>,
    ) -> <Self::PgJsonType as PgJsonType>::Read;
    fn read_ids_and_create_into_read(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> <Self::PgJsonType as PgJsonType>::Read;
    fn read_ids_and_create_into_opt_v_read(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> Option<V<<Self::PgJsonType as PgJsonType>::Read>>;
    fn read_ids_and_create_into_table_type(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> <Self::PgJsonType as PgJsonType>::TableType;
    fn read_ids_and_create_into_where_equal(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> <Self::PgJsonType as PgJsonType>::Where;
    fn read_ids_and_create_into_vec_where_equal_using_fields(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> NotEmptyUniqueVec<<Self::PgJsonType as PgJsonType>::Where>;
    fn read_ids_and_create_into_vec_where_equal_to_json_field(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> NotEmptyUniqueVec<<Self::PgJsonType as PgJsonType>::Where>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_dim_one_equal(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> Option<NotEmptyUniqueVec<<Self::PgJsonType as PgJsonType>::Where>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_dim_two_equal(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> Option<NotEmptyUniqueVec<<Self::PgJsonType as PgJsonType>::Where>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_dim_three_equal(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> Option<NotEmptyUniqueVec<<Self::PgJsonType as PgJsonType>::Where>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_dim_four_equal(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> Option<NotEmptyUniqueVec<<Self::PgJsonType as PgJsonType>::Where>>;
    fn create_into_pg_json_type_opt_vec_where_length_equal(
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> Option<NotEmptyUniqueVec<<Self::PgJsonType as PgJsonType>::Where>>;
    fn create_into_pg_json_type_opt_vec_where_length_greater_than(
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> Option<NotEmptyUniqueVec<<Self::PgJsonType as PgJsonType>::Where>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_greater_than(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> Option<NotEmptyUniqueVec<SingleOrMultiple<<Self::PgJsonType as PgJsonType>::Where>>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_between(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> Option<NotEmptyUniqueVec<SingleOrMultiple<<Self::PgJsonType as PgJsonType>::Where>>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_in(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> Option<NotEmptyUniqueVec<SingleOrMultiple<<Self::PgJsonType as PgJsonType>::Where>>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_regex(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> Option<NotEmptyUniqueVec<SingleOrMultiple<<Self::PgJsonType as PgJsonType>::Where>>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_contains_el_greater_than(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> Option<NotEmptyUniqueVec<SingleOrMultiple<<Self::PgJsonType as PgJsonType>::Where>>>;
    fn read_ids_and_create_into_pg_json_type_opt_vec_where_contains_el_regex(
        read_ids: <Self::PgJsonType as PgJsonType>::ReadIds,
        create: <Self::PgJsonType as PgJsonType>::Create,
    ) -> Option<NotEmptyUniqueVec<SingleOrMultiple<<Self::PgJsonType as PgJsonType>::Where>>>;
}
pub trait PgTypeWhereFilter<'query_lifetime> {
    fn qb(
        self,
        query: Query<'query_lifetime, Postgres, PgArguments>,
    ) -> Result<Query<'query_lifetime, Postgres, PgArguments>, String>;
    fn qp(&self, incr: &mut u64, column: &dyn Display, add_oprtr: bool) -> Result<String, QpEr>;
}
//todo custom deserialization - must not contain more than one el
#[derive(
    Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema, JsonSchema, OptimalPack,
)]
pub struct NullableJsonObjectPgTypeWhereFilter<
    T: Debug + PartialEq + Clone + for<'lt> PgTypeWhereFilter<'lt> + AllEnumVrtsArrDfltOptSomeVecOneEl,
>(pub Option<NotEmptyUniqueVec<T>>);
impl<'query_lifetime, T> PgTypeWhereFilter<'query_lifetime>
    for NullableJsonObjectPgTypeWhereFilter<T>
where
    T: Debug
        + PartialEq
        + Clone
        + for<'t_lifetime> PgTypeWhereFilter<'t_lifetime>
        + AllEnumVrtsArrDfltOptSomeVecOneEl,
{
    fn qb(
        self,
        query: Query<'query_lifetime, Postgres, PgArguments>,
    ) -> Result<Query<'query_lifetime, Postgres, PgArguments>, String> {
        match self.0 {
            Some(v) => v.qb(query),
            None => Ok(query), //todo mb wrong
        }
    }
    fn qp(&self, incr: &mut u64, column: &dyn Display, add_oprtr: bool) -> Result<String, QpEr> {
        self.0.as_ref().map_or_else(
            || Ok(format!("{column} = 'null'")),
            |v_b4a9fcfb| v_b4a9fcfb.qp(incr, column, add_oprtr),
        )
    }
}
impl<T> ToErrString for NullableJsonObjectPgTypeWhereFilter<T>
where
    T: Debug
        + PartialEq
        + Clone
        + for<'t_lifetime> PgTypeWhereFilter<'t_lifetime>
        + AllEnumVrtsArrDfltOptSomeVecOneEl,
{
    fn to_err_string(&self) -> String {
        format!("{self:#?}")
    }
}
impl<T> AllEnumVrtsArrDfltOptSomeVecOneEl for NullableJsonObjectPgTypeWhereFilter<T>
where
    T: Debug
        + PartialEq
        + Clone
        + for<'t_lifetime> PgTypeWhereFilter<'t_lifetime>
        + AllEnumVrtsArrDfltOptSomeVecOneEl,
{
    fn all_vrts_dflt_opt_some_vec_one_el() -> Vec<Self> {
        vec![Self(Some(DfltOptSomeVecOneEl::dflt_opt_some_vec_one_el()))]
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Error, Location, OptimalPack)]
pub enum QpEr {
    CheckedAdd { loc: Loc },
    WriteIntoBuffer { loc: Loc },
}
#[allow(clippy::arbitrary_source_item_ordering)]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, ToSchema, JsonSchema, OptimalPack)]
pub struct PgTypeWhere<T> {
    v: NotEmptyUniqueVec<T>,
    oprtr: Oprtr,
}
impl<T: PartialEq + Clone> PgTypeWhere<T> {
    #[must_use]
    pub const fn get_oprtr(&self) -> &Oprtr {
        &self.oprtr
    }
    #[must_use]
    pub const fn new(oprtr: Oprtr, v: NotEmptyUniqueVec<T>) -> Self {
        Self { v, oprtr }
    }
    pub fn try_new(oprtr: Oprtr, v: Vec<T>) -> Result<Self, NotEmptyUniqueVecTryNewEr<T>> {
        match NotEmptyUniqueVec::try_new(v) {
            Ok(v0) => Ok(Self { oprtr, v: v0 }),
            Err(er) => Err(er),
        }
    }
}
#[allow(unused_qualifications)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::arbitrary_source_item_ordering)]
const _: () = {
    #[expect(clippy::useless_attribute)]
    extern crate serde as _serde;
    #[automatically_derived]
    impl<'de, T: Debug + PartialEq + Clone + Deserialize<'de>> Deserialize<'de> for PgTypeWhere<T> {
        fn deserialize<__D>(__deserializer: __D) -> Result<Self, __D::Error>
        where
            __D: Deserializer<'de>,
        {
            #[expect(non_camel_case_types)]
            #[doc(hidden)]
            enum __Field {
                f0,
                f1,
                __ignore,
            }
            #[doc(hidden)]
            struct __FieldVisitor;
            impl _serde::de::Visitor<'_> for __FieldVisitor {
                type Value = __Field;
                fn expecting(&self, __f: &mut Formatter<'_>) -> _serde::__private228::fmt::Result {
                    _serde::__private228::Formatter::write_str(__f, "field identifier")
                }
                fn visit_u64<__E>(self, v: u64) -> Result<Self::Value, __E>
                where
                    __E: _serde::de::Error,
                {
                    match v {
                        0u64 => Ok(__Field::f0),
                        1u64 => Ok(__Field::f1),
                        _ => Ok(__Field::__ignore),
                    }
                }
                fn visit_str<__E>(self, v: &str) -> Result<Self::Value, __E>
                where
                    __E: _serde::de::Error,
                {
                    match v {
                        "oprtr" => Ok(__Field::f0),
                        "v" => Ok(__Field::f1),
                        _ => Ok(__Field::__ignore),
                    }
                }
                fn visit_bytes<__E>(self, v: &[u8]) -> Result<Self::Value, __E>
                where
                    __E: _serde::de::Error,
                {
                    match v {
                        b"oprtr" => Ok(__Field::f0),
                        b"v" => Ok(__Field::f1),
                        _ => Ok(__Field::__ignore),
                    }
                }
            }
            impl<'de> Deserialize<'de> for __Field {
                #[inline]
                fn deserialize<__D>(__deserializer: __D) -> Result<Self, __D::Error>
                where
                    __D: Deserializer<'de>,
                {
                    Deserializer::deserialize_identifier(__deserializer, __FieldVisitor)
                }
            }
            #[doc(hidden)]
            struct __Visitor<'de, PgTypeWhere> {
                marker: _serde::__private228::PhantomData<PgTypeWhere>,
                lifetime: _serde::__private228::PhantomData<&'de ()>,
            }
            impl<'de, T: Debug + PartialEq + Clone + Deserialize<'de>> _serde::de::Visitor<'de>
                for __Visitor<'de, T>
            {
                type Value = PgTypeWhere<T>;
                fn expecting(&self, __f: &mut Formatter<'_>) -> _serde::__private228::fmt::Result {
                    Formatter::write_str(__f, "struct PgTypeWhere")
                }
                #[inline]
                fn visit_seq<__A>(self, mut __seq: __A) -> Result<Self::Value, __A::Error>
                where
                    __A: _serde::de::SeqAccess<'de>,
                {
                    let Some(f0) = _serde::de::SeqAccess::next_element::<Oprtr>(&mut __seq)? else {
                        return Err(_serde::de::Error::invalid_length(
                            0usize,
                            &"struct PgTypeWhere with 2 els",
                        ));
                    };
                    let Some(f1) = _serde::de::SeqAccess::next_element::<Vec<T>>(&mut __seq)?
                    else {
                        return Err(_serde::de::Error::invalid_length(
                            1usize,
                            &"struct PgTypeWhere with 2 els",
                        ));
                    };
                    match PgTypeWhere::try_new(f0, f1) {
                        Ok(v) => Ok(v),
                        Err(er) => Err(serde::de::Error::custom(format!("{er:?}"))),
                    }
                }
                #[inline]
                fn visit_map<__A>(self, mut __map: __A) -> Result<Self::Value, __A::Error>
                where
                    __A: _serde::de::MapAccess<'de>,
                {
                    let mut f0: Option<Oprtr> = None;
                    let mut f1: Option<Vec<T>> = None;
                    while let Some(__k) = _serde::de::MapAccess::next_key::<__Field>(&mut __map)? {
                        match __k {
                            __Field::f0 => {
                                if Option::is_some(&f0) {
                                    return Err(
                                        <__A::Error as _serde::de::Error>::duplicate_field("oprtr"),
                                    );
                                }
                                f0 = Some(_serde::de::MapAccess::next_value::<Oprtr>(&mut __map)?);
                            }
                            __Field::f1 => {
                                if Option::is_some(&f1) {
                                    return Err(
                                        <__A::Error as _serde::de::Error>::duplicate_field("v"),
                                    );
                                }
                                f1 = Some(_serde::de::MapAccess::next_value::<Vec<T>>(&mut __map)?);
                            }
                            __Field::__ignore => {
                                let _: serde::de::IgnoredAny =
                                    _serde::de::MapAccess::next_value::<_serde::de::IgnoredAny>(
                                        &mut __map,
                                    )?;
                            }
                        }
                    }
                    let f0_v = match f0 {
                        Some(v) => v,
                        None => _serde::__private228::de::missing_field("oprtr")?,
                    };
                    let f1_v = match f1 {
                        Some(v) => v,
                        None => _serde::__private228::de::missing_field("v")?,
                    };
                    match PgTypeWhere::try_new(f0_v, f1_v) {
                        Ok(v) => Ok(v),
                        Err(er) => Err(serde::de::Error::custom(format!("{er:?}"))),
                    }
                }
            }
            #[doc(hidden)]
            const FIELDS: &[&str] = &["oprtr", "v"];
            Deserializer::deserialize_struct(
                __deserializer,
                "PgTypeWhere",
                FIELDS,
                __Visitor {
                    marker: _serde::__private228::PhantomData::<T>,
                    lifetime: _serde::__private228::PhantomData,
                },
            )
        }
    }
};
impl<'query_lifetime, T: PgTypeWhereFilter<'query_lifetime>> PgTypeWhereFilter<'query_lifetime>
    for PgTypeWhere<T>
{
    fn qb(
        self,
        mut query: Query<'query_lifetime, Postgres, PgArguments>,
    ) -> Result<Query<'query_lifetime, Postgres, PgArguments>, String> {
        for el in self.v.0 {
            match PgTypeWhereFilter::qb(el, query) {
                Ok(v) => {
                    query = v;
                }
                Err(er) => {
                    return Err(er);
                }
            }
        }
        Ok(query)
    }
    fn qp(&self, incr: &mut u64, column: &dyn Display, add_oprtr: bool) -> Result<String, QpEr> {
        let mut acc = String::default();
        let mut add_oprtr_inner_handle = false;
        for el in &self.v.0 {
            match PgTypeWhereFilter::qp(el, incr, column, add_oprtr_inner_handle) {
                Ok(v) => {
                    use std::fmt::Write as _;
                    if write!(acc, "{v} ").is_err() {
                        return Err(QpEr::WriteIntoBuffer { loc: loc!() });
                    }
                    add_oprtr_inner_handle = true;
                }
                Err(er) => {
                    return Err(er);
                }
            }
        }
        let _: Option<char> = acc.pop();
        Ok(format!("{}({acc})", &self.oprtr.to_qp(add_oprtr)))
    }
}
impl<T: Debug + PartialEq + Clone + AllEnumVrtsArrDfltOptSomeVecOneEl> DfltOptSomeVecOneEl
    for PgTypeWhere<T>
{
    fn dflt_opt_some_vec_one_el() -> Self {
        Self {
            oprtr: DfltOptSomeVecOneEl::dflt_opt_some_vec_one_el(),
            v: NotEmptyUniqueVec::try_new(
                AllEnumVrtsArrDfltOptSomeVecOneEl::all_vrts_dflt_opt_some_vec_one_el(),
            )
            .expect("a918b427"),
        }
    }
}
#[derive(
    Debug, Default, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, FromStr, OptimalPack,
)]
pub enum Order {
    #[serde(rename(serialize = "asc", deserialize = "asc"))]
    #[default]
    Asc,
    #[serde(rename(serialize = "desc", deserialize = "desc"))]
    Desc,
}
impl Display for Order {
    fn fmt(&self, f: &mut Formatter<'_>) -> StdFmtResult {
        match self {
            Self::Asc => write!(f, "{AscUcc}"),
            Self::Desc => write!(f, "{DescUcc}"),
        }
    }
}
impl DfltOptSomeVecOneEl for Order {
    fn dflt_opt_some_vec_one_el() -> Self {
        Self::default()
    }
}
impl Order {
    #[must_use]
    pub fn to_sc_str(&self) -> String {
        DisplayToScStr::case(&self)
    }
    #[must_use]
    pub fn to_ucc_str(&self) -> String {
        DisplayToUccStr::case(&self)
    }
}
#[derive(Debug, Serialize, Deserialize, OptimalPack)]
pub struct OrderBy<ColumnGeneric> {
    pub column: ColumnGeneric,
    pub order: Option<Order>,
}
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema, JsonSchema, OptimalPack,
)]
pub struct PgnBase {
    limit: i64,
    offset: i64,
}
impl PgnBase {
    #[must_use]
    pub const fn end(&self) -> i64 {
        self.offset.checked_add(self.limit).expect("8a297b66")
    }
    #[must_use]
    pub const fn new_unchecked(limit: i64, offset: i64) -> Self {
        Self { limit, offset }
    }
    #[must_use]
    pub const fn start(&self) -> i64 {
        self.offset
    }
}
impl<'query_lifetime> PgTypeWhereFilter<'query_lifetime> for PgnBase {
    fn qb(
        self,
        mut query: Query<'query_lifetime, Postgres, PgArguments>,
    ) -> Result<Query<'query_lifetime, Postgres, PgArguments>, String> {
        if let Err(er) = query.try_bind(self.limit) {
            return Err(er.to_string());
        }
        if let Err(er) = query.try_bind(self.offset) {
            return Err(er.to_string());
        }
        Ok(query)
    }
    fn qp(&self, incr: &mut u64, _: &dyn Display, _: bool) -> Result<String, QpEr> {
        let limit_incr = match incr_checked_add_one_returning_incr(incr) {
            Ok(v) => v,
            Err(er) => {
                return Err(er);
            }
        };
        let offset_incr = match incr_checked_add_one_returning_incr(incr) {
            Ok(v) => v,
            Err(er) => {
                return Err(er);
            }
        };
        Ok(format!("limit ${limit_incr} offset ${offset_incr}"))
    }
}
impl Default for PgnBase {
    fn default() -> Self {
        Self::new_unchecked(DEFAULT_PAGINATION_LIMIT, 0)
    }
}
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, ToSchema, JsonSchema, OptimalPack,
)]
pub struct PgnStartsWithZero(PgnBase);
#[derive(Debug, Serialize, Deserialize, Error, Location, OptimalPack)]
pub enum PgnStartsWithZeroTryNewEr {
    LimitIsLessThanOrEqualToZero {
        #[eo_to_err_string_serde]
        limit: i64,
        loc: Loc,
    },
    OffsetIsLessThanZero {
        #[eo_to_err_string_serde]
        offset: i64,
        loc: Loc,
    },
    OffsetPlusLimitIsIntOverflow {
        #[eo_to_err_string_serde]
        limit: i64,
        #[eo_to_err_string_serde]
        offset: i64,
        loc: Loc,
    },
}
impl PgnStartsWithZero {
    #[must_use]
    pub const fn end(&self) -> i64 {
        self.0.end()
    }
    #[must_use]
    pub const fn start(&self) -> i64 {
        self.0.start()
    }
    pub fn try_new(limit: i64, offset: i64) -> Result<Self, PgnStartsWithZeroTryNewEr> {
        if limit <= 0 || offset < 0 {
            if limit <= 0 {
                Err(PgnStartsWithZeroTryNewEr::LimitIsLessThanOrEqualToZero { limit, loc: loc!() })
            } else {
                Err(PgnStartsWithZeroTryNewEr::OffsetIsLessThanZero {
                    offset,
                    loc: loc!(),
                })
            }
        } else if offset.checked_add(limit).is_some() {
            Ok(Self(PgnBase::new_unchecked(limit, offset)))
        } else {
            Err(PgnStartsWithZeroTryNewEr::OffsetPlusLimitIsIntOverflow {
                limit,
                offset,
                loc: loc!(),
            })
        }
    }
}
#[allow(unused_qualifications)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::arbitrary_source_item_ordering)]
impl<'de> Deserialize<'de> for PgnStartsWithZero {
    fn deserialize<__D>(__deserializer: __D) -> Result<Self, __D::Error>
    where
        __D: Deserializer<'de>,
    {
        #[expect(non_camel_case_types)]
        #[doc(hidden)]
        enum __Field {
            f0,
            f1,
            __ignore,
        }
        #[doc(hidden)]
        struct __FieldVisitor;
        impl serde::de::Visitor<'_> for __FieldVisitor {
            type Value = __Field;
            fn expecting(&self, __f: &mut Formatter<'_>) -> serde::__private228::fmt::Result {
                serde::__private228::Formatter::write_str(__f, "field identifier")
            }
            fn visit_u64<__E>(self, v: u64) -> Result<Self::Value, __E>
            where
                __E: serde::de::Error,
            {
                match v {
                    0u64 => Ok(__Field::f0),
                    1u64 => Ok(__Field::f1),
                    _ => Ok(__Field::__ignore),
                }
            }
            fn visit_str<__E>(self, v: &str) -> Result<Self::Value, __E>
            where
                __E: serde::de::Error,
            {
                match v {
                    "limit" => Ok(__Field::f0),
                    "offset" => Ok(__Field::f1),
                    _ => Ok(__Field::__ignore),
                }
            }
            fn visit_bytes<__E>(self, v: &[u8]) -> Result<Self::Value, __E>
            where
                __E: serde::de::Error,
            {
                match v {
                    b"limit" => Ok(__Field::f0),
                    b"offset" => Ok(__Field::f1),
                    _ => Ok(__Field::__ignore),
                }
            }
        }
        impl<'de> Deserialize<'de> for __Field {
            #[inline]
            fn deserialize<__D>(__deserializer: __D) -> Result<Self, __D::Error>
            where
                __D: Deserializer<'de>,
            {
                Deserializer::deserialize_identifier(__deserializer, __FieldVisitor)
            }
        }
        #[doc(hidden)]
        struct __Visitor<'de> {
            marker: serde::__private228::PhantomData<PgnStartsWithZero>,
            lifetime: serde::__private228::PhantomData<&'de ()>,
        }
        impl<'de> serde::de::Visitor<'de> for __Visitor<'de> {
            type Value = PgnStartsWithZero;
            fn expecting(&self, __f: &mut Formatter<'_>) -> serde::__private228::fmt::Result {
                Formatter::write_str(__f, "struct PgnStartsWithZero")
            }
            #[inline]
            fn visit_seq<__A>(self, mut __seq: __A) -> Result<Self::Value, __A::Error>
            where
                __A: serde::de::SeqAccess<'de>,
            {
                let Some(f0) = serde::de::SeqAccess::next_element::<i64>(&mut __seq)? else {
                    return Err(serde::de::Error::invalid_length(
                        0usize,
                        &"struct PgnStartsWithZero with 2 els",
                    ));
                };
                let Some(f1) = serde::de::SeqAccess::next_element::<i64>(&mut __seq)? else {
                    return Err(serde::de::Error::invalid_length(
                        1usize,
                        &"struct PgnStartsWithZero with 2 els",
                    ));
                };
                match PgnStartsWithZero::try_new(f0, f1) {
                    Ok(v) => Ok(v),
                    Err(er) => Err(serde::de::Error::custom(format!("{er:?}"))), //todo use serde_json::to_string(&er).unwrap_or_else(|_|"failed to serialize er".into())
                }
            }
            #[inline]
            fn visit_map<__A>(self, mut __map: __A) -> Result<Self::Value, __A::Error>
            where
                __A: serde::de::MapAccess<'de>,
            {
                let mut f0: Option<i64> = None;
                let mut f1: Option<i64> = None;
                while let Some(__k) = serde::de::MapAccess::next_key::<__Field>(&mut __map)? {
                    match __k {
                        __Field::f0 => {
                            if Option::is_some(&f0) {
                                return Err(<__A::Error as serde::de::Error>::duplicate_field(
                                    "limit",
                                ));
                            }
                            f0 = Some(serde::de::MapAccess::next_value::<i64>(&mut __map)?);
                        }
                        __Field::f1 => {
                            if Option::is_some(&f1) {
                                return Err(<__A::Error as serde::de::Error>::duplicate_field(
                                    "offset",
                                ));
                            }
                            f1 = Some(serde::de::MapAccess::next_value::<i64>(&mut __map)?);
                        }
                        __Field::__ignore => {
                            let _: serde::de::IgnoredAny =
                                serde::de::MapAccess::next_value::<serde::de::IgnoredAny>(
                                    &mut __map,
                                )?;
                        }
                    }
                }
                let f0_v = match f0 {
                    Some(v) => v,
                    None => serde::__private228::de::missing_field("limit")?,
                };
                let f1_v = match f1 {
                    Some(v) => v,
                    None => serde::__private228::de::missing_field("offset")?,
                };
                match PgnStartsWithZero::try_new(f0_v, f1_v) {
                    Ok(v) => Ok(v),
                    Err(er) => Err(serde::de::Error::custom(format!("{er:?}"))),
                }
            }
        }
        #[doc(hidden)]
        const FIELDS: &[&str] = &["limit", "offset"];
        Deserializer::deserialize_struct(
            __deserializer,
            "PgnStartsWithZero",
            FIELDS,
            __Visitor {
                marker: serde::__private228::PhantomData::<Self>,
                lifetime: serde::__private228::PhantomData,
            },
        )
    }
}
impl<'query_lifetime> PgTypeWhereFilter<'query_lifetime> for PgnStartsWithZero {
    fn qb(
        self,
        query: Query<'query_lifetime, Postgres, PgArguments>,
    ) -> Result<Query<'query_lifetime, Postgres, PgArguments>, String> {
        self.0.qb(query)
    }
    fn qp(&self, incr: &mut u64, column: &dyn Display, add_oprtr: bool) -> Result<String, QpEr> {
        self.0.qp(incr, column, add_oprtr)
    }
}
impl DfltOptSomeVecOneEl for PgnStartsWithZero {
    #[inline]
    fn dflt_opt_some_vec_one_el() -> Self {
        Self(PgnBase::new_unchecked(DEFAULT_PAGINATION_LIMIT, 0))
    }
}
impl DfltOptSomeVecOneElMaxPageSize for PgnStartsWithZero {
    #[inline]
    fn dflt_opt_some_vec_one_el_max_page_size() -> Self {
        Self(PgnBase::new_unchecked(i32::MAX.into(), 0))
    }
}
//this needed coz serde Option<Opt<T>> #[serde(skip_serializing_if = "Option::is_none")] - if both opts: inner and parent is null then it skip - its not correct
#[derive(
    Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema, JsonSchema, OptimalPack,
)]
pub struct V<T> {
    pub v: T,
}
//todo ExactSizeIterator now is not a solution. er[E0658]: use of unstable library feature `exact_size_is_empty`. mb rewrite it later
pub trait IsStringEmpty {
    fn is_string_empty(&self) -> bool;
}
#[derive(Debug, Serialize, Deserialize, Error, Location, OptimalPack)]
pub enum NotEmptyUniqueVecTryNewEr<T> {
    IsEmpty {
        loc: Loc,
    },
    NotUnique {
        #[eo_to_err_string_serde]
        v: T,
        loc: Loc,
    },
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, ToSchema, JsonSchema, OptimalPack)]
pub struct NotEmptyUniqueVec<T>(Vec<T>);
impl<T: PartialEq + Clone> NotEmptyUniqueVec<T> {
    #[must_use]
    pub fn into_vec(self) -> Vec<T> {
        self.0
    }
    #[must_use]
    pub const fn to_vec(&self) -> &Vec<T> {
        &self.0
    }
    pub fn try_new(v: Vec<T>) -> Result<Self, NotEmptyUniqueVecTryNewEr<T>> {
        if v.is_empty() {
            return Err(NotEmptyUniqueVecTryNewEr::IsEmpty { loc: loc!() });
        }
        {
            let mut acc = Vec::new();
            for el in &v {
                if acc.contains(&el) {
                    return Err(NotEmptyUniqueVecTryNewEr::NotUnique {
                        v: el.clone(),
                        loc: loc!(),
                    });
                }
                acc.push(el);
            }
        }
        Ok(Self(v))
    }
}
#[allow(unused_qualifications)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::arbitrary_source_item_ordering)]
const _: () = {
    #[expect(clippy::useless_attribute)]
    extern crate serde as _serde;
    #[automatically_derived]
    impl<'de, T: Debug + PartialEq + Clone + Deserialize<'de>> Deserialize<'de>
        for NotEmptyUniqueVec<T>
    {
        fn deserialize<__D>(__deserializer: __D) -> Result<Self, __D::Error>
        where
            __D: Deserializer<'de>,
        {
            #[doc(hidden)]
            struct __Visitor<'de, T>
            where
                T: Deserialize<'de>,
            {
                marker: _serde::__private228::PhantomData<NotEmptyUniqueVec<T>>,
                lifetime: _serde::__private228::PhantomData<&'de ()>,
            }
            #[automatically_derived]
            impl<'de, T: Debug + PartialEq + Clone + Deserialize<'de>> _serde::de::Visitor<'de>
                for __Visitor<'de, T>
            {
                type Value = NotEmptyUniqueVec<T>;
                fn expecting(&self, __f: &mut Formatter<'_>) -> _serde::__private228::fmt::Result {
                    Formatter::write_str(__f, "tuple struct NotEmptyUniqueVec")
                }
                #[inline]
                fn visit_newtype_struct<__E>(self, __e: __E) -> Result<Self::Value, __E::Error>
                where
                    __E: Deserializer<'de>,
                {
                    let f0: Vec<T> = <Vec<T> as Deserialize>::deserialize(__e)?;
                    Ok(NotEmptyUniqueVec(f0))
                }
                #[inline]
                fn visit_seq<__A>(self, mut __seq: __A) -> Result<Self::Value, __A::Error>
                where
                    __A: _serde::de::SeqAccess<'de>,
                {
                    let Some(f0) = _serde::de::SeqAccess::next_element::<Vec<T>>(&mut __seq)?
                    else {
                        return Err(_serde::de::Error::invalid_length(
                            0usize,
                            &"tuple struct NotEmptyUniqueVec with 1 el",
                        ));
                    };
                    match NotEmptyUniqueVec::try_new(f0) {
                        Ok(v) => Ok(v),
                        Err(er) => Err(_serde::de::Error::custom(format!("{er:?}"))),
                    }
                }
            }
            Deserializer::deserialize_newtype_struct(
                __deserializer,
                "NotEmptyUniqueVec",
                __Visitor {
                    marker: _serde::__private228::PhantomData::<Self>,
                    lifetime: _serde::__private228::PhantomData,
                },
            )
        }
    }
};
impl<T: AllEnumVrtsArrDfltOptSomeVecOneEl> DfltOptSomeVecOneEl for NotEmptyUniqueVec<T> {
    fn dflt_opt_some_vec_one_el() -> Self {
        Self(AllEnumVrtsArrDfltOptSomeVecOneEl::all_vrts_dflt_opt_some_vec_one_el())
    }
}
impl<T: AllEnumVrtsArrDfltOptSomeVecOneElMaxPageSize> DfltOptSomeVecOneElMaxPageSize
    for NotEmptyUniqueVec<T>
{
    fn dflt_opt_some_vec_one_el_max_page_size() -> Self {
        Self(AllEnumVrtsArrDfltOptSomeVecOneElMaxPageSize::all_vrts_dflt_opt_some_vec_one_el_max_page_size())
    }
}
impl<T> Default for NotEmptyUniqueVec<T> {
    fn default() -> Self {
        Self(Vec::default())
    }
}
impl<T> From<NotEmptyUniqueVec<T>> for Vec<T> {
    fn from(v: NotEmptyUniqueVec<T>) -> Self {
        v.0
    }
}
impl<T1> NotEmptyUniqueVec<T1> {
    pub fn from_t1_impl_from_t2<T2: From<T1>>(v: Self) -> NotEmptyUniqueVec<T2> {
        NotEmptyUniqueVec(v.0.into_iter().map(T2::from).collect::<Vec<T2>>())
    }
}
impl<'query_lifetime, T> PgTypeWhereFilter<'query_lifetime> for NotEmptyUniqueVec<T>
where
    T: Debug
        + PartialEq
        + Clone
        + for<'t_lifetime> PgTypeWhereFilter<'t_lifetime>
        + AllEnumVrtsArrDfltOptSomeVecOneEl,
{
    fn qb(
        self,
        mut query: Query<'query_lifetime, Postgres, PgArguments>,
    ) -> Result<Query<'query_lifetime, Postgres, PgArguments>, String> {
        for el in self.0 {
            match el.qb(query) {
                Ok(v) => {
                    query = v;
                }
                Err(er) => {
                    return Err(er);
                }
            }
        }
        Ok(query)
    }
    fn qp(&self, incr: &mut u64, column: &dyn Display, add_oprtr: bool) -> Result<String, QpEr> {
        let mut acc = String::default();
        for (i, v_953208ce) in self.0.iter().enumerate() {
            match v_953208ce.qp(incr, column, if i == 0 { add_oprtr } else { true }) {
                Ok(v) => {
                    acc.push_str(&v);
                }
                Err(er) => {
                    return Err(er);
                }
            }
        }
        Ok(acc)
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, OptimalPack)]
pub struct JsonFieldRights {
    can_create: bool,
    can_read: bool,
    can_update: bool,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, OptimalPack)]
pub struct NonPkPgTypeReadIds(pub V<Option<()>>);
impl Decode<'_, Postgres> for NonPkPgTypeReadIds {
    fn decode(value: PgValueRef<'_>) -> Result<Self, BoxDynError> {
        match <Json<Self> as Decode<Postgres>>::decode(value) {
            Ok(v0) => Ok(v0.0),
            Err(er) => Err(er),
        }
    }
}
impl Type<Postgres> for NonPkPgTypeReadIds {
    fn compatible(ty: &<Postgres as Database>::TypeInfo) -> bool {
        <Json<Self> as Type<Postgres>>::compatible(ty)
    }
    fn type_info() -> <Postgres as Database>::TypeInfo {
        <Json<Self> as Type<Postgres>>::type_info()
    }
}
impl Default for NonPkPgTypeReadIds {
    fn default() -> Self {
        Self(V { v: None })
    }
}
#[derive(Debug, Clone, Copy, OptimalPack)]
pub enum EqualOprtr {
    Equal,
    IsNull,
}
impl EqualOprtr {
    #[must_use]
    pub const fn to_query_str(&self) -> &'static str {
        match &self {
            Self::Equal => "=",
            Self::IsNull => "is null",
        }
    }
}
pub trait PgTypeEqualOprtr {
    fn oprtr(&self) -> EqualOprtr;
}
#[derive(
    Debug, Default, Clone, Copy, PartialEq, Eq, PartialOrd, Serialize, JsonSchema, OptimalPack,
)]
pub struct UnsignedPartOfI32(i32); //todo why exactly i32? mb different types for pg type and pg json type
#[derive(
    Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Error, Location, JsonSchema, OptimalPack,
)]
pub enum UnsignedPartOfI32TryFromI32Er {
    LessThanZero {
        loc: Loc,
        #[eo_to_err_string_serde]
        v: i32,
    },
}
impl TryFrom<i32> for UnsignedPartOfI32 {
    type Error = UnsignedPartOfI32TryFromI32Er;
    fn try_from(v: i32) -> Result<Self, Self::Error> {
        if v >= 0 {
            Ok(Self(v))
        } else {
            Err(Self::Error::LessThanZero { v, loc: loc!() })
        }
    }
}
#[allow(unused_qualifications)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::arbitrary_source_item_ordering)]
const _: () = {
    extern crate serde as _serde;
    #[automatically_derived]
    impl<'de> Deserialize<'de> for UnsignedPartOfI32 {
        fn deserialize<__D>(__deserializer: __D) -> Result<Self, __D::Error>
        where
            __D: Deserializer<'de>,
        {
            #[doc(hidden)]
            struct __Visitor<'de> {
                marker: _serde::__private228::PhantomData<UnsignedPartOfI32>,
                lifetime: _serde::__private228::PhantomData<&'de ()>,
            }
            #[automatically_derived]
            impl<'de> _serde::de::Visitor<'de> for __Visitor<'de> {
                type Value = UnsignedPartOfI32;
                fn expecting(
                    &self,
                    __formatter: &mut Formatter<'_>,
                ) -> _serde::__private228::fmt::Result {
                    Formatter::write_str(__formatter, "tuple struct UnsignedPartOfI32")
                }
                #[inline]
                fn visit_newtype_struct<__E>(self, __e: __E) -> Result<Self::Value, __E::Error>
                where
                    __E: Deserializer<'de>,
                {
                    let f0: i32 = <i32 as Deserialize>::deserialize(__e)?;
                    match UnsignedPartOfI32::try_from(f0) {
                        Ok(v) => Ok(v),
                        Err(er) => Err(serde::de::Error::custom(format!("{er:?}"))),
                    }
                }
                #[inline]
                fn visit_seq<__A>(self, mut __seq: __A) -> Result<Self::Value, __A::Error>
                where
                    __A: _serde::de::SeqAccess<'de>,
                {
                    let Some(f0) = _serde::de::SeqAccess::next_element::<i32>(&mut __seq)? else {
                        return Err(_serde::de::Error::invalid_length(
                            0usize,
                            &"tuple struct UnsignedPartOfI32 with 1 el",
                        ));
                    };
                    match UnsignedPartOfI32::try_from(f0) {
                        Ok(v) => Ok(v),
                        Err(er) => Err(serde::de::Error::custom(format!("{er:?}"))),
                    }
                }
            }
            Deserializer::deserialize_newtype_struct(
                __deserializer,
                "UnsignedPartOfI32",
                __Visitor {
                    marker: _serde::__private228::PhantomData::<Self>,
                    lifetime: _serde::__private228::PhantomData,
                },
            )
        }
    }
};
impl ToErrString for UnsignedPartOfI32 {
    fn to_err_string(&self) -> String {
        self.0.to_string()
    }
}
impl Type<Postgres> for UnsignedPartOfI32 {
    fn compatible(ty: &<Postgres as Database>::TypeInfo) -> bool {
        <i32 as Type<Postgres>>::compatible(ty)
    }
    fn type_info() -> <Postgres as Database>::TypeInfo {
        <i32 as Type<Postgres>>::type_info()
    }
}
impl Encode<'_, Postgres> for UnsignedPartOfI32 {
    fn encode_by_ref(
        &self,
        buf: &mut PgArgumentBuffer,
    ) -> Result<IsNull, Box<dyn StdErEr + Send + Sync>> {
        <i32 as Encode<Postgres>>::encode_by_ref(&self.0, buf)
    }
}
impl UnsignedPartOfI32 {
    #[must_use]
    pub const fn get(&self) -> i32 {
        self.0
    }
}
impl DfltOptSomeVecOneEl for UnsignedPartOfI32 {
    fn dflt_opt_some_vec_one_el() -> Self {
        Self(0)
    }
}
#[derive(
    Debug, Default, Clone, Copy, PartialEq, Eq, PartialOrd, Serialize, JsonSchema, OptimalPack,
)]
pub struct NotZeroUnsignedPartOfI32(UnsignedPartOfI32);
#[derive(
    Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Error, Location, JsonSchema, OptimalPack,
)]
pub enum NotZeroUnsignedPartOfI32TryFromI32Er {
    IsZero {
        loc: Loc,
    },
    UnsignedPartOfI32TryFromI32Er {
        #[eo_location]
        v: UnsignedPartOfI32TryFromI32Er,
        loc: Loc,
    },
}
impl TryFrom<i32> for NotZeroUnsignedPartOfI32 {
    type Error = NotZeroUnsignedPartOfI32TryFromI32Er;
    fn try_from(v: i32) -> Result<Self, Self::Error> {
        match UnsignedPartOfI32::try_from(v) {
            Ok(v0) => {
                if v0.0 == 0 {
                    Err(Self::Error::IsZero { loc: loc!() })
                } else {
                    Ok(Self(v0))
                }
            }
            Err(er) => Err(Self::Error::UnsignedPartOfI32TryFromI32Er { v: er, loc: loc!() }),
        }
    }
}
#[allow(unused_qualifications)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::arbitrary_source_item_ordering)]
const _: () = {
    extern crate serde as _serde;
    #[automatically_derived]
    impl<'de> Deserialize<'de> for NotZeroUnsignedPartOfI32 {
        fn deserialize<__D>(__deserializer: __D) -> Result<Self, __D::Error>
        where
            __D: Deserializer<'de>,
        {
            #[doc(hidden)]
            struct __Visitor<'de> {
                marker: _serde::__private228::PhantomData<NotZeroUnsignedPartOfI32>,
                lifetime: _serde::__private228::PhantomData<&'de ()>,
            }
            #[automatically_derived]
            impl<'de> _serde::de::Visitor<'de> for __Visitor<'de> {
                type Value = NotZeroUnsignedPartOfI32;
                fn expecting(
                    &self,
                    __formatter: &mut Formatter<'_>,
                ) -> _serde::__private228::fmt::Result {
                    Formatter::write_str(__formatter, "tuple struct NotZeroUnsignedPartOfI32")
                }
                #[inline]
                fn visit_newtype_struct<__E>(self, __e: __E) -> Result<Self::Value, __E::Error>
                where
                    __E: Deserializer<'de>,
                {
                    let f0: i32 = <i32 as Deserialize>::deserialize(__e)?;
                    match NotZeroUnsignedPartOfI32::try_from(f0) {
                        Ok(v) => Ok(v),
                        Err(er) => Err(serde::de::Error::custom(format!("{er:?}"))),
                    }
                }
                #[inline]
                fn visit_seq<__A>(self, mut __seq: __A) -> Result<Self::Value, __A::Error>
                where
                    __A: _serde::de::SeqAccess<'de>,
                {
                    let Some(f0) = _serde::de::SeqAccess::next_element::<i32>(&mut __seq)? else {
                        return Err(_serde::de::Error::invalid_length(
                            0usize,
                            &"tuple struct NotZeroUnsignedPartOfI32 with 1 el",
                        ));
                    };
                    match NotZeroUnsignedPartOfI32::try_from(f0) {
                        Ok(v) => Ok(v),
                        Err(er) => Err(serde::de::Error::custom(format!("{er:?}"))),
                    }
                }
            }
            Deserializer::deserialize_newtype_struct(
                __deserializer,
                "NotZeroUnsignedPartOfI32",
                __Visitor {
                    marker: _serde::__private228::PhantomData::<Self>,
                    lifetime: _serde::__private228::PhantomData,
                },
            )
        }
    }
};
impl ToErrString for NotZeroUnsignedPartOfI32 {
    fn to_err_string(&self) -> String {
        self.0.to_err_string()
    }
}
impl Type<Postgres> for NotZeroUnsignedPartOfI32 {
    fn compatible(ty: &<Postgres as Database>::TypeInfo) -> bool {
        <UnsignedPartOfI32 as Type<Postgres>>::compatible(ty)
    }
    fn type_info() -> <Postgres as Database>::TypeInfo {
        <UnsignedPartOfI32 as Type<Postgres>>::type_info()
    }
}
impl Encode<'_, Postgres> for NotZeroUnsignedPartOfI32 {
    fn encode_by_ref(
        &self,
        buf: &mut PgArgumentBuffer,
    ) -> Result<IsNull, Box<dyn StdErEr + Send + Sync>> {
        <UnsignedPartOfI32 as Encode<Postgres>>::encode_by_ref(&self.0, buf)
    }
}
impl NotZeroUnsignedPartOfI32 {
    #[must_use]
    pub const fn get(&self) -> i32 {
        self.0.get()
    }
}
impl DfltOptSomeVecOneEl for NotZeroUnsignedPartOfI32 {
    fn dflt_opt_some_vec_one_el() -> Self {
        Self(DfltOptSomeVecOneEl::dflt_opt_some_vec_one_el())
    }
}
#[derive(
    Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema, JsonSchema, OptimalPack,
)]
pub enum SingleOrMultiple<T: Debug + PartialEq + Clone> {
    Multiple(NotEmptyUniqueVec<T>),
    Single(T),
}
pub fn incr_checked_add_one_returning_incr(incr: &mut u64) -> Result<u64, QpEr> {
    incr.checked_add(1).map_or_else(
        || Err(QpEr::CheckedAdd { loc: loc!() }),
        |v| {
            *incr = v;
            Ok(v)
        },
    )
}
#[must_use]
pub const fn i8_test_cases_vec() -> [i8; 3] {
    [i8::MIN, 0, i8::MAX]
}
#[must_use]
pub const fn i16_test_cases_vec() -> [i16; 3] {
    [i16::MIN, 0, i16::MAX]
}
#[must_use]
pub const fn i32_test_cases_vec() -> [i32; 3] {
    [i32::MIN, 0, i32::MAX]
}
#[must_use]
pub const fn i64_test_cases_vec() -> [i64; 3] {
    [i64::MIN, 0, i64::MAX]
}
#[must_use]
pub const fn u8_test_cases_vec() -> [u8; 3] {
    [u8::MIN, 0, u8::MAX]
}
#[must_use]
pub const fn u16_test_cases_vec() -> [u16; 3] {
    [u16::MIN, 0, u16::MAX]
}
#[must_use]
pub const fn u32_test_cases_vec() -> [u32; 3] {
    [u32::MIN, 0, u32::MAX]
}
#[must_use]
pub const fn u64_test_cases_vec() -> [u64; 3] {
    [u64::MIN, 0, u64::MAX]
}
#[must_use]
pub const fn f32_test_cases_vec() -> [f32; 18] {
    [
        f32::EPSILON,
        f32::MAX,
        f32::MIN,
        f32::MIN_POSITIVE,
        -1e30,
        -1e-30,
        -16_777_214.0,
        -100.0,
        -10.0,
        -1.0,
        -0.0,
        0.0,
        1.0,
        10.0,
        100.0,
        16_777_214.0,
        1e-30,
        1e30,
    ]
}
#[must_use]
pub const fn f64_test_cases_vec() -> [f64; 18] {
    [
        f64::EPSILON,
        f64::MAX,
        f64::MIN,
        f64::MIN_POSITIVE,
        -1e300,
        -1e-300,
        -9_007_199_254_740_990.0,
        -100.0,
        -10.0,
        -1.0,
        -0.0,
        0.0,
        1.0,
        10.0,
        100.0,
        9_007_199_254_740_990.0,
        1e-300,
        1e300,
    ]
}
#[must_use]
pub const fn bool_test_cases_vec() -> [bool; 2] {
    [true, false]
}
#[must_use]
pub fn string_test_cases_vec() -> [String; 12] {
    #[allow(clippy::non_ascii_literal)]
    [
        String::new(),
        "a".to_owned(),
        "Hello, world!".to_owned(),
        "   ".to_owned(),
        "\n\r\t".to_owned(),
        "1234567890".to_owned(),
        "😀".to_owned(),
        "こんにちは".to_owned(),
        "🌍🚀✨ Rust 💖🦀".to_owned(),
        "a".repeat(1024),
        "line1\nline2\nline3".to_owned(),
        String::from_utf8_lossy(&[0xF0, 0x9F, 0x92, 0x96]).to_string(),
    ]
}
#[must_use]
pub fn uuid_uuid_test_cases_vec() -> [Uuid; 1] {
    [Uuid::new_v4()]
}
