[package]
edition = "2021"
name = "generate_postgresql_crud"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = {version = "=1.0.81"}
quote = {version = "=1.0.36"}
syn = {version = "=2.0.60"}
strum = {version = "=0.24.1"}
strum_macros = {version = "=0.24.3"}
convert_case = {version = "=0.6.0"}
pluralizer = {version = "=0.4.0"}
postgresql_crud_common = {path = "./../postgresql_crud_common"}
proc_macro_assistants = {path = "../../proc_macro_assistants"}
proc_macro_common = {path = "../../proc_macro_common"}
proc_macro_helpers = {path = "../../proc_macro_helpers"}
enum_extension_lib = {path = "../../enum_extension_lib"}
naming_constants = {path = "../../naming_constants"}

[lints]
workspace = true
