[package]
name = "proc_macro_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = {version = "=1.0.67"}
quote = {version = "=1.0.33"}
syn = {version = "=1.0.107"}
strum = {version = "=0.24.1"}
strum_macros = {version = "=0.24.3"}
convert_case = {version = "=0.6.0"}

[lints]
workspace = true
