[package]
edition = "2021"
name = "impl_get_where_was_one_or_many_one_for_error_struct"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"
syn = "1.0.75"
