[target.'cfg(feature = "cargo-clippy")']
rustflags = [
  "-Dabsolute_paths_not_starting_with_crate",
  "-Dbox_pointers",
  "-Delided_lifetimes_in_paths",
  "-Dexplicit_outlives_requirements",
  "-Dkeyword_idents",
  "-Dmacro_use_extern_crate",
  "-Dmeta_variable_misuse",
  "-Dmissing_abi",
  "-Dmissing_copy_implementations",
  "-Dmissing_debug_implementations",
  "-Dmissing_docs",
  "-Dnon_ascii_idents",
  "-Dnoop_method_call",
  "-Dpointer_structural_match",
  "-Drust_2021_incompatible_closure_captures",
  "-Drust_2021_incompatible_or_patterns",
  "-Drust_2021_prefixes_incompatible_syntax",
  "-Drust_2021_prelude_collisions",
  "-Dsingle_use_lifetimes",
  "-Dtrivial_casts",
  "-Dtrivial_numeric_casts",
  "-Dunreachable_pub",
  "-Dunsafe_code",
  "-Dunsafe_op_in_unsafe_fn",
  "-Dunstable_features",
  "-Dunused_crate_dependencies",
  "-Dunused_extern_crates",
  "-Dunused_import_braces",
  "-Dunused_lifetimes",
  "-Dunused_qualifications",
  "-Dunused_results",
  "-Dvariant_size_differences",
  "-Dclippy::as_conversions",
  "-Dclippy::cargo_common_metadata",
  "-Dclippy::clone_on_ref_ptr",
  "-Dclippy::cognitive_complexity",
  "-Dclippy::create_dir",
  "-Dclippy::dbg_macro",
  "-Dclippy::debug_assert_with_mut_call",
  "-Dclippy::decimal_literal_representation",
  "-Dclippy::default_numeric_fallback",
  "-Dclippy::disallowed_method",
  "-Dclippy::disallowed_script_idents",
  "-Dclippy::disallowed_type",
  "-Dclippy::else_if_without_else",
  "-Dclippy::empty_line_after_outer_attr",
  "-Dclippy::exhaustive_enums",
  "-Dclippy::exhaustive_structs",
  "-Dclippy::exit",
  "-Dclippy::expect_used",
  "-Dclippy::fallible_impl_from",
  "-Dclippy::filetype_is_file",
  "-Dclippy::float_arithmetic",
  "-Dclippy::float_cmp_const",
  "-Dclippy::future_not_send",
  "-Dclippy::get_unwrap",
  "-Dclippy::if_then_some_else_none",
  "-Dclippy::implicit_return",
  "-Dclippy::imprecise_flops",
  "-Dclippy::indexing_slicing",
  "-Dclippy::inline_asm_x86_att_syntax",
  "-Dclippy::inline_asm_x86_intel_syntax",
  "-Dclippy::integer_arithmetic",
  "-Dclippy::integer_division",
  "-Dclippy::let_underscore_must_use",
  "-Dclippy::lossy_float_literal",
  "-Dclippy::map_err_ignore",
  "-Dclippy::mem_forget",
  "-Dclippy::missing_const_for_fn",
  "-Dclippy::missing_docs_in_private_items",
  "-Dclippy::missing_enforced_import_renames",
  "-Dclippy::missing_inline_in_public_items",
  "-Dclippy::modulo_arithmetic",
  "-Dclippy::multiple_crate_versions",
  "-Dclippy::multiple_inherent_impl",
  "-Dclippy::mutex_integer",
  "-Dclippy::nonstandard_macro_braces",
  "-Dclippy::panic",
  "-Dclippy::panic_in_result_fn",
  "-Dclippy::path_buf_push_overwrite",
  "-Dclippy::pattern_type_mismatch",
  "-Dclippy::pedantic",
  "-Dclippy::print_stderr",
  "-Dclippy::print_stdout",
  "-Dclippy::rc_buffer",
  "-Dclippy::rc_mutex",
  "-Dclippy::redundant_pub_crate",
  "-Dclippy::rest_pat_in_fully_bound_structs",
  "-Dclippy::shadow_reuse",
  "-Dclippy::shadow_same",
  "-Dclippy::str_to_string",
  "-Dclippy::string_add",
  "-Dclippy::string_lit_as_bytes",
  "-Dclippy::string_to_string",
  "-Dclippy::suboptimal_flops",
  "-Dclippy::suspicious_operation_groupings",
  "-Dclippy::todo",
  "-Dclippy::trivial_regex",
  "-Dclippy::unimplemented",
  "-Dclippy::unnecessary_self_imports",
  "-Dclippy::unneeded_field_pattern",
  "-Dclippy::unreachable",
  "-Dclippy::unwrap_in_result",
  "-Dclippy::unwrap_used",
  "-Dclippy::use_debug",
  "-Dclippy::use_self",
  "-Dclippy::useless_let_if_seq",
  "-Dclippy::useless_transmute",
  "-Dclippy::verbose_file_reads",
  "-Dclippy::wildcard_dependencies",
  "-Dclippy::wildcard_enum_match_arm",
]
