generate_struct_or_enum_derive_token_stream_builder::generate_struct_or_enum_derive_token_stream_builder!([
    "Debug",
    "Default",
    "Clone",
    "Copy",
    "PartialEq",
    "Eq",
    "PartialOrd",
    "Ord",
    "serde::Serialize",
    "serde::Deserialize",
    "utoipa::ToSchema",
    "schemars::JsonSchema",
    "thiserror::Error",
    "error_occurence_lib::ErrorOccurence"
]);