#need to enable vscode rest client  extension https://marketplace.visualstudio.com/items?itemName=humao.rest-client to send requests
 
POST http://127.0.0.1:8080/jsongeneric/create_many HTTP/1.1
content-type: application/json
commit: 926cf2c0bac1dfbd1fd466068b2c9fc5a271bc3b

[
    {
        "std_primitive_bool_as_postgresql_bool_not_null": false,
        # "std_primitive_i32_as_postgresql_int": 0,
        "sqlx_types_json_t_as_postgresql_json_b_not_null": {
            "std_primitive_i8": 0,
            # "std_primitive_i16": 0,
            # "std_primitive_i32": 0,
            # "std_primitive_i64": 0,
            # "std_primitive_i128": 0,
            # "std_primitive_u8": 0,
            # "std_primitive_u16": 0,
            # "std_primitive_u32": 0,
            # "std_primitive_u64": 0,
            # "std_primitive_u128": 0,
            # "std_primitive_f32": 0.0,
            # "std_primitive_f64": 0.0,
            # "std_primitive_bool": false,
            # "std_string_string": "",
            # "std_option_option_std_primitive_i8": 0,
            # "std_option_option_std_primitive_i16": 0,
            # "std_option_option_std_primitive_i32": 0,
            # "std_option_option_std_primitive_i64": 0,
            # "std_option_option_std_primitive_i128": 0,
            # "std_option_option_std_primitive_u8": 0,
            # "std_option_option_std_primitive_u16": 0,
            # "std_option_option_std_primitive_u32": 0,
            # "std_option_option_std_primitive_u64": 0,
            # "std_option_option_std_primitive_u128": 0,
            # "std_option_option_std_primitive_f32": 0.0,
            # "std_option_option_std_primitive_f64": 0.0,
            # "std_option_option_std_primitive_bool": false,
            # "std_option_option_std_string_string": "",
            # "std_vec_vec_std_primitive_i8": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_i16": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_i32": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_i64": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_i128": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_u8": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_u16": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_u32": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_u64": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_u128": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_f32": [
            #     0.0
            # ],
            # "std_vec_vec_std_primitive_f64": [
            #     0.0
            # ],
            # "std_vec_vec_std_primitive_bool": [
            #     false
            # ],
            # "std_vec_vec_std_string_string": [
            #     ""
            # ],
            # "std_option_option_std_vec_vec_std_primitive_i8": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_i16": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_i32": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_i64": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_i128": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_u8": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_u16": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_u32": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_u64": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_u128": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_f32": [
            #     0.0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_f64": [
            #     0.0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_bool": [
            #     false
            # ],
            # "std_option_option_std_vec_vec_std_string_string": [
            #     ""
            # ],
            # "std_vec_vec_std_option_option_std_primitive_i8": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_i16": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_i32": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_i64": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_i128": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_u8": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_u16": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_u32": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_u64": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_u128": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_f32": [
            #     0.0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_f64": [
            #     0.0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_bool": [
            #     false
            # ],
            # "std_vec_vec_std_option_option_std_string_string": [
            #     ""
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_i8": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_i16": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_i32": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_i64": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_i128": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_u8": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_u16": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_u32": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_u64": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_u128": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_f32": [
            #     0.0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_f64": [
            #     0.0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_bool": [
            #     false
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_string_string": [
            #     ""
            # ],
            # "generic": {
            #     "std_string_string": ""
            # },
            # "std_option_option_generic": {
            #     "std_string_string": ""
            # },
            "std_vec_vec_generic": [
                {
                  "std_primitive_i16": 0,
                  "generic": {
                    "std_primitive_i32": 0
                  }
                }
            ]
            # ,
            # "std_option_option_std_vec_vec_generic": [
            #     {
            #         "std_string_string": ""
            #     }
            # ],
            # "std_vec_vec_std_option_option_generic": [
            #     {
            #         "std_string_string": ""
            #     }
            # ],
            # "std_option_option_std_vec_vec_std_option_option_generic": [
            #     {
            #         "std_string_string": ""
            #     }
            # ]
        }
    },
    {
        "std_primitive_bool_as_postgresql_bool_not_null": false,
        # "std_primitive_i32_as_postgresql_int": 0,
        "sqlx_types_json_t_as_postgresql_json_b_not_null": {
            "std_primitive_i8": 0,
            # "std_primitive_i16": 0,
            # "std_primitive_i32": 0,
            # "std_primitive_i64": 0,
            # "std_primitive_i128": 0,
            # "std_primitive_u8": 0,
            # "std_primitive_u16": 0,
            # "std_primitive_u32": 0,
            # "std_primitive_u64": 0,
            # "std_primitive_u128": 0,
            # "std_primitive_f32": 0.0,
            # "std_primitive_f64": 0.0,
            # "std_primitive_bool": false,
            # "std_string_string": "",
            # "std_option_option_std_primitive_i8": 0,
            # "std_option_option_std_primitive_i16": 0,
            # "std_option_option_std_primitive_i32": 0,
            # "std_option_option_std_primitive_i64": 0,
            # "std_option_option_std_primitive_i128": 0,
            # "std_option_option_std_primitive_u8": 0,
            # "std_option_option_std_primitive_u16": 0,
            # "std_option_option_std_primitive_u32": 0,
            # "std_option_option_std_primitive_u64": 0,
            # "std_option_option_std_primitive_u128": 0,
            # "std_option_option_std_primitive_f32": 0.0,
            # "std_option_option_std_primitive_f64": 0.0,
            # "std_option_option_std_primitive_bool": false,
            # "std_option_option_std_string_string": "",
            # "std_vec_vec_std_primitive_i8": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_i16": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_i32": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_i64": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_i128": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_u8": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_u16": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_u32": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_u64": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_u128": [
            #     0
            # ],
            # "std_vec_vec_std_primitive_f32": [
            #     0.0
            # ],
            # "std_vec_vec_std_primitive_f64": [
            #     0.0
            # ],
            # "std_vec_vec_std_primitive_bool": [
            #     false
            # ],
            # "std_vec_vec_std_string_string": [
            #     ""
            # ],
            # "std_option_option_std_vec_vec_std_primitive_i8": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_i16": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_i32": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_i64": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_i128": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_u8": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_u16": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_u32": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_u64": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_u128": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_f32": [
            #     0.0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_f64": [
            #     0.0
            # ],
            # "std_option_option_std_vec_vec_std_primitive_bool": [
            #     false
            # ],
            # "std_option_option_std_vec_vec_std_string_string": [
            #     ""
            # ],
            # "std_vec_vec_std_option_option_std_primitive_i8": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_i16": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_i32": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_i64": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_i128": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_u8": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_u16": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_u32": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_u64": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_u128": [
            #     0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_f32": [
            #     0.0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_f64": [
            #     0.0
            # ],
            # "std_vec_vec_std_option_option_std_primitive_bool": [
            #     false
            # ],
            # "std_vec_vec_std_option_option_std_string_string": [
            #     ""
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_i8": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_i16": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_i32": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_i64": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_i128": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_u8": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_u16": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_u32": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_u64": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_u128": [
            #     0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_f32": [
            #     0.0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_f64": [
            #     0.0
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_primitive_bool": [
            #     false
            # ],
            # "std_option_option_std_vec_vec_std_option_option_std_string_string": [
            #     ""
            # ],
            # "generic": {
            #     "std_string_string": ""
            # },
            # "std_option_option_generic": {
            #     "std_string_string": ""
            # },
            "std_vec_vec_generic": [
                {
                  "std_primitive_i16": 0,
                  "generic": {
                    "std_primitive_i32": 0
                  }
                }
            ]
            # ,
            # "std_option_option_std_vec_vec_generic": [
            #     {
            #         "std_string_string": ""
            #     }
            # ],
            # "std_vec_vec_std_option_option_generic": [
            #     {
            #         "std_string_string": ""
            #     }
            # ],
            # "std_option_option_std_vec_vec_std_option_option_generic": [
            #     {
            #         "std_string_string": ""
            #     }
            # ]
        }
    }
]

###
 
GET http://127.0.0.1:8080/jsongeneric/create_many_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

### 

POST http://127.0.0.1:8080/jsongeneric/create_one HTTP/1.1
content-type: application/json
commit: e9e7647602a980c62e1d20c3d91cf61d3236f5f9

{
  "std_primitive_bool_as_postgresql_bool_not_null": false,
  "sqlx_types_json_t_as_postgresql_json_b_not_null": {
    "std_primitive_i8": 0,
    "std_option_option_std_primitive_i8": 0,
    "std_vec_vec_std_primitive_i8": [
      0
    ],
    "std_option_option_std_vec_vec_std_primitive_i8": [
      0
    ],
    "std_vec_vec_std_option_option_std_primitive_i8": [
      0
    ],
    "std_option_option_std_vec_vec_std_option_option_std_primitive_i8": [
      0
    ],
    "object": {
      "std_primitive_i8": 0,
      "std_primitive_i16": 0
    },
    "std_option_option_object": {
      "std_primitive_i8": 0,
      "std_primitive_i16": 0
    },
    "std_vec_vec_object_with_id": [
      {
        "std_primitive_i8": 0,
        "std_primitive_i16": 0
      }
    ],
    "std_option_option_std_vec_vec_object_with_id": [
      {
        "std_primitive_i8": 0,
        "std_primitive_i16": 0
      }
    ]
  }
}

###
 
GET http://127.0.0.1:8080/jsongeneric/create_one_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

###

POST http://127.0.0.1:8080/jsongeneric/read_many HTTP/1.1
content-type: application/json
commit: 72a7f5c066a08a77fb91e75abee9f6e79e00e2b8

{
    "select": [
        "std_primitive_bool_as_postgresql_bool_not_null",
        "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key",
        {
            "sqlx_types_json_t_as_postgresql_json_b_not_null": {
                "filter": [
                    # {
                    #     "std_primitive_i8": {}
                    # },
                    # {
                    #     "std_option_option_std_primitive_i8": {}
                    # },
                    # {
                    #     "std_vec_vec_std_primitive_i8": {
                    #         "pagination": {
                    #             "offset": 0,
                    #             "limit": 3
                    #         }
                    #     }
                    # }
                    # ,
                    # {
                    #     "std_option_option_std_vec_vec_std_primitive_i8": {
                    #         "pagination": {
                    #             "offset": 0,
                    #             "limit": 3
                    #         }
                    #     }
                    # }
                    # {
                    #     "std_vec_vec_std_option_option_std_primitive_i8": {
                    #         "pagination": {
                    #             "offset": 0,
                    #             "limit": 3
                    #         }
                    #     }
                    # }
                    # ,
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_std_primitive_i8": {
                    #         "pagination": {
                    #             "offset": 0,
                    #             "limit": 5
                    #         }
                    #     }
                    # }
                    # ,
                    {
                        "generic": [
                            {
                                "std_primitive_i32": {}
                            }
                        ]
                    }
                    ,
                    {
                        "std_option_option_generic": [
                            {
                                "std_primitive_i32": {}
                            }
                        ]
                    }
                    ,
                    {
                        "std_vec_vec_generic_with_id": {
                            "field_vec": [
                                {
                                    "id": {}
                                }
                                ,
                                {
                                    "std_primitive_i16": {}
                                }
                            ],
                            "pagination": {
                                "offset": 0,
                                "limit": 5
                            }
                        }
                    }
                    ,
                    {
                        "std_option_option_std_vec_vec_generic_with_id": {
                            "field_vec": [
                                {
                                    "id": {}
                                }
                                ,
                                {
                                    "std_primitive_i16": {}
                                }
                            ],
                            "pagination": {
                                "offset": 0,
                                "limit": 5
                            }
                        }
                    }
                ]
            }
        }
    ],
    # "id": [
    #     "7b51bb9c-124e-44ba-9941-7f32a2c18c78",
    #     "5829d06c-4141-4734-8266-b3d1e618c4de",
    #     "be13a118-e5e5-4cb6-93fe-5a1f1767d666"
    # ],
    # "name":[
    #     {
    #         "regex":"^tesft_namfe$",
    #         "conjuctive_operator":"Or"
    #     }
    # ],
    "order_by": {
        "column": "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key",
        "order": "desc"
    },
    "limit": 100,
    "offset": 0
}

### todo name and color must be  arrays       

POST http://127.0.0.1:8080/jsongeneric/read_one HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

{
  "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key": 1,
  "select": [
    "std_primitive_bool_as_postgresql_bool_not_null",
    "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key",
    {
      "sqlx_types_json_t_as_postgresql_json_b_not_null": {
        "filter": [
          {
            "std_primitive_i8": {}
          },
          {
            "std_option_option_std_primitive_i8": {}
          },
          {
            "std_vec_vec_std_primitive_i8": {
              "pagination": {
                "limit": 1,
                "offset": 0
              }
            }
          },
          {
            "std_option_option_std_vec_vec_std_primitive_i8": {
              "pagination": {
                "limit": 1,
                "offset": 0
              }
            }
          },
          {
            "std_vec_vec_std_option_option_std_primitive_i8": {
              "pagination": {
                "limit": 1,
                "offset": 0
              }
            }
          },
          {
            "std_option_option_std_vec_vec_std_option_option_std_primitive_i8": {
              "pagination": {
                "limit": 1,
                "offset": 0
              }
            }
          },
          {
            "object": [
              {
                "std_primitive_i8": {}
              },
              {
                "std_primitive_i16": {}
              }
            ]
          },
          {
            "std_option_option_object": [
              {
                "std_primitive_i8": {}
              },
              {
                "std_primitive_i16": {}
              }
            ]
          },
          {
            "std_vec_vec_object_with_id": {
              "field_vec": [
                {
                  "id": {}
                },
                {
                  "std_primitive_i8": {}
                },
                {
                  "std_primitive_i16": {}
                }
              ],
              "pagination": {
                "limit": 1,
                "offset": 0
              }
            }
          },
          {
            "std_option_option_std_vec_vec_object_with_id": {
              "field_vec": [
                {
                  "id": {}
                },
                {
                  "std_primitive_i8": {}
                },
                {
                  "std_primitive_i16": {}
                }
              ],
              "pagination": {
                "limit": 1,
                "offset": 0
              }
            }
          }
        ]
      }
    }
  ]
}

###

GET http://127.0.0.1:8080/jsongeneric/read_one_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

### fix this  
 
PATCH http://127.0.0.1:8080/jsongeneric/update_many HTTP/1.1 
content-type: application/json
commit: f7e8bd75a29858f2be33b8076f2ebda4bd413a70

[
    {
        "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key": 1,
        "std_primitive_i32_as_postgresql_int": {
            "value": 84
        }
    },
    {
        "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key": 2,
        "sqlx_types_json_t_as_postgresql_json_not_null": {
            "value": {
                "something": "kekew"
            }
        }
    }
]

### 

PATCH http://127.0.0.1:8080/jsongeneric/update_one HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

{
  "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key": 1,
  "sqlx_types_json_t_as_postgresql_json_b_not_null": {
    "value": [
      {
        "std_primitive_i8": {
          "value": 0
        }
      },
      {
        "std_option_option_std_primitive_i8": {
          "value": 0
        }
      },
      {
        "std_vec_vec_std_primitive_i8": {
          "value": [
            0
          ]
        }
      },
      {
        "std_option_option_std_vec_vec_std_primitive_i8": {
          "value": [
            0
          ]
        }
      },
      {
        "std_vec_vec_std_option_option_std_primitive_i8": {
          "value": [
            0
          ]
        }
      },
      {
        "std_option_option_std_vec_vec_std_option_option_std_primitive_i8": {
          "value": [
            0
          ]
        }
      },
      {
        "object": {
          "value": [
            {
              "std_primitive_i8": {
                "value": 0
              }
            },
            {
              "std_primitive_i16": {
                "value": 0
              }
            }
          ]
        }
      },
      {
        "std_option_option_object": {
          "value": [
            {
              "std_primitive_i8": {
                "value": 0
              }
            },
            {
              "std_primitive_i16": {
                "value": 0
              }
            }
          ]
        }
      },
      {
        "std_vec_vec_object_with_id": {
          "value": {
            "create": [
              {
                "std_primitive_i8": 0,
                "std_primitive_i16": 0
              }
            ],
            "update": [
              {
                "id": "ecea4ddd-4dfa-4a62-b747-27c1bcf9041a",
                "fields": [
                  {
                    "std_primitive_i8": {
                      "value": 0
                    }
                  },
                  {
                    "std_primitive_i16": {
                      "value": 0
                    }
                  }
                ]
              }
            ],
            "delete": [
              "4ace83d4-947d-4672-ba62-9c6b2eaa3e40"
            ]
          }
        }
      },
      {
        "std_option_option_std_vec_vec_object_with_id": {
          "value": {
            "create": [
              {
                "std_primitive_i8": 0,
                "std_primitive_i16": 0
              }
            ],
            "update": [
              {
                "id": "f6e7d667-e17d-45b3-80d6-a908242fcebf",
                "fields": [
                  {
                    "std_primitive_i8": {
                      "value": 0
                    }
                  },
                  {
                    "std_primitive_i16": {
                      "value": 0
                    }
                  }
                ]
              }
            ],
            "delete": [
              "089be3c7-27c6-40ef-b699-afd1992c04b6"
            ]
          }
        }
      }
    ]
  }
}

###
 
GET http://127.0.0.1:8080/jsongeneric/update_one_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

####"^first_test_name_create$"  

DELETE http://127.0.0.1:8080/jsongeneric/delete_many HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

{
    "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key": [
      3
    ]
    # ,
    # "name":[
    #     {
    #         "regex":"first_test_name_create",
    #         "conjuctive_operator":"Or"
    #     }
    # ],
    # "color":[
    #     {
    #         "regex":"first_test_color_create",
    #         "conjuctive_operator":"Or"
    #     }
    # ]
}

###

DELETE http://127.0.0.1:8080/jsongeneric/delete_one HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

{
    "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key": 4
}

###

GET http://127.0.0.1:8080/health_check HTTP/1.1

### 

GET http://127.0.0.1:8080/git_info HTTP/1.1

###

GET http://127.0.0.1:8080/src/main.rs HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786

###

GET http://127.0.0.1:8080/header_extractor_example HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786

###

GET http://127.0.0.1:8080/extract_custom_header_example HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786

###

GET http://127.0.0.1:8080/middleware_message_example HTTP/1.1

###

GET http://127.0.0.1:8080/read_middleware_custom_header HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786


######################################################

POST http://127.0.0.1:8080/example/create_many HTTP/1.1
content-type: application/json
commit: 926cf2c0bac1dfbd1fd466068b2c9fc5a271bc3b

[
  {
    "std_primitive_bool_as_postgresql_bool_not_null": false
  },
  {
    "std_primitive_bool_as_postgresql_bool_not_null": false
  }
]

###
 
GET http://127.0.0.1:8080/example/create_many_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

### 

POST http://127.0.0.1:8080/example/create_one HTTP/1.1
content-type: application/json
commit: e9e7647602a980c62e1d20c3d91cf61d3236f5f9

{
  "std_primitive_bool_as_postgresql_bool_not_null": false
}

###
 
GET http://127.0.0.1:8080/example/create_one_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

###

POST http://127.0.0.1:8080/example/read_many HTTP/1.1
content-type: application/json
commit: 72a7f5c066a08a77fb91e75abee9f6e79e00e2b8

{
  "std_primitive_i64_as_postgresql_big_serial_not_null": [
    1,
    2,
    3,
    4,
    5,
    6
  ],
  "std_primitive_bool_as_postgresql_bool_not_null": null,
  "select": [
    {
      "std_primitive_bool_as_postgresql_bool_not_null": []
    },
    {
      "std_primitive_i64_as_postgresql_big_serial_not_null": []
    }
  ],
  "order_by": {
    "column": {
      "std_primitive_i64_as_postgresql_big_serial_not_null": []
    },
    "order": "desc"
  },
  "limit": 10,
  "offset": 0
}

###

GET http://127.0.0.1:8080/example/read_many_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

###

POST http://127.0.0.1:8080/example/read_one HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

{
  "std_primitive_i64_as_postgresql_big_serial_not_null": 1,
  "select": [
    {
      "std_primitive_bool_as_postgresql_bool_not_null": []
    },
    {
      "std_primitive_i64_as_postgresql_big_serial_not_null": []
    }
  ]
}

###

GET http://127.0.0.1:8080/example/read_one_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

### fix this  
 
PATCH http://127.0.0.1:8080/example/update_many HTTP/1.1 
content-type: application/json
commit: f7e8bd75a29858f2be33b8076f2ebda4bd413a70

[
  {
    "std_primitive_i64_as_postgresql_big_serial_not_null": 4,
    "std_primitive_bool_as_postgresql_bool_not_null": {
      "value": true
    }
  },
  {
    "std_primitive_i64_as_postgresql_big_serial_not_null": 5,
    "std_primitive_bool_as_postgresql_bool_not_null": {
      "value": true
    }
  }
]

###

GET http://127.0.0.1:8080/example/update_many_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

### 

PATCH http://127.0.0.1:8080/example/update_one HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

{
  "std_primitive_i64_as_postgresql_big_serial_not_null": 3,
  "std_primitive_bool_as_postgresql_bool_not_null": {
    "value": true
  }
}

###
 
GET http://127.0.0.1:8080/example/update_one_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

####"^first_test_name_create$"  

DELETE http://127.0.0.1:8080/example/delete_many HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

###

DELETE http://127.0.0.1:8080/example/delete_one HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c