#need to enable vscode rest client  extension https://marketplace.visualstudio.com/items?itemName=humao.rest-client to send requests

POST http://127.0.0.1:8080/jsongeneric/create_many HTTP/1.1
content-type: application/json
commit: 926cf2c0bac1dfbd1fd466068b2c9fc5a271bc3b

[
    {
        "std_primitive_i32_as_postgresql_int": 0,
        "sqlx_types_json_t_as_postgresql_json_b_not_null": {
            "std_primitive_i8": 0,
            "std_primitive_i16": 0,
            "std_primitive_i32": 0,
            "std_primitive_i64": 0,
            "std_primitive_i128": 0,
            "std_primitive_u8": 0,
            "std_primitive_u16": 0,
            "std_primitive_u32": 0,
            "std_primitive_u64": 0,
            "std_primitive_u128": 0,
            "std_primitive_f32": 0.0,
            "std_primitive_f64": 0.0,
            "std_primitive_bool": false,
            "std_string_string": "",
            "std_option_option_std_primitive_i8": 0,
            "std_option_option_std_primitive_i16": 0,
            "std_option_option_std_primitive_i32": 0,
            "std_option_option_std_primitive_i64": 0,
            "std_option_option_std_primitive_i128": 0,
            "std_option_option_std_primitive_u8": 0,
            "std_option_option_std_primitive_u16": 0,
            "std_option_option_std_primitive_u32": 0,
            "std_option_option_std_primitive_u64": 0,
            "std_option_option_std_primitive_u128": 0,
            "std_option_option_std_primitive_f32": 0.0,
            "std_option_option_std_primitive_f64": 0.0,
            "std_option_option_std_primitive_bool": false,
            "std_option_option_std_string_string": "",
            "std_vec_vec_std_primitive_i8": [
                0
            ],
            "std_vec_vec_std_primitive_i16": [
                0
            ],
            "std_vec_vec_std_primitive_i32": [
                0
            ],
            "std_vec_vec_std_primitive_i64": [
                0
            ],
            "std_vec_vec_std_primitive_i128": [
                0
            ],
            "std_vec_vec_std_primitive_u8": [
                0
            ],
            "std_vec_vec_std_primitive_u16": [
                0
            ],
            "std_vec_vec_std_primitive_u32": [
                0
            ],
            "std_vec_vec_std_primitive_u64": [
                0
            ],
            "std_vec_vec_std_primitive_u128": [
                0
            ],
            "std_vec_vec_std_primitive_f32": [
                0.0
            ],
            "std_vec_vec_std_primitive_f64": [
                0.0
            ],
            "std_vec_vec_std_primitive_bool": [
                false
            ],
            "std_vec_vec_std_string_string": [
                ""
            ],
            "std_option_option_std_vec_vec_std_primitive_i8": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_i16": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_i32": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_i64": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_i128": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_u8": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_u16": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_u32": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_u64": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_u128": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_f32": [
                0.0
            ],
            "std_option_option_std_vec_vec_std_primitive_f64": [
                0.0
            ],
            "std_option_option_std_vec_vec_std_primitive_bool": [
                false
            ],
            "std_option_option_std_vec_vec_std_string_string": [
                ""
            ],
            "std_vec_vec_std_option_option_std_primitive_i8": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_i16": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_i32": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_i64": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_i128": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_u8": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_u16": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_u32": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_u64": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_u128": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_f32": [
                0.0
            ],
            "std_vec_vec_std_option_option_std_primitive_f64": [
                0.0
            ],
            "std_vec_vec_std_option_option_std_primitive_bool": [
                false
            ],
            "std_vec_vec_std_option_option_std_string_string": [
                ""
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_i8": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_i16": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_i32": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_i64": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_i128": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_u8": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_u16": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_u32": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_u64": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_u128": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_f32": [
                0.0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_f64": [
                0.0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_bool": [
                false
            ],
            "std_option_option_std_vec_vec_std_option_option_std_string_string": [
                ""
            ],
            "generic": {
                "std_string_string": ""
            },
            "std_option_option_generic": {
                "std_string_string": ""
            },
            "std_vec_vec_generic": [
                {
                    "std_string_string": ""
                }
            ],
            "std_option_option_std_vec_vec_generic": [
                {
                    "std_string_string": ""
                }
            ],
            "std_vec_vec_std_option_option_generic": [
                {
                    "std_string_string": ""
                }
            ],
            "std_option_option_std_vec_vec_std_option_option_generic": [
                {
                    "std_string_string": ""
                }
            ]
        }
    },
    {
        "std_primitive_i32_as_postgresql_int": 0,
        "sqlx_types_json_t_as_postgresql_json_b_not_null": {
            "std_primitive_i8": 0,
            "std_primitive_i16": 0,
            "std_primitive_i32": 0,
            "std_primitive_i64": 0,
            "std_primitive_i128": 0,
            "std_primitive_u8": 0,
            "std_primitive_u16": 0,
            "std_primitive_u32": 0,
            "std_primitive_u64": 0,
            "std_primitive_u128": 0,
            "std_primitive_f32": 0.0,
            "std_primitive_f64": 0.0,
            "std_primitive_bool": false,
            "std_string_string": "",
            "std_option_option_std_primitive_i8": 0,
            "std_option_option_std_primitive_i16": 0,
            "std_option_option_std_primitive_i32": 0,
            "std_option_option_std_primitive_i64": 0,
            "std_option_option_std_primitive_i128": 0,
            "std_option_option_std_primitive_u8": 0,
            "std_option_option_std_primitive_u16": 0,
            "std_option_option_std_primitive_u32": 0,
            "std_option_option_std_primitive_u64": 0,
            "std_option_option_std_primitive_u128": 0,
            "std_option_option_std_primitive_f32": 0.0,
            "std_option_option_std_primitive_f64": 0.0,
            "std_option_option_std_primitive_bool": false,
            "std_option_option_std_string_string": "",
            "std_vec_vec_std_primitive_i8": [
                0
            ],
            "std_vec_vec_std_primitive_i16": [
                0
            ],
            "std_vec_vec_std_primitive_i32": [
                0
            ],
            "std_vec_vec_std_primitive_i64": [
                0
            ],
            "std_vec_vec_std_primitive_i128": [
                0
            ],
            "std_vec_vec_std_primitive_u8": [
                0
            ],
            "std_vec_vec_std_primitive_u16": [
                0
            ],
            "std_vec_vec_std_primitive_u32": [
                0
            ],
            "std_vec_vec_std_primitive_u64": [
                0
            ],
            "std_vec_vec_std_primitive_u128": [
                0
            ],
            "std_vec_vec_std_primitive_f32": [
                0.0
            ],
            "std_vec_vec_std_primitive_f64": [
                0.0
            ],
            "std_vec_vec_std_primitive_bool": [
                false
            ],
            "std_vec_vec_std_string_string": [
                ""
            ],
            "std_option_option_std_vec_vec_std_primitive_i8": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_i16": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_i32": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_i64": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_i128": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_u8": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_u16": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_u32": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_u64": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_u128": [
                0
            ],
            "std_option_option_std_vec_vec_std_primitive_f32": [
                0.0
            ],
            "std_option_option_std_vec_vec_std_primitive_f64": [
                0.0
            ],
            "std_option_option_std_vec_vec_std_primitive_bool": [
                false
            ],
            "std_option_option_std_vec_vec_std_string_string": [
                ""
            ],
            "std_vec_vec_std_option_option_std_primitive_i8": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_i16": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_i32": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_i64": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_i128": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_u8": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_u16": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_u32": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_u64": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_u128": [
                0
            ],
            "std_vec_vec_std_option_option_std_primitive_f32": [
                0.0
            ],
            "std_vec_vec_std_option_option_std_primitive_f64": [
                0.0
            ],
            "std_vec_vec_std_option_option_std_primitive_bool": [
                false
            ],
            "std_vec_vec_std_option_option_std_string_string": [
                ""
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_i8": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_i16": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_i32": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_i64": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_i128": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_u8": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_u16": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_u32": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_u64": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_u128": [
                0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_f32": [
                0.0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_f64": [
                0.0
            ],
            "std_option_option_std_vec_vec_std_option_option_std_primitive_bool": [
                false
            ],
            "std_option_option_std_vec_vec_std_option_option_std_string_string": [
                ""
            ],
            "generic": {
                "std_string_string": ""
            },
            "std_option_option_generic": {
                "std_string_string": ""
            },
            "std_vec_vec_generic": [
                {
                    "std_string_string": ""
                }
            ],
            "std_option_option_std_vec_vec_generic": [
                {
                    "std_string_string": ""
                }
            ],
            "std_vec_vec_std_option_option_generic": [
                {
                    "std_string_string": ""
                }
            ],
            "std_option_option_std_vec_vec_std_option_option_generic": [
                {
                    "std_string_string": ""
                }
            ]
        }
    }
]

###
 
GET http://127.0.0.1:8080/jsongeneric/create_many_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

###

POST http://127.0.0.1:8080/jsongeneric/create_one HTTP/1.1
content-type: application/json
commit: e9e7647602a980c62e1d20c3d91cf61d3236f5f9

{
    # "std_primitive_i32_as_postgresql_int": 83,
    "sqlx_types_json_t_as_postgresql_json_b_not_null": {
        "std_primitive_i8": 8,
        "std_primitive_i16": 16,
        # "std_primitive_i32": 0,
        # "std_primitive_i64": 0,
        # "std_primitive_i128": 0,
        # "std_primitive_u8": 0,
        # "std_primitive_u16": 0, 
        # "std_primitive_u32": 0,
        # "std_primitive_u64": 0,
        # "std_primitive_u128": 0,
        # "std_primitive_f32": 0.9,
        # "std_primitive_f64": 0.9,
        # "std_primitive_bool": true,
        # "std_string_string": "",

        # "std_option_option_std_primitive_i8": 0,
        # "std_option_option_std_primitive_i16": 0,  
        # "std_option_option_std_primitive_i32": 0,
        # "std_option_option_std_primitive_i64": 0,
        # "std_option_option_std_primitive_i128": 0,
        # "std_option_option_std_primitive_u8": 0,
        # "std_option_option_std_primitive_u16": 0, 
        # "std_option_option_std_primitive_u32": 0,
        # "std_option_option_std_primitive_u64": 0,
        # "std_option_option_std_primitive_u128": 0,
        # "std_option_option_std_primitive_f32": 0.9, 
        # "std_option_option_std_primitive_f64": 0.9, 
        # "std_option_option_std_primitive_bool": true,
        # "std_option_option_std_string_string": "",

        # "std_vec_vec_std_primitive_i8": [0, 1, 2],
        # "std_vec_vec_std_primitive_i16": [0, 1, 2], 
        # "std_vec_vec_std_primitive_i32": [0, 1, 2],
        # "std_vec_vec_std_primitive_i64": [0, 1, 2],
        # "std_vec_vec_std_primitive_i128": [0, 1, 2],
        # "std_vec_vec_std_primitive_u8": [0, 1, 2],
        # "std_vec_vec_std_primitive_u16": [0, 1, 2],
        # "std_vec_vec_std_primitive_u32": [0, 1, 2], 
        # "std_vec_vec_std_primitive_u64": [0, 1, 2],  
        # "std_vec_vec_std_primitive_u128": [0, 1, 2],
        # "std_vec_vec_std_primitive_f32": [0.9, 1.3, 1.6],
        # "std_vec_vec_std_primitive_f64": [0.9, 1.3, 1.6], 
        # "std_vec_vec_std_primitive_bool": [true, false, true],
        # "std_vec_vec_std_string_string": ["one", "two", "three"],

        # "std_option_option_std_vec_vec_std_primitive_i8": [0, 1, 2],
        # "std_option_option_std_vec_vec_std_primitive_i16": [0, 1, 2],
        # "std_option_option_std_vec_vec_std_primitive_i32": [0, 1, 2],
        # "std_option_option_std_vec_vec_std_primitive_i64": [0, 1, 2],
        # "std_option_option_std_vec_vec_std_primitive_i128": [0, 1, 2],
        # "std_option_option_std_vec_vec_std_primitive_u8": [0, 1, 2],
        # "std_option_option_std_vec_vec_std_primitive_u16": [0, 1, 2],
        # "std_option_option_std_vec_vec_std_primitive_u32": [0, 1, 2],
        # "std_option_option_std_vec_vec_std_primitive_u64": [0, 1, 2],
        # "std_option_option_std_vec_vec_std_primitive_u128": [0, 1, 2], 
        # "std_option_option_std_vec_vec_std_primitive_f32": [0.9, 1.3, 1.6],
        # "std_option_option_std_vec_vec_std_primitive_f64": [0.9, 1.3, 1.6],
        # "std_option_option_std_vec_vec_std_primitive_bool": [true, false, true], 
        # "std_option_option_std_vec_vec_std_string_string": ["one", "two", "three"],

        # "std_vec_vec_std_option_option_std_primitive_i8": [0, 1, 2, null],
        # "std_vec_vec_std_option_option_std_primitive_i16": [0, 1, 2, null],
        # "std_vec_vec_std_option_option_std_primitive_i32": [0, 1, 2, null],
        # "std_vec_vec_std_option_option_std_primitive_i64": [0, 1, 2, null],
        # "std_vec_vec_std_option_option_std_primitive_i128": [0, 1, 2, null],
        # "std_vec_vec_std_option_option_std_primitive_u8": [0, 1, 2, null],
        # "std_vec_vec_std_option_option_std_primitive_u16": [0, 1, 2, null], 
        # "std_vec_vec_std_option_option_std_primitive_u32": [0, 1, 2, null],
        # "std_vec_vec_std_option_option_std_primitive_u64": [0, 1, 2, null],
        # "std_vec_vec_std_option_option_std_primitive_u128": [0, 1, 2, null],
        # "std_vec_vec_std_option_option_std_primitive_f32": [0.9, 1.3, 1.6, null],
        # "std_vec_vec_std_option_option_std_primitive_f64": [0.9, 1.3, 1.6, null],
        # "std_vec_vec_std_option_option_std_primitive_bool": [true, false, true, null],
        # "std_vec_vec_std_option_option_std_string_string": ["one", "two", "three", null],

        # "std_option_option_std_vec_vec_std_option_option_std_primitive_i8": [0, 1, 2, null],
        # "std_option_option_std_vec_vec_std_option_option_std_primitive_i16": [0, 1, 2, null], 
        # "std_option_option_std_vec_vec_std_option_option_std_primitive_i32": [0, 1, 2, null],
        # "std_option_option_std_vec_vec_std_option_option_std_primitive_i64": [0, 1, 2, null],
        # "std_option_option_std_vec_vec_std_option_option_std_primitive_i128": [0, 1, 2, null],
        # "std_option_option_std_vec_vec_std_option_option_std_primitive_u8": [0, 1, 2, null],
        # "std_option_option_std_vec_vec_std_option_option_std_primitive_u16": [0, 1, 2, null],
        # "std_option_option_std_vec_vec_std_option_option_std_primitive_u32": [0, 1, 2, null],
        # "std_option_option_std_vec_vec_std_option_option_std_primitive_u64": [0, 1, 2, null],
        # "std_option_option_std_vec_vec_std_option_option_std_primitive_u128": [0, 1, 2, null],
        # "std_option_option_std_vec_vec_std_option_option_std_primitive_f32": [0.9, 1.3, 1.6, null],
        # "std_option_option_std_vec_vec_std_option_option_std_primitive_f64": [0.9, 1.3, 1.6, null],
        # "std_option_option_std_vec_vec_std_option_option_std_primitive_bool": [true, false, true, null],
        # "std_option_option_std_vec_vec_std_option_option_std_string_string": ["one", "two", "three", null]
        # ,

        "generic": {
            "std_primitive_i16": 0,
            "std_option_option_std_primitive_i32": 0,
            "std_string_string": "one"
        }
        ,
        "std_option_option_generic": {
            "std_primitive_i16": 0,
            "std_option_option_std_primitive_i32": 0,
            "std_string_string": "two"
        }
        # ,
        # "std_vec_vec_generic": [
        #     {
        #         "std_string_string": "sdss"
        #     }
        # ],
        # "std_option_option_std_vec_vec_generic": [
        #     {
        #         "std_string_string": "sdss"
        #     }
        # ],
        # "std_vec_vec_std_option_option_generic": [
        #     {
        #       "std_string_string": "sdss"
        #     },
        #     null
        # ],
        # "std_option_option_std_vec_vec_std_option_option_generic": [
        #     {
        #         "std_string_string": "sdss"
        #     },
        #     null
        # ]
    }
}

###
 
GET http://127.0.0.1:8080/jsongeneric/create_one_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

###

POST http://127.0.0.1:8080/jsongeneric/read_many HTTP/1.1
content-type: application/json
commit: 72a7f5c066a08a77fb91e75abee9f6e79e00e2b8

{
    "select": [
        # "std_primitive_i32_as_postgresql_int",
        # "std_primitive_i16_as_postgresql_small_int",
        {
            "sqlx_types_json_t_as_postgresql_json_b_not_null":{
                "filter": [

                    "std_primitive_i8",
                    "std_primitive_i16"
                    # ,
                    # "std_primitive_i32",
                    # "std_primitive_i64",
                    # "std_primitive_i128",
                    # "std_primitive_u8",
                    # "std_primitive_u16", 
                    # "std_primitive_u32",
                    # "std_primitive_u64",
                    # "std_primitive_u128",
                    # "std_primitive_f32",
                    # "std_primitive_f64",
                    # "std_primitive_bool",
                    # "std_string_string",

                    # "std_option_option_std_primitive_i8",
                    # "std_option_option_std_primitive_i16",  
                    # "std_option_option_std_primitive_i32",
                    # "std_option_option_std_primitive_i64",
                    # "std_option_option_std_primitive_i128",
                    # "std_option_option_std_primitive_u8",
                    # "std_option_option_std_primitive_u16", 
                    # "std_option_option_std_primitive_u32",
                    # "std_option_option_std_primitive_u64",
                    # "std_option_option_std_primitive_u128",
                    # "std_option_option_std_primitive_f32", 
                    # "std_option_option_std_primitive_f64", 
                    # "std_option_option_std_primitive_bool",
                    # "std_option_option_std_string_string",

                    # {
                    #     "std_vec_vec_std_primitive_i8": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_primitive_i16": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # }, 
                    # {
                    #     "std_vec_vec_std_primitive_i32": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_primitive_i64": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_primitive_i128": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_primitive_u8": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_primitive_u16": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_primitive_u32": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # }, 
                    # {
                    #     "std_vec_vec_std_primitive_u64": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },  
                    # {
                    #     "std_vec_vec_std_primitive_u128": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_primitive_f32": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_primitive_f64": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # }, 
                    # {
                    #     "std_vec_vec_std_primitive_bool": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_string_string": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },

                    # {
                    #     "std_option_option_std_vec_vec_std_primitive_i8": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_primitive_i16": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_primitive_i32": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_primitive_i64": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_primitive_i128": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_primitive_u8": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_primitive_u16": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_primitive_u32": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_primitive_u64": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_primitive_u128": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # }, 
                    # {
                    #     "std_option_option_std_vec_vec_std_primitive_f32": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_primitive_f64": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_primitive_bool": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # }, 
                    # {
                    #     "std_option_option_std_vec_vec_std_string_string": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },

                    # {
                    #     "std_vec_vec_std_option_option_std_primitive_i8": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_option_option_std_primitive_i16": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_option_option_std_primitive_i32": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_option_option_std_primitive_i64": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_option_option_std_primitive_i128": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_option_option_std_primitive_u8": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_option_option_std_primitive_u16": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # }, 
                    # {
                    #     "std_vec_vec_std_option_option_std_primitive_u32": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_option_option_std_primitive_u64": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_option_option_std_primitive_u128": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_option_option_std_primitive_f32": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_option_option_std_primitive_f64": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_option_option_std_primitive_bool": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_vec_vec_std_option_option_std_string_string": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },

                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_std_primitive_i8": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # }
                    # ,
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_std_primitive_i16": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # }
                    # , 
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_std_primitive_i32": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_std_primitive_i64": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_std_primitive_i128": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_std_primitive_u8": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_std_primitive_u16": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_std_primitive_u32": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_std_primitive_u64": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_std_primitive_u128": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_std_primitive_f32": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_std_primitive_f64": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_std_primitive_bool": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_std_string_string": {
                    #         "offset": 0,
                    #         "limit": 8
                    #     }
                    # },

                    # {
                    #     "generic": ["std_string_string"]
                    # }
                    # ,
                    # {
                    #     "std_option_option_generic": ["std_string_string"]
                    # }
                    # ,
                    # {
                    #     "std_vec_vec_generic": {
                    #         "field_vec": [
                    #             "std_string_string"
                    #         ],
                    #         "offset": 0,
                    #         "limit": 3
                    #     }
                    # }
                    # ,
                    # {
                    #     "std_option_option_std_vec_vec_generic": {
                    #         "field_vec": [
                    #             "std_string_string"
                    #         ],
                    #         "offset": 0,
                    #         "limit": 3
                    #     }
                    # }
                    # ,
                    # {
                    #     "std_vec_vec_std_option_option_generic": {
                    #         "field_vec": [
                    #             "std_string_string"
                    #         ],
                    #         "offset": 0,
                    #         "limit": 3
                    #     }
                    # }
                    # ,
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_generic": {
                    #         "field_vec": [
                    #             "std_string_string"
                    #         ],
                    #         "offset": 0,
                    #         "limit": 3
                    #     }
                    # }
                ]
            }
        }
    ],
    # "id": [
    #     "7b51bb9c-124e-44ba-9941-7f32a2c18c78",
    #     "5829d06c-4141-4734-8266-b3d1e618c4de",
    #     "be13a118-e5e5-4cb6-93fe-5a1f1767d666"
    # ],
    # "name":[
    #     {
    #         "regex":"^tesft_namfe$",
    #         "conjuctive_operator":"Or"
    #     }
    # ],
    "order_by": {
        "column": "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key",
        "order": "desc"
    },
    "limit": 100,
    "offset": 0
}

### todo name and color must be  arrays       

POST http://127.0.0.1:8080/jsongeneric/read_one HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

{
    "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key": 14,
    "select": [
        {
            "sqlx_types_json_t_as_postgresql_json_b_not_null":{
                "filter": [
                    "std_primitive_i8",
                    "std_primitive_i16",
                    "std_primitive_i32",
                    "std_primitive_i64",
                    "std_primitive_i128",
                    "std_primitive_u8",
                    "std_primitive_u16", 
                    "std_primitive_u32",
                    "std_primitive_u64",
                    "std_primitive_u128",
                    "std_primitive_f32",
                    "std_primitive_f64",
                    "std_primitive_bool",
                    "std_string_string",

                    "std_option_option_std_primitive_i8",
                    "std_option_option_std_primitive_i16",  
                    "std_option_option_std_primitive_i32",
                    "std_option_option_std_primitive_i64",
                    "std_option_option_std_primitive_i128",
                    "std_option_option_std_primitive_u8",
                    "std_option_option_std_primitive_u16", 
                    "std_option_option_std_primitive_u32",
                    "std_option_option_std_primitive_u64",
                    "std_option_option_std_primitive_u128",
                    "std_option_option_std_primitive_f32", 
                    "std_option_option_std_primitive_f64", 
                    "std_option_option_std_primitive_bool",
                    "std_option_option_std_string_string",

                    {
                        "std_vec_vec_std_primitive_i8": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_primitive_i16": {
                            "offset": 0,
                            "limit": 8
                        }
                    }, 
                    {
                        "std_vec_vec_std_primitive_i32": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_primitive_i64": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_primitive_i128": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_primitive_u8": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_primitive_u16": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_primitive_u32": {
                            "offset": 0,
                            "limit": 8
                        }
                    }, 
                    {
                        "std_vec_vec_std_primitive_u64": {
                            "offset": 0,
                            "limit": 8
                        }
                    },  
                    {
                        "std_vec_vec_std_primitive_u128": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_primitive_f32": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_primitive_f64": {
                            "offset": 0,
                            "limit": 8
                        }
                    }, 
                    {
                        "std_vec_vec_std_primitive_bool": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_string_string": {
                            "offset": 0,
                            "limit": 8
                        }
                    },

                    {
                        "std_option_option_std_vec_vec_std_primitive_i8": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_primitive_i16": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_primitive_i32": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_primitive_i64": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_primitive_i128": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_primitive_u8": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_primitive_u16": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_primitive_u32": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_primitive_u64": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_primitive_u128": {
                            "offset": 0,
                            "limit": 8
                        }
                    }, 
                    {
                        "std_option_option_std_vec_vec_std_primitive_f32": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_primitive_f64": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_primitive_bool": {
                            "offset": 0,
                            "limit": 8
                        }
                    }, 
                    {
                        "std_option_option_std_vec_vec_std_string_string": {
                            "offset": 0,
                            "limit": 8
                        }
                    },

                    {
                        "std_vec_vec_std_option_option_std_primitive_i8": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_option_option_std_primitive_i16": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_option_option_std_primitive_i32": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_option_option_std_primitive_i64": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_option_option_std_primitive_i128": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_option_option_std_primitive_u8": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_option_option_std_primitive_u16": {
                            "offset": 0,
                            "limit": 8
                        }
                    }, 
                    {
                        "std_vec_vec_std_option_option_std_primitive_u32": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_option_option_std_primitive_u64": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_option_option_std_primitive_u128": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_option_option_std_primitive_f32": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_option_option_std_primitive_f64": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_option_option_std_primitive_bool": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_vec_vec_std_option_option_std_string_string": {
                            "offset": 0,
                            "limit": 8
                        }
                    },

                    {
                        "std_option_option_std_vec_vec_std_option_option_std_primitive_i8": {
                            "offset": 0,
                            "limit": 8
                        }
                    }
                    ,
                    {
                        "std_option_option_std_vec_vec_std_option_option_std_primitive_i16": {
                            "offset": 0,
                            "limit": 8
                        }
                    }
                    , 
                    {
                        "std_option_option_std_vec_vec_std_option_option_std_primitive_i32": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_option_option_std_primitive_i64": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_option_option_std_primitive_i128": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_option_option_std_primitive_u8": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_option_option_std_primitive_u16": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_option_option_std_primitive_u32": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_option_option_std_primitive_u64": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_option_option_std_primitive_u128": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_option_option_std_primitive_f32": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_option_option_std_primitive_f64": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_option_option_std_primitive_bool": {
                            "offset": 0,
                            "limit": 8
                        }
                    },
                    {
                        "std_option_option_std_vec_vec_std_option_option_std_string_string": {
                            "offset": 0,
                            "limit": 8
                        }
                    }
                    ,

                    {
                        "generic": ["std_string_string"]
                    }
                    # ,
                    # {
                    #     "std_option_option_generic": ["std_string_string"]
                    # }
                    # ,
                    # {
                    #     "std_vec_vec_generic": {
                    #         "field_vec": [
                    #             "std_string_string"
                    #         ],
                    #         "offset": 0,
                    #         "limit": 3
                    #     }
                    # }
                    # ,
                    # {
                    #     "std_option_option_std_vec_vec_generic": {
                    #         "field_vec": [
                    #             "std_string_string"
                    #         ],
                    #         "offset": 0,
                    #         "limit": 3
                    #     }
                    # }
                    # ,
                    # {
                    #     "std_vec_vec_std_option_option_generic": {
                    #         "field_vec": [
                    #             "std_string_string"
                    #         ],
                    #         "offset": 0,
                    #         "limit": 3
                    #     }
                    # }
                    # ,
                    # {
                    #     "std_option_option_std_vec_vec_std_option_option_generic": {
                    #         "field_vec": [
                    #             "std_string_string"
                    #         ],
                    #         "offset": 0,
                    #         "limit": 3
                    #     }
                    # }
                ]
            }
        }
        # ,
        # "std_primitive_i32_as_postgresql_int"
        # "std_primitive_i16_as_postgresql_small_int"
    ]
}

### fix this  
 
PATCH http://127.0.0.1:8080/jsongeneric/update_many HTTP/1.1 
content-type: application/json
commit: f7e8bd75a29858f2be33b8076f2ebda4bd413a70

[
    {
        "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key": 1,
        "std_primitive_i32_as_postgresql_int": {
            "value": 84
        }
    },
    {
        "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key": 2,
        "sqlx_types_json_t_as_postgresql_json_not_null": {
            "value": {
                "something": "kekew"
            }
        }
    }
]

### 

PATCH http://127.0.0.1:8080/jsongeneric/update_one HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

{
    "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key": 14,
    # "std_primitive_i32_as_postgresql_int": {
    #     "value": 44
    # },
    "sqlx_types_json_t_as_postgresql_json_b_not_null": {
        "value": [
            # {
            #     "std_primitive_i8": {
            #         "value": 79
            #     }
            # }
            # ,
            # {
            #     "std_primitive_i16": {
            #         "value": 27
            #     }
            # },
            # {
            #     "std_primitive_i32": {
            #         "value": 240
            #     }
            # },
            # {
            #     "std_primitive_i64": {
            #         "value": 1
            #     }
            # },
            # {
            #     "std_primitive_i128": {
            #         "value": 44
            #     }
            # },
            # {
            #     "std_primitive_u8": {
            #         "value": 1
            #     }
            # },
            # {
            #     "std_primitive_u16": {
            #         "value": 1
            #     }
            # },
            # {
            #     "std_primitive_u32": {
            #         "value": 1
            #     }
            # },
            # {
            #     "std_primitive_u64": {
            #         "value": 1
            #     }
            # },
            # {
            #     "std_primitive_u128": {
            #         "value": 1
            #     }
            # },
            # {
            #     "std_primitive_f32": {
            #         "value": 1.0
            #     }
            # },
            # {
            #     "std_primitive_f64": {
            #         "value": 1.0
            #     }
            # },
            # {
            #     "std_primitive_bool": {
            #         "value": true
            #     }
            # },
            # {
            #     "std_string_string": {
            #         "value": "meow"
            #     }
            # },

            # {
            #     "std_option_option_std_primitive_i8": {
            #         "value": 76
            #     }
            # },
            # {
            #     "std_option_option_std_primitive_i16": {
            #         "value": 76
            #     }
            # },
            # {
            #     "std_option_option_std_primitive_i32": {
            #         "value": 76
            #     }
            # },
            # {
            #     "std_option_option_std_primitive_i64": {
            #         "value": 76
            #     }
            # },
            # {
            #     "std_option_option_std_primitive_i128": {
            #         "value": 76
            #     }
            # },
            # {
            #     "std_option_option_std_primitive_u8": {
            #         "value": 76
            #     }
            # },
            # {
            #     "std_option_option_std_primitive_u16": {
            #         "value": 76
            #     }
            # },
            # {
            #     "std_option_option_std_primitive_u32": {
            #         "value": 76
            #     }
            # },
            # {
            #     "std_option_option_std_primitive_u64": {
            #         "value": 76
            #     }
            # },
            # {
            #     "std_option_option_std_primitive_u128": {
            #         "value": 76
            #     }
            # },
            # {
            #     "std_option_option_std_primitive_f32": {
            #         "value": 76.0
            #     }
            # },
            # {
            #     "std_option_option_std_primitive_f64": {
            #         "value": 76.0
            #     }
            # },
            # {
            #     "std_option_option_std_primitive_bool": {
            #         "value": true
            #     }
            # },
            # {
            #     "std_option_option_std_string_string": {
            #         "value": "rrr"
            #     }
            # },

            # {
            #     "std_vec_vec_std_primitive_i8": {
            #         "value": [31, 22]
            #     }
            # },
            # {
            #     "std_vec_vec_std_primitive_i16": {
            #         "value": [31, 22]
            #     }
            # },
            # {
            #     "std_vec_vec_std_primitive_i32": {
            #         "value": [31, 22]
            #     }
            # },
            # {
            #     "std_vec_vec_std_primitive_i64": {
            #         "value": [31, 22]
            #     }
            # },
            # {
            #     "std_vec_vec_std_primitive_i128": {
            #         "value": [31, 22]
            #     }
            # },
            # {
            #     "std_vec_vec_std_primitive_u8": {
            #         "value": [31, 22]
            #     }
            # },
            # {
            #     "std_vec_vec_std_primitive_u16": {
            #         "value": [31, 22]
            #     }
            # },
            # {
            #     "std_vec_vec_std_primitive_u32": {
            #         "value": [31, 22]
            #     }
            # },
            # {
            #     "std_vec_vec_std_primitive_u64": {
            #         "value": [31, 22]
            #     }
            # },
            # {
            #     "std_vec_vec_std_primitive_u128": {
            #         "value": [31, 22]
            #     }
            # },
            # {
            #     "std_vec_vec_std_primitive_f32": {
            #         "value": [31.5, 22.8]
            #     }
            # },
            # {
            #     "std_vec_vec_std_primitive_f64": {
            #         "value": [31.4, 22.2]
            #     }
            # },
            # {
            #     "std_vec_vec_std_primitive_bool": {
            #         "value": [true, false, true]
            #     }
            # },
            # {
            #     "std_vec_vec_std_string_string": {
            #         "value": ["one", "two"]
            #     }
            # },

            # {
            #     "std_option_option_std_vec_vec_std_primitive_i8": {
            #         "value": [0, 1, 2]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_primitive_i16": {
            #         "value": [0, 1, 2]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_primitive_i32": {
            #         "value": [0, 1, 2]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_primitive_i64": {
            #         "value": [0, 1, 2]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_primitive_i128": {
            #         "value": [0, 1, 2]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_primitive_u8": {
            #         "value": [0, 1, 2]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_primitive_u16": {
            #         "value": [0, 1, 2]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_primitive_u32": {
            #         "value": [0, 1, 2]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_primitive_u64": {
            #         "value": [0, 1, 2]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_primitive_u128": {
            #         "value": [0, 1, 2]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_primitive_f32": {
            #         "value": [0.5, 1.4, 2.9]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_primitive_f64": {
            #         "value": [0.5, 1.4, 2.7]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_primitive_bool": {
            #         "value": [true, false, true]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_string_string": {
            #         "value": ["one", "two"]
            #     }
            # },


            # {
            #     "std_vec_vec_std_option_option_std_primitive_i8": {
            #         "value": [0, 1, 2, null]
            #     }
            # },
            # {
            #     "std_vec_vec_std_option_option_std_primitive_i16": {
            #         "value": [0, 1, 2, null]
            #     }
            # },
            # {
            #     "std_vec_vec_std_option_option_std_primitive_i32": {
            #         "value": [0, 1, 2, null]
            #     }
            # },
            # {
            #     "std_vec_vec_std_option_option_std_primitive_i64": {
            #         "value": [0, 1, 2, null]
            #     }
            # },
            # {
            #     "std_vec_vec_std_option_option_std_primitive_i128": {
            #         "value": [0, 1, 2, null]
            #     }
            # },
            # {
            #     "std_vec_vec_std_option_option_std_primitive_u8": {
            #         "value": [0, 1, 2, null]
            #     }
            # },
            # {
            #     "std_vec_vec_std_option_option_std_primitive_u16": {
            #         "value": [0, 1, 2, null]
            #     }
            # },
            # {
            #     "std_vec_vec_std_option_option_std_primitive_u32": {
            #         "value": [0, 1, 2, null]
            #     }
            # },
            # {
            #     "std_vec_vec_std_option_option_std_primitive_u64": {
            #         "value": [0, 1, 2, null]
            #     }
            # },
            # {
            #     "std_vec_vec_std_option_option_std_primitive_u128": {
            #         "value": [0, 1, 2, null]
            #     }
            # },
            # {
            #     "std_vec_vec_std_option_option_std_primitive_f32": {
            #         "value": [0.3, 1.1, 2.6, null]
            #     }
            # },
            # {
            #     "std_vec_vec_std_option_option_std_primitive_f64": {
            #         "value": [0.7, 1.3, 2.5, null]
            #     }
            # },
            # {
            #     "std_vec_vec_std_option_option_std_primitive_bool": {
            #         "value": [true, false, true, null]
            #     }
            # },
            # {
            #     "std_vec_vec_std_option_option_std_string_string": {
            #         "value": ["one", "two", null]
            #     }
            # },

            # {
            #     "std_option_option_std_vec_vec_std_option_option_std_primitive_i8": {
            #         "value": [0, 1, 28, null, 43]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_option_option_std_primitive_i16": {
            #         "value": [0, 1, 28, null, 43]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_option_option_std_primitive_i32": {
            #         "value": [0, 1, 28, null, 43]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_option_option_std_primitive_i64": {
            #         "value": [0, 1, 28, null, 43]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_option_option_std_primitive_i128": {
            #         "value": [0, 1, 28, null, 43]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_option_option_std_primitive_u8": {
            #         "value": [0, 1, 28, null, 43]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_option_option_std_primitive_u16": {
            #         "value": [0, 1, 28, null, 43]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_option_option_std_primitive_u32": {
            #         "value": [0, 1, 28, null, 43]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_option_option_std_primitive_u64": {
            #         "value": [0, 1, 28, null, 43]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_option_option_std_primitive_u128": {
            #         "value": [0, 1, 28, null, 43]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_option_option_std_primitive_f32": {
            #         "value": [0.8, 1.4, null]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_option_option_std_primitive_f64": {
            #         "value": [0.4, 1.3, null]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_option_option_std_primitive_bool": {
            #         "value": [true, false, true, null]
            #     }
            # },
            # {
            #     "std_option_option_std_vec_vec_std_option_option_std_string_string": {
            #         "value": ["one", "two", null]
            #     }
            # },


            # {
            #     "generic": {
            #         "value": [
            #             {
            #                 "std_primitive_i16": {
            #                     "value": 4
            #                 }
            #             },
            #             {
            #                 "std_option_option_std_primitive_i32": {
            #                     "value": 5
            #                 }
            #             },
            #             {
            #                 "std_string_string": {
            #                     "value": "ureurer"
            #                 }
            #             }
            #         ]
            #     }
            # }
            # ,
            {
                "std_option_option_generic": {
                    "value": 
                    # null
                    [
                        {
                            "std_primitive_i16": {
                                "value": 88
                            }
                        }
                        ,
                        {
                            "std_option_option_std_primitive_i32": {
                                "value": 55
                            }
                        }
                        ,
                        {
                            "std_string_string": {
                                "value": "88"
                            }
                        }
                    ]
                }
            }
        ]
    }
}

####"^first_test_name_create$"  

DELETE http://127.0.0.1:8080/jsongeneric/delete_many HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

{
    "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key": [
      3
    ]
    # ,
    # "name":[
    #     {
    #         "regex":"first_test_name_create",
    #         "conjuctive_operator":"Or"
    #     }
    # ],
    # "color":[
    #     {
    #         "regex":"first_test_color_create",
    #         "conjuctive_operator":"Or"
    #     }
    # ]
}

###

DELETE http://127.0.0.1:8080/jsongeneric/delete_one HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

{
    "std_primitive_i64_as_postgresql_big_serial_not_null_primary_key": 4
}

###

GET http://127.0.0.1:8080/health_check HTTP/1.1

### 

GET http://127.0.0.1:8080/git_info HTTP/1.1

###

GET http://127.0.0.1:8080/src/main.rs HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786

###

GET http://127.0.0.1:8080/header_extractor_example HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786

###

GET http://127.0.0.1:8080/extract_custom_header_example HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786

###

GET http://127.0.0.1:8080/middleware_message_example HTTP/1.1

###

GET http://127.0.0.1:8080/read_middleware_custom_header HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786