[package]
edition = "2021"
name = "proc_macro_helpers"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
proc-macro2 = {version = "=1.0.81"}
quote = {version = "=1.0.36"}
syn = {version = "=2.0.60"} # activate impl Display trait in proc macros: syn = { version = "1.0.75", features = ["extra-traits"]}
strum = {version = "=0.24.1"}
strum_macros = {version = "=0.24.3"}
proc_macro_assistants = {path = "../proc_macro_assistants"}
proc_macro_common = {path = "../proc_macro_common"}
naming_constants = {path = "../naming_constants"}

[lints]
workspace = true
