[package]
edition = "2021"
name = "generate_postgresql_crud_second"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
# proc-macro2 = {version = "=1.0.81"}
quote = {version = "=1.0.36"}
syn = {version = "=2.0.60"}
# convert_case = {version = "=0.6.0"}
# strum_macros = {version = "=0.24.3"}
# postgresql_crud_common = {path = "./../postgresql_crud_common"}
constants = {path = "../../constants"}
# generate_quotes = {path = "../../generate_quotes"}
panic_location = {path = "../../panic_location"}
# macros_helpers = {path = "../../macros_helpers"}
# naming_conventions = {path = "../../naming_conventions"}
# token_patterns = {path = "../../token_patterns"}

[lints]
workspace = true
