[package]
name = "naming_conventions"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = {version = "=1.0.81"}
quote = {version = "=1.0.36"}
syn = {version = "=2.0.60"}
macros_common = {path = "../macros_common"}
naming_macros = {path = "./naming_macros"}

[lints]
workspace = true
