[package]
edition = "2021"
name = "tufa_grpc_server"
version = "0.1.0"

[dependencies]
prost = "0.10"
tokio = {version = "1.0", features = ["macros", "rt-multi-thread"]}
tonic = "0.7"

[build-dependencies]
tonic-build = "0.7"
