pub use postgresql_crud_common_and_macros_common::*;

macro_rules! trait_alias {
    ($name:ident = $($bounds:tt)+) => {
        pub trait $name: $($bounds)+ {}
        impl<T: $($bounds)+> $name for T {}
    };
}

trait_alias!(DebugClonePartialEqAlias = std::fmt::Debug + Clone + PartialEq);
trait_alias!(DebugClonePartialEqSerializeAlias = DebugClonePartialEqAlias + serde::Serialize);
trait_alias!(DebugClonePartialEqSerializeDeserializeAlias = DebugClonePartialEqSerializeAlias + for<'__> serde::Deserialize<'__>);
trait_alias!(DebugClonePartialEqSerializeDeserializeDefaultSomeOneAlias = DebugClonePartialEqSerializeDeserializeAlias + postgresql_crud_common_and_macros_common::DefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement);
trait_alias!(SqlxEncodePostgresSqlxTypePostgresAlias = for<'__> sqlx::Encode<'__, sqlx::Postgres> + sqlx::Type<sqlx::Postgres>);
trait_alias!(UtoipaToSchemaAndSchemarsJsonSchemaAlias = for<'__> utoipa::ToSchema<'__> + schemars::JsonSchema);

trait_alias!(TableTypeDeclarationAlias = DebugClonePartialEqSerializeDeserializeDefaultSomeOneAlias);
trait_alias!(CreateAlias = DebugClonePartialEqSerializeDeserializeDefaultSomeOneAlias);
trait_alias!(CreateForQueryAlias = DebugClonePartialEqSerializeAlias + SqlxEncodePostgresSqlxTypePostgresAlias);
trait_alias!(SelectAlias = DebugClonePartialEqSerializeDeserializeDefaultSomeOneAlias);
trait_alias!(WhereAlias = DebugClonePartialEqSerializeDeserializeAlias + for<'__> PostgresqlTypeWhereFilter<'__>);
trait_alias!(ReadAlias = DebugClonePartialEqSerializeDeserializeAlias);
trait_alias!(ReadOnlyIdsAlias = DebugClonePartialEqSerializeDeserializeAlias);
trait_alias!(ReadInnerAlias = DebugClonePartialEqAlias);
trait_alias!(UpdateAlias = DebugClonePartialEqSerializeDeserializeDefaultSomeOneAlias);
trait_alias!(UpdateForQueryAlias = DebugClonePartialEqSerializeAlias);

pub trait PostgresqlType {
    //difference between Create and TableTypeDeclaration - Create may not contain generated by postgresql id
    type TableTypeDeclaration: TableTypeDeclarationAlias;
    fn create_table_column_query_part(column: &dyn std::fmt::Display, _: std::primitive::bool) -> impl std::fmt::Display;
    type Create: CreateAlias;
    fn create_query_part(value: &Self::Create, increment: &mut std::primitive::u64) -> Result<std::string::String, QueryPartErrorNamed>;
    fn create_query_bind(value: Self::Create, query: sqlx::query::Query<'_, sqlx::Postgres, sqlx::postgres::PgArguments>) -> Result<
        sqlx::query::Query<'_, sqlx::Postgres, sqlx::postgres::PgArguments>,
        std::string::String
    >;
    type Select: SelectAlias;
    //todo change trait fn select_query_part( to Result String CheckedAdd
    fn select_query_part(value: &Self::Select, column: &std::primitive::str) -> std::string::String;
    type Where: WhereAlias;
    type Read: ReadAlias + for<'__> sqlx::Decode<'__, sqlx::Postgres> + sqlx::Type<sqlx::Postgres>;
    fn normalize(value: Self::Read) -> Self::Read;
    type ReadOnlyIds: ReadOnlyIdsAlias;
    fn select_only_ids_query_part(column: &std::primitive::str) -> std::string::String;
    type ReadInner: ReadInnerAlias;
    fn into_inner(value: Self::Read) -> Self::ReadInner;
    type Update: UpdateAlias;
    type UpdateForQuery: UpdateForQueryAlias;
    fn update_query_part(value: &Self::UpdateForQuery, jsonb_set_accumulator: &std::primitive::str, jsonb_set_target: &std::primitive::str, jsonb_set_path: &std::primitive::str, increment: &mut std::primitive::u64) -> Result<std::string::String, QueryPartErrorNamed>;
    fn update_query_bind(value: Self::UpdateForQuery, query: sqlx::query::Query<'_, sqlx::Postgres, sqlx::postgres::PgArguments>) -> Result<
        sqlx::query::Query<'_, sqlx::Postgres, sqlx::postgres::PgArguments>,
        std::string::String
    >;
    fn select_only_updated_ids_query_part(value: &Self::UpdateForQuery, column: &std::primitive::str, increment: &mut std::primitive::u64) -> Result<std::string::String, QueryPartErrorNamed>;
    fn select_only_updated_ids_query_bind<'a>(value: &'a Self::UpdateForQuery, query: sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>) -> Result<
        sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>,
        std::string::String
    >;
}

pub trait PostgresqlJsonType {
    type TableTypeDeclaration: TableTypeDeclarationAlias + UtoipaToSchemaAndSchemarsJsonSchemaAlias;
    type Create: CreateAlias + UtoipaToSchemaAndSchemarsJsonSchemaAlias;
    type CreateForQuery: CreateForQueryAlias + std::convert::From<Self::Create>;
    type Select: SelectAlias + UtoipaToSchemaAndSchemarsJsonSchemaAlias;
    //todo change trait fn select_query_part( to Result String CheckedAdd
    fn select_query_part(
        value: &Self::Select,
        field_ident: &std::primitive::str,
        column_name_and_maybe_field_getter: &std::primitive::str,
        //todo remove this coz its used properly now
        column_name_and_maybe_field_getter_for_error_message: &std::primitive::str,
        is_postgresql_type: std::primitive::bool,
    ) -> std::string::String;
    type Where: WhereAlias
        + UtoipaToSchemaAndSchemarsJsonSchemaAlias
        + postgresql_crud_common_and_macros_common::AllEnumVariantsArrayDefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement
        + error_occurence_lib::ToStdStringString;
    //todo impl get fields from read
    //todo maybe add sqlx::Decode trait here and sqlx::Type
    type Read: ReadAlias + UtoipaToSchemaAndSchemarsJsonSchemaAlias + postgresql_crud_common_and_macros_common::DefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement;
    type ReadOnlyIds: ReadOnlyIdsAlias;
    fn select_only_ids_query_part(column_name_and_maybe_field_getter: &std::primitive::str) -> std::string::String;
    type ReadInner: ReadInnerAlias;
    fn into_inner(value: Self::Read) -> Self::ReadInner;
    type Update: UpdateAlias + UtoipaToSchemaAndSchemarsJsonSchemaAlias;
    type UpdateForQuery: UpdateForQueryAlias + std::convert::From<Self::Update>;
    fn update_query_part(value: &Self::UpdateForQuery, jsonb_set_accumulator: &std::primitive::str, jsonb_set_target: &std::primitive::str, jsonb_set_path: &std::primitive::str, increment: &mut std::primitive::u64) -> Result<std::string::String, QueryPartErrorNamed>;
    fn update_query_bind(value: Self::UpdateForQuery, query: sqlx::query::Query<'_, sqlx::Postgres, sqlx::postgres::PgArguments>) -> Result<
        sqlx::query::Query<'_, sqlx::Postgres, sqlx::postgres::PgArguments>,
        std::string::String
    >;
    fn select_only_updated_ids_query_part(value: &Self::UpdateForQuery, field_ident: &std::primitive::str, column_name_and_maybe_field_getter: &std::primitive::str, increment: &mut std::primitive::u64) -> Result<std::string::String, QueryPartErrorNamed>;
    fn select_only_updated_ids_query_bind<'a>(value: &'a Self::UpdateForQuery, query: sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>) -> Result<
        sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>,
        std::string::String
    >;
    fn select_only_created_ids_query_part(value: &Self::CreateForQuery, field_ident: &std::primitive::str, column_name_and_maybe_field_getter: &std::primitive::str, increment: &mut std::primitive::u64) -> Result<std::string::String, QueryPartErrorNamed>;
    fn select_only_created_ids_query_bind<'a>(value: &'a Self::CreateForQuery, query: sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>) -> Result<
        sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>,
        std::string::String
    >;
}

pub trait PostgresqlTypePrimaryKey {
    type PostgresqlType: PostgresqlType;
    type TableTypeDeclaration: TableTypeDeclarationAlias + PartialOrd;
    fn read_only_ids_into_table_type_declaration(
        value: <Self::PostgresqlType as PostgresqlType>::ReadOnlyIds
    ) -> <Self::PostgresqlType as PostgresqlType>::TableTypeDeclaration;
    fn read_only_ids_into_read(
        value: <Self::PostgresqlType as PostgresqlType>::ReadOnlyIds
    ) -> <Self::PostgresqlType as PostgresqlType>::Read;
    fn read_only_ids_into_update(
        value: <Self::PostgresqlType as PostgresqlType>::ReadOnlyIds
    ) -> <Self::PostgresqlType as PostgresqlType>::Update;
    fn read_into_table_type_declaration(
        value: <Self::PostgresqlType as PostgresqlType>::Read
    ) -> <Self::PostgresqlType as PostgresqlType>::TableTypeDeclaration;
}

pub trait PostgresqlTypeNotPrimaryKey {
    type PostgresqlType: PostgresqlType;
    type Create: CreateAlias + SqlxEncodePostgresSqlxTypePostgresAlias;
}

pub trait PostgresqlJsonTypeObjectVecElementId {
    type PostgresqlJsonType: PostgresqlJsonType;
    type CreateForQuery: CreateForQueryAlias
        + std::convert::From<<Self::PostgresqlJsonType as PostgresqlJsonType>::Create>
        + std::convert::From<<Self::PostgresqlJsonType as PostgresqlJsonType>::Update>;
    type Update: UpdateAlias + UtoipaToSchemaAndSchemarsJsonSchemaAlias + error_occurence_lib::ToStdStringString;
    type ReadInner: ReadInnerAlias;
    fn query_bind_string_as_postgresql_text_create_for_query(
        value: <Self::PostgresqlJsonType as PostgresqlJsonType>::CreateForQuery,
        query: sqlx::query::Query<'_, sqlx::Postgres, sqlx::postgres::PgArguments>
    ) -> Result<
        sqlx::query::Query<'_, sqlx::Postgres, sqlx::postgres::PgArguments>,
        std::string::String
    >;
    fn query_bind_string_as_postgresql_text_update_for_query(
        value: <Self::PostgresqlJsonType as PostgresqlJsonType>::UpdateForQuery,
        query: sqlx::query::Query<'_, sqlx::Postgres, sqlx::postgres::PgArguments>
    ) -> Result<
        sqlx::query::Query<'_, sqlx::Postgres, sqlx::postgres::PgArguments>,
        std::string::String
    >;
    fn get_inner<'a>(value: &'a <Self::PostgresqlJsonType as PostgresqlJsonType>::CreateForQuery) -> &'a Self::ReadInner;
    fn increment_checked_add_one(increment: &mut std::primitive::u64) -> Result<std::primitive::u64, QueryPartErrorNamed>;
}

#[cfg(feature = "test-utils")]
pub trait PostgresqlTypeTestCases {
    type PostgresqlType: PostgresqlType;
    type Select: SelectAlias + postgresql_crud_common_and_macros_common::DefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElementWithMaxPageSize;
    fn option_vec_create() -> std::option::Option<std::vec::Vec<<Self::PostgresqlType as PostgresqlType>::Create>>;
    fn read_only_ids_to_two_dimensional_vec_read_inner(read_only_ids: &<Self::PostgresqlType as PostgresqlType>::ReadOnlyIds) -> std::vec::Vec<std::vec::Vec<<Self::PostgresqlType as PostgresqlType>::ReadInner>>;
    fn read_inner_into_read_with_new_or_try_new_unwraped(value: <Self::PostgresqlType as PostgresqlType>::ReadInner) -> <Self::PostgresqlType as PostgresqlType>::Read;
    fn read_inner_into_update_with_new_or_try_new_unwraped(value: <Self::PostgresqlType as PostgresqlType>::ReadInner) -> <Self::PostgresqlType as PostgresqlType>::Update;
    fn update_to_read_only_ids(value: &<Self::PostgresqlType as PostgresqlType>::Update) -> <Self::PostgresqlType as PostgresqlType>::ReadOnlyIds;
    fn read_only_ids_to_option_value_read_default_but_option_is_always_some_and_vec_always_contains_one_element(
        value: &<Self::PostgresqlType as PostgresqlType>::ReadOnlyIds
    ) -> std::option::Option<Value<<Self::PostgresqlType as PostgresqlType>::Read>>;
    fn previous_read_merged_with_option_update_into_read(
        read: <Self::PostgresqlType as PostgresqlType>::Read,
        option_update: std::option::Option<<Self::PostgresqlType as PostgresqlType>::Update>,
    ) -> <Self::PostgresqlType as PostgresqlType>::Read;
    fn read_only_ids_merged_with_create_into_read(
        read_only_ids: <Self::PostgresqlType as PostgresqlType>::ReadOnlyIds,
        create: <Self::PostgresqlType as PostgresqlType>::Create
    ) -> <Self::PostgresqlType as PostgresqlType>::Read;
    fn read_only_ids_merged_with_create_into_option_value_read(
        read_only_ids: <Self::PostgresqlType as PostgresqlType>::ReadOnlyIds,
        create: <Self::PostgresqlType as PostgresqlType>::Create
    ) -> std::option::Option<Value<<Self::PostgresqlType as PostgresqlType>::Read>>;
    fn read_only_ids_merged_with_create_into_table_type_declaration(
        read_only_ids: <Self::PostgresqlType as PostgresqlType>::ReadOnlyIds,
        create: <Self::PostgresqlType as PostgresqlType>::Create
    ) -> <Self::PostgresqlType as PostgresqlType>::TableTypeDeclaration;

    //todo add prefix postgresql_type or postgresql_json_type ?
    fn read_only_ids_merged_with_create_into_where_equal(
        read_only_ids: <Self::PostgresqlType as PostgresqlType>::ReadOnlyIds,
        create: <Self::PostgresqlType as PostgresqlType>::Create
    ) -> <Self::PostgresqlType as PostgresqlType>::Where;
    fn read_only_ids_merged_with_create_into_vec_where_equal_using_fields(
        read_only_ids: <Self::PostgresqlType as PostgresqlType>::ReadOnlyIds,
        create: <Self::PostgresqlType as PostgresqlType>::Create
    ) -> std::vec::Vec<<Self::PostgresqlType as PostgresqlType>::Where>;
    fn read_only_ids_merged_with_create_into_option_vec_where_equal_to_json_field(
        read_only_ids: <Self::PostgresqlType as PostgresqlType>::ReadOnlyIds,
        create: <Self::PostgresqlType as PostgresqlType>::Create
    ) -> std::option::Option<std::vec::Vec<<Self::PostgresqlType as PostgresqlType>::Where>>;

    fn create_into_postgresql_type_option_vec_where_dimension_one_equal(
        create: <Self::PostgresqlType as PostgresqlType>::Create
    ) -> std::option::Option<std::vec::Vec<<Self::PostgresqlType as PostgresqlType>::Where>>;
    fn postgresql_type_option_vec_where_greater_than_test() -> std::option::Option<std::vec::Vec<PostgresqlTypeGreaterThanTest<Self::PostgresqlType>>>;
    fn read_only_ids_merged_with_table_type_declaration_into_postgresql_type_option_where_greater_than(
        greater_than_variant: PostgresqlTypeGreaterThanVariant,
        read_only_ids: <Self::PostgresqlType as PostgresqlType>::ReadOnlyIds,
        table_type_declaration: <Self::PostgresqlType as PostgresqlType>::TableTypeDeclaration,
    ) -> std::option::Option<<Self::PostgresqlType as PostgresqlType>::Where>;
    fn read_only_ids_merged_with_create_into_postgresql_json_type_option_vec_where_dimension_one_equal(
        read_only_ids: <Self::PostgresqlType as PostgresqlType>::ReadOnlyIds,
        create: <Self::PostgresqlType as PostgresqlType>::Create
    ) -> std::option::Option<std::vec::Vec<<Self::PostgresqlType as PostgresqlType>::Where>>;
    fn read_only_ids_merged_with_create_into_postgresql_json_type_option_vec_where_dimension_two_equal(
        read_only_ids: <Self::PostgresqlType as PostgresqlType>::ReadOnlyIds,
        create: <Self::PostgresqlType as PostgresqlType>::Create
    ) -> std::option::Option<std::vec::Vec<<Self::PostgresqlType as PostgresqlType>::Where>>;
    fn read_only_ids_merged_with_create_into_postgresql_json_type_option_vec_where_dimension_three_equal(
        read_only_ids: <Self::PostgresqlType as PostgresqlType>::ReadOnlyIds,
        create: <Self::PostgresqlType as PostgresqlType>::Create
    ) -> std::option::Option<std::vec::Vec<<Self::PostgresqlType as PostgresqlType>::Where>>;
    fn read_only_ids_merged_with_create_into_postgresql_json_type_option_vec_where_dimension_four_equal(
        read_only_ids: <Self::PostgresqlType as PostgresqlType>::ReadOnlyIds,
        create: <Self::PostgresqlType as PostgresqlType>::Create
    ) -> std::option::Option<std::vec::Vec<<Self::PostgresqlType as PostgresqlType>::Where>>;

    fn create_into_postgresql_json_type_option_vec_where_length_equal(
        create: <Self::PostgresqlType as PostgresqlType>::Create
    ) -> std::option::Option<std::vec::Vec<<Self::PostgresqlType as PostgresqlType>::Where>>;
    fn postgresql_json_type_vec_where_length_greater_than_test() -> std::vec::Vec<PostgresqlTypeLengthGreaterThanTest<Self::PostgresqlType>>;
    fn create_into_postgresql_json_type_option_vec_where_length_greater_than(
        create: <Self::PostgresqlType as PostgresqlType>::Create
    ) -> std::option::Option<std::vec::Vec<<Self::PostgresqlType as PostgresqlType>::Where>>;
}

#[derive(Debug)]
pub struct PostgresqlTypeGreaterThanTest<T: PostgresqlType> {
    pub variant: PostgresqlTypeGreaterThanVariant,
    pub create: <T as PostgresqlType>::Create,
    pub greater_than: <T as PostgresqlType>::TableTypeDeclaration
}


#[derive(Debug)]
pub struct PostgresqlTypeLengthGreaterThanTest<T: PostgresqlType> {
    pub variant: PostgresqlJsonTypeLengthGreaterThanVariant,
    pub create: <T as PostgresqlType>::Create,
    pub length_greater_than: UnsignedPartOfStdPrimitiveI32,
}
#[derive(Debug)]
pub struct PostgresqlJsonTypeLengthGreaterThanTest<T: PostgresqlJsonType> {
    pub variant: PostgresqlJsonTypeLengthGreaterThanVariant,
    pub create: <T as PostgresqlJsonType>::Create,
    pub length_greater_than: UnsignedPartOfStdPrimitiveI32,
}

#[cfg(feature = "test-utils")]
pub trait PostgresqlJsonTypeTestCases {
    type PostgresqlJsonType: PostgresqlJsonType;
    type Select: SelectAlias + UtoipaToSchemaAndSchemarsJsonSchemaAlias + postgresql_crud_common_and_macros_common::DefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElementWithMaxPageSize;
    fn option_vec_create() -> std::option::Option<std::vec::Vec<<Self::PostgresqlJsonType as PostgresqlJsonType>::Create>>;
    fn read_only_ids_to_two_dimensional_vec_read_inner(read_only_ids: &<Self::PostgresqlJsonType as PostgresqlJsonType>::ReadOnlyIds) -> std::vec::Vec<std::vec::Vec<<Self::PostgresqlJsonType as PostgresqlJsonType>::ReadInner>>;
    fn read_inner_into_read_with_new_or_try_new_unwraped(value: <Self::PostgresqlJsonType as PostgresqlJsonType>::ReadInner) -> <Self::PostgresqlJsonType as PostgresqlJsonType>::Read;
    fn read_inner_into_update_with_new_or_try_new_unwraped(value: <Self::PostgresqlJsonType as PostgresqlJsonType>::ReadInner) -> <Self::PostgresqlJsonType as PostgresqlJsonType>::Update;
    fn read_only_ids_into_option_value_read_inner(value: <Self::PostgresqlJsonType as PostgresqlJsonType>::ReadOnlyIds) -> std::option::Option<Value<<Self::PostgresqlJsonType as PostgresqlJsonType>::ReadInner>>;
    fn update_to_read_only_ids(value: &<Self::PostgresqlJsonType as PostgresqlJsonType>::Update) -> <Self::PostgresqlJsonType as PostgresqlJsonType>::ReadOnlyIds;
    fn read_only_ids_to_option_value_read_default_but_option_is_always_some_and_vec_always_contains_one_element(
        value: &<Self::PostgresqlJsonType as PostgresqlJsonType>::ReadOnlyIds
    ) -> std::option::Option<Value<<Self::PostgresqlJsonType as PostgresqlJsonType>::Read>>;
    fn previous_read_merged_with_option_update_into_read(
        read: <Self::PostgresqlJsonType as PostgresqlJsonType>::Read,
        option_update: std::option::Option<<Self::PostgresqlJsonType as PostgresqlJsonType>::Update>,
    ) -> <Self::PostgresqlJsonType as PostgresqlJsonType>::Read;
    fn read_only_ids_merged_with_create_into_read(
        read_only_ids: <Self::PostgresqlJsonType as PostgresqlJsonType>::ReadOnlyIds,
        create: <Self::PostgresqlJsonType as PostgresqlJsonType>::Create
    ) -> <Self::PostgresqlJsonType as PostgresqlJsonType>::Read;
    fn read_only_ids_merged_with_create_into_option_value_read(
        read_only_ids: <Self::PostgresqlJsonType as PostgresqlJsonType>::ReadOnlyIds,
        create: <Self::PostgresqlJsonType as PostgresqlJsonType>::Create
    ) -> std::option::Option<Value<<Self::PostgresqlJsonType as PostgresqlJsonType>::Read>>;
    fn read_only_ids_merged_with_create_into_table_type_declaration(
        read_only_ids: <Self::PostgresqlJsonType as PostgresqlJsonType>::ReadOnlyIds,
        create: <Self::PostgresqlJsonType as PostgresqlJsonType>::Create
    ) -> <Self::PostgresqlJsonType as PostgresqlJsonType>::TableTypeDeclaration;

    fn read_only_ids_merged_with_create_into_where_equal(
        read_only_ids: <Self::PostgresqlJsonType as PostgresqlJsonType>::ReadOnlyIds,
        create: <Self::PostgresqlJsonType as PostgresqlJsonType>::Create
    ) -> <Self::PostgresqlJsonType as PostgresqlJsonType>::Where;
    fn read_only_ids_merged_with_create_into_vec_where_equal_using_fields(
        read_only_ids: <Self::PostgresqlJsonType as PostgresqlJsonType>::ReadOnlyIds,
        create: <Self::PostgresqlJsonType as PostgresqlJsonType>::Create
    ) -> std::vec::Vec<<Self::PostgresqlJsonType as PostgresqlJsonType>::Where>;
    fn read_only_ids_merged_with_create_into_vec_where_equal_to_json_field(
        read_only_ids: <Self::PostgresqlJsonType as PostgresqlJsonType>::ReadOnlyIds,
        create: <Self::PostgresqlJsonType as PostgresqlJsonType>::Create
    ) -> std::vec::Vec<<Self::PostgresqlJsonType as PostgresqlJsonType>::Where>;
    fn read_only_ids_merged_with_create_into_postgresql_json_type_option_vec_where_dimension_one_equal(
        read_only_ids: <Self::PostgresqlJsonType as PostgresqlJsonType>::ReadOnlyIds,
        create: <Self::PostgresqlJsonType as PostgresqlJsonType>::Create
    ) -> std::option::Option<std::vec::Vec<<Self::PostgresqlJsonType as PostgresqlJsonType>::Where>>;
    fn read_only_ids_merged_with_create_into_postgresql_json_type_option_vec_where_dimension_two_equal(
        read_only_ids: <Self::PostgresqlJsonType as PostgresqlJsonType>::ReadOnlyIds,
        create: <Self::PostgresqlJsonType as PostgresqlJsonType>::Create
    ) -> std::option::Option<std::vec::Vec<<Self::PostgresqlJsonType as PostgresqlJsonType>::Where>>;
    fn read_only_ids_merged_with_create_into_postgresql_json_type_option_vec_where_dimension_three_equal(
        read_only_ids: <Self::PostgresqlJsonType as PostgresqlJsonType>::ReadOnlyIds,
        create: <Self::PostgresqlJsonType as PostgresqlJsonType>::Create
    ) -> std::option::Option<std::vec::Vec<<Self::PostgresqlJsonType as PostgresqlJsonType>::Where>>;
    fn read_only_ids_merged_with_create_into_postgresql_json_type_option_vec_where_dimension_four_equal(
        read_only_ids: <Self::PostgresqlJsonType as PostgresqlJsonType>::ReadOnlyIds,
        create: <Self::PostgresqlJsonType as PostgresqlJsonType>::Create
    ) -> std::option::Option<std::vec::Vec<<Self::PostgresqlJsonType as PostgresqlJsonType>::Where>>;

    //todo
    // LengthGreaterThan
    // GreaterThan
    // ContainsElementGreaterThan
    // Between
    // In
    // RegularExpression
    // ContainsElementRegularExpression

    fn create_into_postgresql_json_type_option_vec_where_length_equal(
        create: <Self::PostgresqlJsonType as PostgresqlJsonType>::Create
    ) -> std::option::Option<std::vec::Vec<<Self::PostgresqlJsonType as PostgresqlJsonType>::Where>>;
    fn postgresql_json_type_vec_where_length_greater_than_test() -> std::vec::Vec<PostgresqlJsonTypeLengthGreaterThanTest<Self::PostgresqlJsonType>>;
    fn create_into_postgresql_json_type_option_vec_where_length_greater_than(
        create: <Self::PostgresqlJsonType as PostgresqlJsonType>::Create
    ) -> std::option::Option<std::vec::Vec<<Self::PostgresqlJsonType as PostgresqlJsonType>::Where>>;
}

pub trait PostgresqlTypeWhereFilter<'a> {
    fn query_part(&self, increment: &mut std::primitive::u64, column: &dyn std::fmt::Display, is_need_to_add_logical_operator: std::primitive::bool) -> Result<std::string::String, QueryPartErrorNamed>;
    fn query_bind(self, query: sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>) -> Result<
        sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>,
        std::string::String
    >;
}
//todo custom deserialization - must not contain more than one element
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, utoipa::ToSchema, schemars::JsonSchema)]
pub struct NullableJsonObjectPostgresqlTypeWhereFilter<T: std::fmt::Debug + PartialEq + Clone + for<'a> PostgresqlTypeWhereFilter<'a> + postgresql_crud_common_and_macros_common::AllEnumVariantsArrayDefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement>(pub std::option::Option<NotEmptyUniqueEnumVec<T>>);
impl<'a, T> PostgresqlTypeWhereFilter<'a> for NullableJsonObjectPostgresqlTypeWhereFilter<T>
where
    T: std::fmt::Debug + PartialEq + Clone + for<'b> PostgresqlTypeWhereFilter<'b> + postgresql_crud_common_and_macros_common::AllEnumVariantsArrayDefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement,
{
    fn query_part(&self, increment: &mut std::primitive::u64, column: &dyn std::fmt::Display, is_need_to_add_logical_operator: std::primitive::bool) -> Result<std::string::String, QueryPartErrorNamed> {
        match &self.0 {
            Some(value) => {
                value.query_part(
                    increment,
                    column,
                    is_need_to_add_logical_operator
                )
            },
            None => Ok(format!("{column} = 'null'")), //todo fix
        }
    }
    fn query_bind(self, query: sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>) -> Result<
        sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>,
        std::string::String
    > {
        match self.0 {
            Some(value) => value.query_bind(query),
            None => Ok(query), //todo maybe wrong
        }
    }
}
impl<T> error_occurence_lib::ToStdStringString for NullableJsonObjectPostgresqlTypeWhereFilter<T>
where
    T: std::fmt::Debug + PartialEq + Clone + for<'a> PostgresqlTypeWhereFilter<'a> + postgresql_crud_common_and_macros_common::AllEnumVariantsArrayDefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement,
{
    fn to_std_string_string(&self) -> std::string::String {
        format!("{self:#?}")
    }
}
impl<T> postgresql_crud_common_and_macros_common::AllEnumVariantsArrayDefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement for NullableJsonObjectPostgresqlTypeWhereFilter<T>
where
    T: std::fmt::Debug + PartialEq + Clone + for<'a> PostgresqlTypeWhereFilter<'a> + postgresql_crud_common_and_macros_common::AllEnumVariantsArrayDefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement,
{
    fn all_enum_variants_array_default_but_std_option_option_is_always_some_and_std_vec_vec_always_contains_one_element() -> std::vec::Vec<Self> {
        vec![
            Self(Some(postgresql_crud_common_and_macros_common::DefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement::default_but_option_is_always_some_and_vec_always_contains_one_element())), // , Self(None)
        ]
    }
}

pub fn wrap_into_jsonb_build_object(field: &std::primitive::str, value: &std::primitive::str) -> std::string::String {
    format!("jsonb_build_object('{field}',{value})||")
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, thiserror::Error, error_occurence_lib::ErrorOccurence)]
pub enum QueryPartErrorNamed {
    CheckedAdd { code_occurence: error_occurence_lib::code_occurence::CodeOccurence },
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, utoipa::ToSchema, schemars::JsonSchema)]
pub struct PostgresqlTypeWhere<T> {
    logical_operator: postgresql_crud_common_and_macros_common::LogicalOperator,
    value: std::vec::Vec<T>,
}
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, thiserror::Error, error_occurence_lib::ErrorOccurence)]
pub enum PostgresqlTypeWhereTryNewErrorNamed<T> {
    IsEmpty {
        code_occurence: error_occurence_lib::code_occurence::CodeOccurence,
    },
    NotUnique {
        #[eo_to_std_string_string_serialize_deserialize]
        value: T,
        code_occurence: error_occurence_lib::code_occurence::CodeOccurence,
    },
}
impl<T: std::cmp::PartialEq + Clone> PostgresqlTypeWhere<T> {
    pub fn try_new(logical_operator: postgresql_crud_common_and_macros_common::LogicalOperator, value: std::vec::Vec<T>) -> Result<Self, PostgresqlTypeWhereTryNewErrorNamed<T>> {
        if value.is_empty() {
            return Err(PostgresqlTypeWhereTryNewErrorNamed::IsEmpty { code_occurence: error_occurence_lib::code_occurence!() });
        }
        {
            let mut acc = vec![];
            for element in &value {
                if acc.contains(&element) {
                    return Err(PostgresqlTypeWhereTryNewErrorNamed::NotUnique {
                        value: element.clone(),
                        code_occurence: error_occurence_lib::code_occurence!(),
                    });
                }
                acc.push(element);
            }
        }
        Ok(Self { logical_operator, value })
    }
    pub fn get_logical_operator(&self) -> &postgresql_crud_common_and_macros_common::LogicalOperator {
        &self.logical_operator
    }
}
const _: () = {
    #[expect(clippy::useless_attribute)]
    extern crate serde as _serde;
    #[automatically_derived]
    impl<'de, T: std::fmt::Debug + std::cmp::PartialEq + std::clone::Clone + _serde::Deserialize<'de>> _serde::Deserialize<'de> for PostgresqlTypeWhere<T> {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>,
        {
            #[expect(non_camel_case_types)]
            #[doc(hidden)]
            enum __Field {
                __field0,
                __field1,
                __ignore,
            }
            #[doc(hidden)]
            struct __FieldVisitor;
            impl _serde::de::Visitor<'_> for __FieldVisitor {
                type Value = __Field;
                fn expecting(&self, __f: &mut _serde::__private::Formatter<'_>) -> _serde::__private::fmt::Result {
                    _serde::__private::Formatter::write_str(__f, "field identifier")
                }
                fn visit_u64<__E>(self, __value: u64) -> _serde::__private::Result<Self::Value, __E>
                where
                    __E: _serde::de::Error,
                {
                    match __value {
                        0u64 => _serde::__private::Ok(__Field::__field0),
                        1u64 => _serde::__private::Ok(__Field::__field1),
                        _ => _serde::__private::Ok(__Field::__ignore),
                    }
                }
                fn visit_str<__E>(self, __value: &str) -> _serde::__private::Result<Self::Value, __E>
                where
                    __E: _serde::de::Error,
                {
                    match __value {
                        "logical_operator" => _serde::__private::Ok(__Field::__field0),
                        "value" => _serde::__private::Ok(__Field::__field1),
                        _ => _serde::__private::Ok(__Field::__ignore),
                    }
                }
                fn visit_bytes<__E>(self, __value: &[u8]) -> _serde::__private::Result<Self::Value, __E>
                where
                    __E: _serde::de::Error,
                {
                    match __value {
                        b"logical_operator" => _serde::__private::Ok(__Field::__field0),
                        b"value" => _serde::__private::Ok(__Field::__field1),
                        _ => _serde::__private::Ok(__Field::__ignore),
                    }
                }
            }
            impl<'de> _serde::Deserialize<'de> for __Field {
                #[inline]
                fn deserialize<__D>(__deserializer: __D) -> _serde::__private::Result<Self, __D::Error>
                where
                    __D: _serde::Deserializer<'de>,
                {
                    _serde::Deserializer::deserialize_identifier(__deserializer, __FieldVisitor)
                }
            }
            #[doc(hidden)]
            struct __Visitor<'de, PostgresqlTypeWhere> {
                marker: _serde::__private::PhantomData<PostgresqlTypeWhere>,
                lifetime: _serde::__private::PhantomData<&'de ()>,
            }
            impl<'de, T: std::fmt::Debug + std::cmp::PartialEq + std::clone::Clone + _serde::Deserialize<'de>> _serde::de::Visitor<'de> for __Visitor<'de, T> {
                type Value = PostgresqlTypeWhere<T>;
                fn expecting(&self, __f: &mut _serde::__private::Formatter<'_>) -> _serde::__private::fmt::Result {
                    _serde::__private::Formatter::write_str(__f, "struct PostgresqlTypeWhere")
                }
                #[inline]
                fn visit_seq<__A>(self, mut __seq: __A) -> _serde::__private::Result<Self::Value, __A::Error>
                where
                    __A: _serde::de::SeqAccess<'de>,
                {
                    let __field0 = match _serde::de::SeqAccess::next_element::<postgresql_crud_common_and_macros_common::LogicalOperator>(&mut __seq)? {
                        _serde::__private::Some(__value) => __value,
                        _serde::__private::None => {
                            return _serde::__private::Err(_serde::de::Error::invalid_length(0usize, &"struct PostgresqlTypeWhere with 2 elements"));
                        }
                    };
                    let __field1 = match _serde::de::SeqAccess::next_element::<std::vec::Vec<T>>(&mut __seq)? {
                        _serde::__private::Some(__value) => __value,
                        _serde::__private::None => {
                            return _serde::__private::Err(_serde::de::Error::invalid_length(1usize, &"struct PostgresqlTypeWhere with 2 elements"));
                        }
                    };
                    match PostgresqlTypeWhere::try_new(__field0, __field1) {
                        Ok(value) => serde::__private::Ok(value),
                        Err(error) => Err(serde::de::Error::custom(format!("{error:?}"))),
                    }
                }
                #[inline]
                fn visit_map<__A>(self, mut __map: __A) -> _serde::__private::Result<Self::Value, __A::Error>
                where
                    __A: _serde::de::MapAccess<'de>,
                {
                    let mut __field0: _serde::__private::Option<postgresql_crud_common_and_macros_common::LogicalOperator> = _serde::__private::None;
                    let mut __field1: _serde::__private::Option<std::vec::Vec<T>> = _serde::__private::None;
                    while let _serde::__private::Some(__key) = _serde::de::MapAccess::next_key::<__Field>(&mut __map)? {
                        match __key {
                            __Field::__field0 => {
                                if _serde::__private::Option::is_some(&__field0) {
                                    return _serde::__private::Err(<__A::Error as _serde::de::Error>::duplicate_field("logical_operator"));
                                }
                                __field0 = _serde::__private::Some(_serde::de::MapAccess::next_value::<postgresql_crud_common_and_macros_common::LogicalOperator>(&mut __map)?);
                            }
                            __Field::__field1 => {
                                if _serde::__private::Option::is_some(&__field1) {
                                    return _serde::__private::Err(<__A::Error as _serde::de::Error>::duplicate_field("value"));
                                }
                                __field1 = _serde::__private::Some(_serde::de::MapAccess::next_value::<std::vec::Vec<T>>(&mut __map)?);
                            }
                            _ => {
                                let _ = _serde::de::MapAccess::next_value::<_serde::de::IgnoredAny>(&mut __map)?;
                            }
                        }
                    }
                    let __field0 = match __field0 {
                        _serde::__private::Some(__field0) => __field0,
                        _serde::__private::None => _serde::__private::de::missing_field("logical_operator")?,
                    };
                    let __field1 = match __field1 {
                        _serde::__private::Some(__field1) => __field1,
                        _serde::__private::None => _serde::__private::de::missing_field("value")?,
                    };
                    match PostgresqlTypeWhere::try_new(__field0, __field1) {
                        Ok(value) => serde::__private::Ok(value),
                        Err(error) => Err(serde::de::Error::custom(format!("{error:?}"))),
                    }
                }
            }
            #[doc(hidden)]
            const FIELDS: &[&str] = &["logical_operator", "value"];
            _serde::Deserializer::deserialize_struct(
                __deserializer,
                "PostgresqlTypeWhere",
                FIELDS,
                __Visitor {
                    marker: _serde::__private::PhantomData::<T>,
                    lifetime: _serde::__private::PhantomData,
                },
            )
        }
    }
};
impl<'a, T: PostgresqlTypeWhereFilter<'a>> PostgresqlTypeWhereFilter<'a> for PostgresqlTypeWhere<T> {
    fn query_part(&self, increment: &mut std::primitive::u64, column: &dyn std::fmt::Display, is_need_to_add_logical_operator: std::primitive::bool) -> Result<std::string::String, QueryPartErrorNamed> {
        let mut acc = std::string::String::default();
        let mut is_need_to_add_logical_operator_inner_handle = false;
        for element in &self.value {
            match PostgresqlTypeWhereFilter::query_part(element, increment, column, is_need_to_add_logical_operator_inner_handle) {
                Ok(value) => {
                    acc.push_str(&format!("{value} "));
                    is_need_to_add_logical_operator_inner_handle = true;
                }
                Err(error) => {
                    return Err(error);
                }
            }
        }
        let _: std::option::Option<std::primitive::char> = acc.pop();
        Ok(format!("{}({acc})", &self.logical_operator.to_query_part(is_need_to_add_logical_operator)))
    }
    fn query_bind(self, mut query: sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>) -> Result<
        sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>,
        std::string::String
    > {
        for element in self.value {
            match PostgresqlTypeWhereFilter::query_bind(element, query) {
                Ok(value) => {
                    query = value;
                },
                Err(error) => {
                    return Err(error);
                }
            }
        }
        Ok(query)
    }
}
impl<T: postgresql_crud_common_and_macros_common::AllEnumVariantsArrayDefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement> postgresql_crud_common_and_macros_common::DefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement for PostgresqlTypeWhere<T> {
    fn default_but_option_is_always_some_and_vec_always_contains_one_element() -> Self {
        Self {
            logical_operator: postgresql_crud_common_and_macros_common::DefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement::default_but_option_is_always_some_and_vec_always_contains_one_element(),
            value: postgresql_crud_common_and_macros_common::AllEnumVariantsArrayDefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement::all_enum_variants_array_default_but_std_option_option_is_always_some_and_std_vec_vec_always_contains_one_element(),
        }
    }
}

#[derive(Debug, Clone, Copy, serde::Serialize, serde::Deserialize, PartialEq, Eq, from_str::FromStr)]
pub enum Order {
    #[serde(rename(serialize = "asc", deserialize = "asc"))]
    Asc,
    #[serde(rename(serialize = "desc", deserialize = "desc"))]
    Desc,
}
impl std::fmt::Display for Order {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Asc => write!(formatter, "{}", naming::AscUpperCamelCase),
            Self::Desc => write!(formatter, "{}", naming::DescUpperCamelCase),
        }
    }
}
impl Default for Order {
    fn default() -> Self {
        Self::Asc
    }
}
impl postgresql_crud_common_and_macros_common::DefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement for Order {
    fn default_but_option_is_always_some_and_vec_always_contains_one_element() -> Self {
        Self::default()
    }
}
impl Order {
    pub fn to_upper_camel_case_stringified(&self) -> std::string::String {
        naming::DisplayToUpperCamelCaseStringified::case(&self)
    }
    pub fn to_snake_case_stringified(&self) -> std::string::String {
        naming::DisplayToSnakeCaseStringified::case(&self)
    }
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct OrderBy<ColumnGeneric> {
    pub column: ColumnGeneric,
    pub order: Option<Order>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, utoipa::ToSchema, schemars::JsonSchema)]
pub struct PaginationBase {
    limit: std::primitive::i64,
    offset: std::primitive::i64,
}
impl PaginationBase {
    pub fn new_unchecked(limit: std::primitive::i64, offset: std::primitive::i64) -> Self {
        Self { limit, offset }
    }
    pub const fn start(&self) -> std::primitive::i64 {
        self.offset
    }
    pub const fn end(&self) -> std::primitive::i64 {
        self.offset.checked_add(self.limit).unwrap()
    }
}
impl<'a> PostgresqlTypeWhereFilter<'a> for PaginationBase {
    fn query_part(&self, increment: &mut std::primitive::u64, _: &dyn std::fmt::Display, _: std::primitive::bool) -> Result<std::string::String, QueryPartErrorNamed> {
        let limit_increment = match increment_checked_add_one_returning_increment(increment) {
            Ok(value) => value,
            Err(error) => {
                return Err(error);
            }
        };
        let offset_increment = match increment_checked_add_one_returning_increment(increment) {
            Ok(value) => value,
            Err(error) => {
                return Err(error);
            }
        };
        Ok(format!("limit ${limit_increment} offset ${offset_increment}"))
    }
    fn query_bind(self, mut query: sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>) -> Result<
        sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>,
        std::string::String
    > {
        if let Err(error) = query.try_bind(self.limit) {
            return Err(error.to_string());
        };
        if let Err(error) = query.try_bind(self.offset) {
            return Err(error.to_string());
        };
        Ok(query)
    }
}
impl std::default::Default for PaginationBase {
    fn default() -> Self {
        Self::new_unchecked(DEFAULT_PAGINATION_LIMIT, 0)
    }
}

pub const DEFAULT_PAGINATION_LIMIT: std::primitive::i64 = 5;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, serde::Serialize, utoipa::ToSchema, schemars::JsonSchema)]
pub struct PaginationStartsWithZero(PaginationBase);
#[derive(Debug, serde::Serialize, serde::Deserialize, thiserror::Error, error_occurence_lib::ErrorOccurence)]
pub enum PaginationStartsWithZeroTryNewErrorNamed {
    OffsetPlusLimitIsIntOverflow {
        #[eo_to_std_string_string_serialize_deserialize]
        limit: std::primitive::i64,
        #[eo_to_std_string_string_serialize_deserialize]
        offset: std::primitive::i64,
        code_occurence: error_occurence_lib::code_occurence::CodeOccurence,
    },
    LimitIsLessThanOrEqualToZero {
        #[eo_to_std_string_string_serialize_deserialize]
        limit: std::primitive::i64,
        code_occurence: error_occurence_lib::code_occurence::CodeOccurence,
    },
    OffsetIsLessThanZero {
        #[eo_to_std_string_string_serialize_deserialize]
        offset: std::primitive::i64,
        code_occurence: error_occurence_lib::code_occurence::CodeOccurence,
    },
}
impl PaginationStartsWithZero {
    pub fn try_new(limit: std::primitive::i64, offset: std::primitive::i64) -> Result<Self, PaginationStartsWithZeroTryNewErrorNamed> {
        if limit <= 0 || offset < 0 {
            if limit <= 0 {
                Err(PaginationStartsWithZeroTryNewErrorNamed::LimitIsLessThanOrEqualToZero { limit, code_occurence: error_occurence_lib::code_occurence!() })
            } else {
                Err(PaginationStartsWithZeroTryNewErrorNamed::OffsetIsLessThanZero { offset, code_occurence: error_occurence_lib::code_occurence!() })
            }
        } else if offset.checked_add(limit).is_some() {
            Ok(Self(PaginationBase::new_unchecked(limit, offset)))
        } else {
            Err(PaginationStartsWithZeroTryNewErrorNamed::OffsetPlusLimitIsIntOverflow { limit, offset, code_occurence: error_occurence_lib::code_occurence!() })
        }
    }
    pub const fn start(&self) -> std::primitive::i64 {
        self.0.start()
    }
    pub const fn end(&self) -> std::primitive::i64 {
        self.0.end()
    }
}
impl<'de> serde::Deserialize<'de> for PaginationStartsWithZero {
    fn deserialize<__D>(__deserializer: __D) -> serde::__private::Result<Self, __D::Error>
    where
        __D: serde::Deserializer<'de>,
    {
        #[expect(non_camel_case_types)]
        #[doc(hidden)]
        enum __Field {
            __field0,
            __field1,
            __ignore,
        }
        #[doc(hidden)]
        struct __FieldVisitor;
        impl serde::de::Visitor<'_> for __FieldVisitor {
            type Value = __Field;
            fn expecting(&self, __f: &mut serde::__private::Formatter<'_>) -> serde::__private::fmt::Result {
                serde::__private::Formatter::write_str(__f, "field identifier")
            }
            fn visit_u64<__E>(self, __value: u64) -> serde::__private::Result<Self::Value, __E>
            where
                __E: serde::de::Error,
            {
                match __value {
                    0u64 => serde::__private::Ok(__Field::__field0),
                    1u64 => serde::__private::Ok(__Field::__field1),
                    _ => serde::__private::Ok(__Field::__ignore),
                }
            }
            fn visit_str<__E>(self, __value: &str) -> serde::__private::Result<Self::Value, __E>
            where
                __E: serde::de::Error,
            {
                match __value {
                    "limit" => serde::__private::Ok(__Field::__field0),
                    "offset" => serde::__private::Ok(__Field::__field1),
                    _ => serde::__private::Ok(__Field::__ignore),
                }
            }
            fn visit_bytes<__E>(self, __value: &[u8]) -> serde::__private::Result<Self::Value, __E>
            where
                __E: serde::de::Error,
            {
                match __value {
                    b"limit" => serde::__private::Ok(__Field::__field0),
                    b"offset" => serde::__private::Ok(__Field::__field1),
                    _ => serde::__private::Ok(__Field::__ignore),
                }
            }
        }
        impl<'de> serde::Deserialize<'de> for __Field {
            #[inline]
            fn deserialize<__D>(__deserializer: __D) -> serde::__private::Result<Self, __D::Error>
            where
                __D: serde::Deserializer<'de>,
            {
                serde::Deserializer::deserialize_identifier(__deserializer, __FieldVisitor)
            }
        }
        #[doc(hidden)]
        struct __Visitor<'de> {
            marker: serde::__private::PhantomData<PaginationStartsWithZero>,
            lifetime: serde::__private::PhantomData<&'de ()>,
        }
        impl<'de> serde::de::Visitor<'de> for __Visitor<'de> {
            type Value = PaginationStartsWithZero;
            fn expecting(&self, __f: &mut serde::__private::Formatter<'_>) -> serde::__private::fmt::Result {
                serde::__private::Formatter::write_str(__f, "struct PaginationStartsWithZero")
            }
            #[inline]
            fn visit_seq<__A>(self, mut __seq: __A) -> serde::__private::Result<Self::Value, __A::Error>
            where
                __A: serde::de::SeqAccess<'de>,
            {
                let __field0 = match serde::de::SeqAccess::next_element::<std::primitive::i64>(&mut __seq)? {
                    serde::__private::Some(__value) => __value,
                    serde::__private::None => {
                        return serde::__private::Err(serde::de::Error::invalid_length(0usize, &"struct PaginationStartsWithZero with 2 elements"));
                    }
                };
                let __field1 = match serde::de::SeqAccess::next_element::<std::primitive::i64>(&mut __seq)? {
                    serde::__private::Some(__value) => __value,
                    serde::__private::None => {
                        return serde::__private::Err(serde::de::Error::invalid_length(1usize, &"struct PaginationStartsWithZero with 2 elements"));
                    }
                };
                match PaginationStartsWithZero::try_new(__field0, __field1) {
                    Ok(value) => serde::__private::Ok(value),
                    Err(error) => Err(serde::de::Error::custom(format!("{error:?}"))), //todo use serde_json::to_string(&error).unwrap_or_else(|_|"failed to serialize error".into())
                }
            }
            #[inline]
            fn visit_map<__A>(self, mut __map: __A) -> serde::__private::Result<Self::Value, __A::Error>
            where
                __A: serde::de::MapAccess<'de>,
            {
                let mut __field0: serde::__private::Option<std::primitive::i64> = serde::__private::None;
                let mut __field1: serde::__private::Option<std::primitive::i64> = serde::__private::None;
                while let serde::__private::Some(__key) = serde::de::MapAccess::next_key::<__Field>(&mut __map)? {
                    match __key {
                        __Field::__field0 => {
                            if serde::__private::Option::is_some(&__field0) {
                                return serde::__private::Err(<__A::Error as serde::de::Error>::duplicate_field("limit"));
                            }
                            __field0 = serde::__private::Some(serde::de::MapAccess::next_value::<std::primitive::i64>(&mut __map)?);
                        }
                        __Field::__field1 => {
                            if serde::__private::Option::is_some(&__field1) {
                                return serde::__private::Err(<__A::Error as serde::de::Error>::duplicate_field("offset"));
                            }
                            __field1 = serde::__private::Some(serde::de::MapAccess::next_value::<std::primitive::i64>(&mut __map)?);
                        }
                        _ => {
                            let _ = serde::de::MapAccess::next_value::<serde::de::IgnoredAny>(&mut __map)?;
                        }
                    }
                }
                let __field0 = match __field0 {
                    serde::__private::Some(__field0) => __field0,
                    serde::__private::None => serde::__private::de::missing_field("limit")?,
                };
                let __field1 = match __field1 {
                    serde::__private::Some(__field1) => __field1,
                    serde::__private::None => serde::__private::de::missing_field("offset")?,
                };
                match PaginationStartsWithZero::try_new(__field0, __field1) {
                    Ok(value) => serde::__private::Ok(value),
                    Err(error) => Err(serde::de::Error::custom(format!("{error:?}"))),
                }
            }
        }
        #[doc(hidden)]
        const FIELDS: &[&str] = &["limit", "offset"];
        serde::Deserializer::deserialize_struct(
            __deserializer,
            "PaginationStartsWithZero",
            FIELDS,
            __Visitor {
                marker: serde::__private::PhantomData::<Self>,
                lifetime: serde::__private::PhantomData,
            },
        )
    }
}
impl<'a> PostgresqlTypeWhereFilter<'a> for PaginationStartsWithZero {
    fn query_part(&self, increment: &mut std::primitive::u64, column: &dyn std::fmt::Display, is_need_to_add_logical_operator: std::primitive::bool) -> Result<std::string::String, QueryPartErrorNamed> {
        self.0.query_part(increment, column, is_need_to_add_logical_operator)
    }
    fn query_bind(self, query: sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>) -> Result<
        sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>,
        std::string::String
    > {
        self.0.query_bind(query)
    }
}
impl postgresql_crud_common_and_macros_common::DefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement for PaginationStartsWithZero {
    #[inline]
    fn default_but_option_is_always_some_and_vec_always_contains_one_element() -> Self {
        Self(PaginationBase::new_unchecked(DEFAULT_PAGINATION_LIMIT, 0))
    }
}
impl postgresql_crud_common_and_macros_common::DefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElementWithMaxPageSize for PaginationStartsWithZero {
    #[inline]
    fn default_but_option_is_always_some_and_vec_always_contains_one_element_with_max_page_size() -> Self {
        Self(PaginationBase::new_unchecked(
            std::primitive::i32::MAX.into(),
            0
        ))
    }
}

//this needed coz serde std::option::Option<std::option::Option<T>> #[serde(skip_serializing_if = "Option::is_none")] - if both options: inner and parent is null then it skip - its not correct
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, utoipa::ToSchema, schemars::JsonSchema)]
pub struct Value<T> {
    pub value: T,
}

//todo ExactSizeIterator now is not a solution. error[E0658]: use of unstable library feature `exact_size_is_empty`. maybe rewrite it later
pub trait IsStringEmpty {
    fn is_string_empty(&self) -> std::primitive::bool;
}

#[derive(Debug, serde::Serialize, serde::Deserialize, thiserror::Error, error_occurence_lib::ErrorOccurence)]
pub enum NotEmptyUniqueVecTryNewErrorNamed<T> {
    IsEmpty {
        code_occurence: error_occurence_lib::code_occurence::CodeOccurence,
    },
    NotUnique {
        #[eo_to_std_string_string_serialize_deserialize]
        value: T,
        code_occurence: error_occurence_lib::code_occurence::CodeOccurence,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, utoipa::ToSchema, schemars::JsonSchema)]
pub struct NotEmptyUniqueEnumVec<T>(std::vec::Vec<T>);
impl<T: std::cmp::PartialEq + Clone> NotEmptyUniqueEnumVec<T> {
    pub fn try_new(value: std::vec::Vec<T>) -> Result<Self, NotEmptyUniqueVecTryNewErrorNamed<T>> {
        if value.is_empty() {
            return Err(NotEmptyUniqueVecTryNewErrorNamed::IsEmpty { code_occurence: error_occurence_lib::code_occurence!() });
        }
        {
            let mut acc = vec![];
            for element in &value {
                if acc.contains(&element) {
                    return Err(NotEmptyUniqueVecTryNewErrorNamed::NotUnique {
                        value: element.clone(),
                        code_occurence: error_occurence_lib::code_occurence!(),
                    });
                }
                acc.push(element);
            }
        }
        Ok(Self(value))
    }
    pub const fn to_vec(&self) -> &std::vec::Vec<T> {
        &self.0
    }
    pub fn into_vec(self) -> std::vec::Vec<T> {
        self.0
    }
}
const _: () = {
    #[expect(clippy::useless_attribute)]
    extern crate serde as _serde;
    #[automatically_derived]
    impl<'de, T: std::fmt::Debug + std::cmp::PartialEq + std::clone::Clone + _serde::Deserialize<'de>> _serde::Deserialize<'de> for NotEmptyUniqueEnumVec<T> {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>,
        {
            #[doc(hidden)]
            struct __Visitor<'de, T>
            where
                T: _serde::Deserialize<'de>,
            {
                marker: _serde::__private::PhantomData<NotEmptyUniqueEnumVec<T>>,
                lifetime: _serde::__private::PhantomData<&'de ()>,
            }
            #[automatically_derived]
            impl<'de, T: std::fmt::Debug + std::cmp::PartialEq + std::clone::Clone + _serde::Deserialize<'de>> _serde::de::Visitor<'de> for __Visitor<'de, T> {
                type Value = NotEmptyUniqueEnumVec<T>;
                fn expecting(&self, __f: &mut _serde::__private::Formatter<'_>) -> _serde::__private::fmt::Result {
                    _serde::__private::Formatter::write_str(__f, "tuple struct NotEmptyUniqueEnumVec")
                }
                #[inline]
                fn visit_newtype_struct<__E>(self, __e: __E) -> _serde::__private::Result<Self::Value, __E::Error>
                where
                    __E: _serde::Deserializer<'de>,
                {
                    let __field0: std::vec::Vec<T> = <std::vec::Vec<T> as _serde::Deserialize>::deserialize(__e)?;
                    _serde::__private::Ok(NotEmptyUniqueEnumVec(__field0))
                }
                #[inline]
                fn visit_seq<__A>(self, mut __seq: __A) -> _serde::__private::Result<Self::Value, __A::Error>
                where
                    __A: _serde::de::SeqAccess<'de>,
                {
                    let __field0 = match _serde::de::SeqAccess::next_element::<std::vec::Vec<T>>(&mut __seq)? {
                        _serde::__private::Some(__value) => __value,
                        _serde::__private::None => {
                            return _serde::__private::Err(_serde::de::Error::invalid_length(0usize, &"tuple struct NotEmptyUniqueEnumVec with 1 element"));
                        }
                    };
                    match NotEmptyUniqueEnumVec::try_new(__field0) {
                        Ok(value) => _serde::__private::Ok(value),
                        Err(error) => Err(_serde::de::Error::custom(format!("{error:?}"))),
                    }
                }
            }
            _serde::Deserializer::deserialize_newtype_struct(
                __deserializer,
                "NotEmptyUniqueEnumVec",
                __Visitor {
                    marker: _serde::__private::PhantomData::<Self>,
                    lifetime: _serde::__private::PhantomData,
                },
            )
        }
    }
};
impl<T: postgresql_crud_common_and_macros_common::AllEnumVariantsArrayDefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement> postgresql_crud_common_and_macros_common::DefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement for NotEmptyUniqueEnumVec<T> {
    fn default_but_option_is_always_some_and_vec_always_contains_one_element() -> Self {
        Self(postgresql_crud_common_and_macros_common::AllEnumVariantsArrayDefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement::all_enum_variants_array_default_but_std_option_option_is_always_some_and_std_vec_vec_always_contains_one_element())
    }
}
impl<T: postgresql_crud_common_and_macros_common::AllEnumVariantsArrayDefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElementWithMaxPageSize> postgresql_crud_common_and_macros_common::DefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElementWithMaxPageSize for NotEmptyUniqueEnumVec<T> {
    fn default_but_option_is_always_some_and_vec_always_contains_one_element_with_max_page_size() -> Self {
        Self(postgresql_crud_common_and_macros_common::AllEnumVariantsArrayDefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElementWithMaxPageSize::all_enum_variants_array_default_but_std_option_option_is_always_some_and_std_vec_vec_always_contains_one_element_with_max_page_size())
    }
}
impl<T> std::default::Default for NotEmptyUniqueEnumVec<T> {
    fn default() -> Self {
        Self(std::vec::Vec::default())
    }
}
impl<T> std::convert::From<NotEmptyUniqueEnumVec<T>> for Vec<T> {
    fn from(value: NotEmptyUniqueEnumVec<T>) -> Self {
        value.0
    }
}
impl<T1> NotEmptyUniqueEnumVec<T1> {
    pub fn from_t1_impl_from_t2<T2: std::convert::From<T1>>(value: NotEmptyUniqueEnumVec<T1>) -> NotEmptyUniqueEnumVec<T2> {
        NotEmptyUniqueEnumVec(
            value.0
            .into_iter()
            .map(T2::from)
            .collect::<std::vec::Vec<T2>>()
        )
    }
}

impl<'a, T> PostgresqlTypeWhereFilter<'a> for NotEmptyUniqueEnumVec<T>
where
    T: std::fmt::Debug + PartialEq + Clone + for<'b> PostgresqlTypeWhereFilter<'b> + postgresql_crud_common_and_macros_common::AllEnumVariantsArrayDefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement,
{
    fn query_part(&self, increment: &mut std::primitive::u64, column: &dyn std::fmt::Display, is_need_to_add_logical_operator: std::primitive::bool) -> Result<std::string::String, QueryPartErrorNamed> {
        let mut acc = std::string::String::default();
        for (index, element) in self.0.iter().enumerate() {
            match element.query_part(
                increment,
                column,
                if index == 0 {
                    is_need_to_add_logical_operator
                }
                else {
                    true
                }
            ) {
                Ok(value) => {
                    acc.push_str(&value);
                }
                Err(error) => {
                    return Err(error);
                }
            }
        }
        Ok(acc)
    }
    fn query_bind(self, mut query: sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>) -> Result<
        sqlx::query::Query<'a, sqlx::Postgres, sqlx::postgres::PgArguments>,
        std::string::String
    > {
        for element in self.0 {
            match element.query_bind(query) {
                Ok(value) => {
                    query = value;
                },
                Err(error) => {
                    return Err(error);
                }
            }
        }
        Ok(query)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct JsonFieldRights {
    can_create: std::primitive::bool,
    can_read: std::primitive::bool,
    can_update: std::primitive::bool,
}

pub fn std_primitive_i8_test_cases_vec() -> [std::primitive::i8;3] {
    [
        std::primitive::i8::MIN,
        0,
        std::primitive::i8::MAX
    ]
}
pub fn std_primitive_i16_test_cases_vec() -> [std::primitive::i16;3] {
    [
        std::primitive::i16::MIN,
        0,
        std::primitive::i16::MAX
    ]
}
pub fn std_primitive_i32_test_cases_vec() -> [std::primitive::i32;3] {
    [
        std::primitive::i32::MIN,
        0,
        std::primitive::i32::MAX
    ]
}
pub fn std_primitive_i64_test_cases_vec() -> [std::primitive::i64;3] {
    [
        std::primitive::i64::MIN,
        0,
        std::primitive::i64::MAX
    ]
}
pub fn std_primitive_u8_test_cases_vec() -> [std::primitive::u8;3] {
    [
        std::primitive::u8::MIN,
        0,
        std::primitive::u8::MAX
    ]
}
pub fn std_primitive_u16_test_cases_vec() -> [std::primitive::u16;3] {
    [
        std::primitive::u16::MIN,
        0,
        std::primitive::u16::MAX
    ]
}
pub fn std_primitive_u32_test_cases_vec() -> [std::primitive::u32;3] {
    [
        std::primitive::u32::MIN,
        0,
        std::primitive::u32::MAX
    ]
}
pub fn std_primitive_u64_test_cases_vec() -> [std::primitive::u64;3] {
    [
        std::primitive::u64::MIN,
        0,
        std::primitive::u64::MAX
    ]
}
pub fn std_primitive_f32_test_cases_vec() -> [std::primitive::f32;12] {
    [
        std::primitive::f32::EPSILON,
        std::primitive::f32::MAX,
        std::primitive::f32::MIN,
        std::primitive::f32::MIN_POSITIVE,
        -1e30,
        -1e-30,
        -1.0,
        -0.0,
        0.0,
        1.0,
        1e-30,
        1e30
    ]
}
pub fn std_primitive_f64_test_cases_vec() -> [std::primitive::f64;12] {
    [
        std::primitive::f64::EPSILON,
        std::primitive::f64::MAX,
        std::primitive::f64::MIN,
        std::primitive::f64::MIN_POSITIVE,
        -1e300,
        -1e-300,
        -1.0,
        -0.0,
        0.0,
        1.0,
        1e-300,
        1e300
    ]
}
pub fn std_primitive_bool_test_cases_vec() -> [std::primitive::bool;2] {
    [
        true,
        false
    ]
}
pub fn std_string_string_test_cases_vec() -> [std::string::String;12] {
    [
        "".to_string(),
        "a".to_string(),
        "Hello, world!".to_string(),
        "   ".to_string(),
        "\n\r\t".to_string(),
        "1234567890".to_string(),
        "😀".to_string(),
        "こんにちは".to_string(),
        "🌍🚀✨ Rust 💖🦀".to_string(),
        "a".repeat(1024),
        "line1\nline2\nline3".to_string(),
        std::string::String::from_utf8_lossy(&[0xF0, 0x9F, 0x92, 0x96]).to_string()
    ]
}
pub fn uuid_uuid_test_cases_vec() -> [uuid::Uuid;1] {
    [
        uuid::Uuid::new_v4()
    ]
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NonPrimaryKeyPostgresqlTypeReadOnlyIds(pub Value<std::option::Option<()>>);
impl sqlx::Decode<'_, sqlx::Postgres> for NonPrimaryKeyPostgresqlTypeReadOnlyIds {
    fn decode(value: sqlx::postgres::PgValueRef<'_>) -> Result<Self, sqlx::error::BoxDynError> {
        match <sqlx::types::Json<Self> as sqlx::Decode<sqlx::Postgres>>::decode(value) {
            Ok(value) => Ok(value.0),
            Err(error) => Err(error),
        }
    }
}
impl sqlx::Type<sqlx::Postgres> for NonPrimaryKeyPostgresqlTypeReadOnlyIds {
    fn type_info() -> <sqlx::Postgres as sqlx::Database>::TypeInfo {
        <sqlx::types::Json<Self> as sqlx::Type<sqlx::Postgres>>::type_info()
    }
    fn compatible(ty: &<sqlx::Postgres as sqlx::Database>::TypeInfo) -> std::primitive::bool {
        <sqlx::types::Json<Self> as sqlx::Type<sqlx::Postgres>>::compatible(ty)
    }
}
impl std::default::Default for NonPrimaryKeyPostgresqlTypeReadOnlyIds {
    fn default() -> Self {
        Self(Value{ value: None })
    }
}
pub fn increment_checked_add_one_returning_increment(increment: &mut std::primitive::u64) -> Result<std::primitive::u64, QueryPartErrorNamed> {
    match increment.checked_add(1) {
        Some(value) => {
            *increment = value;
            Ok(value)
        }
        None => Err(QueryPartErrorNamed::CheckedAdd {
            code_occurence: error_occurence_lib::code_occurence!()
        })
    }
}

pub enum EqualOperator {
    Equal,
    IsNull
}
impl EqualOperator {
    pub fn to_query_str(&self) -> &'static std::primitive::str {
        match &self {
            Self::Equal => "=",
            Self::IsNull => "is null",
        }
    }
}
pub trait PostgresqlTypeEqualOperator {
    fn operator(&self) -> EqualOperator;
}

#[derive(Debug, Default, Clone, PartialEq, Eq, PartialOrd, serde::Serialize, schemars::JsonSchema)]
pub struct UnsignedPartOfStdPrimitiveI32(std::primitive::i32); //todo why exactly i32? maybe different types for postgresql type and postgresql json type
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, thiserror::Error, error_occurence_lib::ErrorOccurence, schemars::JsonSchema)]
pub enum UnsignedPartOfStdPrimitiveI32TryFromStdPrimitiveI32ErrorNamed {
    LessThanZero {
        #[eo_to_std_string_string_serialize_deserialize]
        value: std::primitive::i32,
        code_occurence: error_occurence_lib::code_occurence::CodeOccurence,
    },
}
impl std::convert::TryFrom<std::primitive::i32> for UnsignedPartOfStdPrimitiveI32 {
    type Error = UnsignedPartOfStdPrimitiveI32TryFromStdPrimitiveI32ErrorNamed;
    fn try_from(value: std::primitive::i32) -> Result<Self, Self::Error> {
        if value >= 0 { Ok(Self(value)) } else { Err(Self::Error::LessThanZero { value, code_occurence: error_occurence_lib::code_occurence!() }) }
    }
}
const _: () = {
    extern crate serde as _serde;
    #[automatically_derived]
    impl<'de> _serde::Deserialize<'de> for UnsignedPartOfStdPrimitiveI32 {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>,
        {
            #[doc(hidden)]
            struct __Visitor<'de> {
                marker: _serde::__private::PhantomData<UnsignedPartOfStdPrimitiveI32>,
                lifetime: _serde::__private::PhantomData<&'de ()>,
            }
            #[automatically_derived]
            impl<'de> _serde::de::Visitor<'de> for __Visitor<'de> {
                type Value = UnsignedPartOfStdPrimitiveI32;
                fn expecting(&self, __formatter: &mut _serde::__private::Formatter<'_>) -> _serde::__private::fmt::Result {
                    _serde::__private::Formatter::write_str(__formatter, "tuple struct UnsignedPartOfStdPrimitiveI32")
                }
                #[inline]
                fn visit_newtype_struct<__E>(self, __e: __E) -> _serde::__private::Result<Self::Value, __E::Error>
                where
                    __E: _serde::Deserializer<'de>,
                {
                    let __field0: std::primitive::i32 = <std::primitive::i32 as _serde::Deserialize>::deserialize(__e)?;
                    match UnsignedPartOfStdPrimitiveI32::try_from(__field0) {
                        Ok(value) => serde::__private::Ok(value),
                        Err(error) => Err(serde::de::Error::custom(format!("{error:?}"))),
                    }
                }
                #[inline]
                fn visit_seq<__A>(self, mut __seq: __A) -> _serde::__private::Result<Self::Value, __A::Error>
                where
                    __A: _serde::de::SeqAccess<'de>,
                {
                    let __field0 = match _serde::de::SeqAccess::next_element::<std::primitive::i32>(&mut __seq)? {
                        _serde::__private::Some(__value) => __value,
                        _serde::__private::None => {
                            return _serde::__private::Err(_serde::de::Error::invalid_length(0usize, &"tuple struct UnsignedPartOfStdPrimitiveI32 with 1 element"));
                        }
                    };
                    match UnsignedPartOfStdPrimitiveI32::try_from(__field0) {
                        Ok(value) => serde::__private::Ok(value),
                        Err(error) => Err(serde::de::Error::custom(format!("{error:?}"))),
                    }
                }
            }
            _serde::Deserializer::deserialize_newtype_struct(
                __deserializer,
                "UnsignedPartOfStdPrimitiveI32",
                __Visitor {
                    marker: _serde::__private::PhantomData::<Self>,
                    lifetime: _serde::__private::PhantomData,
                },
            )
        }
    }
};
impl error_occurence_lib::ToStdStringString for UnsignedPartOfStdPrimitiveI32 {
    fn to_std_string_string(&self) -> std::string::String {
        self.0.to_string()
    }
}
impl sqlx::Type<sqlx::Postgres> for UnsignedPartOfStdPrimitiveI32 {
    fn type_info() -> <sqlx::Postgres as sqlx::Database>::TypeInfo {
        <std::primitive::i32 as sqlx::Type<sqlx::Postgres>>::type_info()
    }
    fn compatible(ty: &<sqlx::Postgres as sqlx::Database>::TypeInfo) -> std::primitive::bool {
        <std::primitive::i32 as sqlx::Type<sqlx::Postgres>>::compatible(ty)
    }
}
impl sqlx::Encode<'_, sqlx::Postgres> for UnsignedPartOfStdPrimitiveI32 {
    fn encode_by_ref(&self, buf: &mut sqlx::postgres::PgArgumentBuffer) -> Result<sqlx::encode::IsNull, Box<dyn std::error::Error + Send + Sync>> {
        sqlx::Encode::<sqlx::Postgres>::encode_by_ref(&self.0, buf)
    }
}
impl UnsignedPartOfStdPrimitiveI32 {
    pub const fn get(&self) -> std::primitive::i32 {
        self.0
    }
}
impl DefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement for UnsignedPartOfStdPrimitiveI32 {
    fn default_but_option_is_always_some_and_vec_always_contains_one_element() -> Self {
        Self(0)
    }
}

#[derive(Debug, Default, Clone, PartialEq, Eq, PartialOrd, serde::Serialize, schemars::JsonSchema)]
pub struct NotZeroUnsignedPartOfStdPrimitiveI32(UnsignedPartOfStdPrimitiveI32);
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, thiserror::Error, error_occurence_lib::ErrorOccurence, schemars::JsonSchema)]
pub enum NotZeroUnsignedPartOfStdPrimitiveI32TryFromStdPrimitiveI32ErrorNamed {
    UnsignedPartOfStdPrimitiveI32TryFromStdPrimitiveI32ErrorNamed {
        #[eo_error_occurence]
        value: UnsignedPartOfStdPrimitiveI32TryFromStdPrimitiveI32ErrorNamed,
        code_occurence: error_occurence_lib::code_occurence::CodeOccurence,
    },
    IsZero {
        code_occurence: error_occurence_lib::code_occurence::CodeOccurence,
    },
}
impl std::convert::TryFrom<std::primitive::i32> for NotZeroUnsignedPartOfStdPrimitiveI32 {
    type Error = NotZeroUnsignedPartOfStdPrimitiveI32TryFromStdPrimitiveI32ErrorNamed;
    fn try_from(value: std::primitive::i32) -> Result<Self, Self::Error> {
        match UnsignedPartOfStdPrimitiveI32::try_from(value) {
            Ok(value) => if value.0 == 0 {
                Err(Self::Error::IsZero {
                    code_occurence: error_occurence_lib::code_occurence!()
                })
            }
            else {
                Ok(Self(value))
            },
            Err(error) => Err(Self::Error::UnsignedPartOfStdPrimitiveI32TryFromStdPrimitiveI32ErrorNamed {
                value: error,
                code_occurence: error_occurence_lib::code_occurence!()
            })
        }
    }
}
const _: () = {
    extern crate serde as _serde;
    #[automatically_derived]
    impl<'de> _serde::Deserialize<'de> for NotZeroUnsignedPartOfStdPrimitiveI32 {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>,
        {
            #[doc(hidden)]
            struct __Visitor<'de> {
                marker: _serde::__private::PhantomData<NotZeroUnsignedPartOfStdPrimitiveI32>,
                lifetime: _serde::__private::PhantomData<&'de ()>,
            }
            #[automatically_derived]
            impl<'de> _serde::de::Visitor<'de> for __Visitor<'de> {
                type Value = NotZeroUnsignedPartOfStdPrimitiveI32;
                fn expecting(&self, __formatter: &mut _serde::__private::Formatter<'_>) -> _serde::__private::fmt::Result {
                    _serde::__private::Formatter::write_str(__formatter, "tuple struct NotZeroUnsignedPartOfStdPrimitiveI32")
                }
                #[inline]
                fn visit_newtype_struct<__E>(self, __e: __E) -> _serde::__private::Result<Self::Value, __E::Error>
                where
                    __E: _serde::Deserializer<'de>,
                {
                    let __field0: std::primitive::i32 = <std::primitive::i32 as _serde::Deserialize>::deserialize(__e)?;
                    match NotZeroUnsignedPartOfStdPrimitiveI32::try_from(__field0) {
                        Ok(value) => serde::__private::Ok(value),
                        Err(error) => Err(serde::de::Error::custom(format!("{error:?}"))),
                    }
                }
                #[inline]
                fn visit_seq<__A>(self, mut __seq: __A) -> _serde::__private::Result<Self::Value, __A::Error>
                where
                    __A: _serde::de::SeqAccess<'de>,
                {
                    let __field0 = match _serde::de::SeqAccess::next_element::<std::primitive::i32>(&mut __seq)? {
                        _serde::__private::Some(__value) => __value,
                        _serde::__private::None => {
                            return _serde::__private::Err(_serde::de::Error::invalid_length(0usize, &"tuple struct NotZeroUnsignedPartOfStdPrimitiveI32 with 1 element"));
                        }
                    };
                    match NotZeroUnsignedPartOfStdPrimitiveI32::try_from(__field0) {
                        Ok(value) => serde::__private::Ok(value),
                        Err(error) => Err(serde::de::Error::custom(format!("{error:?}"))),
                    }
                }
            }
            _serde::Deserializer::deserialize_newtype_struct(
                __deserializer,
                "NotZeroUnsignedPartOfStdPrimitiveI32",
                __Visitor {
                    marker: _serde::__private::PhantomData::<Self>,
                    lifetime: _serde::__private::PhantomData,
                },
            )
        }
    }
};
impl error_occurence_lib::ToStdStringString for NotZeroUnsignedPartOfStdPrimitiveI32 {
    fn to_std_string_string(&self) -> std::string::String {
        self.0.to_std_string_string()
    }
}
impl sqlx::Type<sqlx::Postgres> for NotZeroUnsignedPartOfStdPrimitiveI32 {
    fn type_info() -> <sqlx::Postgres as sqlx::Database>::TypeInfo {
        <UnsignedPartOfStdPrimitiveI32 as sqlx::Type<sqlx::Postgres>>::type_info()
    }
    fn compatible(ty: &<sqlx::Postgres as sqlx::Database>::TypeInfo) -> std::primitive::bool {
        <UnsignedPartOfStdPrimitiveI32 as sqlx::Type<sqlx::Postgres>>::compatible(ty)
    }
}
impl sqlx::Encode<'_, sqlx::Postgres> for NotZeroUnsignedPartOfStdPrimitiveI32 {
    fn encode_by_ref(&self, buf: &mut sqlx::postgres::PgArgumentBuffer) -> Result<sqlx::encode::IsNull, Box<dyn std::error::Error + Send + Sync>> {
        sqlx::Encode::<sqlx::Postgres>::encode_by_ref(&self.0, buf)
    }
}
impl NotZeroUnsignedPartOfStdPrimitiveI32 {
    pub const fn get(&self) -> std::primitive::i32 {
        self.0.get()
    }
}
impl DefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement for NotZeroUnsignedPartOfStdPrimitiveI32 {
    fn default_but_option_is_always_some_and_vec_always_contains_one_element() -> Self {
        Self(DefaultButOptionIsAlwaysSomeAndVecAlwaysContainsOneElement::default_but_option_is_always_some_and_vec_always_contains_one_element())
    }
}