
GET http://127.0.0.1:8080/health_check HTTP/1.1

### 

GET http://127.0.0.1:8080/git_info HTTP/1.1

###

GET http://127.0.0.1:8080/src/main.rs HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786

###

GET http://127.0.0.1:8080/header_extractor_example HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786

###

GET http://127.0.0.1:8080/extract_custom_header_example HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786

###

GET http://127.0.0.1:8080/middleware_message_example HTTP/1.1

###

GET http://127.0.0.1:8080/read_middleware_custom_header HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786


######################################################

POST http://127.0.0.1:8080/example/create_many HTTP/1.1
content-type: application/json
commit: 926cf2c0bac1dfbd1fd466068b2c9fc5a271bc3b

[
  {
    "column_6e88acb0_c566_4fef_8a09_66a41338cf36": null,
    "animal_as_not_null_jsonb_object": {
      "field_0": {
        "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
      },
      "field_1": [
        {
          "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
        }
      ],
      "field_2": {
        "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
      },
      "field_3": [
        {
          "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
        }
      ]
    }
  }
]

###
 
GET http://127.0.0.1:8080/example/create_many_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

### 

POST http://127.0.0.1:8080/example/create_one HTTP/1.1
content-type: application/json
commit: e9e7647602a980c62e1d20c3d91cf61d3236f5f9



###
 
GET http://127.0.0.1:8080/example/create_one_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

###

POST http://127.0.0.1:8080/example/read_many HTTP/1.1
content-type: application/json
commit: 72a7f5c066a08a77fb91e75abee9f6e79e00e2b8

{
  "where_filter": {
    "column_6e88acb0_c566_4fef_8a09_66a41338cf36": {
      "logical_operator": "Or",
      "value": [
        {
          "Equal": {
            "logical_operator": "Or",
            "value": 2
          }
        }
        # ,
        # {
        #   "GreaterThan": {
        #     "logical_operator": "Or",
        #     "value": 0
        #   }
        # },
        # {
        #   "Between": {
        #     "logical_operator": "Or",
        #     "value": {
        #       "start": 0,
        #       "end": 0
        #     }
        #   }
        # },
        # {
        #   "In": {
        #     "logical_operator": "Or",
        #     "value": [
        #       0
        #     ]
        #   }
        # }
      ]
    }
    # ,
    # "animal_as_not_null_jsonb_object": {
    #   "logical_operator": "Or",
    #   "value": [
    #     {
    #       "Field0": {
    #         "logical_operator": "Or",
    #         "value": [
    #           {
    #             "Column113F366235A24A7A932603Bbd441815F": {
    #               "logical_operator": "Or",
    #               "value": [
    #                 {
    #                   "Equal": {
    #                     "logical_operator": "Or",
    #                     "value": 0
    #                   }
    #                 },
    #                 {
    #                   "In": {
    #                     "logical_operator": "Or",
    #                     "value": [
    #                       0
    #                     ]
    #                   }
    #                 },
    #                 {
    #                   "GreaterThan": {
    #                     "logical_operator": "Or",
    #                     "value": 0
    #                   }
    #                 },
    #                 {
    #                   "Between": {
    #                     "logical_operator": "Or",
    #                     "value": {
    #                       "start": 0,
    #                       "end": 0
    #                     }
    #                   }
    #                 }
    #               ]
    #             }
    #           }
    #         ]
    #       }
    #     },
    #     {
    #       "Field1": {
    #         "logical_operator": "Or",
    #         "value": [
    #           {
    #             "Equal": {
    #               "logical_operator": "Or",
    #               "value": [
    #                 {
    #                   "id": "45ce20ad-c5af-4783-9080-66039efe82d2",
    #                   "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                 }
    #               ]
    #             }
    #           },
    #           {
    #             "DimensionOneEqual": {
    #               "logical_operator": "Or",
    #               "dimensions": [
    #                 0
    #               ],
    #               "value": {
    #                 "id": "b1637b60-2349-408a-98ae-a2f48f95fd7a",
    #                 "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #               }
    #             }
    #           },
    #           {
    #             "LengthEqual": {
    #               "logical_operator": "Or",
    #               "value": 0
    #             }
    #           },
    #           {
    #             "LengthMoreThan": {
    #               "logical_operator": "Or",
    #               "value": 0
    #             }
    #           },
    #           {
    #             "In": {
    #               "logical_operator": "Or",
    #               "value": [
    #                 [
    #                   {
    #                     "id": "815c9319-0cec-4df4-bab5-668e4dde5fb0",
    #                     "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                   }
    #                 ]
    #               ]
    #             }
    #           },
    #           {
    #             "DimensionOneIn": {
    #               "logical_operator": "Or",
    #               "dimensions": [
    #                 0
    #               ],
    #               "value": [
    #                 {
    #                   "id": "af9fc8cf-2403-4556-8b80-7f749504db68",
    #                   "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                 }
    #               ]
    #             }
    #           },
    #           {
    #             "ContainsAllElementsOfArray": {
    #               "logical_operator": "Or",
    #               "value": [
    #                 {
    #                   "id": "7e52f863-d6b9-4aad-8253-76cf5c4f411b",
    #                   "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                 }
    #               ]
    #             }
    #           },
    #           {
    #             "OverlapsWithArray": {
    #               "logical_operator": "Or",
    #               "value": [
    #                 {
    #                   "id": "196a5dab-1426-472f-85ef-7b927f0b4e32",
    #                   "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                 }
    #               ]
    #             }
    #           },
    #           {
    #             "ElementId": {
    #               "logical_operator": "Or",
    #               "value": [
    #                 {
    #                   "Equal": {
    #                     "logical_operator": "Or",
    #                     "value": "059103f9-3b18-42a5-a0be-69a2347dc93e"
    #                   }
    #                 },
    #                 {
    #                   "In": {
    #                     "logical_operator": "Or",
    #                     "value": [
    #                       "f4718804-0ae8-4eec-913c-2ca4111d0f2f"
    #                     ]
    #                   }
    #                 },
    #                 {
    #                   "RegularExpression": {
    #                     "logical_operator": "Or",
    #                     "regular_expression_case": "Sensitive",
    #                     "value": ""
    #                   }
    #                 }
    #               ]
    #             }
    #           },
    #           {
    #             "ElementColumn113F366235A24A7A932603Bbd441815F": {
    #               "logical_operator": "Or",
    #               "value": [
    #                 {
    #                   "Equal": {
    #                     "logical_operator": "Or",
    #                     "value": 0
    #                   }
    #                 },
    #                 {
    #                   "In": {
    #                     "logical_operator": "Or",
    #                     "value": [
    #                       0
    #                     ]
    #                   }
    #                 },
    #                 {
    #                   "GreaterThan": {
    #                     "logical_operator": "Or",
    #                     "value": 0
    #                   }
    #                 },
    #                 {
    #                   "Between": {
    #                     "logical_operator": "Or",
    #                     "value": {
    #                       "start": 0,
    #                       "end": 0
    #                     }
    #                   }
    #                 }
    #               ]
    #             }
    #           }
    #         ]
    #       }
    #     },
    #     {
    #       "Field2": {
    #         "logical_operator": "Or",
    #         "value": [
    #           [
    #             {
    #               "Column113F366235A24A7A932603Bbd441815F": {
    #                 "logical_operator": "Or",
    #                 "value": [
    #                   {
    #                     "Equal": {
    #                       "logical_operator": "Or",
    #                       "value": 0
    #                     }
    #                   },
    #                   {
    #                     "In": {
    #                       "logical_operator": "Or",
    #                       "value": [
    #                         0
    #                       ]
    #                     }
    #                   },
    #                   {
    #                     "GreaterThan": {
    #                       "logical_operator": "Or",
    #                       "value": 0
    #                     }
    #                   },
    #                   {
    #                     "Between": {
    #                       "logical_operator": "Or",
    #                       "value": {
    #                         "start": 0,
    #                         "end": 0
    #                       }
    #                     }
    #                   }
    #                 ]
    #               }
    #             }
    #           ]
    #         ]
    #       }
    #     },
    #     {
    #       "Field3": {
    #         "logical_operator": "Or",
    #         "value": [
    #           [
    #             {
    #               "Equal": {
    #                 "logical_operator": "Or",
    #                 "value": [
    #                   {
    #                     "id": "64e2f6f1-e883-41ae-9b39-6511371a0042",
    #                     "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                   }
    #                 ]
    #               }
    #             },
    #             {
    #               "DimensionOneEqual": {
    #                 "logical_operator": "Or",
    #                 "dimensions": [
    #                   0
    #                 ],
    #                 "value": {
    #                   "id": "a8d5935e-947d-4821-b6fa-385b57853815",
    #                   "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                 }
    #               }
    #             },
    #             {
    #               "LengthEqual": {
    #                 "logical_operator": "Or",
    #                 "value": 0
    #               }
    #             },
    #             {
    #               "LengthMoreThan": {
    #                 "logical_operator": "Or",
    #                 "value": 0
    #               }
    #             },
    #             {
    #               "In": {
    #                 "logical_operator": "Or",
    #                 "value": [
    #                   [
    #                     {
    #                       "id": "e7bc841b-f800-4bca-892c-a8a5442a42a1",
    #                       "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                     }
    #                   ]
    #                 ]
    #               }
    #             },
    #             {
    #               "DimensionOneIn": {
    #                 "logical_operator": "Or",
    #                 "dimensions": [
    #                   0
    #                 ],
    #                 "value": [
    #                   {
    #                     "id": "024e336a-79e2-4065-9b4d-ceca87078a66",
    #                     "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                   }
    #                 ]
    #               }
    #             },
    #             {
    #               "ContainsAllElementsOfArray": {
    #                 "logical_operator": "Or",
    #                 "value": [
    #                   {
    #                     "id": "fc541b9f-ee00-4bfd-99b3-95b10bb519b8",
    #                     "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                   }
    #                 ]
    #               }
    #             },
    #             {
    #               "OverlapsWithArray": {
    #                 "logical_operator": "Or",
    #                 "value": [
    #                   {
    #                     "id": "783990af-0ec6-404c-bbfb-1d9154923645",
    #                     "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                   }
    #                 ]
    #               }
    #             },
    #             {
    #               "ElementId": {
    #                 "logical_operator": "Or",
    #                 "value": [
    #                   {
    #                     "Equal": {
    #                       "logical_operator": "Or",
    #                       "value": "71ca54cd-3c67-400c-be1a-3b025a0b726c"
    #                     }
    #                   },
    #                   {
    #                     "In": {
    #                       "logical_operator": "Or",
    #                       "value": [
    #                         "e1b92856-0a37-4a40-b925-0427a964a0cd"
    #                       ]
    #                     }
    #                   },
    #                   {
    #                     "RegularExpression": {
    #                       "logical_operator": "Or",
    #                       "regular_expression_case": "Sensitive",
    #                       "value": ""
    #                     }
    #                   }
    #                 ]
    #               }
    #             },
    #             {
    #               "ElementColumn113F366235A24A7A932603Bbd441815F": {
    #                 "logical_operator": "Or",
    #                 "value": [
    #                   {
    #                     "Equal": {
    #                       "logical_operator": "Or",
    #                       "value": 0
    #                     }
    #                   },
    #                   {
    #                     "In": {
    #                       "logical_operator": "Or",
    #                       "value": [
    #                         0
    #                       ]
    #                     }
    #                   },
    #                   {
    #                     "GreaterThan": {
    #                       "logical_operator": "Or",
    #                       "value": 0
    #                     }
    #                   },
    #                   {
    #                     "Between": {
    #                       "logical_operator": "Or",
    #                       "value": {
    #                         "start": 0,
    #                         "end": 0
    #                       }
    #                     }
    #                   }
    #                 ]
    #               }
    #             }
    #           ]
    #         ]
    #       }
    #     }
    #   ]
    # }
  },
  "select": [
    {
      "column_6e88acb0_c566_4fef_8a09_66a41338cf36": null
    },
    {
      "animal_as_not_null_jsonb_object": [
        {
          "field_0": [
            {
              "column_113f3662_35a2_4a7a_9326_03bbd441815f": null
            }
          ]
        },
        {
          "field_1": {
            "doggie_with_id_as_not_null_jsonb_object_with_id_select": [
              {
                "id": null
              },
              {
                "column_113f3662_35a2_4a7a_9326_03bbd441815f": null
              }
            ],
            "dimension1_pagination": {
              "limit": 5,
              "offset": 0
            }
          }
        },
        {
          "field_2": [
            {
              "column_113f3662_35a2_4a7a_9326_03bbd441815f": null
            }
          ]
        },
        {
          "field_3": {
            "doggie_with_id_as_not_null_jsonb_object_with_id_select": [
              {
                "id": null
              },
              {
                "column_113f3662_35a2_4a7a_9326_03bbd441815f": null
              }
            ],
            "dimension1_pagination": {
              "limit": 5,
              "offset": 0
            }
          }
        }
      ]
    }
  ],
  "order_by": {
    "column": {
      "column_6e88acb0_c566_4fef_8a09_66a41338cf36": null
    },
    "order": "asc"
  },
  "pagination": {
    "limit": 5,
    "offset": 0
  }
}

###

GET http://127.0.0.1:8080/example/read_many_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

###

POST http://127.0.0.1:8080/example/read_one HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

###

GET http://127.0.0.1:8080/example/read_one_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

### fix this  
 
PATCH http://127.0.0.1:8080/example/update_many HTTP/1.1 
content-type: application/json
commit: f7e8bd75a29858f2be33b8076f2ebda4bd413a70

[
  {
    "column_6e88acb0_c566_4fef_8a09_66a41338cf36": 1,
    "animal_as_not_null_jsonb_object": {
      "value": [
        {
          "doggie_as_not_null_jsonb_object": {
            "value": [
              {
                "column_0f498e79_5440_4c9d_90cf_c32f9b7d4005": {
                  "value": [
                    1
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  }
]

###

GET http://127.0.0.1:8080/example/update_many_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

### 

PATCH http://127.0.0.1:8080/example/update_one HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c



###
 
GET http://127.0.0.1:8080/example/update_one_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

####"^first_test_name_create$"  

DELETE http://127.0.0.1:8080/example/delete_many HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

{
  "where_filter": {
    "column_6e88acb0_c566_4fef_8a09_66a41338cf36": {
      "logical_operator": "Or",
      "value": [
        {
          "Equal": {
            "logical_operator": "Or",
            "value": 2
          }
        }
        # ,
        # {
        #   "GreaterThan": {
        #     "logical_operator": "Or",
        #     "value": 0
        #   }
        # },
        # {
        #   "Between": {
        #     "logical_operator": "Or",
        #     "value": {
        #       "start": 0,
        #       "end": 0
        #     }
        #   }
        # },
        # {
        #   "In": {
        #     "logical_operator": "Or",
        #     "value": [
        #       0
        #     ]
        #   }
        # }
      ]
    }
    # ,
    # "animal_as_not_null_jsonb_object": {
    #   "logical_operator": "Or",
    #   "value": [
    #     {
    #       "Field0": {
    #         "logical_operator": "Or",
    #         "value": [
    #           {
    #             "Column113F366235A24A7A932603Bbd441815F": {
    #               "logical_operator": "Or",
    #               "value": [
    #                 {
    #                   "Equal": {
    #                     "logical_operator": "Or",
    #                     "value": 0
    #                   }
    #                 },
    #                 {
    #                   "In": {
    #                     "logical_operator": "Or",
    #                     "value": [
    #                       0
    #                     ]
    #                   }
    #                 },
    #                 {
    #                   "GreaterThan": {
    #                     "logical_operator": "Or",
    #                     "value": 0
    #                   }
    #                 },
    #                 {
    #                   "Between": {
    #                     "logical_operator": "Or",
    #                     "value": {
    #                       "start": 0,
    #                       "end": 0
    #                     }
    #                   }
    #                 }
    #               ]
    #             }
    #           }
    #         ]
    #       }
    #     },
    #     {
    #       "Field1": {
    #         "logical_operator": "Or",
    #         "value": [
    #           {
    #             "Equal": {
    #               "logical_operator": "Or",
    #               "value": [
    #                 {
    #                   "id": "c32e6acd-63b4-4d5e-9d0f-51dfab3d63e9",
    #                   "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                 }
    #               ]
    #             }
    #           },
    #           {
    #             "DimensionOneEqual": {
    #               "logical_operator": "Or",
    #               "dimensions": [
    #                 0
    #               ],
    #               "value": {
    #                 "id": "0446adf3-2973-461a-9c53-018d28a22970",
    #                 "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #               }
    #             }
    #           },
    #           {
    #             "LengthEqual": {
    #               "logical_operator": "Or",
    #               "value": 0
    #             }
    #           },
    #           {
    #             "LengthMoreThan": {
    #               "logical_operator": "Or",
    #               "value": 0
    #             }
    #           },
    #           {
    #             "In": {
    #               "logical_operator": "Or",
    #               "value": [
    #                 [
    #                   {
    #                     "id": "1da7944a-0877-4a10-8596-8c1e7e0c2787",
    #                     "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                   }
    #                 ]
    #               ]
    #             }
    #           },
    #           {
    #             "DimensionOneIn": {
    #               "logical_operator": "Or",
    #               "dimensions": [
    #                 0
    #               ],
    #               "value": [
    #                 {
    #                   "id": "1788866c-fcec-40cc-80b3-a2690e6c4af5",
    #                   "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                 }
    #               ]
    #             }
    #           },
    #           {
    #             "ContainsAllElementsOfArray": {
    #               "logical_operator": "Or",
    #               "value": [
    #                 {
    #                   "id": "3299e27c-7a1b-4fbe-a499-f2298432739a",
    #                   "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                 }
    #               ]
    #             }
    #           },
    #           {
    #             "OverlapsWithArray": {
    #               "logical_operator": "Or",
    #               "value": [
    #                 {
    #                   "id": "82ff243f-a78f-447d-9e74-0973c5dcc9cf",
    #                   "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                 }
    #               ]
    #             }
    #           },
    #           {
    #             "ElementId": {
    #               "logical_operator": "Or",
    #               "value": [
    #                 {
    #                   "Equal": {
    #                     "logical_operator": "Or",
    #                     "value": "759839ab-ab91-4393-a941-02463d4ea11a"
    #                   }
    #                 },
    #                 {
    #                   "In": {
    #                     "logical_operator": "Or",
    #                     "value": [
    #                       "afb29e1c-c2ec-470f-a86f-28a075e459bd"
    #                     ]
    #                   }
    #                 },
    #                 {
    #                   "RegularExpression": {
    #                     "logical_operator": "Or",
    #                     "regular_expression_case": "Sensitive",
    #                     "value": ""
    #                   }
    #                 }
    #               ]
    #             }
    #           },
    #           {
    #             "ElementColumn113F366235A24A7A932603Bbd441815F": {
    #               "logical_operator": "Or",
    #               "value": [
    #                 {
    #                   "Equal": {
    #                     "logical_operator": "Or",
    #                     "value": 0
    #                   }
    #                 },
    #                 {
    #                   "In": {
    #                     "logical_operator": "Or",
    #                     "value": [
    #                       0
    #                     ]
    #                   }
    #                 },
    #                 {
    #                   "GreaterThan": {
    #                     "logical_operator": "Or",
    #                     "value": 0
    #                   }
    #                 },
    #                 {
    #                   "Between": {
    #                     "logical_operator": "Or",
    #                     "value": {
    #                       "start": 0,
    #                       "end": 0
    #                     }
    #                   }
    #                 }
    #               ]
    #             }
    #           }
    #         ]
    #       }
    #     },
    #     {
    #       "Field2": {
    #         "logical_operator": "Or",
    #         "value": [
    #           [
    #             {
    #               "Column113F366235A24A7A932603Bbd441815F": {
    #                 "logical_operator": "Or",
    #                 "value": [
    #                   {
    #                     "Equal": {
    #                       "logical_operator": "Or",
    #                       "value": 0
    #                     }
    #                   },
    #                   {
    #                     "In": {
    #                       "logical_operator": "Or",
    #                       "value": [
    #                         0
    #                       ]
    #                     }
    #                   },
    #                   {
    #                     "GreaterThan": {
    #                       "logical_operator": "Or",
    #                       "value": 0
    #                     }
    #                   },
    #                   {
    #                     "Between": {
    #                       "logical_operator": "Or",
    #                       "value": {
    #                         "start": 0,
    #                         "end": 0
    #                       }
    #                     }
    #                   }
    #                 ]
    #               }
    #             }
    #           ]
    #         ]
    #       }
    #     },
    #     {
    #       "Field3": {
    #         "logical_operator": "Or",
    #         "value": [
    #           [
    #             {
    #               "Equal": {
    #                 "logical_operator": "Or",
    #                 "value": [
    #                   {
    #                     "id": "3119d9de-b310-4709-b6c6-cebbd30031c0",
    #                     "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                   }
    #                 ]
    #               }
    #             },
    #             {
    #               "DimensionOneEqual": {
    #                 "logical_operator": "Or",
    #                 "dimensions": [
    #                   0
    #                 ],
    #                 "value": {
    #                   "id": "d8160622-9bea-469b-85bd-256c4186a24b",
    #                   "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                 }
    #               }
    #             },
    #             {
    #               "LengthEqual": {
    #                 "logical_operator": "Or",
    #                 "value": 0
    #               }
    #             },
    #             {
    #               "LengthMoreThan": {
    #                 "logical_operator": "Or",
    #                 "value": 0
    #               }
    #             },
    #             {
    #               "In": {
    #                 "logical_operator": "Or",
    #                 "value": [
    #                   [
    #                     {
    #                       "id": "c5460d8d-c812-466e-b0d1-22c488a72203",
    #                       "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                     }
    #                   ]
    #                 ]
    #               }
    #             },
    #             {
    #               "DimensionOneIn": {
    #                 "logical_operator": "Or",
    #                 "dimensions": [
    #                   0
    #                 ],
    #                 "value": [
    #                   {
    #                     "id": "d9a8e053-c787-499f-85b7-0119b0c6e1f5",
    #                     "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                   }
    #                 ]
    #               }
    #             },
    #             {
    #               "ContainsAllElementsOfArray": {
    #                 "logical_operator": "Or",
    #                 "value": [
    #                   {
    #                     "id": "a662ae0e-b963-401a-8fa7-f3efe6d3fda7",
    #                     "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                   }
    #                 ]
    #               }
    #             },
    #             {
    #               "OverlapsWithArray": {
    #                 "logical_operator": "Or",
    #                 "value": [
    #                   {
    #                     "id": "b2447856-a58a-4a9a-904a-59d2b9f923cd",
    #                     "column_113f3662_35a2_4a7a_9326_03bbd441815f": 0
    #                   }
    #                 ]
    #               }
    #             },
    #             {
    #               "ElementId": {
    #                 "logical_operator": "Or",
    #                 "value": [
    #                   {
    #                     "Equal": {
    #                       "logical_operator": "Or",
    #                       "value": "477fb107-90d6-45a7-af54-69fe20ef5657"
    #                     }
    #                   },
    #                   {
    #                     "In": {
    #                       "logical_operator": "Or",
    #                       "value": [
    #                         "6ce91271-0fc2-4308-b916-fb1c64c665a2"
    #                       ]
    #                     }
    #                   },
    #                   {
    #                     "RegularExpression": {
    #                       "logical_operator": "Or",
    #                       "regular_expression_case": "Sensitive",
    #                       "value": ""
    #                     }
    #                   }
    #                 ]
    #               }
    #             },
    #             {
    #               "ElementColumn113F366235A24A7A932603Bbd441815F": {
    #                 "logical_operator": "Or",
    #                 "value": [
    #                   {
    #                     "Equal": {
    #                       "logical_operator": "Or",
    #                       "value": 0
    #                     }
    #                   },
    #                   {
    #                     "In": {
    #                       "logical_operator": "Or",
    #                       "value": [
    #                         0
    #                       ]
    #                     }
    #                   },
    #                   {
    #                     "GreaterThan": {
    #                       "logical_operator": "Or",
    #                       "value": 0
    #                     }
    #                   },
    #                   {
    #                     "Between": {
    #                       "logical_operator": "Or",
    #                       "value": {
    #                         "start": 0,
    #                         "end": 0
    #                       }
    #                     }
    #                   }
    #                 ]
    #               }
    #             }
    #           ]
    #         ]
    #       }
    #     }
    #   ]
    # }
  }
}

###
 
GET http://127.0.0.1:8080/example/delete_many_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

###

DELETE http://127.0.0.1:8080/example/delete_one HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c



###
 
GET http://127.0.0.1:8080/example/delete_one_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c
