
GET http://127.0.0.1:8080/health_check HTTP/1.1

### 

GET http://127.0.0.1:8080/git_info HTTP/1.1

###

GET http://127.0.0.1:8080/src/main.rs HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786

###

GET http://127.0.0.1:8080/header_extractor_example HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786

###

GET http://127.0.0.1:8080/extract_custom_header_example HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786

###

GET http://127.0.0.1:8080/middleware_message_example HTTP/1.1

###

GET http://127.0.0.1:8080/read_middleware_custom_header HTTP/1.1
commit: 64bd54ae5431a4e8d959a57d1a733f71ef077786


######################################################

POST http://127.0.0.1:8080/example/create_many HTTP/1.1
content-type: application/json
commit: 926cf2c0bac1dfbd1fd466068b2c9fc5a271bc3b

[
  {
    "column_40d64ae4_a646_4394_bfce_3894bdfced87": 0,
    "column_6e88acb0_c566_4fef_8a09_66a41338cf36": null,
    "animal_as_not_null_jsonb_object": {
      "doggie_as_not_null_jsonb_object": {
        "column_32fc16eb_2641_4d65_acec_0c7addbfe338": [
          [
            [
              [
                ""
              ]
            ]
          ]
        ]
      }
    },
    "column_28f3512a_715d_40c2_87a3_2e661699172f": [
      {
        "year": 2025,
        "month": 6,
        "day": 26
      }
    ]
  }
]

###
 
GET http://127.0.0.1:8080/example/create_many_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

### 

POST http://127.0.0.1:8080/example/create_one HTTP/1.1
content-type: application/json
commit: e9e7647602a980c62e1d20c3d91cf61d3236f5f9



###
 
GET http://127.0.0.1:8080/example/create_one_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

###

POST http://127.0.0.1:8080/example/read_many HTTP/1.1
content-type: application/json
commit: 72a7f5c066a08a77fb91e75abee9f6e79e00e2b8

{
  # "column_40d64ae4_a646_4394_bfce_3894bdfced87": {
  #   "logical_operator": "Or",
  #   "value": [
  #     {
  #       "Equal": {
  #         "logical_operator": "Or",
  #         "value": 0
  #       }
  #     },
  #     {
  #       "GreaterThan": {
  #         "logical_operator": "Or",
  #         "value": 0
  #       }
  #     },
  #     {
  #       "Between": {
  #         "logical_operator": "Or",
  #         "value": {
  #           "start": 0,
  #           "end": 0
  #         }
  #       }
  #     },
  #     {
  #       "In": {
  #         "logical_operator": "Or",
  #         "value": [
  #           0
  #         ]
  #       }
  #     }
  #   ]
  # },
  # "column_6e88acb0_c566_4fef_8a09_66a41338cf36": {
  #   "logical_operator": "Or",
  #   "value": [
  #     {
  #       "Equal": {
  #         "logical_operator": "Or",
  #         "value": 0
  #       }
  #     },
  #     {
  #       "GreaterThan": {
  #         "logical_operator": "Or",
  #         "value": 0
  #       }
  #     },
  #     {
  #       "Between": {
  #         "logical_operator": "Or",
  #         "value": {
  #           "start": 0,
  #           "end": 0
  #         }
  #       }
  #     },
  #     {
  #       "In": {
  #         "logical_operator": "Or",
  #         "value": [
  #           0
  #         ]
  #       }
  #     }
  #   ]
  # },
  # "animal_as_not_null_jsonb_object": {
  #   "logical_operator": "Or",
  #   "value": [
  #     {
  #       "DoggieAsNotNullJsonbObject": {
  #         "logical_operator": "Or",
  #         "value": [
  #           {
  #             "Column32Fc16Eb26414D65Acec0C7Addbfe338": {
  #               "logical_operator": "Or",
  #               "value": [
  #                 {
  #                   "Equal": {
  #                     "logical_operator": "Or",
  #                     "value": [
  #                       [
  #                         [
  #                           [
  #                             ""
  #                           ]
  #                         ]
  #                       ]
  #                     ]
  #                   }
  #                 },
  #                 {
  #                   "DimensionOneEqual": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0
  #                     ],
  #                     "value": [
  #                       [
  #                         [
  #                           ""
  #                         ]
  #                       ]
  #                     ]
  #                   }
  #                 },
  #                 {
  #                   "DimensionTwoEqual": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0
  #                     ],
  #                     "value": [
  #                       [
  #                         ""
  #                       ]
  #                     ]
  #                   }
  #                 },
  #                 {
  #                   "DimensionThreeEqual": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0,
  #                       0
  #                     ],
  #                     "value": [
  #                       ""
  #                     ]
  #                   }
  #                 },
  #                 {
  #                   "DimensionFourEqual": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0,
  #                       0,
  #                       0
  #                     ],
  #                     "value": ""
  #                   }
  #                 },
  #                 {
  #                   "DimensionOneLengthEqual": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0
  #                     ],
  #                     "value": 0
  #                   }
  #                 },
  #                 {
  #                   "DimensionTwoLengthEqual": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0
  #                     ],
  #                     "value": 0
  #                   }
  #                 },
  #                 {
  #                   "DimensionThreeLengthEqual": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0,
  #                       0
  #                     ],
  #                     "value": 0
  #                   }
  #                 },
  #                 {
  #                   "DimensionFourLengthEqual": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0,
  #                       0,
  #                       0
  #                     ],
  #                     "value": 0
  #                   }
  #                 },
  #                 {
  #                   "DimensionOneLengthMoreThan": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0
  #                     ],
  #                     "value": 0
  #                   }
  #                 },
  #                 {
  #                   "DimensionTwoLengthMoreThan": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0
  #                     ],
  #                     "value": 0
  #                   }
  #                 },
  #                 {
  #                   "DimensionThreeLengthMoreThan": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0,
  #                       0
  #                     ],
  #                     "value": 0
  #                   }
  #                 },
  #                 {
  #                   "DimensionFourLengthMoreThan": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0,
  #                       0,
  #                       0
  #                     ],
  #                     "value": 0
  #                   }
  #                 },
  #                 {
  #                   "DimensionFourContainsAllElementsOfArray": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0,
  #                       0
  #                     ],
  #                     "value": [
  #                       ""
  #                     ]
  #                   }
  #                 },
  #                 {
  #                   "DimensionFourOverlapsWithArray": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0,
  #                       0
  #                     ],
  #                     "value": [
  #                       ""
  #                     ]
  #                   }
  #                 },
  #                 {
  #                   "DimensionOneAllElementsEqual": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [],
  #                     "value": [
  #                       [
  #                         [
  #                           ""
  #                         ]
  #                       ]
  #                     ]
  #                   }
  #                 },
  #                 {
  #                   "DimensionTwoAllElementsEqual": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0
  #                     ],
  #                     "value": [
  #                       [
  #                         ""
  #                       ]
  #                     ]
  #                   }
  #                 },
  #                 {
  #                   "DimensionThreeAllElementsEqual": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0
  #                     ],
  #                     "value": [
  #                       ""
  #                     ]
  #                   }
  #                 },
  #                 {
  #                   "DimensionFourAllElementsEqual": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0,
  #                       0
  #                     ],
  #                     "value": ""
  #                   }
  #                 },
  #                 {
  #                   "DimensionOneIn": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0
  #                     ],
  #                     "value": [
  #                       [
  #                         [
  #                           [
  #                             ""
  #                           ]
  #                         ]
  #                       ]
  #                     ]
  #                   }
  #                 },
  #                 {
  #                   "DimensionTwoIn": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0
  #                     ],
  #                     "value": [
  #                       [
  #                         [
  #                           ""
  #                         ]
  #                       ]
  #                     ]
  #                   }
  #                 },
  #                 {
  #                   "DimensionThreeIn": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0,
  #                       0
  #                     ],
  #                     "value": [
  #                       [
  #                         ""
  #                       ]
  #                     ]
  #                   }
  #                 },
  #                 {
  #                   "DimensionFourIn": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0,
  #                       0,
  #                       0
  #                     ],
  #                     "value": [
  #                       ""
  #                     ]
  #                   }
  #                 },
  #                 {
  #                   "DimensionFourRegularExpression": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0,
  #                       0,
  #                       0
  #                     ],
  #                     "regular_expression_case": "Sensitive",
  #                     "value": ""
  #                   }
  #                 },
  #                 {
  #                   "DimensionFourContainsElementRegularExpression": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0,
  #                       0
  #                     ],
  #                     "regular_expression_case": "Sensitive",
  #                     "value": ""
  #                   }
  #                 },
  #                 {
  #                   "DimensionFourAllElementsRegularExpression": {
  #                     "logical_operator": "Or",
  #                     "dimensions": [
  #                       0,
  #                       0,
  #                       0
  #                     ],
  #                     "regular_expression_case": "Sensitive",
  #                     "value": ""
  #                   }
  #                 }
  #               ]
  #             }
  #           }
  #         ]
  #       }
  #     }
  #   ]
  # },
  "column_28f3512a_715d_40c2_87a3_2e661699172f": {
    "logical_operator": "Or",
    "value": [
      # {
      #   "Equal": {
      #     "logical_operator": "Or",
      #     "value": [
      #       {
      #         "year": 0,
      #         "month": 1,
      #         "day": 1
      #       }
      #     ]
      #   }
      # },
      # {
      #   "DimensionOneEqual": {
      #     "logical_operator": "Or",
      #     "dimensions": [
      #       1
      #     ],
      #     "value": {
      #       "year": 0,
      #       "month": 1,
      #       "day": 1
      #     }
      #   }
      # },
      # {
      #   "DimensionOneLengthEqual": {
      #     "logical_operator": "Or",
      #     "value": 1
      #   }
      # },
      # {
      #   "DimensionOneLengthMoreThan": {
      #     "logical_operator": "Or",
      #     "value": 1
      #   }
      # },
      # {
      #   "DimensionOneGreaterThan": {
      #     "logical_operator": "Or",
      #     "dimensions": [
      #       1
      #     ],
      #     "value": {
      #       "year": 0,
      #       "month": 1,
      #       "day": 1
      #     }
      #   }
      # },
      # {
      #   "DimensionOneBetween": {
      #     "logical_operator": "Or",
      #     "dimensions": [
      #       1
      #     ],
      #     "value": {
      #       "start": {
      #         "year": 0,
      #         "month": 1,
      #         "day": 1
      #       },
      #       "end": {
      #         "year": 0,
      #         "month": 1,
      #         "day": 1
      #       }
      #     }
      #   }
      # },
      {
        "DimensionOneCurrentDate": {
          "logical_operator": "Or",
          "dimensions": [
            1
          ]
        }
      }
      # ,
      # {
      #   "DimensionOneGreaterThanCurrentDate": {
      #     "logical_operator": "Or",
      #     "dimensions": [
      #       1
      #     ]
      #   }
      # }
    ]
  },
  "select": [
    # {
    #   "column_40d64ae4_a646_4394_bfce_3894bdfced87": null
    # },
    # {
    #   "column_6e88acb0_c566_4fef_8a09_66a41338cf36": null
    # },
    # {
    #   "animal_as_not_null_jsonb_object": [
    #     {
    #       "doggie_as_not_null_jsonb_object": [
    #         {
    #           "column_32fc16eb_2641_4d65_acec_0c7addbfe338": {
    #             "dimension1_pagination": {
    #               "limit": 5,
    #               "offset": 0
    #             },
    #             "dimension2_pagination": {
    #               "limit": 5,
    #               "offset": 0
    #             },
    #             "dimension3_pagination": {
    #               "limit": 5,
    #               "offset": 0
    #             },
    #             "dimension4_pagination": {
    #               "limit": 5,
    #               "offset": 0
    #             }
    #           }
    #         }
    #       ]
    #     }
    #   ]
    # },
    {
      "column_28f3512a_715d_40c2_87a3_2e661699172f": {
        "dimension1_pagination": {
          "limit": 5,
          "offset": 1
        }
      }
    }
  ],
  "order_by": {
    "column": {
      "column_6e88acb0_c566_4fef_8a09_66a41338cf36": null
    },
    "order": "asc"
  },
  "pagination": {
    "limit": 5,
    "offset": 0
  }
}

###

GET http://127.0.0.1:8080/example/read_many_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

###

POST http://127.0.0.1:8080/example/read_one HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

###

GET http://127.0.0.1:8080/example/read_one_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

### fix this  
 
PATCH http://127.0.0.1:8080/example/update_many HTTP/1.1 
content-type: application/json
commit: f7e8bd75a29858f2be33b8076f2ebda4bd413a70

[
  {
    "column_6e88acb0_c566_4fef_8a09_66a41338cf36": 1,
    "animal_as_not_null_jsonb_object": {
      "value": [
        {
          "doggie_as_not_null_jsonb_object": {
            "value": [
              {
                "column_0f498e79_5440_4c9d_90cf_c32f9b7d4005": {
                  "value": [
                    1
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  }
]

###

GET http://127.0.0.1:8080/example/update_many_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

### 

PATCH http://127.0.0.1:8080/example/update_one HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c



###
 
GET http://127.0.0.1:8080/example/update_one_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

####"^first_test_name_create$"  

DELETE http://127.0.0.1:8080/example/delete_many HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c



###
 
GET http://127.0.0.1:8080/example/delete_many_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c

###

DELETE http://127.0.0.1:8080/example/delete_one HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c



###
 
GET http://127.0.0.1:8080/example/delete_one_payload_example HTTP/1.1
content-type: application/json
commit: 7566999599814c9ebc4cacfde468ae840697173c
