#[derive(Debug
    , postgresql_crud::GeneratePostgresqlCrud
)]
#[postgresql_crud::create_many_additional_error_variants{enum CreateManyAdditionalErrorVariants{}}]
#[postgresql_crud::create_one_additional_error_variants{enum CreateOneAdditionalErrorVariants{}}]
#[postgresql_crud::read_many_additional_error_variants{enum ReadManyAdditionalErrorVariants{}}]
#[postgresql_crud::read_one_additional_error_variants{enum ReadOneAdditionalErrorVariants{}}]
#[postgresql_crud::update_many_additional_error_variants{enum UpdateManyAdditionalErrorVariants{}}]
#[postgresql_crud::update_one_additional_error_variants{enum UpdateOneAdditionalErrorVariants{}}]
#[postgresql_crud::delete_many_additional_error_variants{enum DeleteManyAdditionalErrorVariants{}}]
#[postgresql_crud::delete_one_additional_error_variants{enum DeleteOneAdditionalErrorVariants{}}]
#[postgresql_crud::common_additional_error_variants{
    enum CommonAdditionalErrorVariants {
        CheckCommit {
            #[eo_error_occurence]
            check_commit: postgresql_crud::check_commit::CheckCommitErrorNamed,
            code_occurence: error_occurence_lib::code_occurence::CodeOccurence,
        },
    }
}]
#[postgresql_crud::create_many_additional_route_logic{
    println!("kekw");
}]
#[postgresql_crud::create_one_additional_route_logic{}]
#[postgresql_crud::read_many_additional_route_logic{}]
#[postgresql_crud::read_one_additional_route_logic{}]
#[postgresql_crud::update_many_additional_route_logic{}]
#[postgresql_crud::update_one_additional_route_logic{}]
#[postgresql_crud::delete_many_additional_route_logic{}]
#[postgresql_crud::delete_one_additional_route_logic{}]
#[postgresql_crud::common_additional_route_logic{
    // if let Err(error) = postgresql_crud::check_commit::check_commit(
    //     *app_state.get_enable_api_git_commit_check(),
    //     &headers,
    // ) {
    //     let status_code = postgresql_crud::GetAxumHttpStatusCode::get_axum_http_status_code(&error);
    //     //todo use reserved work instead of TryCreateManyRouteLogicErrorNamed
    //     let error = TryCreateManyRouteLogicErrorNamed::CheckCommit {
    //         check_commit: error,
    //         code_occurence: error_occurence_lib::code_occurence!(),
    //     };
    //     eprintln!("{error}");
    //     let mut response = axum::response::IntoResponse::into_response(axum::Json(
    //         TryCreateManyRouteLogicResponseVariants::from(error),
    //     ));
    //     *response.status_mut() = status_code;
    //     return response;
    // }
}]
pub struct Example {
    // pub vec: postgresql_crud::postgresql_type::VecOfStdPrimitiveI16AsNotNullArrayOfNotNullInt2,

    // pub column_40d64ae4_a646_4394_bfce_3894bdfced87: postgresql_crud::postgresql_type::StdPrimitiveI16AsNotNullInt2,
    // // pub column_ebe9a28a_eef0_4b1d_a706_8a9c363db7ab: postgresql_crud::postgresql_type::OptionStdPrimitiveI16AsNullableInt2,
    // // pub column_b225e9b0_80ae_4aea_ab7f_2444d0b3c5fa: postgresql_crud::postgresql_type::StdPrimitiveI32AsNotNullInt4,
    // // pub column_fb5fe9b0_1505_4d68_b2e1_2483bc47ab6c: postgresql_crud::postgresql_type::OptionStdPrimitiveI32AsNullableInt4,
    // // pub column_579f811f_17de_4989_b1f9_be4b5e060641: postgresql_crud::postgresql_type::StdPrimitiveI64AsNotNullInt8,
    // // pub column_55a6dde9_fdae_4025_b9ce_d8fd483a0b86: postgresql_crud::postgresql_type::OptionStdPrimitiveI64AsNullableInt8,
    // // pub column_59f8f4f5_e7e6_4ee3_973e_b73f2e415d81: postgresql_crud::postgresql_type::StdPrimitiveF32AsNotNullFloat4,
    // // pub column_389cc934_2e11_4e86_8429_ef75934563a7: postgresql_crud::postgresql_type::OptionStdPrimitiveF32AsNullableFloat4,
    // // pub column_e8c63c01_7317_4b3a_805f_59df250f3ad0: postgresql_crud::postgresql_type::StdPrimitiveF64AsNotNullFloat8,
    // // pub column_0c72cfa5_60ae_4f8f_b517_a68d5fda7eef: postgresql_crud::postgresql_type::OptionStdPrimitiveF64AsNullableFloat8,
    // // pub column_8ffe8fce_e270_4b32_8c74_2fad827581b1: postgresql_crud::postgresql_type::SqlxPostgresTypesPgMoneyAsNotNullMoney,
    // // pub column_c0956407_a5b3_4b7c_a016_20971edc67d6: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgMoneyAsNullableMoney,
    // // pub column_2311f761_9b1c_40e8_a9ee_2f990f598c7a: postgresql_crud::postgresql_type::SqlxTypesDecimalAsNotNullNumeric,
    // // pub column_521b136c_c5ce_46c8_badb_ce504990ca87: postgresql_crud::postgresql_type::OptionSqlxTypesDecimalAsNullableNumeric,
    // // pub column_a8238982_d31d_46ed_aa86_9d2420666769: postgresql_crud::postgresql_type::SqlxTypesBigDecimalAsNotNullNumeric,
    // // pub column_77e10de9_11aa_4eaf_aefa_8e97720b615a: postgresql_crud::postgresql_type::OptionSqlxTypesBigDecimalAsNullableNumeric,
    // // pub column_39b118e9_44ae_4fa6_8acb_4ea926b2afe4: postgresql_crud::postgresql_type::StdPrimitiveBoolAsNotNullBool,
    // // pub column_f3cfeda5_bff1_49b9_adc0_ee99468e116d: postgresql_crud::postgresql_type::OptionStdPrimitiveBoolAsNullableBool,
    // // pub column_ab072aa7_6b56_4b1f_9491_7b766f6dbc52: postgresql_crud::postgresql_type::StdStringStringAsNotNullCharN,
    // // pub column_b5fde990_7151_4944_95cf_221c59531bbb: postgresql_crud::postgresql_type::OptionStdStringStringAsNullableCharN,
    // // pub column_2a975be8_3b64_463c_b449_c7f678aa973f: postgresql_crud::postgresql_type::StdStringStringAsNotNullVarchar,
    // // pub column_f94b1781_21c6_414a_a1f0_82a1dc9b03d7: postgresql_crud::postgresql_type::OptionStdStringStringAsNullableVarchar,
    // // pub column_7578cdb5_a5b9_484b_ac9f_586fa3bcd2e8: postgresql_crud::postgresql_type::StdStringStringAsNotNullText,
    // // pub column_185e3592_8d03_4962_b423_fe22e0b5e28d: postgresql_crud::postgresql_type::OptionStdStringStringAsNullableText,
    // // pub column_83c47937_8319_43eb_8c42_72d267380602: postgresql_crud::postgresql_type::StdVecVecStdPrimitiveU8AsNotNullBytea,
    // // pub column_6367c2ff_5379_4d67_a49e_1075ff353a25: postgresql_crud::postgresql_type::OptionStdVecVecStdPrimitiveU8AsNullableBytea,
    // // pub column_03d92aed_e8d1_434f_a45d_029df9ad1d22: postgresql_crud::postgresql_type::SqlxTypesChronoNaiveTimeAsNotNullTime,
    // // pub column_7cd3a1c9_75b1_4227_a16e_8e316311568b: postgresql_crud::postgresql_type::OptionSqlxTypesChronoNaiveTimeAsNullableTime,
    // // pub column_0b4ff0bd_ad73_48fd_9ec2_b7bafa908953: postgresql_crud::postgresql_type::SqlxTypesTimeTimeAsNotNullTime,
    // // pub column_3c9b4049_bf22_44e2_a9d2_cecf01cc088d: postgresql_crud::postgresql_type::OptionSqlxTypesTimeTimeAsNullableTime,
    // // pub column_20555517_a10a_4ddf_a2c3_19898345d836: postgresql_crud::postgresql_type::SqlxPostgresTypesPgIntervalAsNotNullInterval,
    // // pub column_e8cd8405_0931_41f2_94cb_9766b405e432: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgIntervalAsNullableInterval,
    // // pub column_ddb3aed3_bcc2_4c14_b537_4e6249be754c: postgresql_crud::postgresql_type::SqlxTypesTimeDateAsNotNullDate,
    // // pub column_ccff97e5_f010_483a_a87d_497f68feb321: postgresql_crud::postgresql_type::OptionSqlxTypesTimeDateAsNullableDate,
    // // pub column_e2bd1441_feba_40d8_bf0e_df45f6d99d15: postgresql_crud::postgresql_type::SqlxTypesChronoNaiveDateAsNotNullDate,
    // // pub column_752433fa_f3d6_4e0d_81e7_5c5f277da8cd: postgresql_crud::postgresql_type::OptionSqlxTypesChronoNaiveDateAsNullableDate,
    // // pub column_e3770284_4ad4_4c87_bbcc_7a7adc738f2f: postgresql_crud::postgresql_type::SqlxTypesChronoNaiveDateTimeAsNotNullTimestamp,
    // // pub column_063e648a_c05e_4db6_9278_b3b131e5d9a7: postgresql_crud::postgresql_type::OptionSqlxTypesChronoNaiveDateTimeAsNullableTimestamp,
    // // pub column_6325da70_e3e9_4289_a1b0_e39be27a8517: postgresql_crud::postgresql_type::SqlxTypesTimePrimitiveDateTimeAsNotNullTimestamp,
    // // pub column_8d1d6adb_45fd_4564_9822_71022d53ec1c: postgresql_crud::postgresql_type::OptionSqlxTypesTimePrimitiveDateTimeAsNullableTimestamp,
    // // pub column_e06e3994_bb74_46a7_b914_1205bff2527c: postgresql_crud::postgresql_type::SqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNotNullTimestampTz,
    // // pub column_22b1b67c_039a_4020_ba36_63622d02cea6: postgresql_crud::postgresql_type::OptionSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNullableTimestampTz,
    // // pub column_293d0e00_6bd6_4a93_af30_67e9ea1ac7dd: postgresql_crud::postgresql_type::SqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNotNullTimestampTz,
    // // pub column_49f974c2_ff30_4ad9_b491_b7e844795808: postgresql_crud::postgresql_type::OptionSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNullableTimestampTz,
    // // pub column_0bb198f5_bf4c_4308_ba13_3f3a18960b25: postgresql_crud::postgresql_type::SqlxTypesUuidUuidAsNotNullUuidInitializedByClient,
    // // pub column_0cf8db36_04be_4fc9_bbcc_008321b357c2: postgresql_crud::postgresql_type::OptionSqlxTypesUuidUuidAsNullableUuidInitializedByClient,
    // // pub column_1e99c21a_69c5_480b_8282_fe38f7b870d7: postgresql_crud::postgresql_type::SqlxTypesIpnetworkIpNetworkAsNotNullInet,
    // // pub column_7c4400a7_c0ce_4470_94f0_bb9dcf3a5786: postgresql_crud::postgresql_type::OptionSqlxTypesIpnetworkIpNetworkAsNullableInet,
    // // pub column_be493f9c_ed9d_4471_8382_0eace73cb918: postgresql_crud::postgresql_type::SqlxTypesIpnetworkIpNetworkAsNotNullCidr,
    // // pub column_16c4828c_1277_479a_8b32_a556f19947a2: postgresql_crud::postgresql_type::OptionSqlxTypesIpnetworkIpNetworkAsNullableCidr,
    // // pub column_dd337b11_4ad8_4c64_b0d6_2e73882ad2d0: postgresql_crud::postgresql_type::SqlxTypesMacAddressMacAddressAsNotNullMacAddr,
    // // pub column_d77afa8a_f30f_439a_9339_fdfe730ee62e: postgresql_crud::postgresql_type::OptionSqlxTypesMacAddressMacAddressAsNullableMacAddr,
    // // pub column_fc22ca9d_1f57_46b4_922f_5ad659dfe5ff: postgresql_crud::postgresql_type::SqlxTypesBitVecAsNotNullBit,
    // // pub column_da0f6a4a_5eb9_46a2_98d1_b7985b537b13: postgresql_crud::postgresql_type::OptionSqlxTypesBitVecAsNullableBit,
    // // pub column_e668b6ec_1920_4346_a5a4_1af8e133b09c: postgresql_crud::postgresql_type::SqlxTypesBitVecAsNotNullVarbit,
    // // pub column_c4ceaa5a_1c93_4545_921e_9c7e38e65e11: postgresql_crud::postgresql_type::OptionSqlxTypesBitVecAsNullableVarbit,
    // // pub column_c203347a_c208_4b2b_8096_364a7fb66685: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeStdPrimitiveI32AsNotNullInt4Range,
    // // pub column_31f58552_715e_48f4_a7fd_a381af1a813f: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeStdPrimitiveI32AsNullableInt4Range,
    // // pub column_b471a4b4_a473_4541_ab51_82587e19d464: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeStdPrimitiveI64AsNotNullInt8Range,
    // // pub column_1aefbea2_7ffa_451c_9966_934f8ebf4f78: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeStdPrimitiveI64AsNullableInt8Range,
    // // pub column_1ddaf386_9a67_4d7d_b3f8_070c35e249c3: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesDecimalAsNotNullNumRange,
    // // pub column_9e4c0068_6974_46de_9dc1_bc95a679d9cb: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesDecimalAsNullableNumRange,
    // // pub column_f699bdd4_9380_44d0_b1be_2c792d3ec895: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesBigDecimalAsNotNullNumRange,
    // // pub column_aa7012af_393b_4736_8b95_725eb6df1ca0: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesBigDecimalAsNullableNumRange,
    // // pub column_abb40538_4eea_40ef_87bb_c55623bffd40: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesTimeDateAsNotNullDateRange,
    // // pub column_6f8fc5c1_3d38_4ca3_b092_0c7a266aaa8b: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesTimeDateAsNullableDateRange,
    // // pub column_5f85250a_f889_4d59_a1fa_12e32542ab04: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateAsNotNullDateRange,
    // // pub column_7051ad39_b56b_432a_9224_d3c46c93d47b: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateAsNullableDateRange,
    // // pub column_ba0e1014_7604_45c7_a475_b22a968108e8: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNotNullTimestampRange,
    // // pub column_4c3cf4d7_121c_4854_aad6_96e5e7820f2e: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNullableTimestampRange,
    // // pub column_29ca5058_5ad4_464e_aa1f_9077dbe1eca4: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesTimePrimitiveDateTimeAsNotNullTimestampRange,
    // // pub column_12f3648d_b7bc_4f36_a302_291c73783ef2: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesTimePrimitiveDateTimeAsNullableTimestampRange,
    // // pub column_a72a15d5_27f0_4a0c_a600_cac0c2d48bd7: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNotNullTimestampTzRange,
    // // pub column_bc3e8a83_9b2b_4709_ae21_f4f79b0dbfd0: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNullableTimestampTzRange,
    // // pub column_e454c17e_d90e_47fe_a0ef_940d7f5afdae: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNotNullTimestampTzRange,
    // // pub column_cc739472_9b4e_432c_a6cc_c803117b0086: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNullableTimestampTzRange,
    // // pub column_35ebd1c3_ddb7_44c2_bddf_92ef5296c432: postgresql_crud::postgresql_type::StdPrimitiveI16AsNotNullSmallSerialInitializedByPostgresql,
    // // pub column_d712ac90_8af2_4a55_9791_314812be4016: postgresql_crud::postgresql_type::StdPrimitiveI32AsNotNullSerialInitializedByPostgresql,
    // #[generate_postgresql_crud_primary_key]
    // pub column_6e88acb0_c566_4fef_8a09_66a41338cf36: postgresql_crud::postgresql_type::StdPrimitiveI64AsNotNullBigSerialInitializedByPostgresql,
    // // pub column_8384082c_21de_4a21_95e9_a398644d8ea1: postgresql_crud::postgresql_type::SqlxTypesUuidUuidAsNotNullUuidV4InitializedByPostgresql,

    // //todo rename like postgresql types: NotNull prefix, not postfix
    // pub object_animal_as_jsonb_not_null: ObjectAnimalAsJsonbNotNull,
    // // pub object_animal_as_jsonb_nullable: OptionObjectAnimalAsJsonbNullable,

    // // pub option_object_animal_as_jsonb_not_null: StdOptionOptionObjectAnimalAsJsonbNotNull,
    // // pub option_object_animal_as_jsonb_nullable: StdOptionOptionObjectAnimalAsJsonbNullable,

    // // pub std_vec_vec_object_with_id_animal_as_jsonb_not_null: StdVecVecObjectWithIdAnimalAsJsonbNotNull,
    // // pub std_vec_vec_object_with_id_animal_as_jsonb_nullable: StdVecVecObjectWithIdAnimalAsJsonbNullable,

    // // pub option_std_vec_vec_object_with_id_animal_as_jsonb_not_null: StdOptionOptionStdVecVecObjectWithIdAnimalAsJsonbNotNull,
    // // pub option_std_vec_vec_object_with_id_animal_as_jsonb_nullable: StdOptionOptionStdVecVecObjectWithIdAnimalAsJsonbNullable,

    // ///////////////////////////
    // // pub vec_std_primitive_i16_as_postgresql_int2_array_not_null: postgresql_crud::postgresql_type::VecStdPrimitiveI16AsInt2ArrayNotNull,
    // //63max
    // //////////////////////////////
    pub column_0dc03c59_6dde_449f_b3dd_b9311da65ea0: postgresql_crud::postgresql_type::StdPrimitiveI16AsNotNullInt2,
    pub column_09e37c52_709d_4c3e_8c3f_051b334e4bea: postgresql_crud::postgresql_type::VecOfStdPrimitiveI16AsNotNullArrayOfNotNullInt2,
    pub column_66a1395a_0480_4220_90c1_3884941cb3a1: postgresql_crud::postgresql_type::VecOfOptionStdPrimitiveI16AsNotNullArrayOfNullableInt2,
    pub column_28e2b732_8653_473d_936a_c8985d94e745: postgresql_crud::postgresql_type::OptionStdPrimitiveI16AsNullableInt2,
    pub column_43d9217b_5798_4987_a353_5db456ef23f3: postgresql_crud::postgresql_type::OptionVecOfStdPrimitiveI16AsNullableArrayOfNotNullInt2,
    pub column_0389cca4_6ff2_4d7d_822d_a3c923293133: postgresql_crud::postgresql_type::OptionVecOfOptionStdPrimitiveI16AsNullableArrayOfNullableInt2,
    pub column_8067abb0_8f77_47a9_b17c_06515e0bdaf9: postgresql_crud::postgresql_type::StdPrimitiveI32AsNotNullInt4,
    pub column_2e4816e7_5944_44b5_8380_f16588ed282f: postgresql_crud::postgresql_type::VecOfStdPrimitiveI32AsNotNullArrayOfNotNullInt4,
    pub column_3ce81ef9_f8fb_4e6d_bd90_54c017051ec0: postgresql_crud::postgresql_type::VecOfOptionStdPrimitiveI32AsNotNullArrayOfNullableInt4,
    pub column_a3d42f35_d3d6_4ae8_90cb_4c997f1f13c3: postgresql_crud::postgresql_type::OptionStdPrimitiveI32AsNullableInt4,
    pub column_25309781_9da1_4438_a153_67185d782271: postgresql_crud::postgresql_type::OptionVecOfStdPrimitiveI32AsNullableArrayOfNotNullInt4,
    pub column_a391c19c_8819_435f_9b14_c3a68cef1185: postgresql_crud::postgresql_type::OptionVecOfOptionStdPrimitiveI32AsNullableArrayOfNullableInt4,
    pub column_a33c4b0f_d62e_46e6_b4c5_1090ae53d13e: postgresql_crud::postgresql_type::StdPrimitiveI64AsNotNullInt8,
    pub column_9696655c_7fa7_41fe_9cbc_02c30b991db5: postgresql_crud::postgresql_type::VecOfStdPrimitiveI64AsNotNullArrayOfNotNullInt8,
    pub column_43a62283_f7d7_4f18_91f9_12b78795df52: postgresql_crud::postgresql_type::VecOfOptionStdPrimitiveI64AsNotNullArrayOfNullableInt8,
    pub column_3912a925_2cb5_44b6_9f4f_3f5f3d9d8cab: postgresql_crud::postgresql_type::OptionStdPrimitiveI64AsNullableInt8,
    pub column_f62b938c_666b_469d_b9c0_6703345521fd: postgresql_crud::postgresql_type::OptionVecOfStdPrimitiveI64AsNullableArrayOfNotNullInt8,
    pub column_532279ac_02de_40df_a4f1_bed1157375b9: postgresql_crud::postgresql_type::OptionVecOfOptionStdPrimitiveI64AsNullableArrayOfNullableInt8,
    pub column_318b2adf_ae49_4850_bfb4_f54a15523e34: postgresql_crud::postgresql_type::StdPrimitiveF32AsNotNullFloat4,
    pub column_1d3e3980_c5c8_42b9_b2e4_4472ef66bcd9: postgresql_crud::postgresql_type::VecOfStdPrimitiveF32AsNotNullArrayOfNotNullFloat4,
    pub column_b5327cef_de14_4364_94c5_6434db3823ac: postgresql_crud::postgresql_type::VecOfOptionStdPrimitiveF32AsNotNullArrayOfNullableFloat4,
    pub column_2249533e_7747_4243_9345_c192c3b42843: postgresql_crud::postgresql_type::OptionStdPrimitiveF32AsNullableFloat4,
    pub column_e585b63c_f89d_4b0c_87ef_d0ff99e412f0: postgresql_crud::postgresql_type::OptionVecOfStdPrimitiveF32AsNullableArrayOfNotNullFloat4,
    pub column_ef13f8c4_c5c4_4317_91f6_6e40ffcb4402: postgresql_crud::postgresql_type::OptionVecOfOptionStdPrimitiveF32AsNullableArrayOfNullableFloat4,
    pub column_ba6283a1_7078_45ce_b1d9_fc8392eecdad: postgresql_crud::postgresql_type::StdPrimitiveF64AsNotNullFloat8,
    pub column_17ccb843_9921_42a1_8f8f_e22d605f77ea: postgresql_crud::postgresql_type::VecOfStdPrimitiveF64AsNotNullArrayOfNotNullFloat8,
    pub column_f6240262_2085_42d4_a738_4b60f8fef774: postgresql_crud::postgresql_type::VecOfOptionStdPrimitiveF64AsNotNullArrayOfNullableFloat8,
    pub column_9d7e82ee_d4f1_4fe7_874b_ea223d0cdf0d: postgresql_crud::postgresql_type::OptionStdPrimitiveF64AsNullableFloat8,
    pub column_ddc6bcba_7551_4de1_a2b9_2f273f5d4eaa: postgresql_crud::postgresql_type::OptionVecOfStdPrimitiveF64AsNullableArrayOfNotNullFloat8,
    pub column_6ff66024_7b99_44be_b0c0_48852dcffae0: postgresql_crud::postgresql_type::OptionVecOfOptionStdPrimitiveF64AsNullableArrayOfNullableFloat8,
    pub column_4caf293a_d0a3_4100_a872_b3c3caa56abd: postgresql_crud::postgresql_type::SqlxPostgresTypesPgMoneyAsNotNullMoney,
    pub column_3bd09bc3_61b6_46c5_beac_8818383b5a90: postgresql_crud::postgresql_type::VecOfSqlxPostgresTypesPgMoneyAsNotNullArrayOfNotNullMoney,
    pub column_e7fcf5ee_5496_4627_a595_731c8301788b: postgresql_crud::postgresql_type::VecOfOptionSqlxPostgresTypesPgMoneyAsNotNullArrayOfNullableMoney,
    pub column_dd9664ea_7c7b_449c_9872_fe158ba7788b: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgMoneyAsNullableMoney,
    pub column_6cde37cf_9083_4e94_b7f7_9ed9b820695a: postgresql_crud::postgresql_type::OptionVecOfSqlxPostgresTypesPgMoneyAsNullableArrayOfNotNullMoney,
    pub column_3529843d_3025_412b_bbe1_7ed50754c527: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxPostgresTypesPgMoneyAsNullableArrayOfNullableMoney,
    pub column_301c7759_0def_4f56_8010_aaddfd019bb0: postgresql_crud::postgresql_type::SqlxTypesDecimalAsNotNullNumeric,
    pub column_8492a4f1_03c6_4260_b3c2_fade0ed88afd: postgresql_crud::postgresql_type::VecOfSqlxTypesDecimalAsNotNullArrayOfNotNullNumeric,
    pub column_fcf02cb6_25ac_43a0_96d1_c68604ad29c4: postgresql_crud::postgresql_type::VecOfOptionSqlxTypesDecimalAsNotNullArrayOfNullableNumeric,
    pub column_042cfb88_a016_420f_959a_449653c8c86c: postgresql_crud::postgresql_type::OptionSqlxTypesDecimalAsNullableNumeric,
    pub column_b523f0a0_ac02_417f_9ede_cd8dbccc1d65: postgresql_crud::postgresql_type::OptionVecOfSqlxTypesDecimalAsNullableArrayOfNotNullNumeric,
    pub column_11e6ec77_92bf_4351_a3a6_dd62bd873719: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxTypesDecimalAsNullableArrayOfNullableNumeric,
    pub column_c68c7a37_ffe1_4ec6_9c47_0001711a0f29: postgresql_crud::postgresql_type::SqlxTypesBigDecimalAsNotNullNumeric,
    pub column_5a4e30b4_ccb4_4486_95c4_d633b6b58dfd: postgresql_crud::postgresql_type::VecOfSqlxTypesBigDecimalAsNotNullArrayOfNotNullNumeric,
    pub column_85048da2_b21a_467b_8769_f84f18215ee2: postgresql_crud::postgresql_type::VecOfOptionSqlxTypesBigDecimalAsNotNullArrayOfNullableNumeric,
    pub column_509437f8_a613_4469_980c_d64659a5a3f7: postgresql_crud::postgresql_type::OptionSqlxTypesBigDecimalAsNullableNumeric,
    pub column_503f5b7c_0487_43ea_b85b_83ee825d2599: postgresql_crud::postgresql_type::OptionVecOfSqlxTypesBigDecimalAsNullableArrayOfNotNullNumeric,
    pub column_89b3c447_3a08_45d3_8e1c_c5f4bde1a17e: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxTypesBigDecimalAsNullableArrayOfNullableNumeric,
    pub column_1eaa0af5_b1e3_4aad_ac6f_70e9a1c1f2ea: postgresql_crud::postgresql_type::StdPrimitiveBoolAsNotNullBool,
    //WORKS BEFORE
    pub column_d0c48627_d840_427a_a1c2_cadfd7a6e1ec: postgresql_crud::postgresql_type::VecOfStdPrimitiveBoolAsNotNullArrayOfNotNullBool,
    pub column_6c9af607_01fe_473d_912c_c7b68280c76a: postgresql_crud::postgresql_type::VecOfOptionStdPrimitiveBoolAsNotNullArrayOfNullableBool,
    pub column_9b08fc37_f608_4449_ad5c_5bf6c28441d1: postgresql_crud::postgresql_type::OptionStdPrimitiveBoolAsNullableBool,
    pub column_57a31692_838c_4c31_8d1d_e3c2c3f5afb7: postgresql_crud::postgresql_type::OptionVecOfStdPrimitiveBoolAsNullableArrayOfNotNullBool,
    pub column_0b31fdee_8a3e_42a6_8654_ad9cd89e9de0: postgresql_crud::postgresql_type::OptionVecOfOptionStdPrimitiveBoolAsNullableArrayOfNullableBool,
    pub column_bd0e3125_cb0d_40f8_9fb1_c9eeb7f624be: postgresql_crud::postgresql_type::StdStringStringAsNotNullText,
    pub column_6373142f_5f82_4d92_b0a6_8fec9d0dc89b: postgresql_crud::postgresql_type::VecOfStdStringStringAsNotNullArrayOfNotNullText,
    pub column_3e26c4f8_c334_4615_a6d9_cb08b341ab69: postgresql_crud::postgresql_type::VecOfOptionStdStringStringAsNotNullArrayOfNullableText,
    pub column_f00f157a_29a9_4e29_9e29_435bfe96f299: postgresql_crud::postgresql_type::OptionStdStringStringAsNullableText,
    pub column_96935805_493d_48c7_b978_401ea56dee81: postgresql_crud::postgresql_type::OptionVecOfStdStringStringAsNullableArrayOfNotNullText,
    pub column_64ac3c54_95f9_4672_ba43_74323004dda7: postgresql_crud::postgresql_type::OptionVecOfOptionStdStringStringAsNullableArrayOfNullableText,
    pub column_c23d26e1_86be_4041_b1c6_5ccd60810897: postgresql_crud::postgresql_type::StdVecVecStdPrimitiveU8AsNotNullBytea,
    pub column_efeb2dbc_7d69_43b4_9ddb_4ae4daef9621: postgresql_crud::postgresql_type::VecOfStdVecVecStdPrimitiveU8AsNotNullArrayOfNotNullBytea,
    pub column_f0b683c5_a7e7_4202_a57d_df81650247cc: postgresql_crud::postgresql_type::VecOfOptionStdVecVecStdPrimitiveU8AsNotNullArrayOfNullableBytea,
    pub column_59c9f3f8_9a73_4bf0_bbf1_2f3d285c94f7: postgresql_crud::postgresql_type::OptionStdVecVecStdPrimitiveU8AsNullableBytea,
    pub column_796fa545_6e01_4b91_9651_1fd6de2d60a8: postgresql_crud::postgresql_type::OptionVecOfStdVecVecStdPrimitiveU8AsNullableArrayOfNotNullBytea,
    pub column_d76598a0_d85b_4567_9e0c_edc8571c25a4: postgresql_crud::postgresql_type::OptionVecOfOptionStdVecVecStdPrimitiveU8AsNullableArrayOfNullableBytea,
    pub column_8d731285_1ca3_4580_bf14_284f911c3655: postgresql_crud::postgresql_type::SqlxTypesChronoNaiveTimeAsNotNullTime,
    pub column_b997bbe0_fd88_47f8_9aa4_e8a12528ea41: postgresql_crud::postgresql_type::VecOfSqlxTypesChronoNaiveTimeAsNotNullArrayOfNotNullTime,
    pub column_e825ae38_f0ea_4644_ae0f_1d3601eeea09: postgresql_crud::postgresql_type::VecOfOptionSqlxTypesChronoNaiveTimeAsNotNullArrayOfNullableTime,
    pub column_bf8b3f56_08b8_4a7c_8ad9_be88dd69761b: postgresql_crud::postgresql_type::OptionSqlxTypesChronoNaiveTimeAsNullableTime,
    pub column_3254c02e_15fd_4168_8308_bb6c8045fc2e: postgresql_crud::postgresql_type::OptionVecOfSqlxTypesChronoNaiveTimeAsNullableArrayOfNotNullTime,
    pub column_e910c5a0_8e9c_4efd_82b3_a9b120b71485: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxTypesChronoNaiveTimeAsNullableArrayOfNullableTime,
    pub column_9f8ad013_ccfb_4f65_a927_09e4ed8712e1: postgresql_crud::postgresql_type::SqlxTypesTimeTimeAsNotNullTime,
    pub column_5d16dcbc_3547_4c45_bfb2_433a01a6d90a: postgresql_crud::postgresql_type::VecOfSqlxTypesTimeTimeAsNotNullArrayOfNotNullTime,
    pub column_3359616b_16c8_486b_a9fa_c37c7dd75715: postgresql_crud::postgresql_type::VecOfOptionSqlxTypesTimeTimeAsNotNullArrayOfNullableTime,
    pub column_4889223a_5e92_45de_9b07_9870b8bbc21c: postgresql_crud::postgresql_type::OptionSqlxTypesTimeTimeAsNullableTime,
    pub column_8c511bf1_2994_41c6_bdfe_981d46eddba4: postgresql_crud::postgresql_type::OptionVecOfSqlxTypesTimeTimeAsNullableArrayOfNotNullTime,
    pub column_860a6846_c18d_467b_8656_ecf278c33624: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxTypesTimeTimeAsNullableArrayOfNullableTime,
    pub column_228c14b7_c808_455c_83fc_7cc5772255f2: postgresql_crud::postgresql_type::SqlxPostgresTypesPgIntervalAsNotNullInterval,
    pub column_cabfc631_e7ae_495f_a958_dfe1affe7540: postgresql_crud::postgresql_type::VecOfSqlxPostgresTypesPgIntervalAsNotNullArrayOfNotNullInterval,
    pub column_1749b695_0939_4f56_a918_fdb3b6f7c8a1: postgresql_crud::postgresql_type::VecOfOptionSqlxPostgresTypesPgIntervalAsNotNullArrayOfNullableInterval,
    pub column_d6b9e298_2ffa_4d08_8370_449ec95fa12b: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgIntervalAsNullableInterval,
    pub column_a5238a8b_d217_413f_bdc8_ad30554551e8: postgresql_crud::postgresql_type::OptionVecOfSqlxPostgresTypesPgIntervalAsNullableArrayOfNotNullInterval,
    pub column_8c60a89d_c3ad_4a4c_a615_26a32da0e74e: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxPostgresTypesPgIntervalAsNullableArrayOfNullableInterval,
    pub column_3ebe5b74_5000_43ae_9bfb_59d89002543b: postgresql_crud::postgresql_type::SqlxTypesTimeDateAsNotNullDate,
    pub column_743204f7_5492_47f9_ae95_c7dc2ccb550c: postgresql_crud::postgresql_type::VecOfSqlxTypesTimeDateAsNotNullArrayOfNotNullDate,
    pub column_573083ec_381e_44b2_a8c9_8baf35d88e54: postgresql_crud::postgresql_type::VecOfOptionSqlxTypesTimeDateAsNotNullArrayOfNullableDate,
    pub column_8ac21f08_8c05_4745_99b3_8c888d6eca18: postgresql_crud::postgresql_type::OptionSqlxTypesTimeDateAsNullableDate,
    pub column_091863b8_625b_49f6_bf4d_79bb447de27b: postgresql_crud::postgresql_type::OptionVecOfSqlxTypesTimeDateAsNullableArrayOfNotNullDate,
    pub column_e0f43b69_bbd8_4d6d_a572_d877d0d61e61: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxTypesTimeDateAsNullableArrayOfNullableDate,
    pub column_ea4f9c39_c2b6_41e2_9e18_c5d7f28e3f2a: postgresql_crud::postgresql_type::SqlxTypesChronoNaiveDateAsNotNullDate,
    pub column_dc632301_7e45_432c_a331_7d931ad4f506: postgresql_crud::postgresql_type::VecOfSqlxTypesChronoNaiveDateAsNotNullArrayOfNotNullDate,
    pub column_b1fc017d_ffa0_45a9_a25a_595848e7bb0b: postgresql_crud::postgresql_type::VecOfOptionSqlxTypesChronoNaiveDateAsNotNullArrayOfNullableDate,
    pub column_f875ad22_a769_4279_b9f1_576c3eb2d0aa: postgresql_crud::postgresql_type::OptionSqlxTypesChronoNaiveDateAsNullableDate,
    pub column_e1b0129e_40be_46d7_9d9b_b28bc6723dc1: postgresql_crud::postgresql_type::OptionVecOfSqlxTypesChronoNaiveDateAsNullableArrayOfNotNullDate,
    pub column_54a0953d_d312_47f5_b305_245707d8b205: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxTypesChronoNaiveDateAsNullableArrayOfNullableDate,
    pub column_77f8fa39_86c4_4e51_9e0e_2ce59a96d02b: postgresql_crud::postgresql_type::SqlxTypesChronoNaiveDateTimeAsNotNullTimestamp,
    pub column_89778f25_aec1_4880_9e9e_8e3db79c4f77: postgresql_crud::postgresql_type::VecOfSqlxTypesChronoNaiveDateTimeAsNotNullArrayOfNotNullTimestamp,
    pub column_c3181c76_e39e_462c_b828_21942b3a6828: postgresql_crud::postgresql_type::VecOfOptionSqlxTypesChronoNaiveDateTimeAsNotNullArrayOfNullableTimestamp,
    pub column_1a156cdf_00fe_4cd0_b6c7_bfddb03b9a88: postgresql_crud::postgresql_type::OptionSqlxTypesChronoNaiveDateTimeAsNullableTimestamp,
    pub column_770194b1_ebca_4e31_94e9_6de7f98c6f58: postgresql_crud::postgresql_type::OptionVecOfSqlxTypesChronoNaiveDateTimeAsNullableArrayOfNotNullTimestamp,
    pub column_e623a4a2_80df_4363_ac7e_281819d9b7ee: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxTypesChronoNaiveDateTimeAsNullableArrayOfNullableTimestamp,
    pub column_02610bb9_93ee_4e23_949e_1cc0b3a136c0: postgresql_crud::postgresql_type::SqlxTypesTimePrimitiveDateTimeAsNotNullTimestamp,
    pub column_1b965abc_c96a_4d91_94f8_08249d58793c: postgresql_crud::postgresql_type::VecOfSqlxTypesTimePrimitiveDateTimeAsNotNullArrayOfNotNullTimestamp,
    pub column_02b7c5b5_be8a_4788_ba41_765b45140ec3: postgresql_crud::postgresql_type::VecOfOptionSqlxTypesTimePrimitiveDateTimeAsNotNullArrayOfNullableTimestamp,
    pub column_6deee79d_f516_4820_8c63_65087b86ed90: postgresql_crud::postgresql_type::OptionSqlxTypesTimePrimitiveDateTimeAsNullableTimestamp,
    pub column_5c78b9ec_2668_463c_a75e_12ff2e3513b8: postgresql_crud::postgresql_type::OptionVecOfSqlxTypesTimePrimitiveDateTimeAsNullableArrayOfNotNullTimestamp,
    pub column_de3e29f5_0550_4e91_9c38_6e7d47a75e47: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxTypesTimePrimitiveDateTimeAsNullableArrayOfNullableTimestamp,
    pub column_f6c001a8_b43e_497b_ae6d_c2cc815baa69: postgresql_crud::postgresql_type::SqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNotNullTimestampTz,
    pub column_d44ab803_3352_439e_b4eb_b630d8668c11: postgresql_crud::postgresql_type::VecOfSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNotNullArrayOfNotNullTimestampTz,
    pub column_287c3e20_aaa8_4ae5_bea4_6fdbcc3391fa: postgresql_crud::postgresql_type::VecOfOptionSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNotNullArrayOfNullableTimestampTz,
    pub column_2d33682b_09ff_4e13_b310_5d659c5de055: postgresql_crud::postgresql_type::OptionSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNullableTimestampTz,
    pub column_5528b07a_dd87_4aec_82e4_83ac7b93dc25: postgresql_crud::postgresql_type::OptionVecOfSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNullableArrayOfNotNullTimestampTz,
    pub column_2573531c_713e_4e11_8fa9_7742fa043d0e: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNullableArrayOfNullableTimestampTz,
    pub column_da5fb61b_0174_4486_9392_8cd5c381fad1: postgresql_crud::postgresql_type::SqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNotNullTimestampTz,
    pub column_dfb12e62_1558_4dc0_ba1f_57e75ff2e57d: postgresql_crud::postgresql_type::VecOfSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNotNullArrayOfNotNullTimestampTz,
    pub column_2dae72be_bdff_47a9_892d_026c377dd585: postgresql_crud::postgresql_type::VecOfOptionSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNotNullArrayOfNullableTimestampTz,
    pub column_ad4a0fdc_7e78_496e_8b8e_964930ad401a: postgresql_crud::postgresql_type::OptionSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNullableTimestampTz,
    pub column_a2688962_8c9d_400d_9e8b_d416f2e83a6a: postgresql_crud::postgresql_type::OptionVecOfSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNullableArrayOfNotNullTimestampTz,
    pub column_9b601f6c_5ca5_47f0_868b_e862fa719909: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNullableArrayOfNullableTimestampTz,
    pub column_6c171e71_f848_440b_9056_a335fe347634: postgresql_crud::postgresql_type::SqlxTypesUuidUuidAsNotNullUuidInitializedByClient,
    pub column_7e906100_dee1_425e_8e29_5029d9f524ed: postgresql_crud::postgresql_type::VecOfSqlxTypesUuidUuidAsNotNullArrayOfNotNullUuidInitializedByClient,
    pub column_7419c7dd_55f9_46de_bf9b_945700ad6ceb: postgresql_crud::postgresql_type::VecOfOptionSqlxTypesUuidUuidAsNotNullArrayOfNullableUuidInitializedByClient,
    pub column_d3402b09_337a_4d21_a4c2_bc9e21ed35dc: postgresql_crud::postgresql_type::OptionSqlxTypesUuidUuidAsNullableUuidInitializedByClient,
    pub column_29480850_eb48_4eda_9956_8ec01d5bd2b7: postgresql_crud::postgresql_type::OptionVecOfSqlxTypesUuidUuidAsNullableArrayOfNotNullUuidInitializedByClient,
    pub column_844bafad_30a8_4667_b36b_a775d1cd2cae: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxTypesUuidUuidAsNullableArrayOfNullableUuidInitializedByClient,
    pub column_388f2022_492b_443b_b939_245e75c74989: postgresql_crud::postgresql_type::SqlxTypesMacAddressMacAddressAsNotNullMacAddr,
    pub column_51076718_323e_4ee9_b92f_b6151c904f4f: postgresql_crud::postgresql_type::VecOfSqlxTypesMacAddressMacAddressAsNotNullArrayOfNotNullMacAddr,
    pub column_14466cd3_5b4d_4c1f_bc21_7b85054a3d75: postgresql_crud::postgresql_type::VecOfOptionSqlxTypesMacAddressMacAddressAsNotNullArrayOfNullableMacAddr,
    pub column_fbc43437_8d0c_4084_9052_2f6b8527aa7d: postgresql_crud::postgresql_type::OptionSqlxTypesMacAddressMacAddressAsNullableMacAddr,
    pub column_8442c438_59bc_409c_bc77_0e7086fc23bf: postgresql_crud::postgresql_type::OptionVecOfSqlxTypesMacAddressMacAddressAsNullableArrayOfNotNullMacAddr,
    pub column_2020ecaa_6158_4d5f_bdfe_c0311bb9add8: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxTypesMacAddressMacAddressAsNullableArrayOfNullableMacAddr,
    pub column_76021775_28eb_4738_a00b_6610221a4d2a: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeStdPrimitiveI32AsNotNullInt4Range,
    pub column_1b392072_9ed9_453c_a320_f114fb1bc70a: postgresql_crud::postgresql_type::VecOfSqlxPostgresTypesPgRangeStdPrimitiveI32AsNotNullArrayOfNotNullInt4Range,
    pub column_7cd9b64b_ea0a_4ebe_91c1_f9a29dabc547: postgresql_crud::postgresql_type::VecOfOptionSqlxPostgresTypesPgRangeStdPrimitiveI32AsNotNullArrayOfNullableInt4Range,
    pub column_e93f5d58_d53b_4c5e_a888_0e83ba74cad6: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeStdPrimitiveI32AsNullableInt4Range,
    pub column_e070b58a_ecc3_4230_bf4e_e7b874b825b2: postgresql_crud::postgresql_type::OptionVecOfSqlxPostgresTypesPgRangeStdPrimitiveI32AsNullableArrayOfNotNullInt4Range,
    pub column_c239320e_20d3_416a_bd75_6262ece8f034: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxPostgresTypesPgRangeStdPrimitiveI32AsNullableArrayOfNullableInt4Range,
    pub column_26c76a9e_d522_451a_a2c3_b2a9b026b9ee: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeStdPrimitiveI64AsNotNullInt8Range,
    pub column_ec9cc1d5_c22b_4f47_91c1_aadead0ecccd: postgresql_crud::postgresql_type::VecOfSqlxPostgresTypesPgRangeStdPrimitiveI64AsNotNullArrayOfNotNullInt8Range,
    pub column_a97c410b_8c9d_4675_9392_b0a2b5c5e8e8: postgresql_crud::postgresql_type::VecOfOptionSqlxPostgresTypesPgRangeStdPrimitiveI64AsNotNullArrayOfNullableInt8Range,
    pub column_27da6e27_bc7d_4d5f_b010_bd54016a7402: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeStdPrimitiveI64AsNullableInt8Range,
    pub column_d3e4be35_1be3_469b_9608_293a1dba5f8c: postgresql_crud::postgresql_type::OptionVecOfSqlxPostgresTypesPgRangeStdPrimitiveI64AsNullableArrayOfNotNullInt8Range,
    pub column_057812f7_9a4e_4f50_a2b3_3cc950f4f2bd: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxPostgresTypesPgRangeStdPrimitiveI64AsNullableArrayOfNullableInt8Range,
    pub column_1faafaaa_0fbb_4089_8ee7_fee81f31ae98: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesDecimalAsNotNullNumRange,
    pub column_159923f8_25a5_431b_844d_cbd532547530: postgresql_crud::postgresql_type::VecOfSqlxPostgresTypesPgRangeSqlxTypesDecimalAsNotNullArrayOfNotNullNumRange,
    pub column_b1f14689_93ce_4968_9d0a_f694b8d19da7: postgresql_crud::postgresql_type::VecOfOptionSqlxPostgresTypesPgRangeSqlxTypesDecimalAsNotNullArrayOfNullableNumRange,
    pub column_f9576876_6035_4425_a6bf_9a67d555814a: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesDecimalAsNullableNumRange,
    pub column_5398cdc4_cef7_48e7_a9ed_d0d0dd6a49a0: postgresql_crud::postgresql_type::OptionVecOfSqlxPostgresTypesPgRangeSqlxTypesDecimalAsNullableArrayOfNotNullNumRange,
    pub column_e1ad22f9_25aa_410a_8110_27028bf45d4a: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxPostgresTypesPgRangeSqlxTypesDecimalAsNullableArrayOfNullableNumRange,
    pub column_94b6a2e1_6c7e_4ea9_89f3_cc07c99fc5c7: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesBigDecimalAsNotNullNumRange,
    pub column_66c7da82_430a_403e_8f26_9b59e1a5f0f5: postgresql_crud::postgresql_type::VecOfSqlxPostgresTypesPgRangeSqlxTypesBigDecimalAsNotNullArrayOfNotNullNumRange,
    pub column_32a7eac4_6a5a_4c57_ac0b_15d9207f6462: postgresql_crud::postgresql_type::VecOfOptionSqlxPostgresTypesPgRangeSqlxTypesBigDecimalAsNotNullArrayOfNullableNumRange,
    pub column_9452c627_2dfa_421e_9302_84911be6141a: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesBigDecimalAsNullableNumRange,
    pub column_26a8f864_741b_4adb_a11c_707f4790b0c6: postgresql_crud::postgresql_type::OptionVecOfSqlxPostgresTypesPgRangeSqlxTypesBigDecimalAsNullableArrayOfNotNullNumRange,
    pub column_271c5d5d_999a_4d6f_81e3_f1c5af69cfed: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxPostgresTypesPgRangeSqlxTypesBigDecimalAsNullableArrayOfNullableNumRange,
    pub column_b08ecb79_69ef_47c9_ae7b_9f0e5beefcb7: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesTimeDateAsNotNullDateRange,
    pub column_fdd65fa4_eb02_4b2b_9c84_1b35368e8a4c: postgresql_crud::postgresql_type::VecOfSqlxPostgresTypesPgRangeSqlxTypesTimeDateAsNotNullArrayOfNotNullDateRange,
    pub column_8d63682e_37ff_4dbb_862f_4cd2f444690a: postgresql_crud::postgresql_type::VecOfOptionSqlxPostgresTypesPgRangeSqlxTypesTimeDateAsNotNullArrayOfNullableDateRange,
    pub column_11223d3e_fefc_47c6_8cc3_a0bdcc2b2bca: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesTimeDateAsNullableDateRange,
    pub column_6db7eddb_e4b4_4334_8532_570c5f08e222: postgresql_crud::postgresql_type::OptionVecOfSqlxPostgresTypesPgRangeSqlxTypesTimeDateAsNullableArrayOfNotNullDateRange,
    pub column_d438ad25_1e68_4b3b_bd6d_963ca36bae79: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxPostgresTypesPgRangeSqlxTypesTimeDateAsNullableArrayOfNullableDateRange,
    pub column_6cce6844_b789_4173_b1f8_d63472d19637: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateAsNotNullDateRange,
    pub column_373940a5_ecc0_48a4_abd7_b83eb44de212: postgresql_crud::postgresql_type::VecOfSqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateAsNotNullArrayOfNotNullDateRange,
    pub column_8970dd80_5c6a_42ba_9567_710f7f6cb3e5: postgresql_crud::postgresql_type::VecOfOptionSqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateAsNotNullArrayOfNullableDateRange,
    pub column_2eb3e410_0691_4193_aaea_ac7a6805cccc: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateAsNullableDateRange,
    pub column_a6f4728c_809c_4dd4_8606_a210983f1532: postgresql_crud::postgresql_type::OptionVecOfSqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateAsNullableArrayOfNotNullDateRange,
    pub column_014ad4fa_563c_428e_9c04_34726c083bea: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateAsNullableArrayOfNullableDateRange,
    pub column_09f87a29_1502_40b1_b706_68e21111b633: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNotNullTimestampRange,
    pub column_18c7d811_628f_4a99_bf30_e9be3e270909: postgresql_crud::postgresql_type::VecOfSqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNotNullArrayOfNotNullTimestampRange,
    pub column_35f2976a_5ef9_4d23_af01_1088f05ace7e: postgresql_crud::postgresql_type::VecOfOptionSqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNotNullArrayOfNullableTimestampRange,
    pub column_66235547_c38b_4815_ac93_411059f31239: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNullableTimestampRange,
    pub column_918b8a8e_0c76_4a5e_9709_3848a3f212fb: postgresql_crud::postgresql_type::OptionVecOfSqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNullableArrayOfNotNullTimestampRange,
    // pub column_d83422dc_7fd3_469c_90a2_863e48631c92: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNullableArrayOfNullableTimestampRange,
    // pub column_09edbee2_8538_462b_94a6_9d00bdc84973: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesTimePrimitiveDateTimeAsNotNullTimestampRange,
    // pub column_ca5a48a9_1d9b_47ad_a615_856aecf0afeb: postgresql_crud::postgresql_type::VecOfSqlxPostgresTypesPgRangeSqlxTypesTimePrimitiveDateTimeAsNotNullArrayOfNotNullTimestampRange,
    // pub column_758c5c57_3617_47db_aa29_c84837669eef: postgresql_crud::postgresql_type::VecOfOptionSqlxPostgresTypesPgRangeSqlxTypesTimePrimitiveDateTimeAsNotNullArrayOfNullableTimestampRange,
    // pub column_10f8435a_edfa_4f25_9e1f_a57054650161: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesTimePrimitiveDateTimeAsNullableTimestampRange,
    // pub column_7ef51028_1fef_4b23_aef3_0fbd8b8ef83c: postgresql_crud::postgresql_type::OptionVecOfSqlxPostgresTypesPgRangeSqlxTypesTimePrimitiveDateTimeAsNullableArrayOfNotNullTimestampRange,
    // pub column_248af663_4054_4647_a537_40311daf1837: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxPostgresTypesPgRangeSqlxTypesTimePrimitiveDateTimeAsNullableArrayOfNullableTimestampRange,
    // pub column_32fd8d94_3593_43bf_8b40_150159569d32: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNotNullTimestampTzRange,
    // pub column_83853dd8_e04d_4619_9119_50f4322cee60: postgresql_crud::postgresql_type::VecOfSqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNotNullArrayOfNotNullTimestampTzRange,
    // pub column_f8624b83_b2da_411e_830d_a984d3d4fa89: postgresql_crud::postgresql_type::VecOfOptionSqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNotNullArrayOfNullableTimestampTzRange,
    // pub column_ec01de9c_74ef_449f_9b12_e993c449ba9f: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNullableTimestampTzRange,
    // pub column_a4f7848c_e183_416d_a159_82ab804fa91d: postgresql_crud::postgresql_type::OptionVecOfSqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNullableArrayOfNotNullTimestampTzRange,
    // pub column_28514827_2565_4a84_97ac_8a744d6653d9: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNullableArrayOfNullableTimestampTzRange,
    // pub column_563cf8fb_0e6b_4187_9ffb_9108f26268db: postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNotNullTimestampTzRange,
    // pub column_fe38890b_2e29_4cc0_9d92_be6e27719668: postgresql_crud::postgresql_type::VecOfSqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNotNullArrayOfNotNullTimestampTzRange,
    // pub column_aaec982a_8c1d_4dc9_a3e0_c02b2caf7f31: postgresql_crud::postgresql_type::VecOfOptionSqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNotNullArrayOfNullableTimestampTzRange,
    // pub column_7b3e9498_119a_48fd_ac02_8dfca28f406c: postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNullableTimestampTzRange,
    // pub column_d8c764c9_3b49_4db8_98c0_782e082ce122: postgresql_crud::postgresql_type::OptionVecOfSqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNullableArrayOfNotNullTimestampTzRange,
    // pub column_dc4164e0_8826_4cf8_bae7_aee4ca27a9c0: postgresql_crud::postgresql_type::OptionVecOfOptionSqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNullableArrayOfNullableTimestampTzRange,
    // pub column_2759bb83_53a6_40ed_8734_e9043f78023d: postgresql_crud::postgresql_type::StdPrimitiveI16AsNotNullSmallSerialInitializedByPostgresql,
    // pub column_33f269d5_7829_4c6f_84d5_f7e1a3904abc: postgresql_crud::postgresql_type::StdPrimitiveI32AsNotNullSerialInitializedByPostgresql,
    #[generate_postgresql_crud_primary_key]
    pub column_fd87e14c_7763_41f1_8b4e_09d06ae2a01b: postgresql_crud::postgresql_type::StdPrimitiveI64AsNotNullBigSerialInitializedByPostgresql,
    pub column_22b44ace_f0eb_4efc_886e_d381322ecf19: postgresql_crud::postgresql_type::SqlxTypesUuidUuidAsNotNullUuidV4InitializedByPostgresql,
}
//todo enum tree support
//todo generate wrapper type for all possible json type
#[derive(Debug, postgresql_crud::GeneratePostgresqlJsonType)]
pub struct Animal {
    // pub id: postgresql_crud::postgresql_json_type::Uuid,//todo check length of uuid = 36 // must not be updatable, only readable. postgresql must create it than return object with new ids

    // pub std_vec_vec_uuid_uuid: postgresql_crud::postgresql_json_type::StdVecVecUuidUuid,
    // pub std_vec_vec_std_vec_vec_uuid_uuid: postgresql_crud::postgresql_json_type::StdVecVecStdVecVecUuidUuid,
    //todo check field max length in postgresql
    pub std_primitive_i8: postgresql_crud::postgresql_json_type::StdPrimitiveI8,
    // pub std_primitive_i16: postgresql_crud::postgresql_json_type::StdPrimitiveI16,
    // pub std_primitive_i32: postgresql_crud::postgresql_json_type::StdPrimitiveI32,
    // pub std_primitive_i64: postgresql_crud::postgresql_json_type::StdPrimitiveI64,
    // pub std_primitive_u8: postgresql_crud::postgresql_json_type::StdPrimitiveU8,
    // pub std_primitive_u16: postgresql_crud::postgresql_json_type::StdPrimitiveU16,
    // pub std_primitive_u32: postgresql_crud::postgresql_json_type::StdPrimitiveU32,
    // pub std_primitive_u64: postgresql_crud::postgresql_json_type::StdPrimitiveU64,
    // pub std_primitive_f32: postgresql_crud::postgresql_json_type::StdPrimitiveF32,
    // pub std_primitive_f64: postgresql_crud::postgresql_json_type::StdPrimitiveF64,
    // pub std_primitive_bool: postgresql_crud::postgresql_json_type::StdPrimitiveBool,
    // pub std_string_string: postgresql_crud::postgresql_json_type::StdStringString,
    // pub std_option_option_std_primitive_i8: postgresql_crud::postgresql_json_type::StdOptionOptionStdPrimitiveI8,
    // pub std_option_option_std_primitive_i16: postgresql_crud::postgresql_json_type::StdOptionOptionStdPrimitiveI16,
    // pub std_option_option_std_primitive_i32: postgresql_crud::postgresql_json_type::StdOptionOptionStdPrimitiveI32,
    // pub std_option_option_std_primitive_i64: postgresql_crud::postgresql_json_type::StdOptionOptionStdPrimitiveI64,
    // pub std_option_option_std_primitive_u8: postgresql_crud::postgresql_json_type::StdOptionOptionStdPrimitiveU8,
    // pub std_option_option_std_primitive_u16: postgresql_crud::postgresql_json_type::StdOptionOptionStdPrimitiveU16,
    // pub std_option_option_std_primitive_u32: postgresql_crud::postgresql_json_type::StdOptionOptionStdPrimitiveU32,
    // pub std_option_option_std_primitive_u64: postgresql_crud::postgresql_json_type::StdOptionOptionStdPrimitiveU64,
    // pub std_option_option_std_primitive_f32: postgresql_crud::postgresql_json_type::StdOptionOptionStdPrimitiveF32,
    // pub std_option_option_std_primitive_f64: postgresql_crud::postgresql_json_type::StdOptionOptionStdPrimitiveF64,
    // pub std_option_option_std_primitive_bool: postgresql_crud::postgresql_json_type::StdOptionOptionStdPrimitiveBool,
    // pub std_option_option_std_string_string: postgresql_crud::postgresql_json_type::StdOptionOptionStdStringString,
    // pub std_vec_vec_std_primitive_i8: postgresql_crud::postgresql_json_type::StdVecVecStdPrimitiveI8,
    // pub std_vec_vec_std_primitive_i16: postgresql_crud::postgresql_json_type::StdVecVecStdPrimitiveI16,
    // pub std_vec_vec_std_primitive_i32: postgresql_crud::postgresql_json_type::StdVecVecStdPrimitiveI32,
    // pub std_vec_vec_std_primitive_i64: postgresql_crud::postgresql_json_type::StdVecVecStdPrimitiveI64,
    // pub std_vec_vec_std_primitive_u8: postgresql_crud::postgresql_json_type::StdVecVecStdPrimitiveU8,
    // pub std_vec_vec_std_primitive_u16: postgresql_crud::postgresql_json_type::StdVecVecStdPrimitiveU16,
    // pub std_vec_vec_std_primitive_u32: postgresql_crud::postgresql_json_type::StdVecVecStdPrimitiveU32,
    // pub std_vec_vec_std_primitive_u64: postgresql_crud::postgresql_json_type::StdVecVecStdPrimitiveU64,
    // pub std_vec_vec_std_primitive_f32: postgresql_crud::postgresql_json_type::StdVecVecStdPrimitiveF32,
    // pub std_vec_vec_std_primitive_f64: postgresql_crud::postgresql_json_type::StdVecVecStdPrimitiveF64,
    // pub std_vec_vec_std_primitive_bool: postgresql_crud::postgresql_json_type::StdVecVecStdPrimitiveBool,
    // pub std_vec_vec_std_string_string: postgresql_crud::postgresql_json_type::StdVecVecStdStringString,
    // pub std_option_option_std_vec_vec_std_primitive_i8: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdPrimitiveI8,
    // pub std_option_option_std_vec_vec_std_primitive_i16: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdPrimitiveI16,
    // pub std_option_option_std_vec_vec_std_primitive_i32: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdPrimitiveI32,
    // pub std_option_option_std_vec_vec_std_primitive_i64: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdPrimitiveI64,
    // pub std_option_option_std_vec_vec_std_primitive_u8: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdPrimitiveU8,
    // pub std_option_option_std_vec_vec_std_primitive_u16: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdPrimitiveU16,
    // pub std_option_option_std_vec_vec_std_primitive_u32: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdPrimitiveU32,
    // pub std_option_option_std_vec_vec_std_primitive_u64: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdPrimitiveU64,
    // pub std_option_option_std_vec_vec_std_primitive_f32: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdPrimitiveF32,
    // pub std_option_option_std_vec_vec_std_primitive_f64: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdPrimitiveF64,
    // pub std_option_option_std_vec_vec_std_primitive_bool: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdPrimitiveBool,
    // pub std_option_option_std_vec_vec_std_string_string: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdStringString,
    // pub std_vec_vec_std_option_option_std_primitive_i8: postgresql_crud::postgresql_json_type::StdVecVecStdOptionOptionStdPrimitiveI8,
    // pub std_vec_vec_std_option_option_std_primitive_i16: postgresql_crud::postgresql_json_type::StdVecVecStdOptionOptionStdPrimitiveI16,
    // pub std_vec_vec_std_option_option_std_primitive_i32: postgresql_crud::postgresql_json_type::StdVecVecStdOptionOptionStdPrimitiveI32,
    // pub std_vec_vec_std_option_option_std_primitive_i64: postgresql_crud::postgresql_json_type::StdVecVecStdOptionOptionStdPrimitiveI64,
    // pub std_vec_vec_std_option_option_std_primitive_u8: postgresql_crud::postgresql_json_type::StdVecVecStdOptionOptionStdPrimitiveU8,
    // pub std_vec_vec_std_option_option_std_primitive_u16: postgresql_crud::postgresql_json_type::StdVecVecStdOptionOptionStdPrimitiveU16,
    // pub std_vec_vec_std_option_option_std_primitive_u32: postgresql_crud::postgresql_json_type::StdVecVecStdOptionOptionStdPrimitiveU32,
    // pub std_vec_vec_std_option_option_std_primitive_u64: postgresql_crud::postgresql_json_type::StdVecVecStdOptionOptionStdPrimitiveU64,
    // pub std_vec_vec_std_option_option_std_primitive_f32: postgresql_crud::postgresql_json_type::StdVecVecStdOptionOptionStdPrimitiveF32,
    // pub std_vec_vec_std_option_option_std_primitive_f64: postgresql_crud::postgresql_json_type::StdVecVecStdOptionOptionStdPrimitiveF64,
    // pub std_vec_vec_std_option_option_std_primitive_bool: postgresql_crud::postgresql_json_type::StdVecVecStdOptionOptionStdPrimitiveBool,
    // pub std_vec_vec_std_option_option_std_string_string: postgresql_crud::postgresql_json_type::StdVecVecStdOptionOptionStdStringString,
    // pub std_option_option_std_vec_vec_std_option_option_std_primitive_i8: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdOptionOptionStdPrimitiveI8,
    // pub std_option_option_std_vec_vec_std_option_option_std_primitive_i16: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdOptionOptionStdPrimitiveI16,
    // pub std_option_option_std_vec_vec_std_option_option_std_primitive_i32: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdOptionOptionStdPrimitiveI32,
    // pub std_option_option_std_vec_vec_std_option_option_std_primitive_i64: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdOptionOptionStdPrimitiveI64,
    // pub std_option_option_std_vec_vec_std_option_option_std_primitive_u8: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdOptionOptionStdPrimitiveU8,
    // pub std_option_option_std_vec_vec_std_option_option_std_primitive_u16: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdOptionOptionStdPrimitiveU16,
    // pub std_option_option_std_vec_vec_std_option_option_std_primitive_u32: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdOptionOptionStdPrimitiveU32,
    // pub std_option_option_std_vec_vec_std_option_option_std_primitive_u64: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdOptionOptionStdPrimitiveU64,
    // pub std_option_option_std_vec_vec_std_option_option_std_primitive_f32: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdOptionOptionStdPrimitiveF32,
    // pub std_option_option_std_vec_vec_std_option_option_std_primitive_f64: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdOptionOptionStdPrimitiveF64,
    // pub std_option_option_std_vec_vec_std_option_option_std_primitive_bool: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdOptionOptionStdPrimitiveBool,
    // pub std_option_option_std_vec_vec_std_option_option_std_string_string: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdOptionOptionStdStringString,

    // pub object_doggie: ObjectDoggie,
    // pub std_option_option_object: StdOptionOptionObjectDoggie,
    // pub std_vec_vec_object: StdVecVecObjectWithIdDoggie,
    // pub std_option_option_std_vec_vec_object: StdOptionOptionStdVecVecObjectWithIdDoggie,

    // pub std_vec_vec_object_with_id: StdVecVecObjectWithIdDoggie,
    // pub std_option_option_std_vec_vec_object_with_id: StdOptionOptionStdVecVecObjectWithIdDoggie
}
// /////////////////////////////////////////
// #[derive(
//     Debug,
//     Clone,
//     PartialEq,
//     Default,
//     serde::Serialize,
//     serde::Deserialize,
//     utoipa::ToSchema,
//     schemars::JsonSchema,
//     postgresql_crud::GeneratePostgresqlJsonType
// )] //user type must implement utoipa::ToSchema trait
// pub struct Doggie {
//     pub std_primitive_i8: postgresql_crud::postgresql_json_type::StdPrimitiveI8,
//     pub std_option_option_std_primitive_i8: postgresql_crud::postgresql_json_type::StdOptionOptionStdPrimitiveI8,
//     pub std_vec_vec_std_primitive_i8: postgresql_crud::postgresql_json_type::StdVecVecStdPrimitiveI8,
//     pub std_option_option_std_vec_vec_std_primitive_i8: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdPrimitiveI8,
//     pub std_vec_vec_std_option_option_std_primitive_i8: postgresql_crud::postgresql_json_type::StdVecVecStdOptionOptionStdPrimitiveI8,
//     pub std_option_option_std_vec_vec_std_option_option_std_primitive_i8: postgresql_crud::postgresql_json_type::StdOptionOptionStdVecVecStdOptionOptionStdPrimitiveI8,
// }
///////////////////////////////////////////////////
#[cfg(test)]
mod tests {
    #[test]
    fn test_size_of() {
        assert_eq!(std::mem::size_of::<crate::repositories_types::server::routes::api::example::Example>(), 0);
    }
}
//////////////////
// pub async fn create_table_if_not_exists(pool: &sqlx::Pool<sqlx::Postgres>) {
//     let create_extension_if_not_exists_pg_jsonschema_query_stringified = "create extension if not exists pg_jsonschema";
//     println!("{create_extension_if_not_exists_pg_jsonschema_query_stringified}");
//     let _ = sqlx::query(create_extension_if_not_exists_pg_jsonschema_query_stringified).execute(pool).await.unwrap();
//     let create_extension_if_not_exists_uuid_ossp_query_stringified = "create extension if not exists \"uuid-ossp\"";
//     println!("{create_extension_if_not_exists_uuid_ossp_query_stringified}");
//     let _ = sqlx::query(create_extension_if_not_exists_uuid_ossp_query_stringified).execute(pool).await.unwrap();
//     let create_table_if_not_exists_query_stringified = format!(
//         // "create table if not exists example ({},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{})",
//          "create table if not exists example ({},{},{},{})",
//          <postgresql_crud::postgresql_type::VecOfStdPrimitiveI16AsNotNullArrayOfNotNullInt2 as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"vec", false),

//         <postgresql_crud::postgresql_type::StdPrimitiveI64AsNotNullBigSerialInitializedByPostgresql as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_6e88acb0_c566_4fef_8a09_66a41338cf36", true),
//         <postgresql_crud::postgresql_type::StdPrimitiveI16AsNotNullInt2 as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_40d64ae4_a646_4394_bfce_3894bdfced87", false),
//         // <postgresql_crud::postgresql_type::OptionStdPrimitiveI16AsNullableInt2 as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_ebe9a28a_eef0_4b1d_a706_8a9c363db7ab", false),
//         // <postgresql_crud::postgresql_type::StdPrimitiveI32AsNotNullInt4 as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_b225e9b0_80ae_4aea_ab7f_2444d0b3c5fa", false),
//         // <postgresql_crud::postgresql_type::OptionStdPrimitiveI32AsNullableInt4 as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_fb5fe9b0_1505_4d68_b2e1_2483bc47ab6c", false),
//         // <postgresql_crud::postgresql_type::StdPrimitiveI64AsNotNullInt8 as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_579f811f_17de_4989_b1f9_be4b5e060641", false),
//         // <postgresql_crud::postgresql_type::OptionStdPrimitiveI64AsNullableInt8 as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_55a6dde9_fdae_4025_b9ce_d8fd483a0b86", false),
//         // <postgresql_crud::postgresql_type::StdPrimitiveF32AsNotNullFloat4 as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_59f8f4f5_e7e6_4ee3_973e_b73f2e415d81", false),
//         // <postgresql_crud::postgresql_type::OptionStdPrimitiveF32AsNullableFloat4 as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_389cc934_2e11_4e86_8429_ef75934563a7", false),
//         // <postgresql_crud::postgresql_type::StdPrimitiveF64AsNotNullFloat8 as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_e8c63c01_7317_4b3a_805f_59df250f3ad0", false),
//         // <postgresql_crud::postgresql_type::OptionStdPrimitiveF64AsNullableFloat8 as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_0c72cfa5_60ae_4f8f_b517_a68d5fda7eef", false),
//         // <postgresql_crud::postgresql_type::SqlxPostgresTypesPgMoneyAsNotNullMoney as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_8ffe8fce_e270_4b32_8c74_2fad827581b1", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgMoneyAsNullableMoney as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_c0956407_a5b3_4b7c_a016_20971edc67d6", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesDecimalAsNotNullNumeric as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_2311f761_9b1c_40e8_a9ee_2f990f598c7a", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesDecimalAsNullableNumeric as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_521b136c_c5ce_46c8_badb_ce504990ca87", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesBigDecimalAsNotNullNumeric as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_a8238982_d31d_46ed_aa86_9d2420666769", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesBigDecimalAsNullableNumeric as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_77e10de9_11aa_4eaf_aefa_8e97720b615a", false),
//         // <postgresql_crud::postgresql_type::StdPrimitiveBoolAsNotNullBool as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_39b118e9_44ae_4fa6_8acb_4ea926b2afe4", false),
//         // <postgresql_crud::postgresql_type::OptionStdPrimitiveBoolAsNullableBool as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_f3cfeda5_bff1_49b9_adc0_ee99468e116d", false),
//         // <postgresql_crud::postgresql_type::StdStringStringAsNotNullCharN as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(
//         //     &"column_ab072aa7_6b56_4b1f_9491_7b766f6dbc52",
//         //     false,
//         //     postgresql_crud::postgresql_type::StdStringStringAsCharNLength::try_from(1).unwrap()
//         // ),
//         // <postgresql_crud::postgresql_type::OptionStdStringStringAsNullableCharN as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(
//         //     &"column_b5fde990_7151_4944_95cf_221c59531bbb",
//         //     false,
//         //     postgresql_crud::postgresql_type::StdStringStringAsCharNLength::try_from(1).unwrap()
//         // ),
//         // <postgresql_crud::postgresql_type::StdStringStringAsNotNullVarchar as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(
//         //     &"column_2a975be8_3b64_463c_b449_c7f678aa973f",
//         //     false,
//         //     postgresql_crud::postgresql_type::StdStringStringAsVarcharLength::try_from(1).unwrap()
//         // ),
//         // <postgresql_crud::postgresql_type::OptionStdStringStringAsNullableVarchar as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(
//         //     &"column_f94b1781_21c6_414a_a1f0_82a1dc9b03d7",
//         //     false,
//         //     postgresql_crud::postgresql_type::StdStringStringAsVarcharLength::try_from(1).unwrap()
//         // ),
//         // <postgresql_crud::postgresql_type::StdStringStringAsNotNullText as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_7578cdb5_a5b9_484b_ac9f_586fa3bcd2e8", false),
//         // <postgresql_crud::postgresql_type::OptionStdStringStringAsNullableText as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_185e3592_8d03_4962_b423_fe22e0b5e28d", false),
//         // <postgresql_crud::postgresql_type::StdVecVecStdPrimitiveU8AsNotNullBytea as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_83c47937_8319_43eb_8c42_72d267380602", false),
//         // <postgresql_crud::postgresql_type::OptionStdVecVecStdPrimitiveU8AsNullableBytea as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_6367c2ff_5379_4d67_a49e_1075ff353a25", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesChronoNaiveTimeAsNotNullTime as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_03d92aed_e8d1_434f_a45d_029df9ad1d22", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesChronoNaiveTimeAsNullableTime as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_7cd3a1c9_75b1_4227_a16e_8e316311568b", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesTimeTimeAsNotNullTime as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_0b4ff0bd_ad73_48fd_9ec2_b7bafa908953", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesTimeTimeAsNullableTime as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_3c9b4049_bf22_44e2_a9d2_cecf01cc088d", false),
//         // <postgresql_crud::postgresql_type::SqlxPostgresTypesPgIntervalAsNotNullInterval as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_20555517_a10a_4ddf_a2c3_19898345d836", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgIntervalAsNullableInterval as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_e8cd8405_0931_41f2_94cb_9766b405e432", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesTimeDateAsNotNullDate as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_ddb3aed3_bcc2_4c14_b537_4e6249be754c", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesTimeDateAsNullableDate as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_ccff97e5_f010_483a_a87d_497f68feb321", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesChronoNaiveDateAsNotNullDate as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_e2bd1441_feba_40d8_bf0e_df45f6d99d15", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesChronoNaiveDateAsNullableDate as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_752433fa_f3d6_4e0d_81e7_5c5f277da8cd", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesChronoNaiveDateTimeAsNotNullTimestamp as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_e3770284_4ad4_4c87_bbcc_7a7adc738f2f", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesChronoNaiveDateTimeAsNullableTimestamp as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_063e648a_c05e_4db6_9278_b3b131e5d9a7", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesTimePrimitiveDateTimeAsNotNullTimestamp as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_6325da70_e3e9_4289_a1b0_e39be27a8517", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesTimePrimitiveDateTimeAsNullableTimestamp as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_8d1d6adb_45fd_4564_9822_71022d53ec1c", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNotNullTimestampTz as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_e06e3994_bb74_46a7_b914_1205bff2527c", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNullableTimestampTz as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_22b1b67c_039a_4020_ba36_63622d02cea6", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNotNullTimestampTz as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_293d0e00_6bd6_4a93_af30_67e9ea1ac7dd", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNullableTimestampTz as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_49f974c2_ff30_4ad9_b491_b7e844795808", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesUuidUuidAsNotNullUuidInitializedByClient as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_0bb198f5_bf4c_4308_ba13_3f3a18960b25", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesUuidUuidAsNullableUuidInitializedByClient as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_0cf8db36_04be_4fc9_bbcc_008321b357c2", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesIpnetworkIpNetworkAsNotNullInet as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_1e99c21a_69c5_480b_8282_fe38f7b870d7", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesIpnetworkIpNetworkAsNullableInet as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_7c4400a7_c0ce_4470_94f0_bb9dcf3a5786", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesIpnetworkIpNetworkAsNotNullCidr as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_be493f9c_ed9d_4471_8382_0eace73cb918", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesIpnetworkIpNetworkAsNullableCidr as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_16c4828c_1277_479a_8b32_a556f19947a2", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesMacAddressMacAddressAsNotNullMacAddr as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_dd337b11_4ad8_4c64_b0d6_2e73882ad2d0", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesMacAddressMacAddressAsNullableMacAddr as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_d77afa8a_f30f_439a_9339_fdfe730ee62e", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesBitVecAsNotNullBit as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(
//         //     &"column_fc22ca9d_1f57_46b4_922f_5ad659dfe5ff",
//         //     false,
//         //     postgresql_crud::postgresql_type::SqlxTypesBitVecAsBitLength::try_from(1).unwrap()
//         // ),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesBitVecAsNullableBit as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(
//         //     &"column_da0f6a4a_5eb9_46a2_98d1_b7985b537b13",
//         //     false,
//         //     postgresql_crud::postgresql_type::SqlxTypesBitVecAsBitLength::try_from(1).unwrap()
//         // ),
//         // <postgresql_crud::postgresql_type::SqlxTypesBitVecAsNotNullVarbit as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(
//         //     &"column_e668b6ec_1920_4346_a5a4_1af8e133b09c",
//         //     false,
//         //     postgresql_crud::postgresql_type::SqlxTypesBitVecAsVarbitLength::try_from(1).unwrap()
//         // ),
//         // <postgresql_crud::postgresql_type::OptionSqlxTypesBitVecAsNullableVarbit as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(
//         //     &"column_c4ceaa5a_1c93_4545_921e_9c7e38e65e11",
//         //     false,
//         //     postgresql_crud::postgresql_type::SqlxTypesBitVecAsVarbitLength::try_from(1).unwrap()
//         // ),
//         // <postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeStdPrimitiveI32AsNotNullInt4Range as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_c203347a_c208_4b2b_8096_364a7fb66685", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeStdPrimitiveI32AsNullableInt4Range as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_31f58552_715e_48f4_a7fd_a381af1a813f", false),
//         // <postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeStdPrimitiveI64AsNotNullInt8Range as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_b471a4b4_a473_4541_ab51_82587e19d464", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeStdPrimitiveI64AsNullableInt8Range as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_1aefbea2_7ffa_451c_9966_934f8ebf4f78", false),
//         // <postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesDecimalAsNotNullNumRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_1ddaf386_9a67_4d7d_b3f8_070c35e249c3", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesDecimalAsNullableNumRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_9e4c0068_6974_46de_9dc1_bc95a679d9cb", false),
//         // <postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesBigDecimalAsNotNullNumRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_f699bdd4_9380_44d0_b1be_2c792d3ec895", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesBigDecimalAsNullableNumRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_aa7012af_393b_4736_8b95_725eb6df1ca0", false),
//         // <postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesTimeDateAsNotNullDateRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_abb40538_4eea_40ef_87bb_c55623bffd40", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesTimeDateAsNullableDateRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_6f8fc5c1_3d38_4ca3_b092_0c7a266aaa8b", false),
//         // <postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateAsNotNullDateRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_5f85250a_f889_4d59_a1fa_12e32542ab04", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateAsNullableDateRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_7051ad39_b56b_432a_9224_d3c46c93d47b", false),
//         // <postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNotNullTimestampRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_ba0e1014_7604_45c7_a475_b22a968108e8", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNullableTimestampRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_4c3cf4d7_121c_4854_aad6_96e5e7820f2e", false),
//         // <postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesTimePrimitiveDateTimeAsNotNullTimestampRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_29ca5058_5ad4_464e_aa1f_9077dbe1eca4", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesTimePrimitiveDateTimeAsNullableTimestampRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_12f3648d_b7bc_4f36_a302_291c73783ef2", false),
//         // <postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNotNullTimestampTzRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_a72a15d5_27f0_4a0c_a600_cac0c2d48bd7", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNullableTimestampTzRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_bc3e8a83_9b2b_4709_ae21_f4f79b0dbfd0", false),
//         // <postgresql_crud::postgresql_type::SqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNotNullTimestampTzRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_e454c17e_d90e_47fe_a0ef_940d7f5afdae", false),
//         // <postgresql_crud::postgresql_type::OptionSqlxPostgresTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoLocalAsNullableTimestampTzRange as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_cc739472_9b4e_432c_a6cc_c803117b0086", false),
//         // <postgresql_crud::postgresql_type::StdPrimitiveI16AsNotNullSmallSerialInitializedByPostgresql as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_35ebd1c3_ddb7_44c2_bddf_92ef5296c432", false),
//         // <postgresql_crud::postgresql_type::StdPrimitiveI32AsNotNullSerialInitializedByPostgresql as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_d712ac90_8af2_4a55_9791_314812be4016", false),
//         // <postgresql_crud::postgresql_type::SqlxTypesUuidUuidAsNotNullUuidV4InitializedByPostgresql as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"column_8384082c_21de_4a21_95e9_a398644d8ea1", false),
//         <ObjectAnimalAsJsonbNotNull as postgresql_crud::PostgresqlType>::TableTypeDeclaration::create_table_column_query_part(&"object_animal_as_jsonb_not_null", false)
//     );
//     println!("{create_table_if_not_exists_query_stringified}");
//     let _ = sqlx::query(&create_table_if_not_exists_query_stringified).execute(pool).await.unwrap();
// }


