#need to enable vscode rest client  extension https://marketplace.visualstudio.com/items?itemName=humao.rest-client to send requests
 
POST http://127.0.0.1:8080/dogs/create_many HTTP/1.1
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

[
    {
        "name": "3333333333",
        "color": "3333333333"
    },
    {
        "name": "4444444444",
        "color": "44444444"
    }
]

### 

POST http://127.0.0.1:8080/dogs/create_one HTTP/1.1
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

{
    "name": "first_test_name_create",
    "color": "first_test_color_create"
}



### todo name and color must be  arrays              

POST http://127.0.0.1:8080/dogs/read_one HTTP/1.1
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

{
    "id": "75ef376b-0f75-4a2b-aff2-f61e9f44099a",
    "select": "IdName"
}

### 

POST http://127.0.0.1:8080/dogs/read_many HTTP/1.1
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

{
    "select": "IdNameColor",
    # "id": [
    #     "7b51bb9c-124e-44ba-9941-7f32a2c18c78",
    #     "5829d06c-4141-4734-8266-b3d1e618c4de",
    #     "be13a118-e5e5-4cb6-93fe-5a1f1767d666"
    # ],
    # "name":[
    #     {
    #         "regex":"^tesft_namfe$",
    #         "conjuctive_operator":"Or"
    #     }
    # ],
    # "color":[
    #     {
    #         "regex":"test",
    #         "conjuctive_operator":"Or"
    #     }
    # ],
    "order_by": {
        "column": "id",
        "order": "desc"
    },
    "limit": 100,
    "offset": 0
}

###  

PATCH http://127.0.0.1:8080/dogs/update_one HTTP/1.1
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

{
    "id": "b5d3c50e-b99f-4ada-a89d-8a8af63f9a0c",
    "name": "namef666668",
    "color":"colorf66666666866"
}

### fix this

PATCH http://127.0.0.1:8080/dogs/update_many HTTP/1.1 
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

[
    {
        "id": "439e3e1a-3b3d-4d54-b847-6600ef27a9bd",
        "name": "meowmoew",
        "color":"meow"
    },
    {
        "id": "1177ef97-232b-4698-bbbf-5367dc76344d",
        "name": "ffffff",
        "color":"gfggggggggggggg"
    }
]

###

DELETE http://127.0.0.1:8080/dogs/delete_one HTTP/1.1
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

{
    "id": "65c5f4f3-f604-467d-bdc9-cbe64b53dbe1"
}

####"^first_test_name_create$"  

DELETE http://127.0.0.1:8080/dogs/delete_many HTTP/1.1
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

{
    "id": [
      "f4977a3c-ca1f-41da-b135-ee6a47936ff8",
      "f854a08d-9c4a-453e-9561-d91f2caf1fc1"
    ]
    # ,
    # "name":[
    #     {
    #         "regex":"first_test_name_create",
    #         "conjuctive_operator":"Or"
    #     }
    # ],
    # "color":[
    #     {
    #         "regex":"first_test_color_create",
    #         "conjuctive_operator":"Or"
    #     }
    # ]
}

###

GET http://127.0.0.1:8080/health_check HTTP/1.1

### 

GET http://127.0.0.1:8080/git_info HTTP/1.1

###

GET http://127.0.0.1:8080/src/main.rs HTTP/1.1
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

GET http://127.0.0.1:8080/header_extractor_example HTTP/1.1
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

GET http://127.0.0.1:8080/extract_custom_header_example HTTP/1.1
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

GET http://127.0.0.1:8080/middleware_message_example HTTP/1.1

###

GET http://127.0.0.1:8080/read_middleware_custom_header HTTP/1.1
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696