use optml::Optml;
#[allow(clippy::arbitrary_source_item_ordering)]
#[derive(Debug, Clone, Copy, pg_crud::GenPgTable, Optml)]
#[pg_crud::gen_pg_table_config{{
    "tests_write_into_file": "False",
    "cmn_write_into_file": "False",
    "whole_write_into_file": "False"
}}]
#[pg_crud::cm_er_vrts{enum CmErVrts{}}]
#[pg_crud::co_er_vrts{enum CoErVrts{}}]
#[pg_crud::rm_er_vrts{enum RmErVrts{}}]
#[pg_crud::ro_er_vrts{enum RoErVrts{}}]
#[pg_crud::um_er_vrts{enum UmErVrts{}}]
#[pg_crud::uo_er_vrts{enum UoErVrts{}}]
#[pg_crud::dm_er_vrts{enum DmErVrts{}}]
#[pg_crud::dlo_er_vrts{enum DloErVrts{}}]
#[pg_crud::cmn_er_vrts{
    enum CmnErVrts {
        // CheckCommit {
        //     #[eo_location]
        //     check_commit: pg_crud::check_commit::CommitEr,
        //     loc: location_lib::loc::Loc,
        // },
    }
}]
#[pg_crud::cm_logic{}]
#[pg_crud::co_logic{}]
#[pg_crud::rm_logic{}]
#[pg_crud::ro_logic{}]
#[pg_crud::um_logic{}]
#[pg_crud::uo_logic{}]
#[pg_crud::dm_logic{}]
#[pg_crud::dlo_logic{}]
#[pg_crud::cmn_logic{}]
pub struct TableExample {
    // #[gen_pg_crud_pk]
    // pub pk: pg_crud::I64AsNnBigSerialInitByPg,
    #[gen_pg_table_pk]
    pub pk_column: pg_crud::SqlxTypesUuidUuidAsNnUuidV4InitByPg,
    // pub column_0: pg_crud::I16AsNnInt2,
    // pub column_1: pg_crud::OptI16AsNlInt2,
    // pub column_2: pg_crud::VecOfI16AsNnArrOfNnInt2,
    // pub column_3: pg_crud::OptVecOfI16AsNlArrOfNnInt2,
    // pub column_4: pg_crud::VecOfOptI16AsNnArrOfNlInt2,
    // pub column_5: pg_crud::OptVecOfOptI16AsNlArrOfNlInt2,
    // pub column_6: pg_crud::I32AsNnInt4,
    // pub column_7: pg_crud::OptI32AsNlInt4,
    // pub column_8: pg_crud::VecOfI32AsNnArrOfNnInt4,
    // pub column_9: pg_crud::OptVecOfI32AsNlArrOfNnInt4,
    // pub column_10: pg_crud::VecOfOptI32AsNnArrOfNlInt4,
    // pub column_11: pg_crud::OptVecOfOptI32AsNlArrOfNlInt4,
    // pub column_12: pg_crud::I64AsNnInt8,
    // pub column_13: pg_crud::OptI64AsNlInt8,
    // pub column_14: pg_crud::VecOfI64AsNnArrOfNnInt8,
    // pub column_15: pg_crud::OptVecOfI64AsNlArrOfNnInt8,
    // pub column_16: pg_crud::VecOfOptI64AsNnArrOfNlInt8,
    // pub column_17: pg_crud::OptVecOfOptI64AsNlArrOfNlInt8,
    // pub column_18: pg_crud::F32AsNnFloat4,
    // pub column_19: pg_crud::OptF32AsNlFloat4,
    // pub column_20: pg_crud::VecOfF32AsNnArrOfNnFloat4,
    // pub column_21: pg_crud::OptVecOfF32AsNlArrOfNnFloat4,
    // pub column_22: pg_crud::VecOfOptF32AsNnArrOfNlFloat4,
    // pub column_23: pg_crud::OptVecOfOptF32AsNlArrOfNlFloat4,
    // pub column_24: pg_crud::F64AsNnFloat8,
    // pub column_25: pg_crud::OptF64AsNlFloat8,
    // pub column_26: pg_crud::VecOfF64AsNnArrOfNnFloat8,
    // pub column_27: pg_crud::OptVecOfF64AsNlArrOfNnFloat8,
    // pub column_28: pg_crud::VecOfOptF64AsNnArrOfNlFloat8,
    // pub column_29: pg_crud::OptVecOfOptF64AsNlArrOfNlFloat8,
    // pub column_30: pg_crud::I16AsNnSmallSerialInitByPg,
    // pub column_31: pg_crud::I32AsNnSerialInitByPg,
    // pub column_32: pg_crud::I64AsNnBigSerialInitByPg,
    // pub column_33: pg_crud::SqlxPgTypesPgMoneyAsNnMoney,
    // pub column_34: pg_crud::OptSqlxPgTypesPgMoneyAsNlMoney,
    // pub column_35: pg_crud::VecOfSqlxPgTypesPgMoneyAsNnArrOfNnMoney,
    // pub column_36: pg_crud::OptVecOfSqlxPgTypesPgMoneyAsNlArrOfNnMoney,
    // pub column_37: pg_crud::VecOfOptSqlxPgTypesPgMoneyAsNnArrOfNlMoney,
    // pub column_38: pg_crud::OptVecOfOptSqlxPgTypesPgMoneyAsNlArrOfNlMoney,
    // pub column_39: pg_crud::BoolAsNnBool,
    // pub column_40: pg_crud::OptBoolAsNlBool,
    // pub column_41: pg_crud::VecOfBoolAsNnArrOfNnBool,
    // pub column_42: pg_crud::OptVecOfBoolAsNlArrOfNnBool,
    // pub column_43: pg_crud::VecOfOptBoolAsNnArrOfNlBool,
    // pub column_44: pg_crud::OptVecOfOptBoolAsNlArrOfNlBool,
    // pub column_45: pg_crud::StringAsNnText,
    // pub column_46: pg_crud::OptStringAsNlText,
    // pub column_47: pg_crud::VecOfStringAsNnArrOfNnText,
    // pub column_48: pg_crud::OptVecOfStringAsNlArrOfNnText,
    // pub column_49: pg_crud::VecOfOptStringAsNnArrOfNlText,
    // pub column_50: pg_crud::OptVecOfOptStringAsNlArrOfNlText,
    // pub column_51: pg_crud::StdVecVecU8AsNnBytea,
    // pub column_52: pg_crud::OptStdVecVecU8AsNlBytea,
    // pub column_53: pg_crud::VecOfStdVecVecU8AsNnArrOfNnBytea,
    // pub column_54: pg_crud::OptVecOfStdVecVecU8AsNlArrOfNnBytea,
    // pub column_55: pg_crud::VecOfOptStdVecVecU8AsNnArrOfNlBytea,
    // pub column_56: pg_crud::OptVecOfOptStdVecVecU8AsNlArrOfNlBytea,
    // pub column_57: pg_crud::SqlxTypesChronoNaiveTimeAsNnTime,
    // pub column_58: pg_crud::OptSqlxTypesChronoNaiveTimeAsNlTime,
    // pub column_59: pg_crud::VecOfSqlxTypesChronoNaiveTimeAsNnArrOfNnTime,
    // pub column_60: pg_crud::OptVecOfSqlxTypesChronoNaiveTimeAsNlArrOfNnTime,
    // pub column_61: pg_crud::VecOfOptSqlxTypesChronoNaiveTimeAsNnArrOfNlTime,
    // pub column_62: pg_crud::OptVecOfOptSqlxTypesChronoNaiveTimeAsNlArrOfNlTime,
    // pub column_63: pg_crud::SqlxTypesTimeTimeAsNnTime,
    // pub column_64: pg_crud::OptSqlxTypesTimeTimeAsNlTime,
    // pub column_65: pg_crud::VecOfSqlxTypesTimeTimeAsNnArrOfNnTime,
    // pub column_66: pg_crud::OptVecOfSqlxTypesTimeTimeAsNlArrOfNnTime,
    // pub column_67: pg_crud::VecOfOptSqlxTypesTimeTimeAsNnArrOfNlTime,
    // pub column_68: pg_crud::OptVecOfOptSqlxTypesTimeTimeAsNlArrOfNlTime,
    // pub column_69: pg_crud::SqlxPgTypesPgIntervalAsNnInterval,
    // pub column_70: pg_crud::OptSqlxPgTypesPgIntervalAsNlInterval,
    // pub column_71: pg_crud::VecOfSqlxPgTypesPgIntervalAsNnArrOfNnInterval,
    // pub column_72: pg_crud::OptVecOfSqlxPgTypesPgIntervalAsNlArrOfNnInterval,
    // pub column_73: pg_crud::VecOfOptSqlxPgTypesPgIntervalAsNnArrOfNlInterval,
    // pub column_74: pg_crud::OptVecOfOptSqlxPgTypesPgIntervalAsNlArrOfNlInterval,
    // pub column_75: pg_crud::SqlxTypesChronoNaiveDateAsNnDate,
    // pub column_76: pg_crud::OptSqlxTypesChronoNaiveDateAsNlDate,
    // pub column_77: pg_crud::VecOfSqlxTypesChronoNaiveDateAsNnArrOfNnDate,
    // pub column_78: pg_crud::OptVecOfSqlxTypesChronoNaiveDateAsNlArrOfNnDate,
    // pub column_79: pg_crud::VecOfOptSqlxTypesChronoNaiveDateAsNnArrOfNlDate,
    // pub column_80: pg_crud::OptVecOfOptSqlxTypesChronoNaiveDateAsNlArrOfNlDate,
    // pub column_81: pg_crud::SqlxTypesChronoNaiveDateTimeAsNnTimestamp,
    // pub column_82: pg_crud::OptSqlxTypesChronoNaiveDateTimeAsNlTimestamp,
    // pub column_83: pg_crud::VecOfSqlxTypesChronoNaiveDateTimeAsNnArrOfNnTimestamp,
    // pub column_84: pg_crud::OptVecOfSqlxTypesChronoNaiveDateTimeAsNlArrOfNnTimestamp,
    // pub column_85: pg_crud::VecOfOptSqlxTypesChronoNaiveDateTimeAsNnArrOfNlTimestamp,
    // pub column_86: pg_crud::OptVecOfOptSqlxTypesChronoNaiveDateTimeAsNlArrOfNlTimestamp,
    // pub column_87: pg_crud::SqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNnTimestampTz,
    // pub column_88: pg_crud::OptSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNlTimestampTz,
    // pub column_89: pg_crud::VecOfSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNnArrOfNnTimestampTz,
    // pub column_90: pg_crud::OptVecOfSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNlArrOfNnTimestampTz,
    // pub column_91: pg_crud::VecOfOptSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNnArrOfNlTimestampTz,
    // pub column_92: pg_crud::OptVecOfOptSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNlArrOfNlTimestampTz,
    // pub column_93: pg_crud::SqlxTypesUuidUuidAsNnUuidV4InitByPg,
    // pub column_94: pg_crud::SqlxTypesUuidUuidAsNnUuidInitByClient,
    // pub column_95: pg_crud::OptSqlxTypesUuidUuidAsNlUuidInitByClient,
    // pub column_96: pg_crud::VecOfSqlxTypesUuidUuidAsNnArrOfNnUuidInitByClient,
    // pub column_97: pg_crud::OptVecOfSqlxTypesUuidUuidAsNlArrOfNnUuidInitByClient,
    // pub column_98: pg_crud::VecOfOptSqlxTypesUuidUuidAsNnArrOfNlUuidInitByClient,
    // pub column_99: pg_crud::OptVecOfOptSqlxTypesUuidUuidAsNlArrOfNlUuidInitByClient,
    // pub column_100: pg_crud::SqlxTypesIpnetworkIpNetworkAsNnInet,
    // pub column_101: pg_crud::OptSqlxTypesIpnetworkIpNetworkAsNlInet,
    // pub column_102: pg_crud::VecOfSqlxTypesIpnetworkIpNetworkAsNnArrOfNnInet,
    // pub column_103: pg_crud::OptVecOfSqlxTypesIpnetworkIpNetworkAsNlArrOfNnInet,
    // pub column_104: pg_crud::VecOfOptSqlxTypesIpnetworkIpNetworkAsNnArrOfNlInet,
    // pub column_105: pg_crud::OptVecOfOptSqlxTypesIpnetworkIpNetworkAsNlArrOfNlInet,
    // pub column_106: pg_crud::SqlxTypesMacAddressMacAddressAsNnMacAddr,
    // pub column_107: pg_crud::OptSqlxTypesMacAddressMacAddressAsNlMacAddr,
    // pub column_108: pg_crud::VecOfSqlxTypesMacAddressMacAddressAsNnArrOfNnMacAddr,
    // pub column_109: pg_crud::OptVecOfSqlxTypesMacAddressMacAddressAsNlArrOfNnMacAddr,
    // pub column_110: pg_crud::VecOfOptSqlxTypesMacAddressMacAddressAsNnArrOfNlMacAddr,
    // pub column_111: pg_crud::OptVecOfOptSqlxTypesMacAddressMacAddressAsNlArrOfNlMacAddr,
    // pub column_112: pg_crud::SqlxPgTypesPgRangeI32AsNnInt4Range,
    // pub column_113: pg_crud::OptSqlxPgTypesPgRangeI32AsNlInt4Range,
    // pub column_114: pg_crud::VecOfSqlxPgTypesPgRangeI32AsNnArrOfNnInt4Range,
    // pub column_115: pg_crud::OptVecOfSqlxPgTypesPgRangeI32AsNlArrOfNnInt4Range,
    // pub column_116: pg_crud::VecOfOptSqlxPgTypesPgRangeI32AsNnArrOfNlInt4Range,
    // pub column_117: pg_crud::OptVecOfOptSqlxPgTypesPgRangeI32AsNlArrOfNlInt4Range,
    // pub column_118: pg_crud::SqlxPgTypesPgRangeI64AsNnInt8Range,
    // pub column_119: pg_crud::OptSqlxPgTypesPgRangeI64AsNlInt8Range,
    // pub column_120: pg_crud::VecOfSqlxPgTypesPgRangeI64AsNnArrOfNnInt8Range,
    // pub column_121: pg_crud::OptVecOfSqlxPgTypesPgRangeI64AsNlArrOfNnInt8Range,
    // pub column_122: pg_crud::VecOfOptSqlxPgTypesPgRangeI64AsNnArrOfNlInt8Range,
    // pub column_123: pg_crud::OptVecOfOptSqlxPgTypesPgRangeI64AsNlArrOfNlInt8Range,
    // pub column_124: pg_crud::SqlxPgTypesPgRangeSqlxTypesChronoNaiveDateAsNnDateRange,
    // pub column_125: pg_crud::OptSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateAsNlDateRange,
    // pub column_126: pg_crud::VecOfSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateAsNnArrOfNnDateRange,
    // pub column_127: pg_crud::OptVecOfSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateAsNlArrOfNnDateRange,
    // pub column_128: pg_crud::VecOfOptSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateAsNnArrOfNlDateRange,
    // pub column_129: pg_crud::OptVecOfOptSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateAsNlArrOfNlDateRange,
    // pub column_130: pg_crud::SqlxPgTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNnTimestampRange,
    // pub column_131: pg_crud::OptSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNlTimestampRange,
    // pub column_132: pg_crud::VecOfSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNnArrOfNnTimestampRange,
    // pub column_133: pg_crud::OptVecOfSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNlArrOfNnTimestampRange,
    // pub column_134: pg_crud::VecOfOptSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNnArrOfNlTimestampRange,
    // pub column_135: pg_crud::OptVecOfOptSqlxPgTypesPgRangeSqlxTypesChronoNaiveDateTimeAsNlArrOfNlTimestampRange,
    // pub column_136: pg_crud::SqlxPgTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNnTimestampTzRange,
    // pub column_137: pg_crud::OptSqlxPgTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNlTimestampTzRange,
    // pub column_138: pg_crud::VecOfSqlxPgTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNnArrOfNnTimestampTzRange,
    // pub column_139: pg_crud::OptVecOfSqlxPgTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNlArrOfNnTimestampTzRange,
    // pub column_140: pg_crud::VecOfOptSqlxPgTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNnArrOfNlTimestampTzRange,
    // pub column_141: pg_crud::OptVecOfOptSqlxPgTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsNlArrOfNlTimestampTzRange,
    pub column_142: server_types::AnimalAsNnJsonbObj,
    // pub column_143: server_types::OptAnimalAsNlJsonbObj,
    // pub column_144: server_types::VecOfAnimalWithIdAsNnArrOfNnJsonbObjWithId,
    // pub column_145: server_types::OptVecOfAnimalWithIdAsNlArrOfNnJsonbObjWithId,
}
