[package]
name = "generate_quotes"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = {version = "=1.0.95"}
constants = {path = "../constants"}

[lints]
workspace = true
